### DISCUSSION TITLE
Syntax highlighting in README.md

### DISCUSSION THREAD

**Discussion by Codelica** [verdaccio/verdaccio#1926] [Ideas]
**Describe the solution you'd like**
Would like to see code block syntax highlighting ala GitHub and GitLab:

```js
console.log(`This is JavaScript!`);
```

```yaml
# This is YAML!
web:
  scope: \@something
```

Thanks for considering :)
