### DISCUSSION TITLE
Configure auth for uplinks with basic auth (Nexus)

### DISCUSSION THREAD

**Discussion by raDiesle** [verdaccio/verdaccio#2064] [Q&A] [answered]
The documentation only shows configuration for uplinks with type: "bearer" but this seems not to be supported by private npm company repository of Nexus https://help.sonatype.com/repomanager3/formats/npm-registry#npmRegistry-AuthenticationUsingBasicAuth

How to not use "bearer" auth type but "basic auth" with provided username/email and token, instead?

Ok by checking your source code it should work the following way, but still struggling, can you verify?

```
uplinks:
  privateRepo:
    url: https://nexus.dev.crxmarkets.com/repository/npm-crx-group/
    auth:
      type: basic
      user: myuser
      token: mytoken
```

**Comment by jachstet-sea** [comment, marked as answer]
This is working for us:
```
  myNexusUplink:
    url: https://nexus.tools.myCloud.com/repository/reponame-npm/
    headers:
      Authorization: "Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="
```
