### DISCUSSION TITLE
Plugin not found error upon starting docker container using docker-compose

### DISCUSSION THREAD

**Discussion by buzziam** [verdaccio/verdaccio#2078] [Q&A]
**Describe the bug**
attempting to start docker container using docker compose per docs: 

`docker-compose up --build`

The following is output:
```
Pulling verdaccio (verdaccio/verdaccio:latest)...
latest: Pulling from verdaccio/verdaccio
0a6724ff3fcd: Pull complete
7ceedf9dd120: Pull complete
ce91790a06ab: Pull complete
15917197957b: Pull complete
b7fbee624dc7: Pull complete
1d47affba06c: Pull complete
c5d3ae34c450: Pull complete
4901e46df5c8: Pull complete
1b3bae55cd60: Pull complete
120fe11d7281: Pull complete
Digest: sha256:31b4e79c50baedca4e94ae505bad8589b5840a8c0a706981d0dbbbe206ac84e3
Status: Downloaded newer image for verdaccio/verdaccio:latest
Creating verdaccio ...
Creating verdaccio ... done
Attaching to verdaccio
verdaccio    |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio    |  warn --- Verdaccio started
verdaccio    |  warn --- Plugin successfully loaded: verdaccio-htpasswd
verdaccio    |  error--- plugin not found. try npm install verdaccio-packages
verdaccio    | (node:7) UnhandledPromiseRejectionWarning: Error:
verdaccio    |         verdaccio-packages plugin not found. try "npm install verdaccio-packages"
verdaccio    |     at /opt/verdaccio/build/lib/plugin-loader.js:110:13
verdaccio    |     at Array.map (<anonymous>)
verdaccio    |     at loadPlugin (/opt/verdaccio/build/lib/plugin-loader.js:62:37)
verdaccio    |     at Auth._loadPlugin (/opt/verdaccio/build/lib/auth.js:54:38)
verdaccio    |     at new Auth (/opt/verdaccio/build/lib/auth.js:44:25)
verdaccio    |     at defineAPI (/opt/verdaccio/build/api/index.js:43:16)
verdaccio    |     at _default (/opt/verdaccio/build/api/index.js:127:10)
verdaccio    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
verdaccio    | (Use `node --trace-warnings ...` to show where the warning was created)
verdaccio    | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
verdaccio    | (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
verdaccio exited with code 0
```

furthermore, attempting to try the reported action: `try npm install verdaccio-packages` does not work regardless of the registry specified (no registry specified (an no .npmrc at all) => https://registry.npmjs.org/ or `--registry=https://registry.verdaccio.org`)

**To Reproduce**
1. execute the following:
`docker-compose up --build`

with the following specified in docker-compose.yml

```
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    environment:
    - VERDACCIO_PORT=4873
    ports:
    - "4873:4873"
    volumes:
    - "./storage:/verdaccio/storage"
    - "./config:/verdaccio/conf"
    - "./plugins:/verdaccio/plugins"
```

**Expected behavior**
verdaccio starts with some pertinent output and is ready to handle requests of npm registry nature

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: /home/blah/verdaccio/storage
auth:
  htpasswd:
    file: /home/blah/verdaccio/.htpasswd
    max_users: 10
  packages:
    '@blah/*':
      access: $authenticated
      publish: $authenticated
```

**Comment by juanpicado** [comment]
You need your own container https://verdaccio.org/docs/en/docker#plugins

**Reply by buzziam** [reply]
Hi @juanpicado - thank you for the fast triage. 

Isn't it the case that I would need my own container if a requirement in my deployment was to have specific plugins installed? The thing is I don't require any plugins. This should be just like bringing the standard verdaccio container up by executing the following except that I'm using docker-compose (and the corresponding YML) to do it:

`docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio` except using docker-compose. 

Also, I'm just following the docs: https://verdaccio.org/docs/en/docker#using-docker-compose - and that's it. Does that mean this is a doc bug? 

Additionally, the error message states: `error--- plugin not found. try npm install verdaccio-packages` but as far as I can tell, the `verdaccio-packages` npm package doesn't exist.

**Reply by juanpicado** [reply]
You have a typo, extra space, this section is inside auth, that's the mistake.

```

packages:
    '@blah/*':
      access: $authenticated
      publish: $authenticated

```
