### DISCUSSION TITLE
Docker-compose: Error: CONFIG: it does not look like a valid config file

### DISCUSSION THREAD

**Discussion by avxkim** [verdaccio/verdaccio#2132] [Q&A]
**Describe the bug**

**To Reproduce**
 - `docker-compose up`
 - Compose file contents:

```
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
networks:
  node-network:
    driver: bridge
~
```

**Expected behavior**
- container starts...

**Environment information**
- Ubuntu 18.04

When i fire `docker-compose up` it does create 3 folders: config, storage, plugins, but they are empty. I've read a section about SELinux, tried these commands, but it had no effect, what else it might be?
