### DISCUSSION TITLE
404 Not found no such package available

### DISCUSSION THREAD

**Discussion by joaomelorodrigues** [verdaccio/verdaccio#2170] [Q&A] [answered]
Hello, I'm new on using verdaccio.
I'm using the latest version of verdaccio from docker hub.
I'm using a custom domain on a hosted server with docker. I can access the verdaccio homepage on my custom domain (https://npm.customdomain.com)
Added a user and  login successfuly using ```npm login --registry https://npm.customdomain.com```
Then when I try to publish a new package with ``` npm publish --registry https://npm.customdomain.com``` it gives me the 404 error.

My config.yaml:

```
storage: /verdaccio/storage
plugins: /verdaccio/plugins
web:
  title: NPM
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@myscope1/*':
    access: $all
    publish: $authenticated
  '@myscope2/*':
    access: $all
    publish: $authenticated
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
middlewares:
    audit:
	enabled: true
listen: https://npm.dotesfera.com
https:
    key: /verdaccio/conf/verdaccio-key.pem
    cert: /verdaccio/conf/verdaccio-cert.pem
logs:
  - {type: stdout, format: pretty, level: http}

```

![image](https://user-images.githubusercontent.com/30806279/113586117-05c9ce00-9625-11eb-8d91-c9da6d82525f.png)
