### DISCUSSION TITLE
How to configure a user group for a package access ?

### DISCUSSION THREAD

**Discussion by hiyangguo** [verdaccio/verdaccio#2173] [Q&A] [answered]
Hi,[In the document](https://verdaccio.org/docs/en/packages#usage) ,I didn't found how to create a user group control access.Now my configuration is like this
```yaml
packages:
  '@hypers/*':
    access: user-a user-b user-c
    publish: user-a user-b user-c
```
I want to config it like this
```yaml
$user-group: user-a user-b user-c
packages:
  '@hypers/*':
    access: $user-group
    publish:  $user-group
```
What should I do?

**Comment by juanpicado** [comment]
It's not possible in that way, currently, `user === group`. So, you must define all users are allowed in each section (access, publish).

**Comment by hiyangguo** [comment]
@juanpicado Thank you answer very much.So, will you add this feature in the future?

**Comment by juanpicado** [comment]
We are open to improvements 👍 of course. 

```
$user-group: user-a user-b user-c
packages:
  '@hypers/*':
    access: $user-group
    publish:  $user-group
````

I got your point here, but I think a real implementation (eg: config) might look a bit different due to the current design. I'll be happy to support to anyone that PR something like that.
