### DISCUSSION TITLE
External network resources will still be pulled after remove the proxy property

### DISCUSSION THREAD

**Discussion by cobolbaby** [verdaccio/verdaccio#2214] [Q&A] [answered]
**Describe the bug**

Even if I configure a private package hosting strategy, I can still see requests sent to npmjs when I install or publish the private package.

**To Reproduce**

- The client operation is as follows:

![2021-04-29 10-13-38屏幕截图](https://user-images.githubusercontent.com/11460848/116494597-b436fb00-a8d3-11eb-9c13-c9fde8025979.png)

- The server log is as follows

![2021-04-29 10-15-03屏幕截图](https://user-images.githubusercontent.com/11460848/116494628-cadd5200-a8d3-11eb-8498-11d383ea77a4.png)

**Expected behavior**

Avoid downloading needlessly to external registries, merging external metadata.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
packages:
  '@itc-*':
    access: $all
    publish: $authenticated

  'e-planet-*':
    # scoped packages
    access: $all
    publish: $authenticated

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
```

**Environment information**

- version: 4.12.0
