### DISCUSSION TITLE
"JWT not active" error return by server when requesting /verdaccio/packages from the Web

### DISCUSSION THREAD

**Discussion by kopax** [verdaccio/verdaccio#2238] [Q&A]
We are using `verdaccio` 4 and we want to configure `JWT` authentication.

We have read: 

- https://verdaccio.org/blog/2019/04/19/diving-into-jwt-support-for-verdaccio-4
- https://github.com/auth0/node-jsonwebtoken#usage

When we set the `jwt` configuration as in the [sample](https://github.com/verdaccio/verdaccio/blob/master/conf/default.yaml#L28):

```yaml

security:
  legacy: false
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1
```

We are having issue after connecting using with a user and it's password from the Web:

The `GET` request to `http://localhost:4873/-/verdaccio/packages` return the following content:

```json
{
  "error": "jwt not active"
}
```

What have I done wrong?
