### DISCUSSION TITLE
Add uplink to JFrog based repository

### DISCUSSION THREAD

**Discussion by amitdhiman000** [verdaccio/verdaccio#2251] [Q&A]
I want to add **uplink** to my company's private repository.

repository details are like this.
```
@webcomp:registry=https://artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-dev/
//artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-release/:_password=HUtDcDVlMuyeDShksFGzE5RD==
//artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-release/:username=user1
//artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-release/:email=user1@abcd.com
//artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-release/:always-auth=true
```

I am trying to translate it into configuration file, but no luck.

```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  private1:
    url: https://artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-dev
    auth:
      type: bearer
      token: "HUtDcDVlMuyeDShksFGzE5RD=="
```

I Also tried with JFrog API key by adding in headers, but not working. (I verified same API key curl command, which is working)

```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  private1:
    url: https://artifactory.corp.abcd.com/artifactory/api/npm/npm-webteam-dev
    headers:
      -
        X-JFrog-Art-Api: "<api-key>"
```

Any Idea, How to translate this information into uplink ?
