### DISCUSSION TITLE
Cache maxage: 100y doesn't find new versions on the uplink

### DISCUSSION THREAD

**Discussion by andreas-wagner** [verdaccio/verdaccio#2305] [Q&A] [answered]
Hi,

I wanted to have an offline cache that persists.
This is why I set the `maxage` to 100y.

The catch is, that `yarn outdated` only gets the package version list from verdaccio, w/o verdaccio checking the uplink.
This way I am stuck to the versions that were available back when the package.json was initially fetched.
Essentially I can not see new versions with `yarn outdated`.

Am I missing a config setting?

For reference here is my verdaccio.yaml:
```yaml
auth:
  htpasswd:
    file: ./shared/.htpasswd
listen: http://localhost:4873/
logs:
  - {type: rotating-file, format: json, path: ./verdaccio.log, level: info, options: {period: 1d}}
packages:
  '**':
    access: $authenticated
    proxy: npm
    publish: $authenticated
    unpublish: $authenticated
plugins: ./plugins
storage: ./shared/storage
uplinks:
  npm:
    cache: true
    maxage: 100y
    url: https://registry.npmjs.org/
  yarn:
    cache: true
    maxage: 100y
    url: https://registry.yarnpkg.com/
web:
  enable: true
```
