### DISCUSSION TITLE
plugin allow_publish (pkg) got a undefined version

### DISCUSSION THREAD

**Discussion by sheweifan** [verdaccio/verdaccio#2310] [Q&A] [answered]
<img width="314" alt="WX20210626-161541@2x" src="https://user-images.githubusercontent.com/14147143/123507031-cd70e380-d699-11eb-8faf-1cd0c80c5a46.png">

```
 allow_publish(user, pkg, callback) {
    console.log(`pkg`, pkg)
      callback(null, true)
  }
```

how can i get the publish version? thank you

------

I am deploying the NPM privatization service for my company. Our workflow needs to allow only some members to push the official version, while others can only push the beta version.

[npm link:](https://www.npmjs.com/package/verdaccio-publishauth)
The code is very simple. I created a new plugin:

```
class DynamicPublishPlugin {
  constructor(config, stuff) {
    this.config = config;
  }

  allow_publish(user, pkg, callback) {
    const userName = user.name
    const pkgVersion = pkg.version
    const { users } = this.config

    console.log(`pkg`, pkg)

    if (pkgVersion.indexOf('beta')) {
      callback(null, true)
    }
  
    callback(null, users.split(' ').indexOf(userName) > -1)
  }
}

module.exports = (cfg, stuff) => new DynamicPublishPlugin(cfg, stuff);

```

config.yaml like this:

```
storage: /Users/dolor/.local/share/verdaccio/storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  publishauth:
    users: sheweifan
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all

    publish: $authenticated
    unpublish: $authenticated

    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }

```

node: v10.24.0
verdaccio: v4.12.2
