### DISCUSSION TITLE
About configuring HTTPS

### DISCUSSION THREAD

**Discussion by MarsXH** [verdaccio/verdaccio#2387] [Q&A] [answered]
Hello, I have a problem configuring HTTPS access, My config file is as follows:
```
storage: ./storage
plugins: ./plugins

web:
  title: 'NPM'
  gravatar: true 
  sort_packages: desc
i18n:
  web: zh-CN

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  taoBaoNpmJs:
      url: https://registry.npm.taobao.org/
  npmJs:
      url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taoBaoNpmJs npmJs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taoBaoNpmJs npmJs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: http}
listen: 0.0.0.0:4873
```
When I finish deploying verdaccio, There is no problem trying to use HTTP access.
When I use HTTPS to access, The gateway will add a layer of SSL to jump over.
But when I look at the network, I found that the resource is still requesting HTTP:
eg:
- my url: `https://npm.test.mobi/ `
- resource request url: `http://npm.test.mobi/-/static/runtime.f6e570dfe38870a45bf5.js 	`
- error:  `Mixed Content: The page at 'https://npm.test.mobi/' was loaded over HTTPS, but requested an insecure script 'http://npm.test.mobi/-/static/runtime.f6e570dfe38870a45bf5.js'. This request has been blocked; the content must be served over HTTPS.  `

![1629776565436](https://user-images.githubusercontent.com/25813176/130553245-aaff157f-163e-44d4-822d-1cff3baed6f8.jpg)

![WX20210824-114200](https://user-images.githubusercontent.com/25813176/130553429-94ab9b04-6a59-405e-babc-723b1bc570dc.png)

How should I configure them to let them all work properly ?
