### DISCUSSION TITLE
is there a way to persist the JWT tokens?

### DISCUSSION THREAD

**Discussion by aeweda** [verdaccio/verdaccio#2430] [Q&A] [answered]
currently if I restart the container the token is invalidated and I need to do another npm login and generate a new token

so I'm wondering if there is an argument in the config file or some file I need to mount to persist that token.

**Comment by InputNeuron** [comment]
This is really killing us... if a box has any issue and needs to be restarted we have to push out new tokens to ALL of our devs? 

There's no fix for this?

**Comment by juanpicado** [comment, marked as answer]
> currently if I restart the container the token is invalidated and I need to do another npm login and generate a new token

you might describe more about your environments, tokens should not be invalidated because the secret that sign tokens is persisted in the small database (or whatever you use as storage), if you persist your storage correctly this should never happens. Waiting for your detailed info.

**Reply by aeweda** [reply]
@juanpicado here is the current docker-compose we are using
```yml
version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio:5.1.1
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=443
      - VERDACCIO_PROTOCOL=https
    ports:
      - "443:443"
    volumes:
      - "./config:/verdaccio/conf"
      - "./storage:/verdaccio/storage"
      - "./plugins:/verdaccio/plugins"
      - "./cache/npm:/opt/verdaccio/.npm"
      - "./cache/yarn:/opt/verdaccio/.yarn/cache"

networks:
  node-network:
    driver: bridge
```
