### DISCUSSION TITLE
WebUI packages disappeared after restarting the server

### DISCUSSION THREAD

**Discussion by mopinon** [verdaccio/verdaccio#2441] [Q&A] [answered]
**Your Environment**
  
 * **verdaccio version**: 5.1.4
 * **node version** 14.17.6
 * **package manager**: npm@6.14.15
 * **os**: clients: [mac, win10], server: ubuntu
 * **platform**: docker

**Describe the bug**
Packages disappeared from WebUI after restarting the server and update verdaccio 5.1.0 -> 5.1.4, package comes back after upgrading with version history, all packages remained on the server in the folder

_**docker-compose.yaml**_
```yaml
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
    user: "root:root"  
networks:
  node-network:
    driver: bridge

```

**_config.yaml_**
```yaml
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: davs
  '**':
    access: $authenticated
    publish: davs
    proxy: npmjs
logs:
  - { type: stdout, format: pretty, level: http }
```

**Comment by alexn-s** [comment]
i have the same issue.

are there any updates on this problem?

**Comment by thorin8k** [comment]
I also have the same issue. 

I couldn't find a way to keep the packages listed on the ui so i gave up and stop upgrading.

**Comment by Link2Twenty** [comment]
Oh good I thought it was just me

**Comment by mbtools** [comment, marked as answer]
https://github.com/verdaccio/verdaccio/issues/3943 fixed by https://github.com/verdaccio/verdaccio/pull/3944

**Reply by hellorayza** [reply]
I have a set of data that used to run on version 5.31.
Now, when I run this data on version 5.33, I still can't find the package on webUI.

**data path**
```bash
admin@NAS2:/$ ls /volume1/docker/verdaccio
conf  plugins  storage
admin@NAS2:/$ ls /volume1/docker/verdaccio/storage/
data
admin@NAS2:/$ ls /volume1/docker/verdaccio/storage/data
outils  zutils
```
**docker container config / docker run**
![image](https://github.com/user-attachments/assets/f90d08a7-1860-4f35-bcce-8617b448fd5f)

**config.yaml**
```yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

# https://verdaccio.org/zh-CN/docs/configuration
security:
  api:
    migrateToSecureLegacySignature: true

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # convert your UI to the dark side
  # darkMode: true
  # logo: http://somedomain/somelogo.png
  # favicon: http://somedomain/favicon.ico | /path/favicon.ico

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    algorithm: bcrypt
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmmirror:
    url: https://registry.npmmirror.com/
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmmirror

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60
  max_body_size: 1000mb

middlewares:
  audit:
    enabled: true

max_body_size: 1000mb
# log settings
log: { type: stdout, format: pretty, level: http }

#experiments:
#  # support for npm token command
#  token: false
#  # disable writing body size to logs, read more on ticket 1912
#  bytesin_off: false
#  # enable tarball URL redirect for hosting tarball with a different server, the tarball_url_redirect can be a template string
#  tarball_url_redirect: 'https://mycdn.com/verdaccio/${packageName}/${filename}'
#  # the tarball_url_redirect can be a function, takes packageName and filename and returns the url, when working with a js configuration file
#  tarball_url_redirect(packageName, filename) {
#    const signedUrl = // generate a signed url
#    return signedUrl;
#  }

# This affect the web and api (not developed yet)
#i18n:
#web: en-US
listen: 0.0.0.0:4873

```

**.verdaccio-db.json**
```json
{"list":["outils","zutils"],"secret":"xxxx same as inhtpasswd "}
```
```
admin@NAS2:/$ sudo docker ps -a
Password: 
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS                   PORTS                                                     NAMES
bcd064e16822   docker.1ms.run/verdaccio/verdaccio:5.33.0   "uid_entrypoint /bin…"   49 minutes ago   Up 49 minutes            0.0.0.0:4873->4873/tcp, :::4873->4873/tcp         verdaccio-5.33

admin@NAS2:/$ sudo docker exec -it bcd064e16822  ls -l /verdaccio/storage/
total 0
drwxr-xr-x    1 verdacci nogroup         36 Apr 14 03:24 data
admin@NAS2:/$ sudo docker exec -it bcd064e16822  ls -l /verdaccio/storage/data
total 0
admin@NAS2:/$  sudo docker inspect bcd064e16822 | grep -A10 Mounts
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/docker/verdaccio",
                "Destination": "/verdaccio",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",

```
