### DISCUSSION TITLE
Two registries, same scope - for migration?

### DISCUSSION THREAD

**Discussion by jwo** [verdaccio/verdaccio#2464] [Q&A] [answered]
We have an internal legacy npm server and are wanting to migrate over to github packages... so I'm wondering if the two uplinks with verdaccio can help with that.

For example, if our scope is @companyco , and there's a package named coolutils... could verdaccio help us do the following:

* fetch @companyco/coolutils v1 from npm.companyco registry
* fetch @companyco/coolutils v2 from github.compancyco registry

I realize this is a super edge case; but it seems like it _might_ work -- depending on how the lookup works.

**Comment by sergiohgz** [comment, marked as answer]
You can setup a scope to use multiple proxies as shown here: https://verdaccio.org/docs/packages#use-multiple-uplinks

In your case, I would set v1 registry first and, because v2 packages should not exist there, it will fallback in GH registry

**Reply by juanpicado** [reply]
Exactly as @sergiohgz says, here an example

```yaml
   uplinks:
     privatecorp:
           .........
     github:
           ...........
  '@companyco/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: privatecorp github
```
