### DISCUSSION TITLE
Getting `E500` from npm when trying to change password

### DISCUSSION THREAD

**Discussion by sepsol** [verdaccio/verdaccio#2678] [Q&A]
**Your Environment**
  
SERVER:
 * **verdaccio version**: `5.2.2`
 * **node version** : `16.13.0 (LTS)`
 * **package manager**: `npm@8.1.3`
 * **os**: `Linux Server Focal v20.04.3 (LTS)`
 * **platform**: `npm`

 CLIENT:
 * **node version** : `14.18.0 (LTS)`
 * **package manager**: `npm@8.1.2`
 * **os**: `macOS Monterey v12.0.1`
 * **platform**: `npm`

**Describe the bug**

I have set up my `verdaccio` server as described [here](https://gist.github.com/sepsol/1ae4f98ab79a2b88a6fd27b7f86f96a3). Now whenever I or my users try to reset their password using the recommended method mentioned [here](https://medium.com/verdaccio/verdaccio-4-alpha-release-400c7ed4884d), they get the following error:
```sh
npm ERR! code E500
npm ERR! 500 Internal Server Error - POST http://192.168.150.105:4873/-/npm/v1/user - Invalid old Password
npm verb exit 1
```
We've check multiple times and we're positive that the old password was entered correctly since we were able to login using:
```sh
npm login --registry=OUR_SERVER_IP_AND_PORT
```

**To Reproduce**

1. Set up the server as described [here](https://gist.github.com/sepsol/1ae4f98ab79a2b88a6fd27b7f86f96a3).
2. Run `npm profile set password -ddd --registry=YOUR_REGISTRY_IP` on your client
3. See the error being thrown at you

**Expected behavior**

**Screenshots, server logs, package manager log**

CLIENT TERMINAL:
```sh
$ npm profile set password -ddd --registry=http://192.168.150.105:4873
npm verb cli [
npm verb cli   '/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/node',
npm verb cli   '/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/npm',
npm verb cli   'profile',
npm verb cli   'set',
npm verb cli   'password',
npm verb cli   '-ddd',
npm verb cli   '--registry=http://192.168.150.105:4873'
npm verb cli ]
npm info using npm@8.1.2
npm info using node@v14.18.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/npmrc Completed in 4ms
npm timing config:load:builtin Completed in 4ms
npm timing config:load:cli Completed in 5ms
npm timing config:load:env Completed in 0ms
npm timing config:load:project Completed in 5ms
npm timing config:load:file:/Users/Sepehr/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/Sepehr/.nvm/versions/node/v14.18.0/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 19ms
npm timing npm:load:configload Completed in 19ms
npm timing npm:load:setTitle Completed in 16ms
npm timing npm:load:setupLog Completed in 1ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:cleanupLog Completed in 1ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 45ms
Current password: 
New password: 
Again: 
npm timing command:profile Completed in 17863ms
npm verb stack HttpErrorGeneral: 500 Internal Server Error - POST http://192.168.150.105:4873/-/npm/v1/user - Invalid old Password
npm verb stack     at /Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm verb stack     at async Profile.set (/Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/lib/profile.js:229:20)
npm verb statusCode 500
npm verb cwd /Users/Sepehr
npm verb Darwin 21.1.0
npm verb argv "/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/node" "/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/npm" "profile" "set" "password" "-ddd" "--registry=http://192.168.150.105:4873"
npm verb node v14.18.0
npm verb npm  v8.1.2
npm ERR! code E500
npm ERR! 500 Internal Server Error - POST http://192.168.150.105:4873/-/npm/v1/user - Invalid old Password
npm verb exit 1
npm timing npm Completed in 18229ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Sepehr/.npm/_logs/2021-11-16T19_55_36_974Z-debug.log
```

CLIENT LOGS:
```
Sepehr@MacBook-Pro ~
$ cat /Users/Sepehr/.npm/_logs/2021-11-16T19_55_36_974Z-debug.log 
0 verbose cli [
0 verbose cli   '/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/node',
0 verbose cli   '/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/npm',
0 verbose cli   'profile',
0 verbose cli   'set',
0 verbose cli   'password',
0 verbose cli   '-ddd',
0 verbose cli   '--registry=http://192.168.150.105:4873'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v14.18.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 5ms
10 timing config:load:file:/Users/Sepehr/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/Users/Sepehr/.nvm/versions/node/v14.18.0/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 19ms
18 timing npm:load:configload Completed in 19ms
19 timing npm:load:setTitle Completed in 16ms
20 timing npm:load:setupLog Completed in 1ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:cleanupLog Completed in 1ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 45ms
26 timing command:profile Completed in 17863ms
27 verbose stack HttpErrorGeneral: 500 Internal Server Error - POST http://192.168.150.105:4873/-/npm/v1/user - Invalid old Password
27 verbose stack     at /Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
27 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
27 verbose stack     at async Profile.set (/Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/lib/profile.js:229:20)
28 verbose statusCode 500
29 verbose cwd /Users/Sepehr
30 verbose Darwin 21.1.0
31 verbose argv "/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/node" "/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/npm" "profile" "set" "password" "-ddd" "--registry=http://192.168.150.105:4873"
32 verbose node v14.18.0
33 verbose npm  v8.1.2
34 error code E500
35 error 500 Internal Server Error - POST http://192.168.150.105:4873/-/npm/v1/user - Invalid old Password
36 verbose exit 1
```

SERVER LOGS:
```sh
administrator@package-server:~$ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/administrator/.pm2/pm2.log last 15 lines:
PM2        | 2021-11-16T17:48:00: PM2 log: Stopping app:verdaccio id:0
PM2        | 2021-11-16T17:48:00: PM2 log: App [verdaccio:0] exited with code [0] via signal [SIGINT]
PM2        | 2021-11-16T17:48:00: PM2 log: pid=2977 msg=process killed
PM2        | 2021-11-16T17:48:00: PM2 log: App [verdaccio:0] starting in -fork mode-
PM2        | 2021-11-16T17:48:00: PM2 log: App [verdaccio:0] online
PM2        | 2021-11-16T18:12:07: PM2 log: Stopping app:verdaccio id:0
PM2        | 2021-11-16T18:12:07: PM2 log: App [verdaccio:0] exited with code [0] via signal [SIGINT]
PM2        | 2021-11-16T18:12:07: PM2 log: pid=3003 msg=process killed
PM2        | 2021-11-16T18:12:07: PM2 log: App [verdaccio:0] starting in -fork mode-
PM2        | 2021-11-16T18:12:07: PM2 log: App [verdaccio:0] online
PM2        | 2021-11-16T19:44:57: PM2 log: Stopping app:verdaccio id:0
PM2        | 2021-11-16T19:44:57: PM2 log: App [verdaccio:0] exited with code [0] via signal [SIGINT]
PM2        | 2021-11-16T19:44:57: PM2 log: pid=3041 msg=process killed
PM2        | 2021-11-16T19:44:57: PM2 log: App [verdaccio:0] starting in -fork mode-
PM2        | 2021-11-16T19:44:57: PM2 log: App [verdaccio:0] online

/home/administrator/.pm2/logs/verdaccio-error.log last 15 lines:
0|verdacci | (node:2318) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
0|verdacci | (Use `node --trace-deprecation ...` to show where the warning was created)
0|verdacci | (node:3003) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
0|verdacci | (Use `node --trace-deprecation ...` to show where the warning was created)
0|verdacci | (node:3041) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
0|verdacci | (Use `node --trace-deprecation ...` to show where the warning was created)
0|verdacci | (node:3192) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
0|verdacci | (Use `node --trace-deprecation ...` to show where the warning was created)

/home/administrator/.pm2/logs/verdaccio-out.log last 15 lines:
0|verdacci |  http --- 200, user: sepsol(192.168.150.106), req: 'POST /-/npm/v1/user', bytes: 88/0
0|verdacci |  error--- An error has been produced
0|verdacci |             updating the password for sepsol. Error: Invalid old Password
0|verdacci |  http --- 192.168.150.106 requested 'GET /-/npm/v1/user'
0|verdacci |  http --- 200, user: null(192.168.150.106), req: 'GET /-/npm/v1/user', bytes: 0/0
0|verdacci |  http --- 192.168.150.106 requested 'POST /-/npm/v1/user'
0|verdacci |  http --- 200, user: sepsol(192.168.150.106), req: 'POST /-/npm/v1/user', bytes: 91/0
0|verdacci |  error--- An error has been produced
0|verdacci |             updating the password for sepsol. Error: Invalid old Password
0|verdacci |  http --- 192.168.150.106 requested 'GET /-/npm/v1/user'
0|verdacci |  http --- 200, user: null(192.168.150.106), req: 'GET /-/npm/v1/user', bytes: 0/0
0|verdacci |  http --- 192.168.150.106 requested 'POST /-/npm/v1/user'
0|verdacci |  http --- 200, user: sepsol(192.168.150.106), req: 'POST /-/npm/v1/user', bytes: 90/0
0|verdacci |  error--- An error has been produced
0|verdacci |             updating the password for sepsol. Error: Invalid old Password
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /home/administrator/verdaccio/storage
# path to a directory with plugins to include
plugins: /home/administrator/verdaccio/plugins

# You can specify listen address (or simply a port).
# If you add multiple values, verdaccio will listen on all of them.
#
# Examples:
#
#listen:
# - localhost:4873            # default value
# - http://localhost:4873     # same thing
# - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
# - https://example.org:4873  # if you want to use https
# - [::1]:4873                # ipv6
# - unix:/tmp/verdaccio.sock    # unix socket
listen:
  0.0.0.0:4873

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # convert your UI to the dark side
  # darkMode: true
  # logo: http://somedomain/somelogo.png
  # favicon: http://somedomain/favicon.ico | /path/favicon.ico

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: /home/administrator/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@mbhc/*':
    # company's packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated

  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs: { type: stdout, format: pretty, level: http }

#experiments:
#  # support for npm token command
#  token: false
#  # disable writing body size to logs, read more on ticket 1912
#  bytesin_off: false
#  # enable tarball URL redirect for hosting tarball with a different server, the tarball_url_redirect can be a template string
#  tarball_url_redirect: 'https://mycdn.com/verdaccio/${packageName}/${filename}'
#  # the tarball_url_redirect can be a function, takes packageName and filename and returns the url, when working with a js configuration file
#  tarball_url_redirect(packageName, filename) {
#    const signedUrl = // generate a signed url
#    return signedUrl;
#  }

# This affect the web and api (not developed yet)
#i18n:
#web: en-US
```

**Environment information**

```sh
administrator@package-server:~$ verdaccio --info

Environment Info:
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmGlobalPackages:
    verdaccio: 5.2.2
```

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
```sh
administrator@package-server:~$ NODE_DEBUG=request verdaccio
 warn --- config file  - /home/administrator/verdaccio/config.yaml
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/5.2.2
```
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
```sh
administrator@package-server:~$ DEBUG=verdaccio* verdaccio
  verdaccio:logger setup logger +0ms
  verdaccio:logger logging stdout enabled +1ms
  verdaccio:logger has prettifier? true +1ms
 warn --- config file  - /home/administrator/verdaccio/config.yaml
  verdaccio:logger setup logger +852ms
  verdaccio:logger logging stdout enabled +1ms
  verdaccio:logger has prettifier? true +0ms
  verdaccio:plugin:local-storage sync database started +0ms
  verdaccio:plugin:local-storage sync folder '/home/administrator/verdaccio/storage' created succeed +1ms
  verdaccio:plugin:local-storage sync write succeed +1ms
  verdaccio:plugin:local-storage sync database started +2ms
  verdaccio:plugin:local-storage sync folder '/home/administrator/verdaccio/storage' created succeed +1ms
  verdaccio:plugin:local-storage sync write succeed +0ms
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
  verdaccio static path '/home/administrator/.nvm/versions/node/v16.13.0/lib/node_modules/verdaccio/node_modules/@verdaccio/ui-theme/static' +0ms
  verdaccio:plugin:local-storage storage path selected:  /home/administrator/verdaccio/storage +25ms
  verdaccio:plugin:local-storage storage absolute path:  /home/administrator/verdaccio/storage/@mbhc/test1 +0ms
  verdaccio:plugin:local-storage:fs read a package '@mbhc/test1' +0ms
  verdaccio:plugin:local-storage:fs reading the file: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' +0ms
  verdaccio:plugin:local-storage get full list of packages (1) has been fetched +2ms
  verdaccio:plugin:local-storage storage path selected:  /home/administrator/verdaccio/storage +2ms
  verdaccio:plugin:local-storage storage absolute path:  /home/administrator/verdaccio/storage/@mbhc/test1 +0ms
  verdaccio:plugin:local-storage:fs read a package '@mbhc/test1' +3ms
  verdaccio:plugin:local-storage:fs reading the file: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' +0ms
  verdaccio:plugin:local-storage get full list of packages (1) has been fetched +1ms
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/5.2.2
  verdaccio:plugin:local-storage:fs error reading the file: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' with error [Error: ENOENT: no such file or directory, open '/home/administrator/verdaccio/storage/@mbhc/test1/package.json'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' } +7ms
  verdaccio:plugin:local-storage:fs read storage file '@mbhc/test1' has failed with error [Error: ENOENT: no such file or directory, open '/home/administrator/verdaccio/storage/@mbhc/test1/package.json'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' } +2ms
  verdaccio:plugin:local-storage:fs error reading the file: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' with error [Error: ENOENT: no such file or directory, open '/home/administrator/verdaccio/storage/@mbhc/test1/package.json'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' } +0ms
  verdaccio:plugin:local-storage:fs read storage file '@mbhc/test1' has failed with error [Error: ENOENT: no such file or directory, open '/home/administrator/verdaccio/storage/@mbhc/test1/package.json'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/administrator/verdaccio/storage/@mbhc/test1/package.json' } +1ms
```
- `$ npm -ddd` prints:
SERVER:
```sh
administrator@package-server:~$ npm -ddd
npm verb cli [
npm verb cli   '/home/administrator/.nvm/versions/node/v16.13.0/bin/node',
npm verb cli   '/home/administrator/.nvm/versions/node/v16.13.0/bin/npm',
npm verb cli   '-ddd'
npm verb cli ]
npm info using npm@8.1.3
npm info using node@v16.13.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/home/administrator/.nvm/versions/node/v16.13.0/lib/node_modules/npm/npmrc Completed in 4ms
npm timing config:load:builtin Completed in 5ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/administrator/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/home/administrator/.nvm/versions/node/v16.13.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 2ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 11ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 42ms
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term>
npm help npm       more involved overview

All commands:

    access, adduser, audit, bin, bugs, cache, ci, completion,
    config, dedupe, deprecate, diff, dist-tag, docs, doctor,
    edit, exec, explain, explore, find-dupes, fund, get, help,
    hook, init, install, install-ci-test, install-test, link,
    ll, login, logout, ls, org, outdated, owner, pack, ping,
    pkg, prefix, profile, prune, publish, rebuild, repo,
    restart, root, run-script, search, set, set-script,
    shrinkwrap, star, stars, start, stop, team, test, token,
    uninstall, unpublish, unstar, update, version, view, whoami

Specify configs in the ini-formatted file:
    /home/administrator/.npmrc
or on the command line via: npm <command> --key=value

More configuration info: npm help config
Configuration fields: npm help 7 config

npm@8.1.3 /home/administrator/.nvm/versions/node/v16.13.0/lib/node_modules/npm
npm verb exit 0
npm timing npm Completed in 163ms
npm verb code 1
```
CLIENT:
```sh
Sepehr@MacBook-Pro ~
$ npm -ddd
npm verb cli [
npm verb cli   '/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/node',
npm verb cli   '/Users/Sepehr/.nvm/versions/node/v14.18.0/bin/npm',
npm verb cli   '-ddd'
npm verb cli ]
npm info using npm@8.1.2
npm info using node@v14.18.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/Users/Sepehr/.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/Users/Sepehr/.nvm/versions/node/v14.18.0/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 10ms
npm timing npm:load:configload Completed in 10ms
npm timing npm:load:setTitle Completed in 15ms
npm timing npm:load:setupLog Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 33ms
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term>
npm help npm       more involved overview

All commands:

    access, adduser, audit, bin, bugs, cache, ci, completion,
    config, dedupe, deprecate, diff, dist-tag, docs, doctor,
    edit, exec, explain, explore, find-dupes, fund, get, help,
    hook, init, install, install-ci-test, install-test, link,
    ll, login, logout, ls, org, outdated, owner, pack, ping,
    pkg, prefix, profile, prune, publish, rebuild, repo,
    restart, root, run-script, search, set, set-script,
    shrinkwrap, star, stars, start, stop, team, test, token,
    uninstall, unpublish, unstar, update, version, view, whoami

Specify configs in the ini-formatted file:
    /Users/Sepehr/.npmrc
or on the command line via: npm <command> --key=value

More configuration info: npm help config
Configuration fields: npm help 7 config

npm@8.1.2 /Users/Sepehr/.nvm/versions/node/v14.18.0/lib/node_modules/npm
npm verb exit 0
npm timing npm Completed in 152ms
npm verb code 1
```
- `$ npm config get registry` prints:
```sh
Sepehr@MacBook-Pro ~
$ npm config get registry
https://registry.npmjs.org/
```
**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
