### DISCUSSION TITLE
migrate from v4 to v5 - the urls to tarballs are broken

### DISCUSSION THREAD

**Discussion by osher** [verdaccio/verdaccio#2702] [Q&A]
**Your Environment**
  
 * **verdaccio version**: 5.2.2
 * **node version** [12.x.x]:
 * **package manager**: [npm@6]
 * **os**: [linux] 
 * **platform**: [docker]

**Describe the bug**

I'm running verdaccio locally in a docker.
When I'm addressing it from my localhost natively - things worked.
When I'm addressing it from a container - npm gets stuck and ends with connection-refused error - as it tries to connect to `localhost`.
On the server logs you see only 'granted access' messages for responses to information inquiry, no hits of downloading archives.

See details in reproduction *& logs below.

**To Reproduce**

0. given a package available trough the upstream - `@company/package`.
1. run verdaccio in a docker container on your local docker daemon with the configured upstream, exposing and binding the default port (4873:4873), name it `ci-npm`.
2. use it to install natively - all well.
```
npm i @company/package --registry http://localhost:4873
```
3. use it to install from a container in the same docker network (like `ci-npm`)
```
docker run --rm node:alpine 
# npm i @company/package --registry http://ci-npm:4873
```

**Expected behavior**

successful installation (just like it worked at v4).

Specifically - that the URLs to the tarballs will use the hostname it was addressed with.
Now it defaults to `localhost`.

I expected this default to be overridden only when the `VERDACCIO_PUBLIC_URL` is set.
If it's not set - I expect the old behavior.

**In more detail**
In more detail - version 4 works because it knows to return in the tarball url using the same `Host` header it heard.
While version 5 lets you configure the hostname with a new var - it breaks the old behavior - when this variable is not provided it defaults to `localhost` as hostname - which is wrong.

Since I'm not using a proxy - I did not expect to be have to update this variable.

The usecase is - verdaccio acts like a CI intermediary server for a big monorepo build.
Projects are built in stages and packageas are published to verdaccio so they can be consumed in later build stages.
Only when the entire repo build succeeds - the packages are all published together to the company-level registry.

When developers work with it - they run verdaccio in a container. They use it in two "flavors" interchangably.
Either install from it on their native OS (addressed like localhost:4873) , or from docker-containers (addressed like verdaccio:4873) each developer and her own per-case preferences.

So - asking us to set a fixed name to be addressed from both native and containerized env will also require me to ask developers update the hosts file of their host OS, which I managed so far not to need it at all.

I appreciate the new capability for behind-proxy server, but not in expanse of breaking the setup...
I hope a solution could be found soon. Should not be that a bummer...
Keep up the good work!

**Screenshots, server logs, package manager log**

npm client log from inside the container:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@company/package',
1 verbose cli   '--registry',
1 verbose cli   'http://host.docker.internal:4873'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.9.0
4 verbose npm-session 95ba08e4f41d1c02
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 http://host.docker.internal:4873/@wm-insights%2fenv-reader 71ms (from cache)
8 silly fetchPackageMetaData error for @company/package@latest request to http://localhost:4873/@wm-insights%2fenv-reader/-/env-reader-1.4.3.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:4873
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 70144ms
11 verbose type system
12 verbose stack FetchError: request to http://localhost:4873/@company%2fpackage/-/package-1.4.3.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:4873
12 verbose stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
12 verbose stack     at ClientRequest.emit (events.js:209:13)
12 verbose stack     at Socket.socketErrorListener (_http_client.js:406:9)
12 verbose stack     at Socket.emit (events.js:209:13)
12 verbose stack     at emitErrorNT (internal/streams/destroy.js:91:8)
12 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
13 verbose cwd /project
14 verbose Linux 5.10.16.3-microsoft-standard-WSL2
15 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@company/package" "--registry" "http://host.docker.internal:4873"
16 verbose node v12.9.0
17 verbose npm  v6.10.2
18 error code ECONNREFUSED
19 error errno ECONNREFUSED
20 error FetchError: request to http://localhost:4873/@company%2fpackage/-/package-1.4.3.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:4873
20 error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
....
22 verbose exit [ 1, true ]
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf

storage: /verdaccio/storage
plugins: ./plugins
max_body_size: 200mb

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  company-npm:
    url: https://artifactory.company.com/artifactory/api/npm/npm/
    auth:
      type: Basic
      token_env: WM_NPM_REGISTRY_TOKEN
    max_fails: 20
    #cache: false
    maxage: 60m
    timeout: 10s
    agent_options:
      timeout: 10000

packages:
  '@*/*':
    access: $all
    publish: $all
    unpublish: $authenticated
    proxy: company-npm 

  '**':
    access: $all
    publish: $all
    unpublish: $authenticated
    proxy: company-npm 

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: false

logs: { type: stdout, format: pretty, level: info }

```

**Environment information**

```
{19:29}~/ws:ci--verdaccio-5 ✗ ➭ docker exec -it ws_verdaccio_1 sh
~ $ verdaccio --info
sh: verdaccio: not found
```
??? interesting. 
Anyway - the image is [vercaccio:5.2.2](https://hub.docker.com/layers/verdaccio/verdaccio/5.2.2/images/sha256-a40a90e7714a7876d399146c8184d3c1e5de1ddf8b979350aa19cd81e63f9cb2?context=explore)

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', '-ddd' ]
npm info using npm@6.10.2
npm info using node@v12.9.0

<and the synopsis & help>
```
- `$ npm config get registry` prints:
The URL to the company registry, but it's irrelevant, the scenario uses `--registry` flags

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇 

I would, but I REALLLLY hate type-script. So no :(
