### DISCUSSION TITLE
Unable to download the latest public bag

### DISCUSSION THREAD

**Discussion by AmbitionJs** [verdaccio/verdaccio#2741] [Q&A]
I want to control all the bags download through Verdaccio, the following is my related configuration：

**.npmrc**
``` 
registry=myVerdaccioUrl
```

**VerdaccioConfigFile:**
```
...
uplinks:
  taobao:
    url: https://registry.npmmirror.com/
    cache: true
    maxage: 30m
    max_fails: 100

packages:
'**':
    access: $all
    publish: dustess
    proxy:
      - taobao
...
```

When I download the latest package, I will "find the corresponding version：
![image](https://user-images.githubusercontent.com/45837094/145344361-6784cccf-bb64-4549-b834-2b9d08e003f3.png)
I really want to know if I am confirmed. thanks
