### DISCUSSION TITLE
pull packages

### DISCUSSION THREAD

**Discussion by njavilas** [verdaccio/verdaccio#2752] [Q&A]
Hello, good morning, is there a way to make a pull packages to be able to work online, it turns out that you don't always download the packets .. therefore it is not possible to finish working offline

my console 
![image](https://user-images.githubusercontent.com/47610140/145690069-a6ed8f97-a80e-44d2-8e33-9183185a8075.png)

![image](https://user-images.githubusercontent.com/47610140/145690240-4e5c8e57-1a40-432c-868c-8a2dc43d3a4a.png)

```

storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: Insert Mendoza
  
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    #proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    #proxy: npmjs


server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

publish:
  allow_offline: false

logs: { type: stdout, format: pretty, level: http }

https:    
  key: /etc/letsencrypt/privkey.pem   
  cert: /etc/letsencrypt/fullchain.pem 


```

It's work with npm update --loglevel verbose --no-audit --force
