### DISCUSSION TITLE
Docker 5.1.0-5.4.0 versions results in "Cannot find module 'pino'" error

### DISCUSSION THREAD

**Discussion by kerbs17** [verdaccio/verdaccio#2857] [Q&A] [answered]
**Your Environment**
  
 * **verdaccio version**: 5.1.0-5.4.0
 * **node version** [12.x.x, 14.x.x]: 14.16.1
 * **package manager**: npm@6.14.12
 * **os**: mac
 * **platform**: docker

**Describe the bug**

Running the docker image 5.1.0 and later results in error trying to run the container:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'pino'
Require stack:
- /opt/verdaccio/build/lib/logger/logger.js
- /opt/verdaccio/build/lib/logger/index.js
- /opt/verdaccio/build/lib/cli.js
- /opt/verdaccio/bin/verdaccio
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/opt/verdaccio/build/lib/logger/logger.js:11:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/verdaccio/build/lib/logger/logger.js',
    '/opt/verdaccio/build/lib/logger/index.js',
    '/opt/verdaccio/build/lib/cli.js',
    '/opt/verdaccio/bin/verdaccio'
  ]
}
```

Note: Works fine on the docker 5.0.4 build
**To Reproduce**

Dockerfile:
```
FROM verdaccio/verdaccio:5.4.0

COPY config.yaml /config.yaml

CMD source /verdaccio/config/env.sh && $VERDACCIO_APPDIR/bin/verdaccio --config /config.yaml --listen $VERDACCIO_PROTOCOL://0.0.0.0:${VERDACCIO_PORT}
```

config.yaml
```
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/config/htpasswd
    max_users: 2

packages:
  '@comp/*':
    access: $all
    publish: $authenticated

publish:
  allow_offline: false

logs: {type: stdout, format: pretty, level: http}

web:
  enable: true
  title: Comp NPM Registry
  primary_color: "#0067ff"
  scope: "@comp"
```

**Expected behavior**

Successful start of docker container

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

See Above
**Environment information**

Running via docker, not able to start
**Debugging output**

Running via docker, all output listed above (error)

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
