### DISCUSSION TITLE
web-ui not visualizing all the libraries

### DISCUSSION THREAD

**Discussion by danilo-patrucco** [verdaccio/verdaccio#2973] [Q&A]
``Hello,

My web-ui is not visualizing all the repos that have been uploaded in the storage folder. I have caching enabled (meaning it is caching the libraries from https://registry.npmjs.org/) but the other libraries do not show.

Here is my config file 
```
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  enable: true
  title: something Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  primary_color: "#121417"
  sort_packages: asc
  darkMode: true

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: something
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 100


# a list of other known repositories we can talk to
uplinks:
 npmjs:
    url: https://registry.npmjs.org/

packages:
  '@shi/*':
    access: $authenticated
    publish: something
    unpublish: something
  '@shicis/*':
    access: $authenticated
    publish: something
    unpublish: something
  '@stratascale/*':
    access: $authenticated
    publish: something
    unpublish: something
  '@*/*':
    access: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    proxy: npmjs
    # if package is not available locally, proxy requests to 'npmjs' registry

middlewares:
  audit:
    enabled: true

# log settings
# log settings
logs:
  # Logger as STDOUT
  { type: stdout, format: pretty, level: http }
  # Logger as STDOUT as JSON
  # { type: stdout, format: json, level: http }
  # Logger as STDOUT as JSON
  # { type: stdout, format: pretty-timestamped, level: http }
  # Logger as STDOUT as custom prettifier
  # { type: stdout, plugin: { dest: '@verdaccio/logger-prettify' : options: { foo: 1, bar: 2}}, level: http }
  # Logger as file
  # { type: file, path: verdaccio.log, level: http}
  # FIXME: this should be documented
# More info about log rotation https://github.com/pinojs/pino/blob/master/docs/help.md#log-rotation

flags:
  # support for npm token command
  token: false
  # support for the new v1 search endpoint, functional by incomplete read more on ticket 1732
  search: false
# This affect the web and api (not developed yet)
#i18n:
#web: en-US
```
