### DISCUSSION TITLE
Setting VERDACCIO_PUBLIC_URL value

### DISCUSSION THREAD

**Discussion by sreejaptfa** [verdaccio/verdaccio#3055] [Q&A] [answered]
Hi! We are upgrading from v 4.x to 5.x. Below is our config.yml:

```
#
# #
# Ansible managed
#
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /home/verdaccio/verdaccio/storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
# == Change - log to a file
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}


listen: 0.0.0.0:4873

url_prefix: '/'
https_proxy: 'https://ourdomain.test.org/'
```

do we add VERDACCIO_PUBLIC_URL  to this file? 
Currently, we have VERDACCIO_PUBLIC_URL set up as linux env variable. When we access via our vanity url 
 'https://ourdomain.test.org/', the page source has 
"base":"http://<server_hostname>:4873/" which results in a blank page.

@juanpicado 
Could you please help us with configuring VERDACCIO_PUBLIC_URL

**Comment by jaysonpotter** [comment]
Same here. I was setting this up locally and trying to test out the VERDACCIO_PUBLIC_URL configuration option and nothing I've tried seems to have worked. 

I set VERDACCIO_PUBLIC_URL as a temporary env variable on macos, that didn't work. 
I also went to the install directory and plopped an .env file, containing VERDACCIO_PUBLIC_URL, and that didn't seem to work either. 

Thank you for any help @juanpicado!!

**Comment by jaysonpotter** [comment, marked as answer]
Alright [after reading a little in the node docs](https://nodejs.dev/learn/how-to-read-environment-variables-from-nodejs) figured out a way to get this running and testing that environment variable locally that I know could help out others. 

`VERDACCIO_PUBLIC_URL=https://somedomain.org verdaccio`

**Reply by YiFan-1024** [reply]
Where do we set VERDACCIO_PUBLIC_URL ?

**Reply by juanpicado** [reply]
It's an environment variable, 

https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/

**Reply by juanpicado** [reply]
Also you can see reply here https://github.com/verdaccio/verdaccio/discussions/3055#discussioncomment-3746590

**Comment by juanpicado** [comment]
`VERDACCIO_PUBLIC_URL` only has effect on the UI, it's meant for environments where need a more dinamyc approach and requires the UI, but does not affect the port of domain of the server.

Running on the terminal the node js cli `VERDACCIO_PUBLIC_URL=https://somedomain.org verdaccio` as @jaysonpotter has shared above

You can review which url the UI using checking the chrome dev tool panel

![image](https://user-images.githubusercontent.com/558752/157815252-66e99d74-487b-4849-a0fe-4578ccfd367c.png)

or typing `__VERDACCIO_BASENAME_UI_OPTIONS` this on the console

![image](https://user-images.githubusercontent.com/558752/157815646-274f2475-43c6-4c80-95b8-3ba6cf7f924e.png)

The `base` is what the page uses for load JS, CSS assets.

**Reply by jaysonpotter** [reply]
Thank you for verifying Juan! Hope you have a wonderful weekend.

**Reply by juanpicado** [reply]
Likewise!

**Comment by sreejaptfa** [comment]
@jaysonpotter and @juanpicado , Thank you both for your help. Have a great weekend!

**Comment by alamothe** [comment]
`VERDACCIO_PUBLIC_URL` will almost always need to be configured when Verdaccio is exposed via load balancer (Kubernetes):
- why is it not in `config.yaml`?
- why is it not documented?

**Reply by juanpicado** [reply]
It's not documented? https://verdaccio.org/docs/configuration#url-prefix

**Reply by juanpicado** [reply]
> why is it not in config.yaml?

Because the host header is dynamic, setup up on static file is not a good choice, 99% of user requests usually use in a dynamically way, since Verdaccio rely on the `Host` header which is external configured, it was decided `VERDACCIO_PUBLIC_URL` also works in that way. Do you have any good reason why should be on the config.yaml file? I'd like to hear more. Also setup env variables for Docker and Helm is much easier than force people update the yaml file dynamically.

**Reply by alamothe** [reply]
> It's not documented? https://verdaccio.org/docs/configuration#url-prefix

No, it is mentioned as a side note for "URL Prefix" field in "Configuration file" section. It doesn't have much to do with either. There probably should be another place/section which explains how to expose Verdaccio publicly. 

> Do you have any good reason why should be on the config.yaml file?

Yes, because configuration should be in a single place, not in 3+ places. At the very least there should be a section "Environment variables" which explains environment variables that Verdaccio uses (as there is a section for "Configuration file").

**Reply by juanpicado** [reply]
> There probably should be another place/section which explains how to expose Verdaccio publicly.

I'm open to suggestions, or even better, PR :)

> Yes, because configuration should be in a single place, not in 3+ places. 

Well, not always easy unfortunately. 

> At the very least there should be a section "Environment variables" which explains environment variables that Verdaccio uses (as there is a section for "Configuration file").

Good you mention that, https://github.com/verdaccio/verdaccio/blob/master/docs/env.variables.md some improvements are made for next major (6.x), so I guess is what you expect to have. (this markdown refers to 6.x, I'm showing this as an example for 5.x)

---

but, suggestions are very welcome as also the help, for now I'm sure we can improve current status docs even more, if you consider https://github.com/verdaccio/verdaccio/tree/master/website/docs we need a page for env variables, then let's create one (open a PR) and feel free add it to the side bar https://github.com/verdaccio/verdaccio/blob/master/website/sidebars.js wherever you consider fits better so others will get less confused.

**Comment by HamzaRino** [comment]
how do I set a verdaccio nodejs env while running it as a linux service (systemd)?

**Reply by juanpicado** [reply]
https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service

**Reply by HamzaRino** [reply]
https://stackoverflow.com/a/45378063

**Reply by HamzaRino** [reply]
thanks for the fast reply

**Comment by Hamzak100** [comment]
How do I make my verdaccio server start on a ip address that can be publicly accessible? I  am using verdaccio v4

**Comment by ThePlenkov** [comment]
Hi! Just coming back here with a general feedback - I hope someone can hear it. Using VERDACCIO_PUBLIC_URL is extremely not convenient because the server always returns  absolute links with a hostname. It makes it very difficult to use in compose for example.

So i have two services, devcontainer and verdaccio. It's up and running - I can access it from devcontainer, but when I access from the browser via localhost ( because I proxy the port ) - ui doesn't even load because in the html page I have static absolute path like http://verdaccio:4873/some/file.js while I expect to have indeed just localhost ( basically it should be relative path, not absolute ).

Another problem appears when I use VERDACCIO_PUBLIC_URL=http://localhost:4873 as envrionemnt variable for the container. Now UI starts working, but.. I cannot use it as a registry for npm install in my devcontainer.  Because I can access it via --registry http://verdaccio:4873 - but its api still responds with localhost URLs for downloading packages and my devcontainer doesn't understand this. So again - it would be great if middleware could just send relative links, not absolute - then it would just worked. 

The only way I managed to use verdaccio in the compose - is to use a host network for a devcontainer. 
```
version: '3'

services:
  devcontainer:   
    network_mode: host

  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873    
    environment:
      - VERDACCIO_PUBLIC_URL=http://localhost:4873
```

What do you think of this?

Thanks!
