### DISCUSSION TITLE
Uplinks stopped working (solved)

### DISCUSSION THREAD

**Discussion by Tomobodo** [verdaccio/verdaccio#3067] [Q&A] [answered]
Hello everyone,

I'm starting to pull my hair out over my problem. 
Untill recently everything was fine but suddenly uplinks stopped working. 
Looked all over the web, as far as I know my configuration is fine, it worked untill recently.
Didn't touch my server in a while either.

when i try to get a package that is not on my registry, uplinks doesn't seem to work.

Software versions:
server :
 - verdaccio 5.8
 - npm 8.5.0
 - node 16.14.1
 - ubuntu 20.04

local : 
 - npm 6.14.16

when it try :
``` shell
npm i vue --registry https://packages.xyz.com
```

i get

``` shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://packages.xyz.com/vue - no such package available
npm ERR! 404
npm ERR! 404  'vue@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

but my config.yaml look like this :

``` yaml

storage: /home/thomas/.local/share/verdaccio/storage
plugins: /home/thomas/.local/share/verdaccio/plugins

listen: 0.0.0.0:4873

web:
  title: XYZ Package Registry
  gravatar: true
  darkMode: true

auth:
  htpasswd:
    file: /path
    max_users: X

publish:
  allow_offline: true

uplinks:
  npmjs:
    url: https://registry.npmjs.org

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

http_proxy: http://packages.xyz.com
https_proxy: https://packages.xyz.com

logs: { type: file, path: /home/thomas/verdaccio/verdaccio.log, format: pretty-timestamped, level: http}
```

As far as I know I don't have anything else to add for the uplink to work ?
This was working for a while but not anymore, I don't understand what could be the issue. 
verdaccio is ran as a service and has all read write acces to the storage.
I use nginx to serve verdaccio :

```nginx
upstream verdaccio_v4 {
        server xyz.com:4873;
        keepalive 8;
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        charset utf-8;

        server_name packages.xyz.com;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://verdaccio_v4;
                proxy_read_timeout 600;
                proxy_redirect off;
        }

        location ~ ^/verdaccio/(.*)$ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://verdaccio_v4/$1;
                proxy_redirect off;
        }

    ssl_certificate /etc/letsencrypt/live/packages.xyz.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/packages.xyz.com/privkey.pem; # managed by Certbot



}

server {
    if ($host = packages.xyz.games) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;

    server_name packages.xyz.com;
    return 404; # managed by Certbot

}
```

I can't find anything in the verdaccio's log either :

```shell
[2022-03-16 18:26:45] http --- 127.0.0.1 requested 'GET /vue'
[2022-03-16 18:26:45] http --- ESC[33m200ESC[39m, user: ESC[1mnullESC[22m(92.158.149.7 via 127.0.0.1), req: 'GET /vue', bytes: ESC[33m0ESC[39m/ESC[33m0ESC[39m
[2022-03-16 18:26:45] info --- auth/allow_action: access granted to: ESC[90mundefinedESC[39m
[2022-03-16 18:26:45] info --- allowed access for vue
```

Has anyone overcome this problem ? This was working so I must have messed up something but I just can't put the finger on it.

Thank you for your help.
