### DISCUSSION TITLE
403 on publishing a scoped package, behind a reverse proxy, with docker image

### DISCUSSION THREAD

**Discussion by demolitions** [verdaccio/verdaccio#3188] [Q&A] [answered]
I'm pretty sure I botched something in my installation, since it does not seem to be a problem to others.
I'm receiving a 403 error, with "invalid package" as the reason when publishing a scoped package, while I can publish non-scoped packages without any problems.

I`m running verdaccio with docker-compose, using the latest image (at the time of this writing it is version 5.10),
my docker-compose.yml:
```
version: "3"
services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    restart: always
    ports:
      - 4873:4873
    volumes:
      - /srv/verdaccio/conf:/verdaccio/conf
      - /srv/verdaccio/plugins:/verdaccio/plugins
      - /srv/verdaccio/storage:/verdaccio/storage
```
I have given (recursively) all `/srv/verdaccio` ownership to UID 10001, GID 65533 and all three main directories have 777 permissions.
my config.yaml:
```
storage: /verdaccio/storage
plugins: /verdaccio/plugins

web:
  title: Local npm repo
  sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@myscope/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

  '@myscope%2f*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

  '@*/*':
    access: $all
    proxy: npmjs

  'myscope-*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

  '**':
    access: $all
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
```
both ` '@myscope%2f*':` and ` 'myscope-*':` are tries to get it to accept my package, but while the latter one (the unscoped, or "fake-scoped" one) works, the former does not.

It is running behind an apache httpd reverse proxy, this is the virtual host configuration:
```
<VirtualHost *:443>
    ServerName npm.internal.domain
    ProxyPass / http://localhost:4873/
    ProxyPassReverse / http://localhost:4873/
    ProxyPreserveHost on
    ProxyRequests off
    AllowEncodedSlashes NoDecode
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"
    SSLEngine on
    SSLProtocol all -SSLv2
    SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM:+LOW
    SSLCertificateFile /path/to/my/certificate.pem
    SSLCertificateKeyFile /path/to/my/privkey.pem
    SSLCertificateChainFile /path/to/my/chain.pem

    <Files ~ "\.(cgi|shtml|phtml|php3?)$">
        SSLOptions +StdEnvVars
    </Files>
    SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
</VirtualHost>
```
If I remove the `AllowEncodedSlashes NoDecode` directive, the error changes from 403 Forbidden to 404 Not Found, I'm posting both below.

Error with `AllowEncodedSlashes NoDecode`:
```
npm notice 
npm notice 📦  @myscope/cli@1.0.0
npm notice === Tarball Contents === 
npm notice 17.6kB LICENSE     
npm notice 13B    README.md   
npm notice 514B   package.json
npm notice 3.4kB  src/Cli.js  
npm notice === Tarball Details === 
npm notice name:          @myscope/cli                              
npm notice version:       1.0.0                                   
npm notice filename:      @myscope/cli-1.0.0.tgz                    
npm notice package size:  6.7 kB                                  
npm notice unpacked size: 21.6 kB                                 
npm notice shasum:        81ce64d171b16d2f8836e31b516dbfc17ec1a09a
npm notice integrity:     sha512-J5Fmtw8meaNDQ[...]js68E9Oe6GKDg==
npm notice total files:   4                                       
npm notice 
npm notice Publishing to https://npm.internal.domain/
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://npm.internal.domain/@myscope%2fcli - invalid package
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myusername/.npm/_logs/2022-05-19T09_28_02_917Z-debug-0.log
```
Error without `AllowEncodedSlashes NoDecode`:
```
npm notice 
npm notice 📦  @myscope/cli@1.0.0
npm notice === Tarball Contents === 
npm notice 17.6kB LICENSE     
npm notice 13B    README.md   
npm notice 514B   package.json
npm notice 3.4kB  src/Cli.js  
npm notice === Tarball Details === 
npm notice name:          @myscope/cli                              
npm notice version:       1.0.0                                   
npm notice filename:      @myscope/cli-1.0.0.tgz                    
npm notice package size:  6.7 kB                                  
npm notice unpacked size: 21.6 kB                                 
npm notice shasum:        81ce64d171b16d2f8836e31b516dbfc17ec1a09a
npm notice integrity:     sha512-J5Fmtw8meaNDQ[...]js68E9Oe6GKDg==
npm notice total files:   4                                       
npm notice 
npm notice Publishing to https://npm.internal.domain/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://npm.internal.domain/@myscope%2fcli
npm ERR! 404 
npm ERR! 404  '@myscope/cli@1.0.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myusername/.npm/_logs/2022-05-19T09_51_04_533Z-debug-0.log
```
In both cases, the command executed is `npm publish --registry https://npm.internal.domain/ .`

container output with `AllowEncodedSlashes NoDecode` active:
```
Starting verdaccio ... done
Attaching to verdaccio
verdaccio    |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio    | (node:7) Warning: deprecate: multiple logger configuration is deprecated, please check the migration guide.
verdaccio    | (Use `node --trace-warnings ...` to show where the warning was created)
verdaccio    |  warn --- Plugin successfully loaded: verdaccio-htpasswd
verdaccio    |  warn --- Plugin successfully loaded: verdaccio-audit
verdaccio    |  warn --- http address - http://0.0.0.0:4873/ - verdaccio/5.10.2
verdaccio    |  http --- 172.18.0.1 requested 'PUT /@myscope%252fcli'
verdaccio    | (node:7) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
verdaccio    |  http --- 403, user: myusername(192.168.0.173 via 172.18.0.1), req: 'PUT /@myscope%252fcli', error: invalid package
```
Strangely enough, if I remove the `AllowEncodedSlashes NoDecode` directive, no request output is seen from the container:
```
Starting verdaccio ... done
Attaching to verdaccio
verdaccio    |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio    | (node:7) Warning: deprecate: multiple logger configuration is deprecated, please check the migration guide.
verdaccio    | (Use `node --trace-warnings ...` to show where the warning was created)
verdaccio    |  warn --- Plugin successfully loaded: verdaccio-htpasswd
verdaccio    |  warn --- Plugin successfully loaded: verdaccio-audit
verdaccio    |  warn --- http address - http://0.0.0.0:4873/ - verdaccio/5.10.2
```
Can anyone see what I'm missing?
