### DISCUSSION TITLE
verdaccio shows json data nginx

### DISCUSSION THREAD

**Discussion by bolti95** [verdaccio/verdaccio#3193] [Q&A]
I am trying to set up Verdaccio as described here in this article https://verdaccio.org/blog/2018/11/19/setting-up-verdaccio-on-digitalocean/ - to show the UI that allows my packages to be displayed, although I am not using docker or a nodeJs image as described in the article. I can get the reverse proxy working on my IP eg "http://myipaddress" with NO prefix and the packages to display on  "http://myipaddress" .  When I run "verdaccio" I get these messages in my console:
` warn --- config file  - /home/drawandcode/verdaccio/config.yaml
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- web logo is wrong, path /home/drawandcode/logo.png does not exist or is not readable
 warn --- http address - http://127.0.0.1:4873/ - verdaccio/5.10.2
 http --- 127.0.0.1 requested 'GET /verdaccio/'
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for verdaccio
 http --- 200, user: null(127.0.0.1), req: 'GET /verdaccio/', bytes: 0/0`
 
I would ideally like the registry to be displayed at "http://myipaddress/verdaccio" ... not just shown at "http://myipaddress" ... or some on a server block sub domain however I do not own a domain for this project so I am currently looking at hosting applications on server blocks at their own locations on the IP address. e.g. "http://myipaddress/verdaccio" , "http://myipaddress/another-application".  

<img width="580" alt="Screenshot 2022-05-24 at 11 40 45" src="https://user-images.githubusercontent.com/64425758/170014486-e38d8d6d-7e2b-4ee2-b558-9b41b6be142f.png">

<img width="618" alt="Screenshot 2022-05-24 at 11 30 51" src="https://user-images.githubusercontent.com/64425758/170014575-04ff96c2-f53b-4fe1-835d-81c39e9a7dad.png">

This is how my server block is set up for verdaccio:
```
server {
        listen 80;
        listen [::]:80 ipv6only=on;

        server_name xxx.xxx.xxx.xxx;

        location ~ ^/verdaccio/(.*)$ {
                proxy_pass http://localhost:4873;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
}
```

config: 

```
storage: /home/drawandcode/verdaccio/storage/
plugins: ./plugins
web:
  enable: true
  title: Verdaccio
  logo: logo.png
  login: true
  showInfo: true
auth:
  htpasswd:
    file: ./htpasswd
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
   '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
server:
  keepAliveTimeout: 60
listen:
    127.0.0.1:4873
http_proxy: http://xxx.xxx.xxx.xxx/verdaccio
middlewares:
  audit:
    enabled: true
logs: { type: stdout, format: pretty, level: http }
```

How can I get the registry to display at this server block location, not my plain IP... thank you #2200
