### DISCUSSION TITLE
web.title, next to favicon and logo, are not applied to the UI in frontend

### DISCUSSION THREAD

**Discussion by iammati** [verdaccio/verdaccio#3195] [Q&A]
Hello,

I'm running Verdaccio inside a docker environment (via docker-compose configured).
I've applied few changes to the basic `verdaccio/config.yaml` file - which gets mounted to `/verdaccio/conf/config.yaml` (which happens by the official used `verdaccio/verdaccio` docker image itself).

My question is why changes I've done to e.g. the title (`web.title`) are not used?
The generated JavaScript window variable is the following:

`window.__VERDACCIO_BASENAME_UI_OPTIONS={"darkMode":false,"basename":"/","base":"https://npm.company.name/","primaryColor":"#4b5e40","version":"5.9.0","pkgManagers":["yarn","pnpm","npm"],"login":true,"logo":"","title":"Verdaccio","scope":"","language":"es-US"}`

My `verdaccio/config.yaml` file:
```yaml
# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

http_proxy: https://npm.company.name/
https_proxy: https://npm.company.name/

web:
  enable: true
  title: NPM Private Registry
  # comment out to disable gravatar support
  gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  sort_packages: asc
  # convert your UI to the dark side
  darkMode: true
  html_cache: true
  logo: ./logo.svg
  favicon: ./favicon.ico
  # rateLimit:
  #   windowMs: 1000
  #   max: 10000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true
```
