### DISCUSSION TITLE
Can't found the package by uplink When  the package publish latest version to npm。

### DISCUSSION THREAD

**Discussion by pacez** [verdaccio/verdaccio#3199] [Q&A]
* **verdaccio version**: 5.8.0
 * **node version** [12.18.x]:
 * **package manager**: [yarn@1]
 * **os**: [linux]
 * **platform**: [npm]

Can't found the package by uplink When  the package publish latest version to npm。
The error message as follows: 
Error: Couldn't find package "log4js" on the "npm" registry.

log4js just publish to npm at a few seconds ago

**Comment by pacez** [comment]
Has anyone encountered this problem?

**Reply by juanpicado** [reply]
Remember the uplinks have a cache by default of 2 min see ([https://verdaccio.org/docs/uplinks](https://verdaccio.org/docs/uplinks)), if you publish a package in npm you need to wait until that time has expired and try again or reduce the time to seconds, but I don't recommend that otherwise the performance of the proxy decreases.

**Reply by pacez** [reply]
> Remember the uplinks have a cache by default of 2 min see (https://verdaccio.org/docs/uplinks), if you publish a package in npm you need to wait until that time has expired and try again or reduce the time to seconds, but I don't recommend that otherwise the performance of the proxy decreases.

I waited for more than 10 minutes to try and still had the problem, which was solved after I manually synchronized the mirror.
But I can't do it manually every time.

**Reply by juanpicado** [reply]
You must have an issue in your setup, if you detailed describe your environment that helps.

**Reply by pacez** [reply]
> You must have an issue in your setup, if you detailed describe your environment that helps.

Could you help me analyze it if there is something wrong with the configuration? config.yaml as follow:

```yaml
storage: ./storage
plugins: ./plugins

web:
  title: NPM([REDACTED])
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1 

uplinks:
  npmjs:
    #url: https://registry.npm.taobao.org/
    url: https://registry.npmmirror.com/
    cache: false

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs: { type: stdout, format: pretty, level: http }
listen: 0.0.0.0:9082
max_body_size: 50mb
```
