### DISCUSSION TITLE
Setup Verdaccio with self signed certificates behind nginx proxy with Docker gets DEPTH_ZERO_SELF_SIGNED_CERT exception

### DISCUSSION THREAD

**Discussion by TimThaler** [verdaccio/verdaccio#3203] [Q&A]
Hello everybody - first of all thanks for this nice npm. Its really rock solid.
I have a question regarding the setup with self signed certificates behind a nginx proxy with docker.

When trying to add a user through npm adduser --registry https://myurl.local/ i get a DEPTH_ZERO_SELF_SIGNED_CERT exception.
I tried to add the location of the self created/signed certificate through setting NODE_EXTRA_CA_CERTS on 

- [ verdaccio (process.env.NODE_EXTRA_CA_CERTS = ["/etc/ssl/certs/mycert-local.pem"];) ] 
- [ verdaccio-host (export NODE_EXTRA_CA_CERTS='/etc/ssl/certs/mycert-local.pem') ] 
- [my local win client. ] 

All of them reject this setup though. I do not want to ignore SSL entierly i would like to accept NPM/Verdaccio these certificates. How do i do that? This is the message the client receives:

```
npm adduser --registry https://myurl.local/
npm notice Log in on https://myurl.local/
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! errno DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! request to https://myurl.local/-/v1/login failed, reason: self-signed certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Local\npm-cache\_logs\2022-05-30T10_34_31_296Z-debug-0.log

```

Certificates are created like this (browser happily accepts them after adding them to win-cert-store):

```
SUBJECT=mycert-local
CONFFILE=$SUBJECT.conf
KEYFILE=$SUBJECT.key
CSRFILE=$SUBJECT.csr
CRTFILE=$SUBJECT.crt
openssl genrsa -out $KEYFILE
openssl req -new -key $KEYFILE -out $CSRFILE -config $CONFFILE
openssl x509 -req -days 365 -in $CSRFILE -signkey $KEYFILE -out $CRTFILE -extensions req_ext -extfile $CONFFILE
```

**docker-compose.yaml**
```
version: "3.7"
services:
  verdaccio:
    image: "myverdaccio:${version}"
    build:
      context: ./app
      args:
        version: ${version}  #resolves to 5.8     
    environment:
      - $VERDACCIO_PORT:4873
    volumes:
      - C:\Services\verdaccio\config:/verdaccio/conf/
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    restart: always
    networks: 
      - verdaccio-network
volumes:
  verdaccio-storage:
    external: true
networks:
  verdaccio-network:
    external: true
    driver: bridge
```
    
**Dockerfile:**
```
ARG version
FROM verdaccio/verdaccio:${version}
COPY .env /opt/verdaccio/.env
COPY mycert.crt /etc/ssl/certs/mycert-local.crt
COPY mycert.pem /etc/ssl/certs/mycert.pem
COPY mycert.key /etc/ssl/private/mycert.key
RUN npm config set ca "/etc/ssl/certs/mycert.pem"
RUN npm config set strict-ssl false

```

**Content of .env in working directory of Dockerfile:**
`NODE_EXTRA_CA_CERTS=/etc/ssl/certs/mycert.pem`

**Config.yaml:**
```
storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio
  darkMode: true

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated

  '**':
    publish: $authenticated
    unpublish: $authenticated

server:
  keepAliveTimeout: 60

https:
  key: /etc/ssl/private/mycert.key
  cert: /etc/ssl/certs/mycert.crt
  strict_ssl: false
  ca: /etc/ssl/certs/mycert.pem

middlewares:
  audit:
    enabled: true
logs: { type: stdout, format: pretty, level: trace}
```

**local npmrc: (windows)**
```
registry=https://myurl.local/
cafile=C:\Users\name\Desktop\Certificates\my-cert-local.pem
```

**Detailed log:**
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'adduser',
0 verbose cli   '--registry',
0 verbose cli   'https://myurl.local/'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v17.8.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Users\name\AppData\Roaming\nvm\v17.8.0\node_modules\npm\npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 6ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:C:\Users\name\.npmrc Completed in 3ms
11 timing config:load:user Completed in 3ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 1ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 25ms
18 timing npm:load:configload Completed in 25ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 4ms
21 timing npm:load:display Completed in 5ms
22 verbose logfile C:\Users\name\AppData\Local\npm-cache\_logs\2022-05-30T10_34_31_296Z-debug-0.log
23 timing npm:load:logFile Completed in 8ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 40ms
27 notice Log in on https://myurl.local/
28 verbose web login before first POST
29 silly logfile start cleaning logs, removing 1 files
30 timing command:adduser Completed in 114ms
31 verbose type system
32 verbose stack FetchError: request to https://myurl.local/-/v1/login failed, reason: self-signed certificate
32 verbose stack     at ClientRequest.<anonymous> (C:\Users\name\AppData\Roaming\nvm\v17.8.0\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
32 verbose stack     at ClientRequest.emit (node:events:527:28)
32 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:454:9)
32 verbose stack     at TLSSocket.emit (node:events:539:35)
32 verbose stack     at emitErrorNT (node:internal/streams/destroy:164:8)
32 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
32 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
33 verbose cwd C:\Users\name
34 verbose Windows_NT 10.0.19044
35 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser" "--registry" "htps://myurl.local/"
36 verbose node v17.8.0
37 verbose npm  v8.5.5
38 error code DEPTH_ZERO_SELF_SIGNED_CERT
39 error errno DEPTH_ZERO_SELF_SIGNED_CERT
40 error request to https://myurl.local/-/v1/login failed, reason: self-signed certificate
41 verbose exit 1
42 timing npm Completed in 722ms
43 verbose code 1
44 error A complete log of this run can be found in:
44 error     C:\Users\name\AppData\Local\npm-cache\_logs\2022-05-30T10_34_31_296Z-debug-0.log
