### DISCUSSION TITLE
Is it possible to find scoped package from local verdaccio instance and then proxy?

### DISCUSSION THREAD

**Discussion by luisxiaomai** [verdaccio/verdaccio#3214] [Q&A]
It can put server1, server2 in proxy key for scoped packages. But how to configure it so that when installing dependencies, it can look up the local instance first and then go to the proxy?

**Comment by juanpicado** [comment]
> Is it possible to find scoped package from local verdaccio instance and then proxy?

Assuming you have this in the config file.

```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@yourScope/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
```

Let's imagine you have a project and run `npm install --registry http://localhost:4873`

Verdaccio will first try to locate the package locally, if is not found then if you have a `proxy` setup will also try to find it there, if exist in npmjs will deliver the package to your client.

It's that what you meant?

**Reply by luisxiaomai** [reply]
@juanpicado Our old packages are stored in nexus, we want verdaccio as the unified registry which was configured as below. 
All projects will use verdaccio as the npm registry and we hope new package can be published to verdaccio and old packages can be downloaded from nexus. But it seems that new packages will still be published to nexus, can you help on this? 
```
uplinks:
  nexus:
    url: http://nexus.xx.com/repository/npm_hosted/
    auth:
      type: bearer
      token: "xxx"
    cache: false
packages:
  '@scoped/*':
    access: $all
    publish: admin
    unpublish: admin
    proxy: nexus
```

Thanks
