### DISCUSSION TITLE
Having Trouble with url_prefix and/or Traefik routing

### DISCUSSION THREAD

**Discussion by bushwald** [verdaccio/verdaccio#3260] [Q&A]
Hello and thanks in advance for any help here.  I can't seem to get Verdaccio to play nice with my Traefik reverse proxy on K8s.  I've read the url prefix and reverse proxy docs carefully but I'm having trouble translating them to my setup.  

My end goal here is to be able to access Verdaccio from `http://subd.myfakecompany.com/js-registry/`  
Is there anything that I'm obviously doing wrong below?

I've tried going about this a couple of ways:
1. define the url_prefix in config.yaml and public url env var in the container, point the Traefik IngressRouter at the url prefix  
#### config.yaml
``` yaml  
...
url_prefix: '/js-registry/'
...
listen:
  - 0.0.0.0:4873
```
#### k8s.yaml
``` yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: verdaccio
...
    spec:
      containers:
        - name: verdaccio
          image: IMAGE_NAME
          env:
            - name: VERDACCIO_PUBLIC_URL
              value: http://subd.myfakecompany.com
...
---

kind: Service
apiVersion: v1
metadata:
  name: verdaccio
  namespace: services
  labels:
    k8s-app: verdaccio
spec:
  ports:
    - name: web
      protocol: TCP
      port: 44873
      targetPort: 4873
  selector:
    k8s-app: verdaccio
    
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: verdaccio-ingressroute
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - middlewares:
      - name: verdaccio-add-prefix
    - match: PathPrefix(`/js-registry`)
      kind: Rule
      services:
        - name: verdaccio
          kind: Service
          port: 44873
```

2. don't define a url_prefix or public url.  Use a replacePathRegex traefik middleware to try and reroute the request to the `/` path inside the container (apologies if this part is out of the scope of this repo's discussions)
#### config.yaml
same as above but with the url_prefix commented out

#### k8s.yaml
``` yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: verdaccio-replace-prefix
  namespace: services
spec:
  replacePathRegex:
    regex: ^/js-registry/(.*)
    replacement: /$1

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: verdaccio-ingressroute
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - middlewares:
      - name: verdaccio-replace-prefix
      kind: Rule
      services:
        - name: verdaccio
          kind: Service
          port: 44873
```
