### DISCUSSION TITLE
nginx proxy verdaccio ui loading resources error

### DISCUSSION THREAD

**Discussion by UltramanWeiLai** [verdaccio/verdaccio#3275] [Q&A] [answered]
## nginx proxy verdaccio ui loading resources error
```
// nginx config
server {
  listen        8200;
  listen        localhost;
  server_name   npm_registry;

  location / {
      proxy_set_header 'X-Forwarded-For' $proxy_add_x_forwarded_for;
      proxy_pass  http://localhost:4873;
  }
}
```

![image](https://user-images.githubusercontent.com/23336585/181696461-b4d21d01-a6db-450e-9799-78f16ef41863.png)

**Comment by juanpicado** [comment, marked as answer]
` proxy_set_header Host $host;` is misisng check https://verdaccio.org/docs/reverse-proxy

**Reply by UltramanWeiLai** [reply]
access page return
```
{
  "error": "internal server error"
}
```
```
Error: invalid host
    at getPublicUrl (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/build/lib/utils.js:763:13)
    at renderHTML (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/build/api/web/html/renderHTML.js:76:40)
    at /root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/build/api/web/index.js:134:29
    at Layer.handle [as handle_request] (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:95:5)
    at /root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:346:12)
    at next (/root/.nvm/versions/node/v16.15.1/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:280:10)
```

```
// nginx config
server {
    listen        8200;
    listen        localhost;
    server_name   npm_registry;

    location / {
        proxy_pass                          http://127.0.0.1:4873/;
        proxy_set_header Host               $host:$server_port;
        proxy_set_header X-Forwarded-For    $remote_addr;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}
```

```
// config.yaml
storage: ./storage
plugins: ./plugins

web:
  title: verdaccio
  html_cache: false

auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
listen:
- 0.0.0.0:4873

middlewares:
  audit:
    enabled: true

logs: { type: stdout, format: pretty, level: http }

```

**Reply by juanpicado** [reply]
why `$host:$server_port`? Verdaccio validate the host https://github.com/verdaccio/verdaccio/blob/5.x/src/lib/utils.ts#L632 ensure you are sending something valid or maybe share what you are sending to verdaccio or use `VERDACCIO_PUBLIC_URL` envrionment variable instead the host header if  want to make it simpler.

**Reply by UltramanWeiLai** [reply]
VERDACCIO_PUBLIC_URL how to configure in the configuration file ？
It's not clear in the document, or I don't understand it. Sorry

**Reply by juanpicado** [reply]
`VERDACCIO_PUBLIC_URL` is just a environment variable you need to add out of the program, example:
Via Node.js CLI: `VERDACCIO_PUBLIC_URL=https://some.domain.org verdaccio`
Via Docker compose

```
  verdaccio:
    image: verdaccio/verdaccio:5
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PUBLIC_URL=https://some.domain.org
    ports:
      - '4873:4873'
```
or if you are using linux https://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables

I hope that helps.
