### DISCUSSION TITLE
Using verdaccio with a private Azure Feed

### DISCUSSION THREAD

**Discussion by lucassarcanjo** [verdaccio/verdaccio#3307] [Q&A] [answered]
Hi there,

I'm trying to use verdaccio as a proxy for a private azure feed.

I found a resource that describes authentication for uplinks with a Bearer token [here](https://verdaccio.org/docs/uplinks), but Azure doesn't seem to support that according to [this link](https://www.code4it.dev/blog/connect-npm-feeds-from-azure-devops). The .npmrc of my project looks like this:

```
registry=https://my-site/my organization/_packaging/my-project/npm/registry/
always-auth=true

; begin auth token
//my-site/my organization/_packaging/my-project/npm/registry/:username=myusername
//my-site/my organization/_packaging/my-project/npm/registry/:_password=a-key==
//my-site/my organization/_packaging/my-project/npm/registry/:email=user@example.com
//my-site/my organization/_packaging/my-project/npm/:username=myusername
//my-site/my organization/_packaging/my-project/npm/:_password=a-key==
//my-site/my organization/_packaging/my-project/npm/:email=user@example.com
; end auth token
```

How can I write the uplink section on verdaccio config file? Has anyone done this?

```
uplinks:
  private:
    url: https://private-registry.domain.com/registry
    auth:
      type: bearer
      token: "token"
```

**Comment by gentoo90** [comment, marked as answer]
It's done with basic authentication. You need to take your personal access token from the Azure settings page and convert it to the basic auth header like this:
```bash
echo -n 'VssSessionToken:<YOUR_PAT>'|base64 -w 0
```
and then insert the output of that into the `token` field of the Verdaccio config:
```yaml
uplinks:
  private:
    url: https://private-registry.domain.com/registry
    auth:
      type: basic
      token: "<THE_BASIC_AUTH_BASE64>"
```
