### DISCUSSION TITLE
verdaccio uplink set Nexus proxy address  still GET https://registry.npmjs.org

### DISCUSSION THREAD

**Discussion by guoshuke** [verdaccio/verdaccio#3400] [Q&A] [answered]
I want to set up a private package management tool. We use nexus in the intranet environment. After I set up the uplink, http still requests registry.npmjs.org

environment
verdaccio version 5.12.0
node version [14.17.6]:
package manager: npm@6.14.15
centos
platform: [npm]

when i install angular cli , It will get the registry.npmjs.org  
`npm install @angular/cli`

![image](https://user-images.githubusercontent.com/20693126/192481186-ae25d8a1-457d-4b0b-bcce-a4693dbc8648.png)

config.yaml  config
![WechatIMG13](https://user-images.githubusercontent.com/20693126/192480373-80821ff4-7f97-4ff1-95ee-b53cd7b668e4.png)

what can i do for it?  
thanks

**Comment by guoshuke** [comment]
Description: 

`npm config set registry  http://10.10.100.105:8081/repository/npm-image-js/`   is successed to install !

**Comment by juanpicado** [comment]
I see your log, seems you are using docker not npm, that's correct?

**Comment by guoshuke** [comment]
> Member
no,  it`s pm2

**Reply by juanpicado** [reply]
I think you are hitting the wrong config file, you might want to check that.

**Reply by guoshuke** [reply]
I not found question in this config file

```
storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: http://10.10.100.105:8081/repository/npm-image-js/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

publish:
  allow_offline: false

listen:
# - localhost:4873            # default value
  0.0.0.0:11000              # listen on all addresses (INADDR_ANY)

middlewares:
  audit:
    enabled: true

logs: { type: stdout, format: pretty, level: http }

# i18n:
#   web: en-US
```

I tried again at home and found that some packages will not be cached by verdaccio
for example `magic-string@0.26.2`
I can`t found  in storge 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/20693126/192681342-72b330b8-5e88-4cc1-b72c-dd3272d5b41a.png">

I found getting `registry.npmjs.org`  in this package.json 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/20693126/192682960-082b0d70-2d63-4d41-abfa-9e24f365b8dd.png">

verdaccio will useing local npm cache url?
This is a bad experience
and I want to use the set uplink url   when the npm cache not found

thanks
