### DISCUSSION TITLE
Can I use verdaccio as real proxy ? or it's only a private registry that caches?

### DISCUSSION THREAD

**Discussion by gregpavl** [verdaccio/verdaccio#3427] [Q&A]
Hi Verdaccio team, 

Based on your docs/presentations, we should be able to also use `verdaccio` as proxy. 

However, after testing it, I am unsure if it works precisely as a proxy. So, I want to clarify the usage here. 

**What we have done**

- We have deployed `verdaccio` in a k8s cluster to optimize and reduce the latency of packages from `npmjs` & `yarnpkg`
- We point in the `yarn` config our `verdaccio` internal URL
- Our `yarn.lock` files `resolve` from the internal `http://verdaccio.verdaccio:4873` URL
- We see in the `/verdaccio/storage/data/` all the packages that have been cached
- We have set the `verdaccio` cache up to 6 months

However, we see in our logs that `yarn` has a delay and `network connection` issue which does not really make sense because we receive the packages locally.

So, the clarification here:

Should we add the `verdaccio` as well as `yarn proxy`? 
eg. 
```cmd
yarn config set proxy http://verdaccio.verdaccio:4873
yarn config set https-proxy http://verdaccio.verdaccio:4873
yarn config set "strict-ssl" false
```

or we should only use the `verdaccio` as a private registry only, such as:
```cmd
    yarn config set registry "http://verdaccio.verdaccio:4873"
    yarn config set "strict-ssl" false
```

or both ?
```cmd
yarn config set registry "http://verdaccio.verdaccio:4873"
yarn config set proxy http://verdaccio.verdaccio:4873
yarn config set https-proxy http://verdaccio.verdaccio:4873
yarn config set "strict-ssl" false
```

---

logs: 

```log
+ yarn install '--production=false' --frozen-lockfile
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
...
```

The `yarn` configs:

```cmd
    yarn config set registry "http://verdaccio.verdaccio:4873"
    yarn config set "strict-ssl" false
    yarn install --production --frozen-lockfile
    yarn build
```

our `yarn.lock`

```cmd
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@adobe/css-tools@^4.0.1":
  version "4.0.1"
  resolved "http://verdaccio.verdaccio:4873/@adobe/css-tools/-/css-tools-4.0.1.tgz#b38b444ad3aa5fedbb15f2f746dcd934226a12dd"
  integrity sha512-+u76oB43nOHrF4DDWRLWDCtci7f3QJoEBigemIdIeTi1ODqjx6Tad9NCVnPRwewWlKkVab5PlK8DCtPTyX7S8g==

"@ampproject/remapping@^2.1.0":
  version "2.2.0"
  resolved "http://verdaccio.verdaccio:4873/@ampproject/remapping/-/remapping-2.2.0.tgz#56c133824780de3174aed5ab6834f3026790154d"
  integrity sha512-qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w==
  dependencies:
    "@jridgewell/gen-mapping" "^0.1.0"
    "@jridgewell/trace-mapping" "^0.3.9"

"@apideck/better-ajv-errors@^0.3.1":
  version "0.3.6"
  resolved "http://verdaccio.verdaccio:4873/@apideck/better-ajv-errors/-/better-ajv-errors-0.3.6.tgz#957d4c28e886a64a8141f7522783be65733ff097"
  integrity sha512-P+ZygBLZtkp0qqOAJJVX4oX/sFo5JR3eBWwwuqHHhK0GIgQOKWrAfiAaWX0aArHkRWHMuggFEgAZNxVPwPZYaA==
  dependencies:
    json-schema "^0.4.0"
    jsonpointer "^5.0.0"
    leven "^3.1.0"

....
```

The `configmap.yaml`

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio
  namespace: verdaccio
  labels:
    app: verdaccio
data:
  config.yaml: |-
    #
    # This is the config file used for the docker images.
    # It allows all users to do anything, so don't use it on production systems.
    #
    # Do not configure host and port under `listen` in this file
    # as it will be ignored when using docker.
    # see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
    #
    # Look here for more config file examples:
    # https://github.com/verdaccio/verdaccio/tree/master/conf
    #

    # path to a directory with all packages
    storage: /verdaccio/storage/data
    # path to a directory with plugins to include
    plugins: /verdaccio/plugins

    web:
      enable: true
      title: Verdaccio
    url_prefix: '/'

    # auth:
    #   htpasswd:
    #     file: /verdaccio/conf/htpasswd
        # Maximum amount of users allowed to register, defaults to "+infinity".
        # You can set this to -1 to disable registration.
        #max_users: 1000

    # a list of other known repositories we can talk to
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
        cache: true
        maxage: 259200m
      yarnpkg:
        url: https://registry.yarnpkg.com/
        cache: true
        maxage: 259200m

    packages:
      '@*/*':
        # scoped packages
        access: $all
        publish: $authenticated
        proxy: yarnpkg npmjs

      '**':
        # allow all users (including non-authenticated users) to read and
        # publish all packages
        #
        # you can specify usernames/groupnames (depending on your auth plugin)
        # and three keywords: "$all", "$anonymous", "$authenticated"
        access: $all

        # allow all known users to publish packages
        # (anyone can register by default, remember?)
        publish: $authenticated

        # if package is not available locally, proxy requests to 'npmjs' registry
        proxy: yarnpkg npmjs

    # To use `npm audit` uncomment the following section
    middlewares:
      audit:
        enabled: true

    # log settings
    logs:
      - {type: stdout, format: pretty, level: debug}
      #- {type: file, path: verdaccio.log, level: info}
    # htpasswd: |-
      # username:$2y$05$S83b6n9QThQnqMoP9ZeQ8.BzRaYpSTgjyeymQaHULl1kMQrCF620K
```
