### DISCUSSION TITLE
Can't install sharp package with verdaccio as a proxy

### DISCUSSION THREAD

**Discussion by dacatchman** [verdaccio/verdaccio#3482] [Q&A] [answered]
I'm doubtful it's sharp specifically but probably something to to do with the self downloading binaries and install script that package includes.  Anyway, the gist is this: with verdaccio as a proxy I get errors trying to install this package (particularly this issue with libvips: https://github.com/lovell/sharp-libvips/issues/34).  None of the suggestions there work or matter, because to fix it all I had to do was not use verdaccio and point at npmjs as the registry -- in which case it installs without issue.  Which is why i started here and not at the sharp package.

So I'm leaning maybe a config problem with verdaccio? Before I delve too deeply into the IT side of the proxy server, I'm wondering if this might be a common known things or simple fix with configuration ?  It doesn't seem like it should be.... I haven't had any other package install issues yet (but I'm new to verdaccio admittedly).

I get no error output when doing `npm i sharp` pointing at verdaccio and watching the verdaccio logs during the requests.  I tried clearing verdaccio's cache, to no avail.

Both the installation machine and verdaccio proxy are RHEL 8 servers.

Any thoughts ?

Here is my verdaccio config:

```
storage: /srv/registry/storage
plugins: /srv/registry/plugins
web:
  title: Verdaccio
auth:
  htpasswd:
    file: /srv/registry/.htpasswd
    max_users: -1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@<snip>/*':
    access: $authenticated
    publish: <snip>
  '@<snip>/*':
    access: $authenticated
    publish: $authenticated
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

listen:
  - http://<snip>:4873

middlewares:
  audit:
    enabled: true
logs: { type: stdout, format: pretty, level: http }
```
