### DISCUSSION TITLE
packages runtime reload Q/A

### DISCUSSION THREAD

**Discussion by NoahHahm** [verdaccio/verdaccio#3503] [Ideas]
Is there a way to rewrite and load packages without restarting the server every time?
we plan to authorize new users to access the new packages via the auth plugin.

```
packages:
  'jquery':
    access: $all
    publish: $all
    unpublish: root
  'my-company-*':
    access: $all
    publish: $authenticated
    unpublish:
  '@my-local-scope/*':
    access: $all
    publish: $authenticated
    # unpublish: property commented out
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
````
