### DISCUSSION TITLE
Verdaccio does not obey to Configurations

### DISCUSSION THREAD

**Discussion by samitha9125** [verdaccio/verdaccio#3518] [Q&A]
I'm currently trying to run `verdaccio:5` latest docker image with customised authentication plugin. Setup and execusion all works well, but Verdaccio does not obey the configurations which I have managed under conf/config.yaml file. 

Folder structure
- conf -> config.yaml
- plugins -> verdaccio-gitlab-oauth2 -> verdaccio-gitlab-oauth2-1.0.11.tgz
- storage
- docker-compose.yml
- dockerfile

config file

```
storage: /verdaccio/storage
plugins: /verdaccio/plugins
middlewares:
  gitlab-oauth2:
    enabled: true
auth:
  gitlab-oauth2:
    group: GROUP
    client-id: CLIENT_ID
    client-secret: CLIENT_SECRET
    gitlab-host: https://gitlab.com
web:
  darkMode: false
  title: Sample Title
```

docker-compose.yml

```
version: '3.1'

services:
  verdaccio:
    build: .
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"  
networks:
  node-network:
    driver: bridge
```

dockerfile

```
FROM node:lts-alpine as builder
RUN mkdir -p /verdaccio/plugins
ADD plugins/verdaccio-gitlab-oauth2 /verdaccio/plugins/verdaccio-gitlab-oauth2
RUN apk update && apk add bash
RUN cd /verdaccio/plugins/verdaccio-gitlab-oauth2 && npm install --global-style --no-bin-links --omit=optional verdaccio-gitlab-oauth2-1.0.11.tgz

FROM verdaccio/verdaccio:5
COPY --chown=$VERDACCIO_USER_UID:root --from=builder \
  /verdaccio/plugins/verdaccio-gitlab-oauth2 \
  /verdaccio/plugins/verdaccio-gitlab-oauth2

RUN cd /verdaccio/plugins/verdaccio-gitlab-oauth2
USER root
RUN npm install --global /verdaccio/plugins/verdaccio-gitlab-oauth2/verdaccio-gitlab-oauth2-1.0.11.tgz
USER $VERDACCIO_USER_UID
```

### Issue ###

As you can see in the config.yaml file, i have mentioned web title and have disabled the darkMode but none of these changes are available once I run the below command and access the `http://localhost:4873`

command: `docker-compose up --build -d`

Also, plugin should be able to intercept the login button click but it does not work as well. I'm not sure whether that is a bug of Verdaccio latest docker image. I would really appreciate if someone can help me to find the root cause of this issue.
