### DISCUSSION TITLE
Plugin installation when using `helm` in k8s

### DISCUSSION THREAD

**Discussion by Neneil94** [verdaccio/verdaccio#3646] [Q&A] [answered]
Hi all :) 

I get the following error from my pod in k8s installing with `helm`:

```shell
warn --- config file - /verdaccio/conf/config.yaml
fatal--- uncaught exception, please report this
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
at new NodeError (node:internal/errors:393:5)
at validateString (node:internal/validators:163:11)
at Object.resolve (node:path:1098:7)
at /usr/local/lib/node_modules/verdaccio/build/lib/plugin-loader.js:75:48
at Array.map (<anonymous>)
at loadPlugin (/usr/local/lib/node_modules/verdaccio/build/lib/plugin-loader.js:61:37)
at Auth._loadPlugin (/usr/local/lib/node_modules/verdaccio/build/lib/auth.js:38:38)
at new Auth (/usr/local/lib/node_modules/verdaccio/build/lib/auth.js:30:25)
at defineAPI (/usr/local/lib/node_modules/verdaccio/build/api/index.js:26:16)
at _default (/usr/local/lib/node_modules/verdaccio/build/api/index.js:119:10) 
```

I am installing verdaccio in my k8s cluster by using helm.
I want to add a plugin (in this case `verdaccio-azure-ad-login`).
I also asked chatGPT how to setup azureAD for verdaccio but it seems his knowledge is too old, the 2021 problem...

I also didn't found any solutions or instructions for installing plugins by using helm... 
Do I have to create my own verdaccio image for that??

I've tested multiple things (setting plugins in config, setting env variables in values...). My values during installation looks like this:
```yaml
affinity: {}
configMap: >
  # This is the config file used for the docker images

  # It allows all users to do anything, so don't use it on production systems.

  #

  # Do not configure host and port under `listen` in this file

  # as it will be ignored when using docker.

  # see
  https://github.com/verdaccio/verdaccio/blob/master/docs/docker.md#docker-and-custom-port-configuration

  #

  # Look here for more config file examples:

  # https://github.com/verdaccio/verdaccio/tree/master/conf

  #


  # path to a directory with all packages

  storage: /verdaccio/storage/data


  web:
    # WebUI is enabled as default, if you want disable it, just uncomment this line
    #enable: false
    title: Verdaccio
    baseUrl: <My-URL>
    
  plugins: 
    - verdaccio-azure-ad-login
    
  plugin_path: /verdaccio/plugins

  auth:
    #htpasswd:
      # Do not change this path if secrets htpasswd is used.
      #file: /verdaccio/storage/htpasswd
      # Maximum amount of users allowed to register, defaults to "+infinity".
      # You can set this to -1 to disable registration.
      #max_users: 1000
    azure-ad-login:
      # REQUIRED, Azure application tenant
      tenant: <My-Data>
      # REQUIRED, Azure client_id
      client_id: <My-Data>
      # REQUIRED, Azure application client_secret
      client_secret: <My-Data>
      # OPTIONAL, default email domain for accounts, example: organization.com
      organization_domain: <My-Data>
      # OPTIONAL, custom azure scope for users
      # Standard scope: user.read openid profile offline_access
      # Other permissions added here will be added to the end of the standard one
      scope: ""
      # OPTIONAL, users of these groups will be allowed to authenticate
      # This requires the App to have GroupMember.Read.All permission:
      # https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0&tabs=http
      allow_groups:
        - <My-Data>
        - <My-Data>
        - <My-Data>

  # a list of other known repositories we can talk to

  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
      agent_options:
        keepAlive: true
        maxSockets: 40
        maxFreeSockets: 10

  packages:
    '@private/*':
      access: <My-Data>
      publish: <My-Data>
      unpublish: <My-Data>

    '@*/*':
      # scoped packages
      access: $authenticated
      publish: $authenticated
      proxy: npmjs

    '**':
      # allow all users (including non-authenticated users) to read and
      # publish all packages
      #
      # you can specify usernames/groupnames (depending on your auth plugin)
      # and three keywords: "$all", "$anonymous", "$authenticated"
      access: $authenticated

      # allow all known users to publish packages
      # (anyone can register by default, remember?)
      publish: $authenticated

      # if package is not available locally, proxy requests to 'npmjs' registry
      proxy: npmjs

  # To use `npm audit` uncomment the following section

  middlewares:
    audit:
      enabled: true

  # log settings

  logs: {type: stdout, format: pretty, level: http}

  # logs: {type: file, path: verdaccio.log, level: info}
existingConfigMap: false
existingSecret: ''
extraEnvVars: null
extraInitContainers: []
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  repository: verdaccio/verdaccio
ingress:
  className: ''
  enabled: false
  extraPaths: []
  paths:
    - /
livenessProbe: {}
nameOverride: ''
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  mounts: null
  selector: {}
  size: 8Gi
  volumes: null
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 101
priorityClass:
  enabled: false
readinessProbe: {}
replicaCount: 1
resources: {}
secretEnvVars: {}
secrets:
  htpasswd: []
securityContext:
  runAsUser: 10001
service:
  annotations: {}
  clusterIP: ''
  externalIPs: []
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  port: 4873
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []
env:
  VERDACCIO_PLUGINS: verdaccio-azure-ad-login
global:
  cattle:
    systemProjectId: p-4rwdw

```

Is that even possible? I do not want to create my own image... But if necessary okay 😄 

Would very much appreciate help and further information on this topic

Thanks in advance!

Kind regards :)
