### DISCUSSION TITLE
Verdaccio changing the response base href after a while

### DISCUSSION THREAD

**Discussion by Lasto13** [verdaccio/verdaccio#3684] [General]
Hello,
Verdaccio `latest:5.22.1`  is deployed at EC2 with private IP 10.32.11.100, we have loadbalancer configured with certificates at https://npm.the_company.com/.

After it is started it returns index.html with basename like: 

`<base href="https://npm.the_company.com/">`

but after cca one hour it starts to serve a different index.html

`<base href="http://10.32.11.100/">`

Thus browser is rightfully complaining about mixed content.

Verdaccio itself is configured with compose like this: 

```
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    restart: always
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PUBLIC_URL='https://npm.the_company.com'
    ports:
      - '80:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './config:/verdaccio/conf'
      - './plugins:/verdaccio/plugins'
networks:
  node-network:
    driver: bridge
```

and config.yml

```
storage: ../storage
auth:
  htpasswd:
    file: ./htpasswd
listen: 'http://npm.the_company.com'
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $anonymous
    publish: $anonymous
    proxy: npmjs
  '**':
    access: $anonymous
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }
```

After we start it we receive following index.html 

```
    <!DOCTYPE html>
      <html lang="en-us"> 
      <head>
        <meta charset="utf-8">
        <base href="https://npm.the_company.com/">
        <title>Verdaccio</title>        
        <link rel="icon" href="https://npm.the_company.com/-/static/favicon.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <script>
            window.__VERDACCIO_BASENAME_UI_OPTIONS={"darkMode":false,"basename":"/","base":"https://npm.the_company.com/","primaryColor":"#4b5e40","logo":"","flags":{},"login":true,"pkgManagers":["yarn","pnpm","npm"],"title":"Verdaccio","scope":"","language":"es-US"}
        </script>
        
      </head>
      <body class="body">
      
        <div id="root"></div>
        <script defer="defer" src="https://npm.the_company.com/-/static/runtime.46bd00483c91daa50e74.js"></script><script defer="defer" src="https://npm.the_company.com/-/static/vendors.46bd00483c91daa50e74.js"></script><script defer="defer" src="https://npm.the_company.com/-/static/main.46bd00483c91daa50e74.js"></script>
        
      </body>
    </html>
 ```
And this is after one cca hour

```
<!DOCTYPE html>
      <html lang="en-us"> 
      <head>
        <meta charset="utf-8">
        <base href="http://10.32.11.100/">
        <title>Verdaccio</title>
        <link rel="icon" href="http://10.32.11.100/-/static/favicon.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <script>
            window.__VERDACCIO_BASENAME_UI_OPTIONS={"darkMode":false,"basename":"/","base":"http://10.32.11.100/","primaryColor":"#4b5e40","logo":"","flags":{},"login":true,"pkgManagers":["yarn","pnpm","npm"],"title":"Verdaccio","scope":"","language":"es-US"}
        </script>
        
      </head>    
      <body class="body">
      
        <div id="root"></div>
        <script defer="defer" src="http://10.32.11.100/-/static/runtime.46bd00483c91daa50e74.js"></script><script defer="defer" src="http://10.32.11.100/-/static/vendors.46bd00483c91daa50e74.js"></script><script defer="defer" src="http://10.32.11.100/-/static/main.46bd00483c91daa50e74.js"></script>
        
      </body>
    </html>
```
