### DISCUSSION TITLE
Building Docker image on Linux fails when pulling verdaccio/verdaccio image

### DISCUSSION THREAD

**Discussion by jfreitas-dev** [verdaccio/verdaccio#3686] [Q&A]
**Your Environment**
 * **verdaccio version**: 5.22.1
 * **node version**: 18.14.0
 * **package manager**: npm@9.3.1
 * **os**: linux + mac
 * **platform**: docker

**Describe the bug**

When pulling the verdaccio/verdaccio docker image on a linux system the build fails due to high container ids being mapped as uid's.

It seems its possible the issue has to do with specific npm versions and userns mapping within docker + linux. When the uid is too high, linux has issues. I have supplied some articles below that lead me in that direction.

**To Reproduce**
Running locally on a Mac and Docker does not replicate this issue and I have not found a way to do so.
I have started to run into the issue when deploying via linux containers in both Bitbucket pipelines during build and Azure Web Apps during deployment as they both use Linux environments

 - How to reproduce the issue
 Build a docker image within a linux environment from the verdaccio/verdaccio base image

 - Steps to reproduce the issue

Dockerfile
```
FROM verdaccio/verdaccio:5
ARG VERDACCIO_CONFIG_PATH
ARG VERDACCIO_PLUGINS
ADD ${VERDACCIO_CONFIG_PATH} /verdaccio/conf/config.yaml
USER root
RUN npm install --global ${VERDACCIO_PLUGINS}
ENV VERDACCIO_USER_UID=10001
USER $VERDACCIO_USER_UID
```

docker-compose.yaml
```
services:
  package-manager:
    build:
      context: .
      args:
        - VERDACCIO_CONFIG_PATH=config.yaml
        - VERDACCIO_PLUGINS=verdaccio-azure-ad-login
    container_name: package-manager
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_USER_UID=10001
      - AZURE_TENANT_ID
      - AZURE_APP_REG_SECRET
      - AZURE_APP_REG_ID
    ports:
      - 4873:4873
    image: mypackagemanager.io:latest
    volumes:
      - "/verdaccio/storage"
      - "/verdaccio/config"
      - "/verdaccio/plugins"
```

Command to get error:
```
docker-compose build
```

**Expected behavior**

The build should not error when pulling images

**Screenshots, server logs, package manager log**

![image](https://user-images.githubusercontent.com/36017906/225318972-bbeda734-968c-4ddc-a59c-70f909fca99f.png)

Some links I have found while attempting to debug this problem:
- https://azureossd.github.io/2022/06/30/Docker-User-Namespace-remapping-issues/index.html
- https://github.com/npm/cli/issues/5900
- https://github.com/projectkudu/kudu/issues/2512#issuecomment-319779570

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

config.yaml
```
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
web:
  title: Lous Supreme Private Registry
  darkMode: true
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt
    rounds: 10
  azure-ad-login:
    # REQUIRED, Azure application tenant
    tenant: ${AZURE_TENANT_ID}
    # REQUIRED, Azure client_id
    client_id: ${AZURE_APP_REG_ID}
    # REQUIRED, Azure application client_secret
    client_secret: ${AZURE_APP_REG_SECRET}
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    # proxy: npmjs
  "**":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
log: { type: stdout, format: pretty, level: http }
```

**Environment information**

Environment Info:
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    npm: 9.3.1 - /usr/local/bin/npm
  npmGlobalPackages:
    verdaccio: 5.22.1

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
