### DISCUSSION TITLE
Issue hosting with url_prefix

### DISCUSSION THREAD

**Discussion by gevalo1** [verdaccio/verdaccio#3719] [Q&A] [answered]
Hi!

I'm trying to set up Verdaccio using Helm on Kubernetes, and getting stuck on the configuration of `url_prefix`.
(This is a migration from just Docker to Kubernetes, and from v3 to v5)

Our `url_prefix` is set as follows:
```
url_prefix: /npm
```

However no matter what I do, when I try to access the page `https://{domain}/npm/` I get (trailing slash doesn't matter I think, it redirects there automatically):
```
{
  "error": "authorization required to access package npm"
}
```

I have tried to enable debug logs with:
```
extraEnvVars:
  - name: DEBUG
    value: "verdaccio*"
```
This gives me some extra logs but I get the impression I'm still missing quite a lot, not sure though...
Either way I didn't see anything helpful for my issue there.

Do you have any clue what I could still be missing?

FWIW, I also tried setting `VERDACCIO_PUBLIC_URL` to `https://{domain}` but this did not make any difference.

We also have the ingress from the Verdaccio helm Chart enabled as follows:
```
ingress:
  enabled: true
  paths:
    - /npm
  hosts:
    - {domain}
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
      - {domain}
```

**Comment by juanpicado** [comment]
@verdaccio/kubernetes fyi

**Comment by gevalo1** [comment]
Just tested still if I disable the requirement to be authenticated to access all packages, when I go to `https://{domain}/npm` it just loads the entire package history for the `npm` package (which crashes the page because it's so big).

Also when I change the ingress to
```
ingress:
  enabled: true
  paths:
    - /
```
and go to `https://{domain}`, then in the devtools I see it is trying to load some files from `https://{domain}/npm`, but failing with 404 (E.g.: `'GET /npm/-/static/main.7f277b39ee739df5e322.js', error: no such file available`).

So it seems to recognize the `url_prefix`, but not apply it correctly everywhere? Not sure if this is purely a Kubernetes issue, because Verdaccio definitely seems to pick it up. 🤔

**Comment by gevalo1** [comment]
I think I found a workaround that works for us while still using `url_prefix: /npm`.

First I disabled Verdaccio's ingress
```
ingress:
  enabled: false
```

Then I created my own ingress which looks like this
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "verdaccio-npm"
  labels:
    app.kubernetes.io/instance: verdaccio-npm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: verdaccio
    app: verdaccio-npm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {domain}
  rules:
    - host: {domain}
      http:
        paths:
          - backend:
              service:
                name: "verdaccio-npm"
                port:
                  name: http
            pathType: ImplementationSpecific
            path: "/npm/?(.*)"
```

Again, it's only a workaround and I haven't been able to do enough testing yet to be able to tell if it works 100%.

So while it seems to work for now, I think someone who is more experienced here should try out my scenario as well if/when they have time.

**Comment by rblaine95** [comment, marked as answer]
You can add the path and annotations to the ingress with the helm chart
```yaml
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  paths:
    -  "/npm/?(.*)"
```
