### DISCUSSION TITLE
Readmes/Markdown rendering with strange theming

### DISCUSSION THREAD

**Discussion by 100KILOFUNK** [verdaccio/verdaccio#3850] [Q&A] [answered]
The Readme inside our packages are rendered with a strange theming, making code blocks hard to read and always in dark mode. Have someone encountered this? I can't find much information on the topic. Sorry for the minimal screenshot, I don't want to include sensitive information. 

![image](https://github.com/verdaccio/verdaccio/assets/13716369/8b71735d-1481-4f70-a1e3-359dbb246a80)

Version 5.24.1

Web configuration

```
web:
  title: NPM - *****
  primary_color: "#de4136"
  scope: "@*****"
  metaScripts:
    - '<meta name="robots" content="noindex" />'
```

What I've tested:
- Removing the `primary_color` attribute
- Forcing light mode using `dark: False` and disabling the theme switcher. 

We have no added styles of our own and no additional plugins installed.

Thanks in advance.

Update:

We've understood the cause to be because of system theme settings. On devices set to Dark mode, the README is rendered with a black background. Our next question is this can be circumvented, or should this be reported as a bug?
