### DISCUSSION TITLE
Logged in web users cannot view packages anymore after 5.26.0

### DISCUSSION THREAD

**Discussion by gramakri** [verdaccio/verdaccio#3941] [Q&A] [answered]
I looked for an existing bug report and couldn't find one. Seems like a pretty basic bug, so I am not sure why it's not been reported.

We have verdaccio configured with LDAP (this is via Cloudron package):

Step 1:
* Login to web ui
![image](https://github.com/verdaccio/verdaccio/assets/82041/8c682b7c-bcd6-47de-9f6b-27ed76727de3)

* Publish package using npm. This works fine.
* The UI still remains same as above screenshot. I thought this is a cache issue but it's the same in another browser too.

My config.yaml has:
```
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
```

If I change `    access: $authenticated` above to `    access: $all` it works but this is not what I want.
