### DISCUSSION TITLE
Probably a bug with verdaccio 5.26.2 behind apache using Chrome

### DISCUSSION THREAD

**Discussion by mavek87** [verdaccio/verdaccio#4053] [Q&A]
Hi,

I think there is a bug with verdaccio 5.26.2 behind apache, that may depends by some security Chrome behaviour.

In Firefox everything works, but in Chrome I receive this error when I visit: https://www.mysite.com/registrynode

```Refused to connect to 'https://www.mysite.com/registrynode/-/verdaccio/data/packages' because it violates the following Content Security Policy directive: "connect-src 'self'".```
```Refused to connect to 'https://www.mysite.com/registrynode/-/verdaccio/data/packages' because it violates the document's Content Security Policy.```

And only in chrome if I try to login it doesn't work (in firefox does) and I receive this errors:

```Refused to connect to 'https://www.mysite.com/registrynode/-/verdaccio/sec/login' because it violates the following Content Security Policy directive: "connect-src 'self'".```
```main.1786c686be2d1b9a3aa7.js:2 Refused to connect to 'https://www.mysite.com/registrynode/-/verdaccio/sec/login' because it violates the document's Content Security Policy.```

This looks similar to duplicate bugs already resolved (https://github.com/verdaccio/verdaccio/issues/1523) but 

1. I don't think this is the case.
2. If the user have to do something to fix it there is no explanation.

**I followed all the instructions in the documentation here**: https://verdaccio.org/docs/reverse-proxy

This is my **apache configuration** for verdaccio:

```     
        ProxyPass  /registrynode http://127.0.0.1:4873 nocanon
        ProxyPassReverse /registrynode http://127.0.0.1:4873

        RequestHeader set X-Forwarded-Host "www.mysite.com"
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"
```
This is my **docker-compose.yml** where I use the **VERDACCIO_PUBLIC_URL** env:
```
version: '3.8'

services:
  verdaccio-npm-registry:
    container_name: verdaccio-node-registry
    image: verdaccio/verdaccio:5
    restart: always
    ports:
      - 127.0.0.1:4873:4873
    expose:
      - 4873
    network_mode: bridge
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_USER_ID=10001
      - VERDACCIO_PUBLIC_URL=https://www.mysite.com
    volumes:
      - ./conf:/verdaccio/conf
      - ./storage:/verdaccio/storage
      - ./plugins:/verdaccio/plugins
```
And finally in my **./conf/config.yaml** I set:

**```url_prefix: '/registrynode/'```**

I repeat again to be clear, everything works perfectly in Firefox. Instead, only using Chrome, I receive the errors written before and I can't login in the UI (when I try to login I realized that probably the Chrome browser is blocking the request for security reasons, because there are no failed logs in the docker container. I checked it using **docker compose -f logs {name-of-container}**)

Last thing. If this is a bug as it seems, I don't know how to report it. 
I tried to open a new bug but there are too much questions that I don't know how to answer.

For example:

 * **node version** [12.x.x, 14.x.x]:   ====> **I'm not using node. I'm using the verdaccio image through docker compose.**
 * **package manager**: [npm@7, pnpm@6, yarn@2]: ====> **I'm not using a package manager, same as before**

So please if it's a bug help me to open it.

Thanks
