### DISCUSSION TITLE
Unable to use ES256 as jwt sign/verify algorithm

### DISCUSSION THREAD

**Discussion by AndrewKahr** [verdaccio/verdaccio#4254] [Q&A]
I just started using Verdaccio so it is very possible that I have misconfigured something, but when I try to set the jwt algorithm to ES256 as specified as an option in the [jsonwebtoken library](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) I get the following error in the log and verdaccio crashes:
```
verdaccio  | fatal--- uncaught exception, please report this
verdaccio  | Error: secretOrPrivateKey must be an asymmetric key when using ES256
verdaccio  |     at module.exports [as sign] (/usr/local/lib/node_modules/verdaccio/node_modules/jsonwebtoken/sign.js:130:22)
verdaccio  |     at /usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/signature/build/jwt-token.js:22:27
verdaccio  |     at new Promise (<anonymous>)
verdaccio  |     at signPayload (/usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/signature/build/jwt-token.js:20:10)
verdaccio  |     at Auth.jwtEncrypt (/usr/local/lib/node_modules/verdaccio/build/lib/auth.js:471:52)
verdaccio  |     at /usr/local/lib/node_modules/verdaccio/build/api/web/api/user.js:28:29
verdaccio  |     at /usr/local/lib/node_modules/verdaccio/build/lib/auth.js:129:18
verdaccio  |     at /usr/local/lib/node_modules/verdaccio/node_modules/verdaccio-htpasswd/build/htpasswd.js:122:14
```
From what I gather, I need to set up a keypair for it to use to sign with but I can't quite find where I can provide the paths for the public/private keys.

I am running Verdaccio inside docker using the latest v5 image (5.28.0) and have it running behind an nginx proxy. Below is the security section inside my config file:
```
security:
  api:
    jwt:
      sign:
        expiresIn: 29d
        algorithm: ES256
      verify:
        algorithms: ['ES256']
  web:
    sign:
      expiresIn: 1h # 1 hour by default
      algorithm: ES256
    verify:
      algorithms: ['ES256']
```

Any guidance on this would be much appreciated!
