### DISCUSSION TITLE
Can support audit middleware in proxy?

### DISCUSSION THREAD

**Discussion by richex-cn** [verdaccio/verdaccio#4274] [General]
Looks like the audit middleware always proxy to registry.npmjs.org now:

https://github.com/verdaccio/verdaccio/blob/2cee1a580124c9e1020fb63e660f973e0ab92fe1/packages/plugins/audit/src/audit.ts#L37

Considering having the audit middleware support the proxy option? Just like the package proxy uplink.

```
uplinks:
  local:
    url: http://localhost:55666/
middlewares:
  audit:
    enabled: true
    proxy: local
```
