### DISCUSSION TITLE
FetchError:Request to https://registry.npmjs.org/*** failed.

### DISCUSSION THREAD

**Discussion by LJQQQQQQ** [verdaccio/verdaccio#4286] [Q&A] [answered]
**Your Environment**
  
 * **verdaccio version**: 5.27.0
 * **node version** [18.18.2]:
 * **package manager**: [npm@9]
 * **os**: [windows@10, linux]
 * **platform**: [npm]

**Describe the bug**

My server has been set to prohibit access https://registry.npmjs.org/ However, when I download the NPM package through verdaccio, there are still requests to download it from this website. Why is this happening? I hope to download dependency from https://registry.npmmirror.com/ , what should I do?

**To Reproduce**

**Expected behavior**

**Screenshots, server logs, package manager log**
This is my project package.json file.
![fpvUbSuHpA](https://github.com/verdaccio/verdaccio/assets/29788169/cf284a7f-8261-4a38-b188-c537931c82ca)
This is my local npm config. http://10.13.35.237:54209 is the verdaccio service.
![BFAHVkeWA9](https://github.com/verdaccio/verdaccio/assets/29788169/8cbe3020-3d86-44b8-b8c5-fb4d023167c9)
This is the log of my local execute the npm i --loglevel verbose  command.
![yIxbGAh6IE](https://github.com/verdaccio/verdaccio/assets/29788169/57776893-c100-4f4e-9d72-f53408dc0e79)
This is the log of verdaccio.
![wqmN7lzvRF](https://github.com/verdaccio/verdaccio/assets/29788169/3a6792c3-1f8d-47a5-80c1-2b49cedb92b4)

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
``` yaml

storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmmirror.com/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

# VERDACCIO_PUBLIC_URL: 'localhost:1000'
# url_prefix: '/npm/'

listen:
  0.0.0.0:54209

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: http }

i18n:
 web: zh-CN

```

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
