### DISCUSSION TITLE
Best way to support repositories

### DISCUSSION THREAD

**Discussion by crutch12** [verdaccio/verdaccio#4308] [Q&A]
Nexus (https://github.com/sonatype/nexus) supports repositories (https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management)

It allows distribute packages in different nested/inner groups (repositories), separate access, etc.

Example:
```
https://example.com/repository/first-npm
https://example.com/repository/second-npm
```

So you can write
```
npm login --registry https://example.com/repository/first-npm
npm login --registry https://example.com/repository/second-npm
```

How could I implement same behaviour with verdaccio? (with my custom api behind verdaccio)

I have some ideas:
1) Use verdaccio instance per "repository" (sounds horrible, not optimal)
2) Force verdaccion use new s3 bucket per "repository" (but how? with custom plugin based on s3 plugin?)

Is there a more proper way for this? Is it even possible?

**Comment by itineric** [comment]
Did you find a way to do that without having 2 instances?

**Reply by crutch12** [reply]
Nope

**Comment by mbtools** [comment]
how do you decide what to publish to first-npm and what to second-npm?

**Reply by crutch12** [reply]
It's about multiple projects and teams. Packages for project-1 could be published to first-npm. So same for the second one.

```
// .npmrc

@project1:registry=https://example.com/repository/first-npm/
@project2:registry=https://example.com/repository/second-npm/
```

**Reply by mbtools** [reply]
Why does it have to be two repositories?

One Verdaccio:

```yml
packages:
  '@project1/*':
    access: project1-user-group
    publish: project1-user-group

  '@project2/*':
    access: project2-user-group
    publish: project2-user-group

  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs
```

If projects are allowed to use but not publish packages from other teams, change `access` to:


```yml
    access: project1-user-group project2-user-group
    # or
    access: $all
```

If you need to keep project data separated in the storage, you can use sub folders:

```
  '@project1/*':
    access: project1-user-group
    publish: project1-user-group
    storage: project1-folder
```
