### DISCUSSION TITLE
Getting HttpErrorAuthUnknown: Unable to authenticate, need: Basic, Bearer

### DISCUSSION THREAD

**Discussion by AayushSaini101** [verdaccio/verdaccio#4404] [General]
Hello Guys, I am using docker container to run the verdaccio in my local, Docker file is below 

```
version: '3'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: 'verdaccio'
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio:/verdaccio/conf'


```
config.yaml:
```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    access: $authenticated
    proxy: npmjs
log: { type: stdout, format: pretty, level: debug }
```
**password:**
```
username: admin
password: nimda
```
**Generator.js**
```
const generator = new Generator('@asyncapi/html-template@0.16.0', outputDir,
      { forceWrite: true, templateParams: { singleFile: true },
        registry: {url: 'http://localhost:4873/', username: 'admin', password: 'nimda'}});
```

this registry options three values URL, username and password, and passes these parameters to _const arb = new Arborist(registry)_; I want to connect the repository and push some templates. but unable to get it. How can I connect to the? private repository
