### DISCUSSION TITLE
Getting {   "error": "authorization required to access package " }

### DISCUSSION THREAD

**Discussion by AayushSaini101** [verdaccio/verdaccio#4409] [Q&A]
Node version :  v20.10.0
Npm version: 10.2.3

I am using below config file:
```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "**":
    access: $authenticated
    publish: $authenticated
    proxy:  npmjs
log: { type: stdout, format: pretty, level: debug }
```
docker.yml

```
version: '3'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: 'verdaccio'
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio:/verdaccio/conf'
    networks:
      - mynetwork

```
htpasswd file:

`admin:$2a$10$mHopVorSKSZPGTrmGfmMfOnLZKU5M/aXapfjafRqK24eMgREtALRq:autocreated 2024-01-04T16:17:07.359Z`

I can able to login the page via credentials admin, but unable to get any package, but if i removed $authenticated to $all i can able to access is the page. Please any one help with this question 
<img width="906" alt="image" src="https://github.com/verdaccio/verdaccio/assets/60972989/46ebf31d-1b80-4c29-be24-b734ef980bc4">
