### DISCUSSION TITLE
EACCES: permission denied, mkdir '/verdaccio/conf/storage/@asyncapi

### DISCUSSION THREAD

**Discussion by AayushSaini101** [verdaccio/verdaccio#4448] [Q&A]
Getting this error logs while running the changes in the PR. https://github.com/chaudharysumit001/api-generator/actions/runs/7537956541/job/20517681450#:~:text=error%2D%2D%2D%20unexpected%20error%3A-,EACCES%3A%20permission%20denied%2C%20mkdir%20%27/verdaccio/conf/storage/%40asyncapi,-%27

<img width="1458" alt="image" src="https://github.com/verdaccio/verdaccio/assets/60972989/2d5bd1a6-1ae7-42b8-a200-27956e37e8b1">

DockerCompose file:
```

version: '3'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: 'verdaccio'
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio:/verdaccio/conf'
      - './verdaccio:/verdaccio/storage'
    networks:
      - mynetwork

  test-project:
    privileged: true
    image: "node:16"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ../../:/app
    command: bash /app/test/test-project/test.sh test-project | bash /app/test/test-project/test.sh test-registry
  
  
networks:
  mynetwork:
    driver: bridge
```
but this is working perfect in my local
