### DISCUSSION TITLE
Getting  EACCES: permission denied, open '/verdaccio/storage/@asyncapi/html-template/package.json.tmp4446934159360625'

### DISCUSSION THREAD

**Discussion by AayushSaini101** [verdaccio/verdaccio#4450] [Q&A] [answered]
**Your Environment**
  
 * **verdaccio version**: 5
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [mac]
 * **platform**: [ docker,]

**Describe the bug:**
* I am getting  EACCES: permission denied, open '/verdaccio/storage/@asyncapi/html-template/package.json.tmp4446934159360625' in the github actions. This is the folder structure and docker-compose.yml for verdaccio.

**Folder Structure:**

<img width="279" alt="image" src="https://github.com/verdaccio/verdaccio/assets/60972989/c4279488-10a2-48c8-9ce2-49bdb078db85">

Dockerfile:

```
FROM verdaccio/verdaccio:5

# Copy your Verdaccio configuration file to the container
ADD ./verdaccio/conf /verdaccio/conf:z

# Change ownership of the directory without using sudo
USER root
RUN chown -R 100:101 /opt/verdaccio
RUN chmod -R 777 /verdaccio
USER $VERDACCIO_USER_UID
```

**docker-compose.yml**
```


version: '3'

services:
  verdaccio:
    build: .
    container_name: 'verdaccio'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio/conf:/verdaccio/conf:z'
      - './verdaccio/storage:/verdaccio/storage:z'
    networks:
      - mynetwork

  test-project:
    privileged: true
    image: "node:${NODE_IMAGE_TAG}"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ../../:/app
    command: bash /app/test/test-project/test.sh test-project 

networks:
  mynetwork:
    driver: bridge

```
I also checked this issue https://github.com/verdaccio/verdaccio/issues/336#issuecomment-375580151 . and have done the same thing still getting error

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
