### DISCUSSION TITLE
Installing in IIS

### DISCUSSION THREAD

**Discussion by apcjs** [verdaccio/verdaccio#4467] [Q&A]
I have been trying to install verdaccio on IIS all day long and I keep getting a HTTP Error 500.1002 when trying to browse the website. I have tried both on Windows Server 2016 and Windows 11.

I created a folder called verdaccio and installed the latest version, created a config.yaml, web.config and opened the website in a browser.

The node process says "The node.exe process has not written any information to stderr or iisnode was unable to capture this information.". I have given all permissions to the folder. That does not seem to be the problem since the storage folder did get created.

Following is my start.js
```
process.argv.push('-l', 'unix:' + process.env.PORT, '-c', './config.yaml');
require('./node_modules/verdaccio/build/lib/cli.js');
```

and my config.yaml file
```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
```

Any help will be appreciated. Thanks
