### DISCUSSION TITLE
Is it possible to store published packages & cached packages in different directories / with different storage plugins?

### DISCUSSION THREAD

**Discussion by lluiscab** [verdaccio/verdaccio#4519] [Q&A] [answered]
Currently, private packages published to verdaccio and public npm packages cached by verdaccio are all stored on the same directory, with no way (other than reading the database file) of knowing whatever a package is a cached or published and therefore making clearing the cache after some time rather difficult.

Is there any way to configure Verdaccio such that it'd use different storage directories (or even plugins!) for cached and published packages? Ideally I'd like to use the local filesystem for cache and a S3 compatible object server (MinIO) for published packages.

My current configuration looks like this:

```yml
(...)
storage: /verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 12h
  yarn:
    url: https://registry.yarnpkg.com/
    maxage: 12h
(...)
```
