### DISCUSSION TITLE
Can't find package

### DISCUSSION THREAD

**Discussion by SageKwun** [verdaccio/verdaccio#4647] [Q&A] [answered]
I published a package in my own verdaccio. It can be searched by npm:

<img width="808" alt="image" src="https://github.com/verdaccio/verdaccio/assets/65765025/83f5c905-8560-4887-a78d-8a91fb70bf89">

but I can't install it:
<img width="861" alt="image" src="https://github.com/verdaccio/verdaccio/assets/65765025/0c45b7b4-d415-47e5-8d02-0dda1bc54214">

It's sure it is in my storage
<img width="260" alt="image" src="https://github.com/verdaccio/verdaccio/assets/65765025/95305d28-7dce-4571-b6ce-43474a3f9039">

I run verdaccio by official docker image: verdaccio/verdaccio:5.31 and it's my config:

docker-compose.yml
```
  verdaccio:
    image: verdaccio/verdaccio:5.31
    container_name: "verdaccio"
    user: root
    environment:
      # VERDACCIO 服务端口
      - VERDACCIO_PORT=3005
      # 当前登录 linux 服务器的用户名
      - VERDACCIO_USER_NAME="root" 
    ports:
      # 宿主和容器的端口
      - "3005:3005"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
```

config.yaml
```
storage: /verdaccio/storage
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
uplinks:
  server2:
    url: https://registry.npmmirror.com
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: server2
  '**':
    # 这里如果不设置在使用 npm i xxx、 npm publish 时将会提示包不存在，为了方便这里直接设置上如下两行
    access: $all
    publish: $authenticated
    proxy: server2
logs:
  - {type: stdout, format: pretty, level: http}
listen:
  # 这个端口务必对应上
  - 0.0.0.0:3005
```
