### DISCUSSION TITLE
Trying to disable all/any anonymous access, but packages are still available to anonymous users

### DISCUSSION THREAD

**Discussion by ca-wvestjens** [verdaccio/verdaccio#4648] [Q&A]
Hi,

I've got the following config enabled:

```
  packages:
    '@*/*':
      access: $authenticated
      publish: $authenticated
      proxy: ""

    '**':
      access: $authenticated
      publish: $authenticated
      proxy: ""
```

With this, I expect that access (read?) and publishing (write) is reserved to authenticated users only.

That, to me, means if I open the web interface I should not be seeing these packages. This is actually the case, my published test package is available. In the search (if I go to `/-/search?text=package`) and through `npm search` it's not visible.

Any help? Did I misconfigure Verdaccio, is it a bug or is it a feature?
