### DISCUSSION TITLE
How can I force publish local package?

### DISCUSSION THREAD

**Discussion by mxvsh** [verdaccio/verdaccio#4649] [Q&A] [answered]
I am using Nx with monorepo, when I publish a package to Verdaccio, and if the same name exists on NPM registry, it fetches the package from NPM instead of publish the local code. 

How can I make it force publish local code instead of using the one on NPM?

**Comment by juanpicado** [comment, marked as answer]
Check documentation the package access section explains how to

**Reply by mbtools** [reply]
https://verdaccio.org/docs/next/packages 

You need something like this that does *not* list a proxy:

```yaml
packages:
  'npmuser-*':
    access: npmuser
    publish: npmuser
```
