### DISCUSSION TITLE
"Allow access" vs "Allow download/install"

### DISCUSSION THREAD

**Discussion by mbtools** [verdaccio/verdaccio#4783] [Q&A] [answered]
### Scenario

1. All users should be able to view all packages via the web interface 
2. Only authenticated users should be able to Install packages (i.e. download the tarball) 

### Config

For (1) it would need to be

```yaml
packages:
  '**':
    access: $all
```

but for (2) it needs to be

```yaml
packages:
  '**':
    access: $authenticated
```

### Question

Can we implement this scenario using an auth plugin or do we need to enhance verdaccio to support such a scenario (for example by adding `allow_tarball` to the auth plugin interface)?

Ref: [Config](https://verdaccio.org/docs/next/packages), [Auth Plugin](https://verdaccio.org/docs/next/plugin-auth)
