### DISCUSSION TITLE
409 Conflict Errors: this package already present.

### DISCUSSION THREAD

**Discussion by With-Darkness** [verdaccio/verdaccio#4794] [Q&A] [answered]
Hi, Verdaccio development team and developers.
First of all, I appreciate your wonderful product and it's glad to use your project.
Btw, I faced some issues while the installation of Verdaccio and usage.
So I need your help to fix the bugs. My goal is to download the npm packages from npmjs.org server and publish them to the verdaccio local server.

This is my step to install verdaccio.
- Install node v20.15.1, npm v10.7.0
- npm install -g verdaccio
- verdaccio ( Run perfectly)
- Run another command line and execute "npm adduser --registry HTTP://localhost:4873"

Then, I just create new folder and download react package from npmjs.org server. 
- mkdir my-project
- cd my-project
- npm install react

My goal is to publish react package to verdaccio local server, so I publish it like these steps.
- cd node_modules/react
- npm publish --registry HTTP://localhost:4873

Suddenly, I faced the bug like 409 Conflict errors.
![image](https://github.com/user-attachments/assets/26333472-eecc-4a9f-a681-bd51cac3765b)
I didn't published the react package before, I can't solve this issue.

*** NOTE ***
I can see this result in verdaccio console logs.
![image](https://github.com/user-attachments/assets/f2b9024d-67b3-42f4-b524-607ec031b32f)

I hope you help me...

**Comment by juanpicado** [comment, marked as answer]
You need to update your config file.

https://verdaccio.org/docs/best#override-public-packages

Why the 409 happens? Because you named react your package and react already exist as a package in npmjs, you can see your logs clearly says already exist, thus if you insist in call your package react (which I don't recommend, please use scopes always) then you need this setup, but keep on mind you won't be able to use `react` from npmjs.

```
packages:
    'react':
     access: $all
     publish: $authenticated
   '@*/*':
     access: $all
     publish: $authenticated
     proxy: npmjs
   '**':
     access: $all
     publish: $authenticated
     proxy: npmjs
```
