### DISCUSSION TITLE
ERR_CERT_COMMON_NAME_INVALID when opening UI

### DISCUSSION THREAD

**Discussion by hello96** [verdaccio/verdaccio#4860] [Q&A]
Hi everyone!
I'm experiencing something strange.
I have set a Verdaccio registry on a virtual machine: I'm starting Verdaccio as a pm2 process, using Nginx as reverse proxy to serve it on a public domain secured with https.

When I start my pm2 verdaccio process, everything works fine, but after a while when I try to reach the browser UI:

![image](https://github.com/user-attachments/assets/1043511b-5042-43c1-b440-f53f2b2a9143)

I see that it tries to take these resources from https://ip_address/-/static/resource_name, while in the beginning it searches for https://domain_name/-/static/resource_name and it succeeds. I do not change anything in the meanwhile, and if I restart the pm2 process it works again.

My Nginx configuration, taken from the docs, is something like that:

```
server_name my_server_name;
listen 443 ssl;
...        
location / {
                proxy_pass http://127.0.0.1:4873/;
                proxy_set_header Host            $host:$server_port;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
}
```

And my config.yaml:

```
storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated

    proxy: npmjs

server:
  keepAliveTimeout: 60
  url: https://my_domain

listen:
  - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
store:
  aws-s3-storage:
    bucket: my_bucket
    keyPrefix: my_prefix
    region: my_region
    accessKeyId: my_key
    secretAccessKey: my_secret

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: http }
```

Any help on this would be appreciated :D
