### DISCUSSION TITLE
The server is offline, and the installation package uploaded to the server is 404

### DISCUSSION THREAD

**Discussion by huangyiman** [verdaccio/verdaccio#4939] [Q&A] [answered]
**Your Environment**
    verdaccio version: 5.32.1
    node version [18.18.0]:
    package manager: [npm@9.8.1]
    os: [linux]

**Problem description**
My server is offline. When I installed the package from verdaccio, the dependent package got a package 404 error because the package was dependent on a remote third-party package. What can I do to solve this problem?

![1731288381567](https://github.com/user-attachments/assets/2ef05998-a445-4bff-ade7-e3ad34304dec)

Here is my config file:
```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmmirror.com/
publish:
  allow_offline: true
packages:
  '@*/*':
    access: $all
    publish: ["root"]  # $authenticated
    unpublish: ["root"] #  $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: ["root"]
    unpublish: ["root"]
    proxy: npmjs
log:
 { type: file, path: verdaccio.log, level: debug }
listen: 0.0.0.0:4873
```
