### DISCUSSION TITLE
Cache directory cannot be changed

### DISCUSSION THREAD

**Discussion by Iatbzh** [verdaccio/verdaccio#5213] [Q&A] [answered]
**Your environment**
docker

 
* **verdaccio version**: 6.x.x

```
verdaccio -v
v6.1.2

 verdaccio --info

Environment Info:
  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (8) x64 Intel Xeon Processor (Icelake)
  Binaries:
    npm: 10.9.2 - /usr/local/bin/npm
  npmGlobalPackages:
    verdaccio: 6.1.2
``` 

* **node version** [20.x.x, 22.x.x]:
* **package manager**: [npm@10.x.x, pnpm@10.x.x, yarn@2.x.x]
* **os**: [mac, windows@11, linux]
* **platform**: [node, docker, helm, other]
* **reverse proxy**: [yes, no]

**Describe the bug**
Modify the module directory of the storage configuration file. During testing, no cache was found in `/verdaccio/storage`, but it was found in the `/opt` directory

**Steps to reproduce**

```
docker run -d --name rsync-npm \
  -p 4873:4873 \
  -v /verdaccio:/verdaccio \
  --restart=always \
  verdaccio/verdaccio
```

**Expected behavior**

**Screenshots, Verdaccio server log, package manager log**

**Configuration file**

```
storage: /verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 30m
  yarn:
    url: https://registry.yarnpkg.com/

packages:
  '@*/*':
    access: all
    publish: none
    proxy: npmjs yarn
  '*':
    access: all
    publish: none
    proxy: npmjs yarn
log: { type: stdout, format: pretty, level: http }
```

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
