### ISSUE TITLE
500 Internal Server Error recurrent issue

### ISSUE THREAD

**Issue by RaedsLab** [verdaccio/verdaccio#1025]
**Describe the bug**
When running `yarn install` on a project that has momentjs as a dependency, I often get this error: 

```
******** react-ui ...
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91mwarning There appears to be trouble with our server. Retrying...
[0m[91merror An unexpected error occurred: "http://verdaccio.internal/moment/-/moment-2.22.1.tgz: Request failed \"500 Internal Server Error\"".
[0minfo If you think this is a bug, please open a bug report with the information provided in "/opt/source/react-ui/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**To Reproduce**
1. Add moment js as a dependency
2. Run `yarn install` 
3. See error

**Expected behavior**
Install to go through without error.

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio:3.8.1

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```yaml
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all

    publish: $authenticated

    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
```
