### ISSUE TITLE
In search results you can see names of private packages

### ISSUE THREAD

**Issue by darkowic** [verdaccio/verdaccio#107]
I have private and not visible package with name starting with `d`

![verdaccio_no_packages](https://cloud.githubusercontent.com/assets/11510581/21500520/fb679b1c-cc3f-11e6-8cf1-011d0aaa502c.png)

But when I start typing in search as a anonymous user I can see it.
![verdaccio_search](https://cloud.githubusercontent.com/assets/11510581/21500555/49193a64-cc40-11e6-98ea-ee1859a0e0ed.png)

**Comment by juanpicado** [comment]
Can you elaborate this a bit more?

**Comment by darkowic** [comment]
There was an error in my post - the package name starts with 'd'.

ok example - Package is called e.g. `demo`. It is private package. When you type `d` in search on page, the `demo` package will be listed even though it should not be there (couse is private)

**Comment by silkentrance** [comment]
See also #15 which might already provide a fix for this issue.

**Comment by juanpicado** [comment]
@darkowic Could you share the configuration of your demo?

**Comment by darkowic** [comment]
@juanpicado What do you mean the configuration? The js package json config or the verdaccio config?

**Comment by silkentrance** [comment]
@darkowic does this occur after you restarted the verdaccio server or after that you published a new private package to the running verdaccio server?

**Comment by juanpicado** [comment]
@darkowic verdaccio config file. I need to know how to reproduce it.

**Comment by Meeeeow** [comment]
Which version of verdaccio? this issue should fixed after 2.1.5

**Comment by darkowic** [comment]
```
$ verdaccio --version
2.1.0
```

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

url_prefix: something

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'demo*': # here is something else but it should not affect anything
    access: $authenticated
    publish: $authenticated

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
```

The package I host here is called e.g. `demo-something`.

@silkentrance I don't remember if it occurs with first publishing. But, I was restarting the server many times and it is still reproducible
