### ISSUE TITLE
Can verdaccio support the problems encountered in the use?

### ISSUE THREAD

**Issue by zhump** [verdaccio/verdaccio#1078]
hi , I have several questions to consult.

```
#conf.yml

storage: ./storage
plugins: ./plugins
web:
  #enable: false
  title: xx

auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org/
    cache:false
packages:
  '@wukong/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish:
    proxy: npmjs
middlewares:
  audit:
    enabled: true
listen: 0.0.0.0:4873

logs:
  - {type: stdout, format: pretty, level: http}

```
---

Question 1：I hope verdaccio does not cache network resource packs. Only store NPM packets uploaded by verdaccio users? How to set it up?

Question 2：I've observed that any user registered with verdaccio can publish or cancel unpublished packages at will. I hope only the author of the NPM package has permission to manage his own NPM package. How do you set it? 

Question 3：If registered users forget their passwords, how can they be retrieved?

Looking forward to your answer, thank you.
