### ISSUE TITLE
404 no such package available : packagename

### ISSUE THREAD

**Issue by BobNobrain** [verdaccio/verdaccio#1085]
**Describe the bug**
After launching clear verdaccio server and trying to publish new private package, it says "404 ...". All related answers in this repo (like using chmod) didn't work.

**To Reproduce**
With `docker-compose.yml`:

```
version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.x-next # or version 3, doesn't matter
    container_name: verdaccio
    ports:
      - "127.0.0.1:4873:4873"
    volumes:
      - /opt/npm-registry/conf:/verdaccio/conf
      - /opt/npm-registry/plugins:/verdaccio/plugins
# no storage volume mounted to be sure it's not permissions issue
# with storage directory mounted, the problem persists
    restart: on-failure
```
And configuration file:

```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
plugins: ./plugins
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  'packagename':
    access: $authenticated
    publish: $authenticated
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
url_prefix: /npm/
```

1. Run `docker-compose up`
2. Login into npm registry
3. Publish `packagename` with npm and `--registry`

**Expected behavior**
4. Package is published succesfully

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: 3/4.x-next
 - Docker Version: `Docker version 18.06.1-ce, build e68fc7a`
 - docker-compose version: `docker-compose version 1.22.0, build f46880fe`

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
(listed above)

**Comment by juanpicado** [comment]
Since I cannot see any log here, hard to help.
It seems quite related to.
https://github.com/verdaccio/verdaccio/issues/483
https://github.com/verdaccio/verdaccio/issues/305

**Comment by feyzullahyildiz** [comment]
Same thing is here. 

Here is verdaccio docker logs, when i try to publish like _**npm publish --registry http://159.***.***.140:4873**_
http <-- 404, user: admin(176.***.***.34), req: 'PUT /test-npm-package', error: no such package available
 http <-- 404, user: admin(176.***.***.34), req: 'PUT /test-npm-package', error: no such package available
 http <-- 508, user: null(172.19.0.1), req: 'GET /test-npm-package', error: loop detected
 http <-- 508, user: null(172.19.0.1), req: 'GET /test-npm-package', error: loop detected
 http --> 508, req: 'GET http://159.***.***.140:4873/test-npm-package' (streaming)
 http --> 508, req: 'GET http://159.***.***.140:4873/test-npm-package', bytes: 0/31
 http <-- 404, user: admin(176.***.***.34), req: 'PUT /test-npm-package', error: no such package available
 http <-- 404, user: admin(176.***.***.34), req: 'PUT /test-npm-package', error: no such package available

### config.yaml
![image](https://user-images.githubusercontent.com/28671359/47321473-941c8600-d65d-11e8-893a-16292340834c.png)

### server, docker, docker-compose
![image](https://user-images.githubusercontent.com/28671359/47320322-c926d980-d659-11e8-81b6-0b162a835ead.png)

### Here is client log
![image](https://user-images.githubusercontent.com/28671359/47320278-a7c5ed80-d659-11e8-895c-3f37f8c73861.png)

I tried to _**sudo chown -R 100:101 /opt/verdaccio**_. But there is nothing in this path _**/opt/verdaccio**_

then i tried this  _**chown -R 100:101 /usr/local/app/bin/verdaccio**_ but it is still same

i tried those on verdaccio/verdaccio:3.0.0 verdaccio/verdaccio:latest

**Comment by BobNobrain** [comment]
I've made a small repo that reproduces this issue
https://github.com/BobNobrain/verdaccio-bug-reproduce
In README you can find step-by-step instructions and verdaccio and npm logs

**Comment by SAprelov** [comment]
I have the same issue. But floating. Re-run "npm i" sometime hepls. Every time different package.
It starts few days ago. Is it http://registry.adv-ms.com changes?

**Comment by LinBoLen** [comment]
maybe you used docker as a server. the verdaccio use `verdaccio` group and user to r/w /verdaccio directory. the default the mounted directory is owned by root:root. 
when i changed the permission i works
```
drwxr-xr-x. 5 root  root 4096 Mar  3 10:34 .
drwxr-xr-x. 3 root  root 4096 Mar  3 10:34 ..
drwxr-xr-x. 2 10001  101 4096 Mar  3 12:07 conf
drwxr-xr-x. 2 10001  101 4096 Mar  3 10:34 plugins
drwxr-xr-x. 3 10001  101 4096 Mar  3 12:54 storage
```

btw. why need use `verdaccio` user/group. it almost block all docker user
https://github.com/verdaccio/verdaccio/blob/master/Dockerfile#L35-L39

**Comment by juanpicado** [comment]
Hi, sorry the big delay. I just stumbled with this while I was doing other tests with Docker

It turns out works for me, 

```
verdaccio-bug-reproduce/pkg1 on  master [!?] is 📦 v1.0.0 via ⬢ v10.15.0 at ☸️  docker-desktop took 4s 
➜ npm publish --registry http://0.0.0.0:4873/
npm notice 
npm notice 📦  pkg1-by-lupa@1.0.0
npm notice === Tarball Contents === 
npm notice 230B package.json
npm notice === Tarball Details === 
npm notice name:          pkg1-by-lupa                            
npm notice version:       1.0.0                                   
npm notice package size:  259 B                                   
npm notice unpacked size: 230 B                                   
npm notice shasum:        4e3a403c2ed8bb39f83da8a8146f373ab6c09cd9
npm notice integrity:     sha512-DTH8QNrICpWeh[...]Ot/5QcT0BvV/g==
npm notice total files:   1                                       
npm notice 
+ pkg1-by-lupa@1.0.0
```

Aside from that, I just noticed you were using `url_prefix: /npm/` but in the example, I do not see any prefix of reverse proxy.


![Screen Shot 2019-05-01 at 5 34 39 PM](https://user-images.githubusercontent.com/558752/57025596-de4b7900-6c37-11e9-9aca-b0e1b457c316.png)



In any case, I made some implementations here https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx

**Comment by Niklv** [comment]
I think it cause error in default configuration presented in [docs](https://verdaccio.org/docs/en/configuration#default-configuration).

I try define path in absolute way:

```yaml
storage: /verdaccio/storage
plugins: /verdaccio/plugins
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
```

And it starts work for me.
