### ISSUE TITLE
Cannot login properly for publishing

### ISSUE THREAD

**Issue by bolrock** [verdaccio/verdaccio#1088]
**Describe the bug**

> Windows 10
> Node is v8.12.0
> Npm is v6.4.1

When I try to login, it always tries to create a new user, even if the user already exists in the htpasswd.
The first time it tells me I'm logged but I can't publish : 'Your credentials could not be authenticated'

**To Reproduce**
1. install verdaccio - npm install verdaccio -g
2. start the server - verdaccio

>  warn --- config file  - C:\Users\toto\.config\verdaccio\config.yaml
>  warn --- Plugin successfully loaded: htpasswd
>  warn --- Plugin successfully loaded: audit
>  warn --- http address - http://localhost:4873/ - verdaccio/3.8.5

3. In my project, try to login - npm login --registry http://localhost:4873/ -ddd

> npm info it worked if it ends with ok
> npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> npm verb cli   'C:\\Users\\toto\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> npm verb cli   'login',
> npm verb cli   '--registry',
> npm verb cli   'http://localhost:4873/',
> npm verb cli   '-ddd' ]
> npm info using npm@6.4.1
> npm info using node@v8.12.0
> npm verb npm-session 14ea0a1a0794ccb8
> npm verb web login before first POST
> npm http request → POST http://localhost:4873/-/v1/login
> npm http 404 ← Not Found (http://localhost:4873/-/v1/login)
> npm verb web login not supported, trying couch
> Username: toto
> Password:
> Email: (this IS public) toto@myhost.be
> npm verb login before first PUT { _id: 'org.couchdb.user:toto',
> npm verb login   name: 'toto',
> npm verb login   password: 'XXXXX',
> npm verb login   type: 'user',
> npm verb login   roles: [],
> npm verb login   date: '2018-10-23T10:26:55.214Z' }
> npm http request → PUT http://localhost:4873/-/user/org.couchdb.user:toto
> npm http 201 ← Created (http://localhost:4873/-/user/org.couchdb.user:toto)
> npm info login Authorized user toto
> Logged in as toto on http://localhost:4873/.
> npm verb exit [ 0, true ]
> npm timing npm Completed in 53593ms
> npm info ok

4. The user is added in the htpasswd, the .npmrc now contains //localhost:4873/:_authToken="..."

5. Trying to publish - npm publish --registry http://localhost:4873/ -ddd

> npm sill publish uploading C:\Users\toto\AppData\Local\Temp\npm-10304-65f22e14\tmp\fromDir-0d32a427\package.tgz
> npm verb request uri http://localhost:4873/calc-area
> npm verb request always-auth set; sending authorization
> npm info attempt registry request try #1 at 12:35:23
> npm verb request using bearer token for auth
> npm verb request id 6ebcd5b8aa5306b6
> npm http request PUT http://localhost:4873/calc-area
> npm http 407 http://localhost:4873/calc-area
> npm verb bad json <HTML><HEAD>
> npm verb bad json <TITLE>Access Denied</TITLE>
> ...
> npm verb bad json Your credentials could not be authenticated: "General authentication failure due to bad user ID or authentication token.". You will not be permitted access until your credentials can be verified.
> ...

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: http}
```

First strange thing : the login url used is http://localhost:4873/-/v1/login. If I'm trying to login with the web interface the url used is http://localhost:4873/-/verdaccio/login (and it is working - I can login)

So it seems that it is not trying to login but just creating a new user. I suppose it is because of the 404 error on the login url.
