### ISSUE TITLE
Problems hosting under IIS using Azure/IISNode

### ISSUE THREAD

**Issue by woakesd** [verdaccio/verdaccio#1102]
I'm trying to run verdaccio under iisnode. OS is Windows Server 2012, NodeJS 8.11.1.

I get the following error when I visit the home page in a browser:

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:
```
Application has thrown an uncaught exception and is terminated:
Error: "audit" plugin not found
try "npm install verdaccio-audit"
    at D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\plugin-loader.js:60:13
    at Array.map (<anonymous>)
    at load_plugins (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\plugin-loader.js:34:51)
    at module.exports (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\api\index.js:89:19)
    at afterConfigLoad (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\cli.js:118:15)
    at Object.<anonymous> (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\cli.js:69:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```
I've installed verdaccio-audit as suggested and the error changes to:

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:
```
Application has thrown an uncaught exception and is terminated:
Error: "audit" doesn't look like a valid plugin
    at D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\plugin-loader.js:65:13
    at Array.map (<anonymous>)
    at load_plugins (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\plugin-loader.js:34:51)
    at module.exports (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\api\index.js:89:19)
    at afterConfigLoad (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\cli.js:118:15)
    at Object.<anonymous> (D:\verdaccio\01-dev\html\node_modules\verdaccio\src\lib\cli.js:69:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**To Reproduce**
Add the following files in the home directory
```
start.js:
`process.argv.push('-l', 'unix:' + process.env.PORT, '-c', './config.yaml');
require('./node_modules/verdaccio/src/lib/cli.js');`

package.json:
`{
  "name": "iisnode-verdaccio",
  "version": "1.0.0",
  "description": "Hosts verdaccio in iisnode",
  "main": "start.js",
  "dependencies": {
    "verdaccio": "^2.7.4"
  }
}`
```
```
Web.config
`<configuration>
  <system.webServer>
    <modules>
        <remove name="WebDAVModule" />
    </modules>

    <!-- indicates that the start.js file is a node.js application
    to be handled by the iisnode module -->
    <handlers>
            <remove name="WebDAV" />
            <add name="iisnode" path="start.js" verb="*" modules="iisnode" resourceType="Unspecified" />
            <add name="WebDAV" path="*" verb="*" modules="WebDAVModule" resourceType="Unspecified" requireAccess="Execute" />
    </handlers>

    <rewrite>
      <rules>

        <!-- iisnode folder is where iisnode stores it's logs. These should
        never be rewritten -->
        <rule name="iisnode" stopProcessing="true">
          <match url="iisnode*" />
          <action type="None" />
        </rule>

        <!-- Rewrite all other urls in order for verdaccio to handle these -->
        <rule name="verdaccio">
          <match url="/*" />
          <action type="Rewrite" url="start.js" />
        </rule>
      </rules>
    </rewrite>

    <!-- exclude node_modules directory and subdirectories from serving
    by IIS since these are implementation details of node.js applications -->
    <security>
      <requestFiltering>
        <hiddenSegments>
          <add segment="node_modules" />
        </hiddenSegments>
      </requestFiltering>
    </security>

  </system.webServer>
</configuration>`
```
**Expected behavior**
Get verdaccio home page

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Dev - Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```
**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
Doesn't work in Windows Powershell

 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
Doesn't work in Windows Powershell
```
 - `$ npm -ddd` prints:
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '-ddd' ]
npm info using npm@5.6.0
npm info using node@v8.11.1

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\davidw\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 C:\Program Files\nodejs\node_modules\npm
```

 - `$ npm config get registry` prints:

https://registry.npmjs.org/

**Additional context**
