### ISSUE TITLE
Unable to publish package after changing listen address

### ISSUE THREAD

**Issue by unional** [verdaccio/verdaccio#111]
I was trying and using `verdaccio` with the default setting (`localhost:4873`) and it was working fine.

I now change the listen address to `0.0.0.0:4873` to allow other machines accessing it.

But then I cannot publish to it anymore:

```sh
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

When I run `npm adduser` again, it complains the user already exists.

I try to uninstall and reinstall `verdaccio` but the error still presist.

How can I clear the users and start over?

EDIT: To clarify, I can't publish when I change the `package.json/publishConfig` pointing to the public ip address of the hosting machine.

Changing it back to `localhost:4873` works.

**Comment by HJoost** [comment]
Same problem here :(

**Comment by Cosaquee** [comment]
I do knot know why this error happens but a quick fix is to setup reverse proxy (Apache or Nginx) so you can have verdaccio running on localhost but still be accessible from other machines.

**Comment by HJoost** [comment]
Please have a look at my edited comment above! (Wrong permission in the config was the failure)

**Comment by unional** [comment]
I checked my config file and it doesn't have the users section. Here is my config:

```yml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: F:/verdaccio/storage

auth:
  htpasswd:
    file: F:/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
listen:
  - 0.0.0.0:4873
```
