### ISSUE TITLE
npm adduser hangs after email

### ISSUE THREAD

**Issue by martijnhiemstra** [verdaccio/verdaccio#1136]
I am using the verdaccio docker image ("verdaccio/verdaccio"). I have it up and running using the default config.yaml file. According to the docker logs the image is up and running and I can view the website by typing in the url in my browser. I see the intro page saying first add a user and then publish. So I start by adding a user. I type in the following. 

npm adduser --registry  http://192.168.1.200:4873

I can confirm that the server can be reached because I am asked to type in a username, password and email address. After the email address the command hangs. The only thing I can do is Ctrl-C. For some reason npm adduser doesn't work with verdaccio!

I am using the latest docker image. This is the config file:

```

storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@jota/*':
      access: $all
      publish: $all

  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  #- {type: file, path: verdaccio.log, level: info}


```
