### ISSUE TITLE
[helm] Dashboard says there is no packages 

### ISSUE THREAD

**Issue by r-moiseev** [verdaccio/verdaccio#1140]
**Describe the bug**
We have one user in verdaccio, and several scoped packages published by this user. Some time ago verdaccio was restarted and and then i can see all packages in storage, everything works fine in npm cli but i can see no packages in web interface

**To Reproduce**
1. deploy verdaccio with stable helm chart
2. publish some packages
3. restart node which hosts verdaccio pod
4. See no packages in web interface, but everything works in cli

**Kubernetes**
 - Docker verdaccio tag: verdaccio:3.8.1
 - Kubernetes version: 1.11
 - Helm chart version: 0.5.0

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/docs/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage/data

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: 1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```
