### ISSUE TITLE
Unable to specify path for config files.

### ISSUE THREAD

**Issue by nsisodiya** [verdaccio/verdaccio#1141]
I have used following config file (YML)

```
storage:  ~/verdaccio/storage
auth:
    htpasswd:
         file: ~/verdaccio/htpasswd
```
But , it is creating verdaccio folder in current directory of config file but not the actual home directory.

**Comment by juanpicado** [comment]
Some info relevant how we treat those paths (https://verdaccio.org/docs/en/cli#default-config-file-location)

**Comment by nsisodiya** [comment]
@juanpicado - I am following following structure.

![image](https://user-images.githubusercontent.com/333455/49202337-461c4000-f3ca-11e8-837d-a3826c58d519.png)

package.json
```json
{
  "name": "verdaccio-repo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "verdaccio --config ./config.yaml"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/rivigotech/verdaccio.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/rivigotech/verdaccio#readme",
  "dependencies": {
    "verdaccio": "^3.8.6"
  }
}
```

config.yml
```yml
storage: ~/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

listen: 0.0.0.0:4000

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Rivigo NPM Registry

auth:
  htpasswd:
    file: ~/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

```

and then starting the verdaccio with following command.

```bash
npm run start
```
====
The above start the verdaccio but it create a directory inside the git repo project "~". Like this

![image](https://user-images.githubusercontent.com/333455/49202472-b9be4d00-f3ca-11e8-8a43-4ff0b5f08464.png)

I actually, want to point the home location or custom location relative to home.

cc - @ayusharma

**Comment by juanpicado** [comment]
why `storage: ~/verdaccio/storage` ? Any specific reason? It takes user home folder by default.

**Comment by nsisodiya** [comment]
@juanpicado 
```
storage: ./storage
```
The default value is `./storage`
If I use this default value then it will create storage folder in the current git repo path.

```yaml
storage: ./storage
plugins: ./plugins
listen: 0.0.0.0:8000
web:
  title: Rivigo NPM Registry
auth:
  htpasswd:
    file: ./htpasswd
```

then these files are created directly inside the git repo like this.

![image](https://user-images.githubusercontent.com/333455/49221065-04a58800-f3fe-11e8-9fbd-a9d4e61ee52a.png)

Am I able to explain my problem?
