### ISSUE TITLE
npm search from CLI crashes verdaccio (jsonparse)

### ISSUE THREAD

**Issue by timo-lindemann-victors** [verdaccio/verdaccio#1146]
**Describe the bug**

when a client issues `npm search` for any package, the following happens on the client (rimraf being just an example): 

```
T:\myapp>npm search rimraf
npm WARN search fast search endpoint errored. Using old search.
npm WARN Failed to read search cache. Rebuilding
npm WARN Building the local index for the first time, please be patient
npm WARN all-package-metadata entry-update-stream Empty or invalid stream
npm ERR! No search sources available

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\npm\cache\_logs\2018-12-04T09_32_31_612Z-debug.log
```

Verdaccio is now crashed! Logging into the server where it is supposed to run, the following snippet is in the logs:

```
 fatal --- uncaught exception, please report this
Error: Invalid JSON (Unexpected "\u001f" at position 0 in state STOP)
    at Parser.proto.charError (E:\Verdaccio\node_modules\jsonparse\jsonparse.js:89:16)
    at Parser.proto.write (E:\Verdaccio\node_modules\jsonparse\jsonparse.js:153:23)
    at Stream.<anonymous> (E:\Verdaccio\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (E:\Verdaccio\node_modules\through\index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:121:20)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
```

These are windows server and client. 

node 8.11.4
winsw 1.17.0.0

**To Reproduce**

Issue `npm search` for anything on a client.

**Expected behavior**

Verdaccio should answer it for 

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: E:\Verdaccio\storage
listen: 0.0.0.0:4873

auth:
  htpasswd:
    file: E:\Verdaccio\htpasswd
    max_users: -1

# Webinterface 	
web:
  enable: true
  title: Verdaccio
  
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:  

  # had to strip this bit, sorry

  '**':
    access: $all
    publish: 
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

**Debugging output**

see above

**Additional context**

I am the developer who just discovered that he can accidentally crash verdaccio, which makes our build bot go up in flames, shortly after, as well.

I am not an admin on the server it is happening on and I probably cannot do much on it. I am also not used to Windows servers.

If this bug report is insufficient or malformed, I will see what I can do to revise it.
