### ISSUE TITLE
Verdaccio lost offline functionality

### ISSUE THREAD

**Issue by berdario** [verdaccio/verdaccio#1157]
**Describe the bug**
Verdaccio 3.x doesn't support anymore its offline mode

**To Reproduce**
1. Install verdaccio (tested with 3.0.0 and 3.10.0)
2. Remove/comment out the `proxy: npmjs` lines, as discussed in https://github.com/verdaccio/verdaccio/issues/199
3. Use verdaccio to cache dependencies
4. Go offline

**Expected behavior**
Verdaccio works, serves cached packages

What happens:

```> yarn run verdaccio
yarn run v1.9.4
warning package.json: No license field
$ /private/tmp/afihw/node_modules/.bin/verdaccio
 warn --- config file  - /Users/berdario/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:4873/ - verdaccio/3.0.0
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /apigeetool/-/apigeetool-0.7.1.tgz', bytes: 0/30089
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /cli-prompt/-/cli-prompt-0.5.1.tgz', bytes: 0/4265
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /config/-/config-1.31.0.tgz', bytes: 0/25338
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /async/-/async-1.5.2.tgz', bytes: 0/38923
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /edgemicro/-/edgemicro-2.5.29.tgz', bytes: 0/81642
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /@google-cloud%2ftrace-agent/-/trace-agent-3.4.0.tgz', bytes: 0/64708
 error--- unexpected error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /body-parser/-/body-parser-1.18.3.tgz', error: internal server error
 warn --> host registry.npmjs.org is now offline
 error--- unexpected error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /commander/-/commander-2.19.0.tgz', error: internal server error
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /cpr/-/cpr-1.1.2.tgz', bytes: 0/21603
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /debug/-/debug-3.2.6.tgz', bytes: 0/20436
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /diff/-/diff-3.5.0.tgz', bytes: 0/189607
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /forever-monitor/-/forever-monitor-1.7.1.tgz', bytes: 0/16346
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /fs-extra/-/fs-extra-0.20.1.tgz', bytes: 0/15229
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /js-yaml/-/js-yaml-3.12.0.tgz', error: uplink is offline
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /jsonwebtoken/-/jsonwebtoken-5.7.0.tgz', bytes: 0/18311
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /lodash/-/lodash-4.17.11.tgz', error: uplink is offline
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /log-symbols/-/log-symbols-1.0.2.tgz', bytes: 0/1755
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /memored/-/memored-1.1.1.tgz', bytes: 0/9146
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /microgateway-config/-/microgateway-config-2.4.14.tgz', bytes: 0/18773
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /microgateway-core/-/microgateway-core-2.5.14.tgz', bytes: 0/32808
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /microgateway-edgeauth/-/microgateway-edgeauth-2.4.9.tgz', bytes: 0/281659
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /microgateway-plugins/-/microgateway-plugins-2.3.31.tgz', bytes: 0/49363
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /pem/-/pem-1.13.2.tgz', bytes: 0/59803
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /portastic/-/portastic-1.0.1.tgz', bytes: 0/4318
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /request/-/request-2.88.0.tgz', error: uplink is offline
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /rimraf/-/rimraf-2.6.2.tgz', bytes: 0/5535
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /tmp/-/tmp-0.0.28.tgz', bytes: 0/10712
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /uuid/-/uuid-3.3.2.tgz', error: uplink is offline
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /volos-cache-memory/-/volos-cache-memory-0.10.1.tgz', bytes: 0/2505
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /volos-spikearrest-common/-/volos-spikearrest-common-0.10.3.tgz', bytes: 0/5086
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /volos-spikearrest-memory/-/volos-spikearrest-memory-0.10.1.tgz', bytes: 0/2337
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /xml2js/-/xml2js-0.4.19.tgz', bytes: 0/12371
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /@google-cloud%2fcommon/-/common-0.27.0.tgz', bytes: 0/20389
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /builtin-modules/-/builtin-modules-3.0.0.tgz', bytes: 0/1970
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /console-log-level/-/console-log-level-1.4.0.tgz', bytes: 0/3381
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /continuation-local-storage/-/continuation-local-storage-3.2.1.tgz', bytes: 0/20521
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /extend/-/extend-3.0.2.tgz', error: uplink is offline
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /gcp-metadata/-/gcp-metadata-0.9.0.tgz', bytes: 0/6582
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /hex2dec/-/hex2dec-1.1.1.tgz', bytes: 0/6695
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /is/-/is-3.2.1.tgz', bytes: 0/11702
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /methods/-/methods-1.1.2.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /commander/-/commander-2.19.0.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /body-parser/-/body-parser-1.18.3.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /js-yaml/-/js-yaml-3.12.0.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /lodash/-/lodash-4.17.11.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /request/-/request-2.88.0.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /uuid/-/uuid-3.3.2.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /extend/-/extend-3.0.2.tgz', error: uplink is offline
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /methods/-/methods-1.1.2.tgz', error: uplink is offline
```

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /Users/berdario/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
    npmjs:
        url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    #proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    #proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**

This works up until verdaccio@2.7.4, as described in this [other issue](https://github.com/verdaccio/verdaccio/issues/199)
