### ISSUE TITLE
UI search is very buggy

### ISSUE THREAD

**Issue by kaiyoma** [verdaccio/verdaccio#1159]
**Describe the bug**
Searching for some simple terms results in no results or an error.

**To Reproduce**
1. In our deployment, if I search for a simple term (e.g. "redux"), there are no results, even though we have multiple packages with that term in the name. This doesn't happen with all words, just some.
2. Likewise, if I search for a package name with a scope (e.g. "@company/package"), I get an error dialog that says "Unable to get search result, please try again later."

**Expected behavior**
The search results should be correct and no errors should appear.

**Screenshots**
![verdaccio-error](https://user-images.githubusercontent.com/10719780/49907925-2c98e080-fe2d-11e8-9f82-58e321c6aa8e.png)

**Extra Information**
Most of our packages have scoped names. Maybe that's causing issues?

**Comment by kaiyoma** [comment]
Sorry, I thought I had included the version: I'm seeing the search problems in 3.7 and 3.10. Can you be more specific about what configuration you need? This is our internal registry, so I can't include any specific details like paths or IP addresses or package names. What is "log server"?

(Sorry if these questions seem rudimentary. We don't have an official Verdaccio maintainer here and it's just kind of ad hoc. I'm not familiar with how this package is configured.)

**Comment by juanpicado** [comment]
> Can you be more specific about what configuration you need? 

A file with this content (please before publish remove or hide sensitive data)
https://github.com/verdaccio/verdaccio/blob/master/conf/default.yaml and you can find it here https://verdaccio.org/docs/en/cli#default-config-file-location

The log server is the output when verdaccio runs, something like this. It's crucial due errors are displayed there. 

![dss](https://verdaccio.org/svg/verdaccio_server.gif)

>  This is our internal registry, so I can't include any specific details like paths or IP addresses or package names. What is "log server"?

I just need the error is displayed in our log if there is any, you can remove sensitive data.

The errors on UI usually are quite abstract and we never raise the original reason to the final user.

> (Sorry if these questions seem rudimentary. We don't have an official Verdaccio maintainer here and it's just kind of ad hoc. I'm not familiar with how this package is configured.)

No worries. I'm here to help.

> https://github.com/verdaccio/verdaccio/issues/1159#issuecomment-446857126

You can try version alpha either installing locally `npm i -g verdaccio@next` and testing locally.
Without your feedback I'm blind.

**Comment by kaiyoma** [comment]
Okay, let me turn on logging to file and see if I can get you something helpful.

**Comment by kaiyoma** [comment]
Okay, here's our config with sensitive info removed:

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: <redacted>

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false

  title: <redacted>

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100

packages:
  <redacted>:
    access: $all
    publish: $all

  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}

listen:
  - 0.0.0.0:4873
```

When I search the UI for "redux", which should result in two matches, I see these two log messages (again, sensitive info redacted):

```
{
  "name": "verdaccio",
  "hostname": "<redacted>",
  "pid": 1,
  "sub": "in",
  "level": 30,
  "req": {
    "method": "GET",
    "url": "/-/verdaccio//search/redux",
    "headers": {
      "host": "<redacted>",
      "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redacted> Safari/537.36",
      "dnt": "1",
      "accept": "*/*",
      "referer": "http://<redacted>/",
      "accept-encoding": "gzip, deflate",
      "accept-language": "en-US,en;q=0.9",
      "cookie": "<Classified>",
      "x-forwarded-for": "<redacted>",
      "connection": "close"
    },
    "remoteAddress": "<redacted>",
    "remotePort": 51916
  },
  "ip": "<redacted>",
  "msg": "<redacted> requested 'GET /-/verdaccio//search/redux'",
  "time": "2018-12-17T08:12:30.040Z",
  "v": 0
}
{
  "name": "verdaccio",
  "hostname": "<redacted>",
  "pid": 1,
  "sub": "in",
  "level": 35,
  "request": {
    "method": "GET",
    "url": "/-/verdaccio//search/redux"
  },
  "user": null,
  "remoteIP": "<redacted> via <redacted>",
  "status": 200,
  "bytes": {
    "in": 0,
    "out": 3
  },
  "msg": "200, user: null(<redacted> via <redacted>), req: 'GET /-/verdaccio//search/redux', bytes: 0/3",
  "time": "2018-12-17T08:12:30.043Z",
  "v": 0
}
```
