### ISSUE TITLE
Yarn fails to publish if --new-version parameter is defined.

### ISSUE THREAD

**Issue by serratedserenade** [verdaccio/verdaccio#1160]
**Describe the bug**
I am currently using Lerna and Yarn along with Verdaccio hosted on Google Cloud. Running `lerna publish --canary` attempts to append `--new-version xxxx` to yarn, which makes yarn fail to perform the upload with a ESOCKETTIMEDOUT error. Yarn is able to publish if `--new-version xxxx` is not provided.

**To Reproduce**
1. Go to project that you are publishing to a Verdaccio private repo with
2. Run `yarn publish --new-version [whateverversion] # other params`

**Expected behavior**
Expect to publish successfully

**Debugging output**
```
verbose 30.845 Error: Couldn't publish package: "https://npm.publift.com/@publift%2fslack: ESOCKETTIMEDOUT"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:727:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:756:123)
    at /usr/lib/node_modules/yarn/lib/cli.js:89265:13
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Couldn't publish package: "https://npm.publift.com/@publift%2fslack: ESOCKETTIMEDOUT"
```

When ran without `--new-version` param for yarn:
```
verbose 2.033 Request "https://npm.publift.com/@publift%2fslack" finished with status code 409.
verbose 2.045 Error: Couldn't publish package: "https://npm.publift.com/@publift%2fslack: this package is already present"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:727:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:756:123)
    at /usr/lib/node_modules/yarn/lib/cli.js:89265:13
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Couldn't publish package: "https://npm.publift.com/@publift%2fslack: this package is already present"
```
Seems to check correctly if the package is already there (since I already published)

Server error:
```
(node:5) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  (0, _assert2.default)((0, _utils.validateName)(filename))
    at LocalStorage.addTarball (/nodejs/lib/node_modules/verdaccio/build/lib/local-storage.js:389:26)
    at Storage.addTarball (/nodejs/lib/node_modules/verdaccio/build/lib/storage.js:147:30)
    at create_tarball (/nodejs/lib/node_modules/verdaccio/build/api/endpoint/api/publish.js:15:28)
    at after_change (/nodejs/lib/node_modules/verdaccio/build/api/endpoint/api/publish.js:65:7)
    at /nodejs/lib/node_modules/verdaccio/build/api/endpoint/api/publish.js:118:9
    at /nodejs/lib/node_modules/verdaccio/build/lib/storage.js:85:9
    at Generator.throw (<anonymous>)
    at step (/nodejs/lib/node_modules/verdaccio/build/lib/storage.js:51:191)
    at /nodejs/lib/node_modules/verdaccio/build/lib/storage.js:51:402
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 234)
 ```

**Additional context**
Using Lerna and Yarn.

**Comment by juanpicado** [comment]
`0, _utils.validateName` seems to be the key here. But without version or config file sample I cannot dive into it.

**Comment by serratedserenade** [comment]
```
store:
  google-cloud:
    projectId: publift-dashboard
    kind: publiftNpmStore
    bucket: publift-npm-store

middlewares:
  github-oauth-ui:
    client-id: xxx 
    client-secret: xxx 
  github-oauth:
    client-id: xxx
    client-secret: xxx

auth:
  github-oauth-ui:
    org: Publift
  github-oauth:
    org: Publift

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@publift/*':
    # scoped packages
    access: $authenticated 
    publish: serratedserenade
    proxy: npmjs

  '**':
    access: all
    publish: all
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: debug}

web:
  enable: true
  title: Publift Private NPM Repo
```

Currently on version 3.8.6
