### ISSUE TITLE
npm install is success, but no package is downloaded in the project

### ISSUE THREAD

**Issue by muzichen** [verdaccio/verdaccio#1162]
I just create a npmtest directory to test the "npm publish" and "npm install" command for verdaccio.  These two commands all executed successfully and there is also the npmtest package in verdaccio's storage directory. But after executed "npm installl npmtest" in my own project directory, the package did not being downloaded.

**config.yaml**
```
storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  cnpmjs:
    url: https://registry.npm.taobao.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: cnpmjs

  '**':
    access: $all

    publish: $authenticated

    proxy: cnpmjs

middlewares:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: http}
```
**output after "npm publish"**
![image](https://user-images.githubusercontent.com/7547416/50070644-cbe11d80-0209-11e9-8342-db98cfecc6b2.png)

**output after "npm install npmtest"**

![image](https://user-images.githubusercontent.com/7547416/50070699-02b73380-020a-11e9-961e-d06838ed1122.png)

After "npm install npmtest", the test2 directory was still empty.

![image](https://user-images.githubusercontent.com/7547416/50070733-211d2f00-020a-11e9-816a-e40b2d412ea0.png)
