### ISSUE TITLE
receive cb() never called! error on npm install when using verdaccio

### ISSUE THREAD

**Issue by TrentonAdams** [verdaccio/verdaccio#1168]
**Describe the bug**
npm install results in the following error.  Contrary to the message below it does not appear to be an npm issue, since if I disable verdaccio and go directly to npm registries, everything works.  I thought it might be a size issue so I added max_body_size to the end of my config.

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trenta/.npm/_logs/2018-12-28T10_01_07_373Z-debug.log

**To Reproduce**
1. npm i -g create-react-native-app
2. create-react-native-app my-project

**Expected behavior**
It should work, but npm fails.

**Screenshots**
```
$ create-react-native-app my-project
? Choose a template: expo-template-tabs
[02:54:38] Extracting project files...
[02:54:39] Customizing project...
[02:54:39] Installing dependencies...
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trenta/.npm/_logs/2018-12-28T09_55_03_457Z-debug.log
[02:55:03] Process exited with non-zero code: 1
[02:55:03] Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

max_body_size: 200mb
```

**Debugging output**
Verdaccio is running in the verdaccio docker image, so it would take me awhile to debug that.  Since the steps are easily reproduced, it's best if a verdaccio developer looks at that.

```
$ npm -ddd install
npm info it worked if it ends with ok
npm verb cli [ '/home/trenta/.nvm/versions/node/v11.6.0/bin/node',
npm verb cli   '/home/trenta/.nvm/versions/node/v11.6.0/bin/npm',
npm verb cli   '-ddd',
npm verb cli   'install' ]
npm info using npm@6.5.0-next.0
npm info using node@v11.6.0
npm verb npm-session f1e79edb6538a8fd
npm sill install runPreinstallTopLevelLifecycles
npm sill preinstall my-project
npm info lifecycle @~preinstall: @
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm timing stage:loadCurrentTree Completed in 24ms
npm sill install loadIdealTree
npm sill install cloneCurrentTreeToIdealTree
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm sill install loadShrinkwrap
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 7ms
npm sill install loadAllDepsIntoIdealTree
npm http fetch GET 200 http://localhost:4873/@expo%2fsamples 672ms
npm http fetch GET 200 http://localhost:4873/babel-preset-expo 693ms
...
npm sill pacote version manifest for react@16.5.0 fetched in 30ms
npm sill resolveWithNewModule react@16.5.0 checking installable status
npm sill pacote range manifest for react-navigation@^2.18.2 fetched in 30ms
npm sill resolveWithNewModule react-navigation@2.18.3 checking installable status
npm timing npm Completed in 30895ms
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trenta/.npm/_logs/2018-12-28T10_01_07_373Z-debug.log
```

```
$ cat ~/.npmrc
registry=http://localhost:4873/
proxy=http://localhost:4873/
https-proxy=http://localhost:4873/
//localhost:4873/:_authToken="dpn8isKmzoTzAualPGNUDQ=="
```
