### ISSUE TITLE
Add support for packages containing @ and /

### ISSUE THREAD

**Issue by zoell** [verdaccio/verdaccio#118]
When trying to install a package like this:

@sailshq/lodash
https://www.npmjs.com/package/@sailshq/lodash

Error:
```
npm ERR! 404 no such package available : @sailshq/lodash
npm ERR! 404
npm ERR! 404  '@sailshq/lodash' is not in the npm registry.
```

**Comment by dananichev** [comment]
@zoell you need to add something like this into your config file
```
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
```
