### ISSUE TITLE
Failure running server with the default configuration

### ISSUE THREAD

**Issue by raffaeler** [verdaccio/verdaccio#1180]
**Describe the bug**
The server cannot listen on the default port/address.
OS: Windows 10 build 1809
nodejs: v8.9.4
```
>verdaccio
 warn --- config file  - C:\Users\raffaeler\AppData\Roaming\verdaccio\config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:4873/ - verdaccio/3.10.1
 fatal--- cannot create server: listen EACCES 127.0.0.1:4873
```  
The installation is fresh and Verdaccio was never installed on this machine

**To Reproduce**
1. Install Verdaccio: `npm install --global verdaccio`
2. run it `verdaccio`
3. See error

**Expected behavior**
I expected to be able to run Verdaccio.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: h:/_npm/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  #- {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio1.log, level: info}
```

**Debugging output**
The verbose log is the following:
```
{"name":"verdaccio","hostname":"tadev","pid":28412,"level":40,"content":"htpasswd","msg":"Plugin successfully loaded: htpasswd","time":"2019-01-14T09:12:53.508Z","v":0}
{"name":"verdaccio","hostname":"tadev","pid":28412,"level":40,"content":"audit","msg":"Plugin successfully loaded: audit","time":"2019-01-14T09:12:53.513Z","v":0}
{"name":"verdaccio","hostname":"tadev","pid":28412,"level":40,"addr":"http://localhost:4873/","version":"verdaccio/3.10.1","msg":"http address - http://localhost:4873/ - verdaccio/3.10.1","time":"2019-01-14T09:12:53.535Z","v":0}
{"name":"verdaccio","hostname":"tadev","pid":28412,"level":60,"err":{"message":"listen EACCES 127.0.0.1:4873","name":"Error","stack":"Error: listen EACCES 127.0.0.1:4873\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1334:19)\n    at listenInCluster (net.js:1392:12)\n    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)","code":"EACCES"},"msg":"cannot create server: listen EACCES 127.0.0.1:4873","time":"2019-01-14T09:12:53.538Z","v":0}
```

**Additional context**
If I change the listen address to `0.0.0.0:4545` **it works**.
If I change the listen address to `0.0.0.0:4873` it doesn't work and no error is shown in the logs (it looks it dies before logging).

The `netstat -na` output tells me that no process is listening to port 4873 (double checked).
