### ISSUE TITLE
"ERROR: No README data found!" appearing for all packages

### ISSUE THREAD

**Issue by kaiyoma** [verdaccio/verdaccio#1213]
**Describe the bug**
For all our internal packages that we publish to our internal registry, the Verdaccio UI shows this message:

`ERROR: No README data found!`

This was not always the case; after a recent upgrade to Verdaccio 3.10.0, any package that's published to the registry starts to develop this problem. The package tarballs definitely have non-empty `README.md` files inside.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /data/sinopia/storage

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false

  title: <redacted>

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100

packages:
  <redacted>
    access: $all
    publish: $all

  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# Use `npm audit`
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}

listen:
  - 0.0.0.0:4873
```
