### ISSUE TITLE
4.x displays Anonymous even if publisher is authenticated

### ISSUE THREAD

**Issue by blackholegalaxy** [verdaccio/verdaccio#1224]
**Describe the bug**
Publishing displays `Anonymous` user.

**To Reproduce**
As an authenticated user, publishing a package under verdaccio v4-next displays Anonymous as uploader.

**Expected behavior**
As a logged user, the user who published the package should be displayed properly

**Screenshots**

![capture](https://user-images.githubusercontent.com/11064123/52523901-bd8d0c00-2c64-11e9-92f3-a577ad4d0445.PNG)

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:beta] verdaccio:4.x-next
 - Docker version: 17.03.2 (through kubernetes)

Command: just running the image with config mounted at proper place.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

web:
  enable: true
  title: OurCompany
  scope:

logs:
  - {type: stdout, format: pretty-timestamped, level: http}
```
