### ISSUE TITLE
Crash when fetching pkg after no internet

### ISSUE THREAD

**Issue by gmastergreatee** [verdaccio/verdaccio#1228]
After disconnecting from internet:-

version 3.11.4
![kjhkj](https://user-images.githubusercontent.com/17880848/52908495-f51b3a00-329c-11e9-8689-468e2fa6c923.gif)

I get a similar crash for v4.0.0-alpha.4

![image](https://user-images.githubusercontent.com/17880848/52908520-8db1ba00-329d-11e9-93af-069330a2fad9.png)

Also the master branch crashes too.

Then I downgraded to v3.10.1 & this one works properly. This one displays the error but it doesn't crash & then gets the file from local cache.(exception handled properly here)

## Config file
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: E:\_npm_cache
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 60

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks) : Says unrecognized command
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api) : Says unrecognized command
 - `$ npm -ddd` prints: Says the command is invalid. No matching command.(npm@6.4.1, node@10.15.1)
 - `$ npm config get registry` prints: http://localhost:4873/

**Additional context**
