### ISSUE TITLE
What is the duration of a login session? [Documentation Question]

### ISSUE THREAD

**Issue by mlamothe** [verdaccio/verdaccio#1231]
When a user successfully logs in using npm login or npm adduser, how long are they authenticated for? And is there a way to configure this duration?

**Comment by juanpicado** [comment]
In `v3` the tokens have no expiration date. For such reason we introduced in the next `v4` the JWT feature https://github.com/verdaccio/verdaccio/pull/896

```
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
```

Using this configuration will override the current system and you will be able to control how long the token will live. 

Using JWT also improves the performance with authentication plugins, the old system will perform an unpackage in each request and validating the credentials in each request, while JWT will rely on the token signature avoiding the overhead for the plugin.

As side note, in npmjs the token never expires.
