### ISSUE TITLE
[question] No Package Published Yet (database corruption)

### ISSUE THREAD

**Issue by slillo** [verdaccio/verdaccio#1237]
From today verdaccio (v3.8.3) stopped showing packages in local registry.

Opening on browser this message is shown: *No Package Published Yet*

The storage folder specified in configuration (~/.local/share/verdaccio/storage) contains all my packages.

But database file is empty ~/.local/share/verdaccio/storage/.sinopia-db.json.
Indeed running verdaccio from terminal I get this:
    
     warn --- config file  - /home/xxx/.config/verdaccio/config.yaml
     error--- Package database file corrupted (invalid JSON), please check the error printed below.
    File Path: /home/xxx/.local/share/verdaccio/storage/.sinopia-db.json SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at LocalDatabase._parseDatabase (/home/xxx/.npm-packages/lib/node_modules/verdaccio/node_modules/@verdaccio/local-storage/lib/local-database.js:298:19)
        at LocalDatabase._fetchLocalPackages (/home/xxx/.npm-packages/lib/node_modules/verdaccio/node_modules/@verdaccio/local-storage/lib/local-database.js:272:23)
        at new LocalDatabase (/home/xxx/.npm-packages/lib/node_modules/verdaccio/node_modules/@verdaccio/local-storage/lib/local-database.js:49:22)
        at LocalStorage._loadStorage (/home/xxx/.npm-packages/lib/node_modules/verdaccio/build/lib/local-storage.js:809:14)
        at new LocalStorage (/home/xxx/.npm-packages/lib/node_modules/verdaccio/build/lib/local-storage.js:54:27)
        at Storage.init (/home/xxx/.npm-packages/lib/node_modules/verdaccio/build/lib/storage.js:64:25)
        at /home/xxx/.npm-packages/lib/node_modules/verdaccio/build/api/index.js:145:19
        at Generator.next (<anonymous>)
        at step (/home/xxx/.npm-packages/lib/node_modules/verdaccio/build/api/index.js:53:191)
     error--- Database is locked, please check error message printed during startup to prevent data loss.
    (node:9242) ExperimentalWarning: The fs.promises API is experimental
     error--- Database is locked, please check error message printed during startup to prevent data loss.
     warn --- Plugin successfully loaded: htpasswd
     warn --- Plugin successfully loaded: audit
     warn --- http address - http://0.0.0.0:4873/ - verdaccio/3.8.3

The configuration is almost untouched

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /home/xxx/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}


listen:
  - http://0.0.0.0:4873

```

What's happened? How can I resolve?
