### ISSUE TITLE
Cannot install private packages

### ISSUE THREAD

**Issue by nfour** [verdaccio/verdaccio#1255]
**Describe the bug**
Cannot install private packages

**To Reproduce**
1. Install a private package without being logged in
2. It fails as it should
3. Login
4. It still fails

```
sam@sam-gl502vs : ~/W/test/foo
[1] % npm login         
Username: nfour
Password: 
Email: (this IS public) ...
Logged in as nfour on http://localhost:4873/.

sam@sam-gl502vs : ~/W/test/foo
[0] % yarn add @temando/errors
yarn add v1.13.0
warning ../package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "http://localhost:4873/@temando%2ferrors: no such package available".
info If you think this is a bug, please open a bug report with the information provided in "/home/sam/W/test/foo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

- When I set the registry in npm back to the default NPM registry, it all works as expected.
- I have also tried purging `~/.share/local/verdaccio`

My .npmrc looks like this:

```
//registry.npmjs.org/:_authToken=SNIP
sign-git-tag=true
logLevel=quiet
registry=http://localhost:4873/
//localhost:4873/:_authToken="SNIP"
ca=null
```

**Expected behavior**
Can install private packages

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

The config file is unmodified - nothing special in it.

**Debugging output**

```
[130] % NODE_DEBUG=request verdaccio
 warn --- config file  - /home/sam/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:4873/ - verdaccio/3.11.6
REQUEST { url: 'https://registry.npmjs.org/@temando%2Ferrors',
  method: 'GET',
  headers:
   { Accept: 'application/json;',
     'Accept-Encoding': 'gzip',
     'User-Agent': 'npm (verdaccio/3.11.6)',
     Via: '1.1 8dd630e1f5f1 (Verdaccio)' },
  encoding: null,
  gzip: true,
  timeout: 30000,
  strictSSL: true,
  callback: [Function] }
REQUEST make request https://registry.npmjs.org/@temando%2Ferrors
REQUEST onRequestResponse https://registry.npmjs.org/@temando%2Ferrors 404 { date: 'Fri, 15 Mar 2019 00:57:50 GMT',
  'content-type': 'application/json',
  'content-length': '21',
  connection: 'close',
  'set-cookie':
   [ '__cfduid=SNIP; expires=Sat, 14-Mar-20 00:57:49 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
  'cf-ray': 'SNIP',
  'expect-ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  vary: 'Accept-Encoding',
  server: 'cloudflare' }
 http --> 404, req: 'GET https://registry.npmjs.org/@temando%2Ferrors' (streaming)
REQUEST reading response's body
REQUEST finish init function https://registry.npmjs.org/@temando%2Ferrors
REQUEST response end https://registry.npmjs.org/@temando%2Ferrors 404 { date: 'Fri, 15 Mar 2019 00:57:50 GMT',
  'content-type': 'application/json',
  'content-length': '21',
  connection: 'close',
  'set-cookie':
   [ '__cfduid=SNIP; expires=Sat, 14-Mar-20 00:57:49 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
  'cf-ray': 'SNIP',
  'expect-ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  vary: 'Accept-Encoding',
  server: 'cloudflare' }
REQUEST end event https://registry.npmjs.org/@temando%2Ferrors
REQUEST has body https://registry.npmjs.org/@temando%2Ferrors 21
REQUEST emitting complete https://registry.npmjs.org/@temando%2Ferrors
 http --> 404, req: 'GET https://registry.npmjs.org/@temando%2Ferrors', bytes: 0/21
 http <-- 404, user: nfour(127.0.0.1), req: 'GET /@temando%2ferrors', error: no such package available
```
```
[1] % npm config get registry      
http://localhost:4873/
```

I've tried the docker image and currently just using the `npm i -g verdaccio` global npm install. No dice.

Running arch linux.

```
[1] % node -v 
v10.15.1
```

**Comment by nfour** [comment]
@adamelliottsweeting can conform reproduction.

**Comment by juanpicado** [comment]
Config file? I don't see the step 1 reflected in the log snapshot you have shared. 

```
REQUEST emitting complete https://registry.npmjs.org/@temando%2Ferrors
 http --> 404, req: 'GET https://registry.npmjs.org/@temando%2Ferrors', bytes: 0/21
 http <-- 404, user: nfour(127.0.0.1), req: 'GET /@temando%2ferrors', error: no such package available
```

**Comment by nfour** [comment]
Seems to work with this config file:

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /home/sam/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    headers:
      Authorization: "Bearer <SNIP>"

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 60

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}



```
