### ISSUE TITLE
cannot download tar/zipped scoped package (@org/packagename)

### ISSUE THREAD

**Issue by carlosen14** [verdaccio/verdaccio#1257]
**Describe the bug**
Cannot download taz/ziped package when it is soped `@org/package`. 

**To Reproduce**
1. upload a non-scoped package, ex:  `@org/packagename`
2. upload a scoped-package, ex: `package`
3. enter repository via web (login if necessary) and try to download both packages

- here i am able to download repo non-scoped
Url download `http://192.6.X.X:4873/test-verdaccio/-/test-verdaccio-1.0.2.tgz`

- and cannot download  scoped one. appears a message 
Url download `http://192.6.X.X:4873/@org/packagename/-/@org/packagename-0.1.0.tgz`
message
```js
{
"error": "File not found"
}
```
**Expected behavior**
I would expect to download both packages individually, doesn't matter if scoped or not.

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio/verdaccio:4.0.0-alpha.5@sha256:68db01985521d2684167f3164355570fc946630e5ac8beb6ebfd2007e42fb14b
 - Docker commands : docker run -itd --name verdaccio --restart always -v /apps/verdaccio4/storage/data:/verdaccio/storage/data -p 4873:4873 verdaccio/verdaccio:4.0.0-alpha.5
 - Docker Version : Docker version 18.09.0, build 4d60db4

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
~/.config/verdaccio/config.yaml  **NOT FOUND**

here it is docker.yaml
```yaml
 #
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use iton production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (dependingon your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` verdaccio command not found
 - `$ DEBUG=express:* verdaccio` verdaccio command not found
 - `$ npm -ddd` prints: 
```bash
npm info it worked if it ends with ok
npm verb cli [ '/home/carlos/.nvm/versions/node/v10.15.2/bin/node',
npm verb cli   '/home/carlos/.nvm/versions/node/v10.15.2/bin/npm',
npm verb cli   '-ddd' ]
npm info using npm@6.4.1
npm info using node@v10.15.2

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/carlos/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.4.1 /home/carlos/.nvm/versions/node/v10.15.2/lib/node_modules/npm
```
 - `$ npm config get registry` prints: http://192.6.X.X:4873/ local ip

**Additional context**
I can perfectly install both of them via NPM, just cannot download Tar file

Also, i get into the docker container using shell, went to the storage folder, and found my scoped-package, this is the path 
```
/verdaccio/storage/data/@org/packagename/packagename-0.1.0.tgz
```
