### ISSUE TITLE
Packages are not cached and won't install when npmjs registry is unreachable

### ISSUE THREAD

**Issue by blackholegalaxy** [verdaccio/verdaccio#1259]
**Describe the bug**
During outage of npmjs earlier this week, we were unable to install packages from our verdaccio installation. Verdaccio (docker, 4.x version) relayed the 500 and 503 errors from npmjs.

Our product has version locked dependencies since more than 3 weeks and our CI always uses the same versions of packages.

Since the error was relayed, we guess verdaccio wasn't caching the packages at all. We checked, our machine has sufficient hard drive available (2TB free) and the directory are mapped correctly. We are able to access our own private packages hosted on our verdaccio installation.

**To Reproduce**
1. Create a verdaccio with configuration as stated in doc pages (cache should be built as far as I understand)
2. Using your project with locked dependencies versions, Install packages once, specifiying verdaccio registry
3. On verdaccio installation's server, cut connection to npmjs registry
4. Try to reinstall
5. It breaks as verdaccio cannot reach npmjs and doesn't serve requested packages through cache

**Expected behavior**
I expect caching to work properly, making verdaccio a safe way for our company to be able to work even if npmjs is down.

**Docker on Kubernetes:**
 - Docker verdaccio tag: **4.x-next** 
 - Docker commands: **pull and run with mapped volume**
 - Docker Version: **17.06.2**

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: /verdaccio/storage/data

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

web:
  enable: true
```
