### ISSUE TITLE
npmjs uplink not working

### ISSUE THREAD

**Issue by flyfishMT** [verdaccio/verdaccio#1262]
**Describe the bug**
This is probably from config or my misunderstanding. I have verdaccio hosted on a Ubuntu 16.04 instance of Windows Subsystem for Linux, nginx port forwards to it.

I only see packages from my local repository, nothing from the npmjs repository, even though the (default) config lists npmjs as an uplink.

**To Reproduce**
Visit my local verdaccio site.

**Expected behavior**

See packages from local repo and npmjs repo.

**Screenshots**
Here's a screenshot searching for "express".  It's interesting it says no packages published, I do have 1 package published that shows when on the home screen, not searching anything.
![verdaccio](https://user-images.githubusercontent.com/5473678/54768597-1c7b6480-4bc5-11e9-9fdb-37387f41701c.png)

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
# a list of other known repositories we can talk to 
uplinks:
   npmjs:
     url: https://registry.npmjs.org/
```
