### ISSUE TITLE
403: error: invalid filename when pulling @scoped packages from Gemfury uplink

### ISSUE THREAD

**Issue by WesTyler** [verdaccio/verdaccio#1263]
**Describe the bug**
When installing any `@namespace/` scoped package from a Gemfury uplink, verdaccio fails out with `403: error: invalid filename`. This appears to be due to a difference in filenames that gemfury returns for namespaced packages compared to the npm registry.

**To Reproduce**

in config.yaml
```
uplinks:
  gemfury:
    url: https://npm-proxy.fury.io/KEY/USER/
```

in .npmrc:
```
registry=http://path.to.verdaccio.proxy.com/
```

Install gemfury package with no scope through verdaccio proxy - no problems:
```
> npm install private-package1
```

Install gemfury package with scope - works only with registry set to gemfury directly. When installed through verdaccio proxy, fails with 403:
```
> npm install @private/scoped-package
npm ERR! 403 Forbidden: @private/scoped-package@^1.0.0
```

log in verdaccio server:
```
 http <-- 403, user: null(IP.REDACTED), req: 'GET /@private%2fscoped-package/-/%40private%2Fscoped-package-1.0.0', error: invalid filename
```

**Expected behavior**
Gemfury's filenames are different than the npm registry, but the npm client is able to translate them correctly when used directly. We would expect the verdaccio caching not to break this compatibility.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio/verdaccio:3.8.1
 - Docker Version: 18.09.0

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
# allow large packages to be published
max_body_size: 1000mb

# path to a directory with all packages
storage: /verdaccio/storage

# a list of other known repositories we can talk to
uplinks:
  gemfury:
    url: https://npm-proxy.fury.io/REDACTED/REDACTED/

packages:
  '**':
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: gemfury

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', '-ddd' ]
npm info using npm@6.4.1
npm info using node@v10.15.0
```
 - `$ npm config get registry` prints:
```
https://npm-proxy.fury.io/REDACTED/REDACTED/
```
**Additional context**
