### ISSUE TITLE
Fetching packages after log in does not work correctly

### ISSUE THREAD

**Issue by metaa** [verdaccio/verdaccio#1296]
**Describe the bug**
After logging in, the request to get the package list (`/-/verdaccio/packages`) is missing the `authorization` header, thus it's not sending authentification information and fails to display packages that need authentification.

**To Reproduce**
1. Set up your Verdaccio with a configuration with something like this:
```yaml
packages:
  '@private/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
  '**':
    access: $authenticated
    proxy: npmjs
```
1. Switch to the frontend
1. Open the devtools of your browser
1. Log in to Verdaccio
1. Spot the call to `packages` in the network trace and see how it lacks authentication information, thus not displaying any package info

**Expected behavior**
After logging in, the packages available should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5056880/56962229-52155500-6b56-11e9-82e9-9a6ffe63b4ac.png)

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: `4.0.0-beta.4`
 - Docker Version `version 18.09.0`, `build 4d60db4`
