### ISSUE TITLE
Error on npm install: Cannot read property 'totalDependencies' of undefined

### ISSUE THREAD

**Issue by mattrussell-sonocent** [verdaccio/verdaccio#1304]
**Describe the bug**
We recently switched to Verdaccio from Nexus, and have started to get intermittent errors during `npm install`:

    npm ERR! Cannot read property 'totalDependencies' of undefined

We're running Verdaccio: 3.10.0 in GKE
npm version 6.1.0

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
----
storage: /verdaccio/storage/data
web:
  title: Verdaccio
auth:
  htpasswd:
    file: /verdaccio/secrets/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
middlewares:
  audit:
    enabled: true
logs:
  - {type: stdout, format: pretty, level: http}
```
