### ISSUE TITLE
Syntax highlighting in README.md

### ISSUE THREAD

**Issue by Codelica** [verdaccio/verdaccio#1317]
**Describe the solution you'd like**
Would like to see code block syntax highlighting ala GitHub and GitLab:

```js
console.log(`This is JavaScript!`);
```

```yaml
# This is YAML!
web:
  scope: \@something
```

Thanks for considering :)
