### ISSUE TITLE
Incorrect anchor URL when using url_prefix

### ISSUE THREAD

**Issue by monry** [verdaccio/verdaccio#1344]
**Describe the bug**
If I specify the complete URL, the link URL will be wrong.

**To Reproduce**
1. Set URL to `url_prefix`
     * `url_prefix: http://localhost:8888`
2. All anchors will have `/` as prefix

**Expected behavior**
All anchors will starts with `url_prefix`

**Screenshots**

![image](https://user-images.githubusercontent.com/838945/59245894-7dab5500-8c55-11e9-9be9-e47dc05a10af.png)

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio:4.0.0
 - Docker commands: 
 - Docker Version: `Docker version 18.09.2, build 6247962`

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
middlewares:
  ## https://github.com/n4bb12/verdaccio-github-oauth-ui
  github-oauth-ui:
    client-id: $GITHUB_OAUTH_UI_CLIENT_ID
    client-secret: $GITHUB_OAUTH_UI_CLIENT_SECRET

# path to a directory with all packages
storage: /verdaccio/storage

# path to a directory with plugins to include
plugins: /verdaccio/plugins

max_body_size: $MAX_BODY_SIZE

auth:
  ## https://github.com/n4bb12/verdaccio-github-oauth-ui
  github-oauth-ui:
    org: $GITHUB_OAUTH_UI_ORG

packages:
  '@*/*': {}
  '**':
    access: $authenticated
    publish: $authenticated

url_prefix: $PROXY_URL

logs:
  - type: stdout
    format: pretty
    level: http

web:
  enable: true
  title: $WEB_TITLE
  gravatar: true
  scope: 
  sort_packages: asc
  
store:
  ## https://github.com/verdaccio/verdaccio-google-cloud
  google-cloud:
    projectId: $GOOGLE_CLOUD_VERDACCIO_PROJECT_ID
    kind: $GOOGLE_CLOUD_VERDACCIO_KIND
    bucket: $GOOGLE_CLOUD_VERDACCIO_BUCKET
    keyFilename: $GOOGLE_CLOUD_VERDACCIO_KEY
```

All variables are provided by docker-compose using `.env`

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/12.1.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '-ddd'
npm verb cli ]
npm info using npm@6.9.0
npm info using node@v12.1.0

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/monry/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.9.0 /usr/local/lib/node_modules/npm
```
 - `$ npm config get registry` prints:
```
https://registry.npmjs.org/
```

**Additional context**
I'm using nginx on Docker with below settings as proxy server to add Authorization header.

```
server {
    listen 8888;
    server_name localhost;
    location / {
        proxy_pass "https://real-verdaccio-registry/";
        proxy_set_header Authorization "Bearer ${AUTH_TOKEN}";
    }
}
```
