### ISSUE TITLE
Cannot download tarball after logging in

### ISSUE THREAD

**Issue by pszalanski** [verdaccio/verdaccio#1351]
**Describe the bug**
Access to packages is restricted to authenticated users, which works fine during browsing. However, on clicking "Download tarball" I get an error:
```json
{
  "error": "authorization required to access package my-package"
}
```

**To Reproduce**
1. Login
2. Navigate to a package with access `$authenticated`
3. Click on "Download tarball"

**Expected behavior**
The tarball should be downloaded.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```yaml
packages:
  '**':
    access: $authenticated
    publish: special
    unpublish: special
    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
```

**Additional context**
I checked the network requests and the download does not contain an `Authorization` header.
