### ISSUE TITLE
Authorization for npm i not working in docker

### ISSUE THREAD

**Issue by Legiew** [verdaccio/verdaccio#1356]
**Describe the bug**
Npm is not able to download a self published private package from a docker instance of verdaccio. The same workflow works without problems on a local instance of verdaccio.

**To Reproduce**
1. Start verdaccio docker image (with given conf and htpasswd files mounted)
2. Login to verdaccio using npm with a existing user from the htpasswd file
3. Publish package (scoped)
4. Try to install the package in another project
5. `http <-- 401, user: null(172.17.0.1), req: 'GET /@org%2fpackage', error: authorization required to access package @org/package`

As you can see the user (here: null) is not set or transferred.

**Expected behavior**
The package should be installed.

If I try the same with a local checkout version of the git repo and running `yarn dev:start` I see: 
`http <-- 200, user: username(127.0.0.1), req: 'GET /@org%2fpackage', bytes: 0/923`
`http <-- 200, user: username(127.0.0.1), req: 'GET /@org%2fpackage/-/packagen-0.1.0.tgz', bytes: 0/5146`

Here the user is passed through to verdaccio.

**Docker:**
 - Docker verdaccio tag: latest (4.0.3)
 - Docker command: `docker run -it --rm --name verdaccio -p 4873:4873 -v /Users/user/.config/verdaccio:/verdaccio/conf -v /Users/user/.local/share/verdaccio/storage:/verdaccio/storage verdaccio/verdaccio`
 - Docker Version: 2.0.0.3 (31259) Mac

**Configuration File** 
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /Users/user/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@org/*':
    # scoped packages
    access: $authenticated
    publish: username
    unpublish: username

  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs


# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
```
