### ISSUE TITLE
[Q] Is there any way to create backup of published packages?

### ISSUE THREAD

**Issue by dehghani-mehdi** [verdaccio/verdaccio#1383]
Hi,

I have 2 questions actually: 
1. I didn't see anything about it in the doc, can I create backup of published packages, users, ... (_and move to another machine and use it_)?
2. How you added redux as package to verdaccio?

**Comment by juanpicado** [comment]
hi @dehghani-mehdi 

> 1. I didn't see anything about it in the doc, can I create backup of published packages, users, ... (and move to another machine and use it)?

That might depends how your storage looks like, if you use the default one you can find a folder https://verdaccio.org/docs/en/cli#default-storage-location (it might be different location based in our OS). 

I'd recommend the following approach if you want to **distribute efficiently your private and public packages**.

```
packages:
  '@juan/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
    storage: private-juan-packages
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
    storage: public-packages
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
    storage: public-packages
```
In the example above, I want that all my private packages under `@juan` scope are located in a specific folder and the others in a public folder, just like the example below. 

Here I am publishing a package named `"name": "@juan/test",`.

![Screen Shot 2019-07-10 at 8 41 37 AM](https://user-images.githubusercontent.com/558752/60946451-9196b500-a2ee-11e9-9ede-ee574f93e58d.png)

In this way, you can remove public if you will, and private are much easier to back up them (do not forget the `.verdaccio-db.json` also must be part of the backup. 

> 2. How you add redux as package to verdaccio?

If you wan to override a package that exist already in any of the uplink, by default is npmjs. Redux is published there https://www.npmjs.com/package/redux as you can see, at time of this writing the latest version  is `4.0.3`. If you checkout Redux in your local computer and try to publish `4.0.3` will fails due already exist in the uplink, **you must define a new version** that does not exist previously anywhere to be able to publish, eg: if you need to patch Redux, you might publish `4.0.3-fix-patch` as version, thus in your project you will have in the **package.json** `"redux": "4.0.3-fix-patch",`. That's the way how to override public packages.
