### ISSUE TITLE
Web Download broken in 4.1

### ISSUE THREAD

**Issue by NathanaelA** [verdaccio/verdaccio#1396]
**Describe the bug**
Clicking the web download link in 4.1 reports:
` "error": "authorization required to access package @proplugins/nativescript-month-calendar"` 
on the web; and 
`http <-- 401, user: null(187.143.137.192), req: 'GET /@proplugins%2fnativescript-month-calendar/-/nativescript-month-calendar-0.0.17.tgz', error: authorization required to access package @proplugins/nativescript-month-calendar
`
in the logs.      I did notice the "user" says null on this line however, a couple lines up in the log it shows:
` http <-- 304, user: nathanaela(187.143.137.192), req: 'GET /-/verdaccio/package/readme/@proplugins/nativescript-month-calendar', bytes: 0/0
`

However, looking at the actual request headers for the request of the .tgz, there is no cookie or header set that would set Auth; so this appears to be a valid that the server has no idea who I am when I request a TGZ.

**To Reproduce**
- Fresh 4.1 install
- Login via npm
- publish a test package
- Login in Web
- Attempt to download via web

**Expected behavior**
Download to work..

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
security:
  api:
    jwt:
      sign:
        expiresIn: 30d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

packages:
  '@proplugins/*':
    access: $authenticated
    publish: acounta, acountb, accountc
    unpublish: accounta
```

**Environment information**

  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Version: 4.1.0

**Additional Information**
Please note both my modified in-use version, and a `npm i` version freshly installed in another directory did this.  Any bugs will be reported against stock version, rather than my customized version, so that I don't report issues that are self inflicted.  :)
