### ISSUE TITLE
Bug/Question Notify doesn't work

### ISSUE THREAD

**Issue by Devqon** [verdaccio/verdaccio#144]
I am trying to use the notify in combination with [hipchat](https://www.hipchat.com/), but cannot get it to work. I have configured the `notify` section in the `config.yaml` as follows:

```
# Notify Settings
notify:
  method: POST
  headers: [{'Content-type': 'application/json'}]
  endpoint: https://[my-company].hipchat.com/v2/room/[roomId]/notification?auth_token=[someAuthToken]
  content: '{"color":"green","message":"New package published: * {{ name }}*","notify":true,"message_format":"text"}'
```

If I'm putting this in Postman it works:

![image](https://cloud.githubusercontent.com/assets/9316480/24502020/4417a528-154c-11e7-8f38-0e03441e1b0a.png)

![image](https://cloud.githubusercontent.com/assets/9316480/24502035/5e7f88ae-154c-11e7-9f10-426f9f786bfd.png)

But when publishing a package I don't get any notification. There is also nothing in the logs about any notifying at all.
	
#### Additional information:
I am using Verdaccio v. 2.1.2

#### Note:
Verdaccio **does** try something, because when I remove the quotes around the content it throws an error in the log that the content should be a string.

What am I doing wrong here?
