### ISSUE TITLE
Multiple Authentication Plugins

### ISSUE THREAD

**Issue by MaycoLucian** [verdaccio/verdaccio#1442]
I'm using Multiple Authentication plugins: htpasswd and bitbucket.
the problem is that it's always only doing the first authentication, in my case is htpasswd, never goes to bitbucket authentication.
Version: verdaccio 3.8.6
I'm doing equals: https://verdaccio.org/docs/en/plugins#multiple-authentication-plugins

Has anyone run into the same problem?
```
auth:
	htpasswd:
             file: /verdaccio/storage/htpasswd
        bitbucket:
             allow: myTeam
```
