### ISSUE TITLE
Error 401 unable to authenticate, your authentication token seems to be invalid

### ISSUE THREAD

**Issue by SystemParadox** [verdaccio/verdaccio#1454]
**Describe the bug**

Authentication seems to be broken. I'm not sure what's happened here, I didn't update verdaccio, but it's broken for all versions of npm, so is this an npm issue or a verdaccio issue?

Updating verdaccio to 4.2.2 hasn't fixed it.

**To Reproduce**

```
$ npm i
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

$ npm show @wd/build
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login
```

**Expected behavior**

I expect all of the above to work without authentication errors!

**Docker || Kubernetes (please complete the following information):**

 - Docker verdaccio tag: verdaccio:4.2.2
 - Docker Version v18.09.5

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: /verdaccio/storage
plugins: /verdaccio/plugins
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # prevent registration of new users
    #max_users: -1
web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  # access/publish default to none
  '@wd/*':
    access: $authenticated
    publish: simon
    storage: /verdaccio/local_storage
  '@*/*':
    access: $authenticated
    # no publish
    proxy: npmjs
  '**':
    access: $authenticated
    # no publish
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true
logs:
  - {type: stdout, format: pretty, level: debug}
```

**Environment information**

Verdaccio 4.2.2 (docker)

```
Environment Info:

  System:
    OS: Linux 4.9 Alpine Linux undefined
    CPU: (8) x64 Intel(R) Xeon(R) CPU D-1520 @ 2.20GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
```

**Debugging output**

 - `$ npm -ddd` prints:

```
$ npm adduser -ddd --registry=http://npm.systemparadox.co.uk --scope=@wd --always-auth
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/home/simon/npm/bin/npm',
npm verb cli   'adduser',
npm verb cli   '-ddd',
npm verb cli   '--registry=http://npm.systemparadox.co.uk',
npm verb cli   '--scope=@wd',
npm verb cli   '--always-auth' ]
npm info using npm@6.3.0
npm info using node@v10.15.2
npm verb npm-session 29208124d9c53929
npm verb web login before first POST
npm http request → POST http://npm.systemparadox.co.uk/-/v1/login
npm http 404 ← Not Found (http://npm.systemparadox.co.uk/-/v1/login)
npm verb web login not supported, trying couch 
Username: simon
Password: 
Email: (this IS public) simon@systemparadox.co.uk
npm verb login before first PUT { _id: 'org.couchdb.user:simon',
npm verb login   name: 'simon',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2019-08-28T15:55:20.128Z' }
npm http request → PUT http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon
npm http 409 ← Conflict (http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon)
npm http request → GET http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon?write=true
npm http 200 ← OK (http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon?write=true)
npm http request → PUT http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon/-rev/undefined
npm http 201 ← Created (http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon/-rev/undefined)
npm info login Authorized user simon
Logged in as simon to scope @wd on http://npm.systemparadox.co.uk/.
npm verb exit [ 0, true ]
npm timing npm Completed in 15742ms
npm info ok 
$ npm login -ddd --registry=http://npm.systemparadox.co.uk
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/home/simon/npm/bin/npm',
npm verb cli   'login',
npm verb cli   '-ddd',
npm verb cli   '--registry=http://npm.systemparadox.co.uk' ]
npm info using npm@6.3.0
npm info using node@v10.15.2
npm verb npm-session ddf35b7c2e480eb7
npm verb web login before first POST
npm http request → POST http://npm.systemparadox.co.uk/-/v1/login
npm http 404 ← Not Found (http://npm.systemparadox.co.uk/-/v1/login)
npm verb web login not supported, trying couch 
Username: simon
Password: 
Email: (this IS public) simon@systemparadox.co.uk
npm verb login before first PUT { _id: 'org.couchdb.user:simon',
npm verb login   name: 'simon',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2019-08-28T15:55:44.911Z' }
npm http request → PUT http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon
npm http 409 ← Conflict (http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon)
npm http request → GET http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon?write=true
npm http 200 ← OK (http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon?write=true)
npm http request → PUT http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon/-rev/undefined
npm http 201 ← Created (http://npm.systemparadox.co.uk/-/user/org.couchdb.user:simon/-rev/undefined)
npm info login Authorized user simon
Logged in as simon on http://npm.systemparadox.co.uk/.
npm verb exit [ 0, true ]
npm timing npm Completed in 10265ms
npm info ok 
$ npm show @wd/build
npm ERR! code E401
npm ERR! authorization required to access package @wd/build : @wd/build
```

 - `$ npm config get registry` prints: `https://registry.npmjs.org/`, but I'm using a custom for specific prefixes. `~/.npmrc`:

```
prefix=/home/simon/npm
@wd:registry=http://npm.systemparadox.co.uk/
//npm.systemparadox.co.uk/:_authToken="[REDACTED]"
always-auth=true
```

**Client environment**

- node version 10.15.2
- npm version 6.30, 6.8.0, 6.9.0, 6.11.2 (same issue for all of them)
