### ISSUE TITLE
[Bug] web.logo does not support base64

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#1478]
`web.logo` does not support Base64 images anymore.

I have seen that when updating from v3 to v4.

My base64 was containing `\` , the last part after the backslash was used as the image static url.

**Comment by juanpicado** [comment]
This is not a bug. The documentation refers to using a file. We do not support base64 yet. 

https://verdaccio.org/docs/en/webui

**Comment by kopax** [comment]
> We do not support base64 yet.

Anymore... @juanpicado it was working in v3, try this in v3:

```yaml
#   - {type: file, path: /verdaccio.log, level: info}
web:
  enable: true
  title: npm kopaxgroup
  logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARkAAAArCAYAAAE70syTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAGpVJREFUeNpi/P//PwMIPFl1KOLO9G3T/zMwMvwD8kE0SOb/fwgfBODi/yE0Mv8fkP546Z4AiP4H5f8D62FC8IFm/YXq+QsV+wvEKm46YVHr8laD7GCEOug/AxXAJuFwsOV/wBZCLPsLdBCIDRPDRv/5zwRW2/BlJiPT2aT+AwxUBKz83GA6/P1yuFjCh8VwdvbHBQx5n+aD2ao+hhj6WV7vu2CHy/DNmzcz3Lp1i8HX15fh5s2bDFu2bGHIzMxkUFNTY3j79i2DrKwsw6pVqxjevHnDkJWVBdYjYqPFoJThxXAqewbcnAUCsaDIALOn8ieAQwbE95yZzHBdOhfFTppEGbucGMOnh2/IizKYwz5efkC1aPv66DVJ6kGhAXIMiA0QQLAQYjjgWPEekpOguQtKg3LGf6imf9BcB5OH5D5Irvp46b7APwZEbkJm/4XmxL+wnAeWh2Jmpv91H2eAA4bxRHjbI/MVlbKUhsgW4TBI9MByFpT+g0ZDoogJQxxICzJR4hBQYkcGcpEODEHvVsD53HKiDPEfloDZUjaaDJkfF4LZBZ/mMZR8ngtmy9uqw5S/Z8Fm+Pfv3xnCwsIguWLBAoaEhAS4mqqqKgZLS0uG48ePg2lk8Gj5AYZ3lx8yBDyYy7BWPgWcfhYKxICjUi3almE6fzyYPYEvCRwisNwGz1Wnorv+my4pZRjoaPoNzFlMQIcwgrLmQAJuCcGXzV9nMAIEEDw3nUnovWayoFiTYRAAUCjDczVS/fcfmnOR68t/aGLY+AgzELn5PwMDCh9mH7CW0ItckXkZ5A5Y2fd/sAQMNsAFzJj2m+voYtfNLRcu1XJngFMMEzCWUGqpvXv3Mnz79g1cNeICx44dg7N7e3vBNKiKhYHHjx/D2enp6fCCAlzSFBRgFCjIetGBXJQDg8nUTAZRay0Ucd2KYAZBXXkwW8IGNV6lbDDjWcZWA6v50dtLGVKOowY8KA3VcGcYUFyNgwJRWFiY4hgDRQgXFxfWbBXwbiXDGqEIumQrmP6mr0hNirdHr5LlKWoEDDjrQAMGG1gHDBh6AVjAgNgAAQQvkGHgXOaUE59uPFFnQGriwJLWf2iig/P/wxIhA4o6ZPX//zOitKvQzWSAd0og7D9fv7N8vfuc5z9SU4sBahe8yYVszn/0Tg+qPf9ROjrIcgh5bnH+98V3u4WwtYwZ9hhk/3e5MHXAC15Q6j3m14gj+yB6e/+Q2qXI8pDsgjt7wXp6/1GyE0QM1J6ApRhwdnqx7fSgCJSBBszAIEGpoSS8TAe1g+3oVHVDUsp/hvneE8qZfN6uwqhmYdUxtg4BTA0x4MKFC1jNQ+fjAqBaCQTeHLnGoFUewmDYFgfmW0zLANPiwCo6DtgRSYB2RpKRuvsZwE5J1kdIcyEX2O3Ph3b93aclMpRCOylyiE4KCrh74EYHE7IAqJsPa6+AqtFp06aB2xugNgooQJDbHs3NzXA2qJ0Cqr5BHgbpA/FB6tFrG9DQATrAFRkgsMsgB0xrAgPlw5UHDKoZnmD+iawZDJbAwHl55DqYv8OnFUPvDGAH6XTHBjD75Zl7DGu9O8HsP99/M3TzJoPZLp0RDDE7MPtIoEKGBV3QysoK3FMD9dpA1THIwZycnAzOzs5wx4PkQIEIYxcXF4PVgjCIP2HCBHgjDtbIA+kF9f5gfJje+Ph4cCBjq7LdLkxh+Pb4DcPro9cYPgJ7iVsN8uBySpG2DMeyIGMxL8ABxIgz5f358ZvhyeEbYDWieoie9J7yFQwPDt3COirBeD5ryn+DqdkDWoaAAhAW0NhqJQ1givkKDKB7yw7StFaC2Qnq6TKxiwvYDnThCgsUXEAl04vhATBQ6AVagD1uJs266CPb5eL+DuZaaZNCEt3sEtWU9GKAlTGejxax3GhdIf9i17kHDge7RmQbBjR41Aht3IEAQABhdAmgQGC3XtbbP5+/MxlOzWIY7O0cerTGj4PLPUh5hdolQu9+oHaT0LtNGGYgdYkw9KLJY5XD6Q5UN6B2xdDMQRnVhowwCskLv8+/1iaELTxQEs1+84JvKgUBnLKRDgyjYGQmGnR1oElDTV+D3MgVmVMQHQQgeLr2qN4xv4b/jicnjCYYCkDwuxUMClH2w8pPTMD0fWPzhcmwLjY80bzed+Gi1aaG0VinAICm2653rgG3SPWBvV5RG61h5T/o4DhkbGavXuZfXP0mUCcQ1jsG9Z5hHUrQkASID5slAM04gPgwtaAeOgjA5JFnEJB76DCzQPqQ9YCGLmDmgzqdMHNB9sD6Wcjmg8wEmQ1zH8gs5J47ujyyvTD3IM94wNxCzBAJaHbD/eIUhsN+TQxS3qbgKaBn284wOGyqZRDQlWeQ9jZB0RP6cA6Yjn6/FC4WBx1CQQfIQyrYZkRMKwNQE+62CqzmhO9AiKdfRTTmkYdg5HEMx2ADLN+fvmXCpwA0twyKLNDIAijQQREKWr0BwiBx0MgDaHQBNEoBG9+6ePEimAbNTSMPzSDPTSN3tEGjGLDEBWIbGBiA7QOZ19bWBpYDDRuBxEHDQKAhIJj5ID0zZ86EJ3JQIqitrUUZ/kGWR/cbLEPAVpuguxsfAA0fidhoM+zUz2EwmprJwK8jD5VZy7BaKJIh9N1yhpWCkSgjJKvlU4AJZhnDUsFogua/OHqDKqXEm6tP4OzbW85TUNowQKbiToS0nDBfXW0+UMUeKCJhiWYwAFCJA8KgITx8DWFOOVEG1/NTGM7lTAcvuLDdVAeunq4CsX5bPMNTYGkDGoOU9jIBJpwolIYnqLRZJZ8KNy/84SwGNj7E0N18gViwHCs/F0P45X6w3IGs2Qy3lh5BMUfBx5jh3pZz8IZwzqcFKH7p50sCq1P2NmLwX57D8OnRW4YVnl0MH4A0SFxMT5bhxaXH4IYwnI2twfwf0bNqgS2LAE0fII+UjwLSe0+gRGS3uR7M36afO2x6T8hLUyT15fKyjlVNhne595nmfzaZV8jDp6swmkpGu9wo6kDjNqCFVyi9JxBwOj2RF5hgGA/YFL8Edr9HU8oIB5DEwsBgV+algJxg8I0Iw8HJyM6Ob49fJzCysrCD1rkiK0fOMciWobIZccv/Z2BgQDODWP3/kTuD/wnI4zQb4QcGlByLWy+qGYw4/IQ/bPD66z8hP+OXw+aP/0TEFzMbyz9uYZ7XHAJciZmnG7bjSxMAAdi58tgqijj8ey9ggQJ9tQUTUqByVbkaDiNai/9YbaWUhIQGUuTSEAqBWEmASAGpR0AQoYgPkFZEaiUEQ+Rq4B85ikeQKGcAOQriQam1BQq02HW+6fttZ/fte/vgmVTa/V42e8zs7LyZb38zO/P9xpY051Zu//LOH5XDKr4/E0UWFWpX4VYMVv9YMFJR0Mr2LyQKQjjrZwQjTGMhVx+74AlUedaEMZaNUW3l8s+jRqa4pnxrxvs1mxdIC1ROpmZHDW8dGXEvpmenb6ceXjD8vglzctHm7ec/2jGq69jnKWHuGCk/bcmAqNKysDUruZ7pXLMO18hfimd5vyHcLPtz+fVXLPtMWoB+kOn59bI5csvjxHFPp43eMKXEjjCeHTGZlc98/RbFJvUlBy2LMJqp0wurk3stv7VhOoEPMOUPsowUn9sOWRy4XRrdq7nbamH7aZolYc6t+OrSSGdsJiyw82RzgmiCKC925j8GwpTET6x3yBIe0M/LuFjQLP9b3e0694aU5ZMlYU7nFT3XIzvd5VR5eEj9abXcQ8Pd7KyM6NWUHf6lUBKmrHDvgT7iS8jBgwNSB8xkA/A0xnlkM/yyzI2c5nHfu3Hb0rpgdll1KghFDmDlKBDMKTIcqA6YgNll3AxzuF18O4yq2EKD10y3bJrKD52i2qpblPlXMfXJTtPDMo7l68fjTdKHiT4vkqzLDTPug+aNNqQ7tWqT3CdkJUt392yfd8mEEw1lPqJ4llxcAl4mr4utZ/pg/d7ZNwqkW7wqe8i5utqQ/vybn9j+56i46HPuPnPG2BYyZAaxsbH6ddaeWJ2rHrqqFwquo5JVL10A5yyn4HtYv6Jqa1TCqs4fyCPOWaoAgkLqYNbxWEkZcB//R7O+xw6lGYvl0gHpl6SlljPYQFnxfko5sIT6+Zqms97GgdNrgkiPRLWjriOG0v7xH+rX96a/K5cc2Ci2om7B3aHOFB30LUkg8hw1iTb1b5j9jxDp5necTKvEtlJs53celdffqC6kDzq8SsvFtq7fHBo6I6Uhfse29/2SVP1aGdsqJohyDFIEFCoIwzoSVXeCwmYNDVsY1RsZhQ9tC4chHhODAc8gPIctEdJD+tizrgYVDr0M4sTFxcn4TFCkD80OEwsExP0gHlZdwYbnmi0k8oE0mSBMqFA1MtdLT9HLFz+lnfFTSJ28RR9mV+JM2SxB9qAC7lfjKr+Qx5sVncyjA7rr4yC/H3pwbQzcz5FGVdl1qrps7Vp/ZM0+4pFfuKUH83KyQiu7COy6xRWKCmOgsM0FDFcwKzBxeM9gS4E9iMnn6puOSof7F0iHvLDYipfikaY6IcGQPkRTSI/zy/HUNHmPZ7FYi/chfUb7dC11ovnRvyiUYyt8N2MdXdllJBIWOIGLWqDplFABFzazc7gZ/bOS6HhRg5UvSlumD9y9GUKTJDu9FcJMBoPZRR+KO7y9sDywALm5ufJtxzlXAI5xjZVuXBGwSGb5JiwJy0FVn0CkzdJNXkUG5MXz1bzB4uF+rOvEVk9NLycnR7eEKkASjoc8Iy2ce73ekD+jIaiCdFPV914VZHhqTTZ1TuorJZxmQIBVW2VPypsiXsyA7mH39e4qz+o8sBu18bQL74tpT/xELfXixibreaOS0KQ0NUAgEAcE4iaWYTU1gE5vzZVy+nGGV5KnxqfEKy89LZV4AAhzcuk2Or5km+9eIo9ovmBRVEvwSmWj3re2uoY2+/oxyd6p1HtcMlWcuEzbknINQ/qZpW/TlqSF+tRA8tIsSsxO0dPZP6+Yjn68T4ZnFM+kXiMG0QlhWXZPK5DpTD68iAqeXaxbmNm/5dOyLrMsl4Pg4+gencpce7pPqE+99FmTjcOoK6c0NVQHXzvCEDXO4UB9ByIM+3y2JMw3I/N0gjysc0kBnh3tfuylIelnl25tuhHS/wlZ1P7UfZNeWJchohkCTvmsS3PEO7fW/u0etG7W7rPvbyUH4aEksWENy3KbPuHDCFiX3i/2lx1SXd6wIyZTc+aTrNES5Q366qLioHX7NrUL/lwVIb+SuFA8g3sNL3l8ksMOB4plAUPcGpPFQJjkfe8djH8tNV5YGvovF9518HACq+y0jY6sybvhNThAGk6emD+2TDRLruNzC3/G+rIX1u52Sq6FWRS5ILHYnkwfmDjvygo/gU9QEfgPWcsG1tfWrb9zvTrB32ugcTTRTgQeWCHva0OtwimUcGulvBr+4F4D/kr70L0GApeNbblpdvm2F4HblaM5TZf4RXRsU9ehi+fA9COLXwhGqn8FaO9agKo6zvBeSmmJVqKA0YaH0RgxKqRNOlbRSOuYJjem6tgZUJuqo5lAoaYzRAKB1EwiwkyGSTuaaDNWx9RC7GRG5BG0Wh9BTahPHm0wGodnjGJ4GVGK9fZ8C//N3sPZc8/lEoG438wZzt2zZ3fPcva7/+7d//vdeg0Y4fwf87ObP65e2l7dEHqjvslZMXyOxV1nsqKNlq4dHo4EK2nSvC6JNi/rsnnUfqN7ZX3l6GN/WO8LmxfluQ7kW23XWVtVrcVy3HuKGPWJu/dGfm4zeUabM8Gdy5Tp++Bw/6wOj/pZTmYOd89imMdm2k82ycSNmyG+33HcGzqqLnT6+PhFBo4B7mCJZKoz38v4ovhfr7Sfa/QLjH6YTYi33/WqZwquIO9iswHukBCIFd8/c+umj76DJpaNp/6Q3vpCmvVHX/wg+8uaEdsixncJenB09Zry1y0FZ/A1IZbwpsMVVa2nLwwf/7ydRZe8/q3cG6+goGANcEAiwmn+7ErEH4Y97/DxsbGopT9dtejPK7ZZtmRALpcKPv6k80qrPwTylCaIgrJklCVjVh4W8EA2IT95YNZzB1OO9SIn8cOZhI274Q0ZvnKePzZYKYJRGCgg3NZT5ZtURwwFC0ejG8ft26yu7OLRN6e9UiMlmbJfZV64vPfUwrln3mLj459WPacwYMDetPAlc9g9oUFsQc02rh+pMLhh67Ftmi82hW8ISe7sRTKnVuT8p+lQ+YS5Z9+66+WEFAYWM3a+yB2PP+nZ/HrkmdeYvXyjIpohQzYOdqPlut8bD6W1UppvVer2318qLJv82F/XWl7YxfZ/bLvXe6pZvW4FcGuEy6Io5y0D/EbI3fLbADhW4ZmMZNa97Tv4+mA3vuj0dScRXbDOVMUKwer2RiXxSH5Aa2UNO5G4mS0w0Vdp/OAUO7rM1dkfRAVPw04Dx7Dh2rX/6q7BJRW+zUbrFcgHfyEC8qGMLytre5WNa0FaWZ8Lbq3wbQ6cFibd+oDymyrqXPIHRYZJ15CuaHmNngv3UXA+5K0vPWfYXwFhQayt7qq0P+/rUQP3Bm2NLQFbf5GTt3pf8hKflrLqdfhZ2pOfpBsaGrjnIPlji8DLDS9EvQeip4B7rFX/Z+SzmncwAH1k5qrrLhy5t33niZtwfwPiBvBXx54aHF3tHaxas1p2j4rjwas76q64BJeFt+kjG5azPQ+s4vEezqa/y+/B0ardjwCReoIhkllcs5VFCKoawLyiDH7oMb+0O/woXJn1R7OOTKYkPMkWlq43fD4QzPziNJc0EAJIh44F2vUfzo5gjdo5jquVdS75odAxPW0hd4k2OvQEE1vyEku+to09mjiPtdd+ycmls+0GW/ReElvTuImTj4iEf2dL48kisMnq4/0T3PeLiobFfLqEXZmB0VM8LgD+YCT8QD78EE/At6g+NgUpemBw4RsanymmLX1z4zOuU+jWoqIi5/2k7iECaUZSNRhAqIti61IEHplUDMpA2ZSf2kKKJUjDZ5SJtlMAFqqDovyIaii4l9zQxT6g66gDRA2QC7vYN+KzI43aT+0TYwW76zuZpYR8Rm036ldZX3tDNPBBgKVRPG4lu7ClhEVqRIJwVV3aALonbLTTkpmpTZ/gBgZLJgYRiYpPsvxxq7h7O/IWRf7OsA6orhREvcCmpS5mj2Y9y9MWVvyJ/90d+YIl1/ehgvujJ7Gz7xxkxzfscVoosHZ2x21iB1PyuGUyELjZfoOLs/J9MoF9jD0GPQSKvoQXMSEhgU+RRE0qDDgMTDHyEaYBSMeLjXMMNFKkIQKD27xeacYKUBYGMA6K9gRg4MkkAaBBQdMH1I1zDGQSGMFziu0HuSCgDt2DtuK5kY4BjHTUj8+YsoAg0Ad68kU/oR/EaR76QxRfQR/BKkH7RfJAmX3tO7SP+oLaLn5Z3AmcTnybTd+51hkBnjDW7hrKDIIr4Uu6pcuDoycz+9lujS9YMf94PNW0Duho7Ilcw54qzWaT4p9kF/NK2Uc98cGN8ERReq+0gtkZhtMiSCp8kxgRFsj1xkR8VnyGFS7Z6FE5VX87ZrhTetqyaMGa+fon7IDwwH5bCEaRGcPiYzjJQESmL9YMwSyqFl7gHTt2uEgnwBLAYMRApUD0NDjF6yReg/twjoFD6zwYnHoVIaoPdUHYhpQAUJ7ZoENZEKmh/FQ3DpCDXlEAdWDAi/fAKgCpxcbGOokLJEMWDakk6a1Bqp+igKGtkO2iZwfR4VxcXyGLykrfySwZ5Ke2o35Se6L1NFFq7MCBA/0+iCAgGKBNLfJHxfK9GLBcJiTYuYWDtUEKi4dpEQJxIoIrrBeoIYA8INIzv3wjK5RYMk4y0CwWSIPNLcwwJRgA2nKXtOmRfk3GCF+ZrGn0BxBBbfvUtYZrMka4dbPLMD2uJIXVadOnYxsKXNIrNfKpda7ZfE0yIJ7IZTO9bj+1ef31LYdtH8aktPj+wP/eGR5EpsULCFUoMTyeu+sYGBg89DJjoIqDl0x33ItrNMDFxWMqA9cojzgwxcVMmj5QfbK2wgqjb3/khywbyiYCM3tWDE7cg+fAPUaSIhjQIhnRfUQe+r5BPWiD+OxEkrK6rPSdaD2J7UB5aJ9I2FQfDrQT5SOfqDrW63/uwWY8EAzWAEEoWATGmgymTFiMpfUYTJFAPEd++RqfMiEyHgije43mN8xPIyKQDQK5FmrWCqZOsg1392n3gGQoRqfRoIXw04m0nc71F6OFX4ewuGsvTmfDw4LYp7mlrFmbmuB87KzJ2hHBqjbvY8dTc6Wb36CSeiI7n53IyjfcjLfogzS+jvJhaq7bhV+k/fi3T7CY7DhOTLBcui2hIDbxmR/x8y0Pp/A1GirnpWtbWa79DSnJ/LrkRbZ++HMu/z/TzX29NvJ1X/v+CP+ujEtv+tkqkt/Jqt2+P3VGwTqvrJmhCiKZwaCuNlhAUskgK0z7QELufumySjLwe5uaudzSr0s43h8Vp1kxMeyxTfFuf11SO34HZsevjGTGzZz49ur9yYncrQAb8VpOnef7ZJR/kkKfftHqJ7cCbMQLnjWF1eYe5iRzMmkzm6gR0/7HU5VbwRAimREhI6+uPZfFN93xzXjT309/0P/+wMv/fCTRrYqxgsI3CWjeEsEA2Pm7380Cr8LgAZegHTmsgwjGSTLAnKM5Y4J/FnVk7/iVrD7vsOothQEDdvt+9GwOK09/l+/4VRga5IJjbGTImZcbclymQ4Ze2PW5hz79X0enn/LCVrjT0yXTKY2aLrHB6oVt87E5IuyRUUt3JVTq3w2paFXpvJdn32rv2PfVhc/9p2QuV06TCopkFMk4z0nACuQSPGnM00knXy2RvRtS0SooRGt/+O+uZbFZfzmX/feVXddu2kLj5miEY2cBysJRULiLpkNC/AQfGwt+aMyhpNOv/tzKvR5r/FZn7gq/dr4xq62yxt5RczmA0gN7nN5GTB3n1mPWapg7b3V/pXm91Pjtv3wDWbe8fquvhJgNWs/1eUek3/j6+TtzyCwLo3utWTLM1OJwzSerq1e6w1wb10yv2EwbuFd9Dvnz6t8Zc5F1d5ab+TMYafz6fu+7twNCRpaPjhizInZXYoWnBPV/apPtNnwPXycAAAAASUVORK5CYII=
```
