### ISSUE TITLE
Some packages fail to download when registry is set to local npm mirror with verdaccio

### ISSUE THREAD

**Issue by mikedevita** [verdaccio/verdaccio#149]
#### My reason:

running `yarn`  or `yarn global add sails@beta` folder yield the error, yet running `npm i` works fine.

```
An unexpected error occurred: "http://npm.domain.local/@sailshq%2flodash: no such package available"
```

#### Steps to reproduce:

1. install verdaccio latest
2. set your registry url to your internal npm mirror
3. run `yarn global add sails@beta`
4. witness the error
	
#### Additional information:

 - `$ npm --verbose` prints: 3.10.10
 - `$ npm config get registry` prints: http://npm.domain.local
 - OS X

**Comment by juanpicado** [comment]
Related https://github.com/verdaccio/verdaccio/issues/118#issuecomment-278297887
@mikedevita  Do you have this in your config file? It works for me.
````
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
````

**Comment by mikedevita** [comment]
thanks that was the issue, I had everything except for the proxy line... adding that seems to have resolved this.

```
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    # adding the proxy: npmjs line fixed this
    proxy: npmjs

  '*':
    access: $all
    publish: $authenticated
    proxy: npmjs
```
