### ISSUE TITLE
`npm owner add` returns 'npm ERR! Cannot read property 'length' of undefined'

### ISSUE THREAD

**Issue by ishowman** [verdaccio/verdaccio#1527]
**Describe the bug**

When using `npm owner add <user> <pkg>` to add a user to maintainer, it returns error message:'npm ERR! Cannot read property 'length' of undefined'。
When input `npm owner ls`, returns  'admin party!' but not my login account.
**To Reproduce**

using npm global install and run it, then using `npm adduser` to create two accout: 'god' and 'xxq'。
1. login as 'god', and create an package called '@local/test', publish it. After refresh I can see it on page.
2. input `npm owner add xxq @local/test` , then returns error message above.
3. check the npm log file of step2, I notice "http fetch GET 200 http://npm.10-top.club/-/user/org.couchdb.user:xxq 257ms" and open the link, the link returns message below:
```
{
  "ok": "you are authenticated as 'undefined'"
}
```
4. `npm owner ls` returns 'admin party!'

**Expected behavior**

Add user as maintainer successfully
**Screenshots**
**npm debug log file:**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'owner',
1 verbose cli   'add',
1 verbose cli   'xxq',
1 verbose cli   '@local/test' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session bfafbc36dc977a9c
5 verbose owner add xxq to @local/test
6 http fetch GET 200 http://npm.10-top.club/-/user/org.couchdb.user:xxq 257ms
7 http fetch GET 304 http://npm.10-top.club/@local%2ftest 1334ms (from cache)
8 silly pacote registry packument for @local/test@latest fetched in 1413ms
9 verbose stack TypeError: Cannot read property 'length' of undefined
9 verbose stack     at packument.then.data (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\lib\owner.js:211:47)
9 verbose stack     at tryCatcher (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
9 verbose stack     at _drainQueueStep (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
9 verbose stack     at _drainQueue (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
9 verbose stack     at Async._drainQueues (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\15622\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:705:18)
9 verbose stack     at tryOnImmediate (timers.js:676:5)
9 verbose stack     at processImmediate (timers.js:658:5)
10 verbose cwd E:\codes\npmtest\@local
11 verbose Windows_NT 10.0.18956
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "owner" "add" "xxq" "@local/test"
13 verbose node v10.16.3
14 verbose npm  v6.9.0
15 error Cannot read property 'length' of undefined
16 verbose exit [ 1, true ]

```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 11

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@test/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '@local/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: admin
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false

```

**Environment information**

**Debugging output**

 - `$ npm -ddd` prints: npm@6.9.0 node@v10.16.3
 - `$ npm config get registry` prints: http://npm.10-top.club/

**Additional context**
