### ISSUE TITLE
HTTP 400 when using jwt

### ISSUE THREAD

**Issue by ViceIce** [verdaccio/verdaccio#1530]
**Describe the bug**

If i enable jwt (which is enabled for web ui by default) i always get a 400 bad request reponse whenever i try to use the jwt auth token.
There is no log entry for the request.

**To Reproduce**
1. configure bitbucket-server as auth
2. push a package
3. login to webui
4. view browser console for 400 error

**Expected behavior**
jwt auth should just work with any auth module

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:4.x]
 - Docker commands [e.g. docker pull ...] 
 - Docker Version [e.g. v18.05.0-ce-rc1] 18.09.9 / Rancher v1.6.28

https://github.com/VisualOn/docker-images/tree/master/docker/verdaccio

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```yaml
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: Verdaccio

auth:
  bitbucket-server:
    url: "http://server.bitbucket:7990"
    allow: "stash-users" # optional; default = ""

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  pkg:
    url: https://server.proget/npm/vo-npm/

packages:
  '@vo/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: pkg
    storage: vo
    
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
    storage: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs    
    storage: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  - { type: file, path: /verdaccio/storage/verdaccio.log, format: pretty-timestamped, level: debug }

experiments:
  # support for npm token command
  token: true
```

**Environment information**

  System:
    OS: Linux 5.0 Alpine Linux undefined
    CPU: (8) x64 AMD Opteron(tm) Processor 6380
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

**Debugging output**

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**

**Comment by juanpicado** [comment]
hi @ViceIce I don't see JWT enabled in your config file

**Comment by ViceIce** [comment]
I've removed it to get `npm login` working. But the docu says it is automatically enabled for web-ui. I can login on web UI, but when it tries to fetch the packages I get the 400 error.

When I enable jwt for API I also get the 400 error with npm cli

**Comment by haritonstefan** [comment]
@ViceIce I had a similar issue. It was because the user I was authorizing had access to too many groups, which in the end were encoded in the Jwt token, and made it too large.

**Comment by ViceIce** [comment]
@haritonstefan I can see that the jwt token is very large. What can i do?

I'm using bitbucket as auth provider. It will send all groups, projects and repos as groups.
Projects and repos are multiplied by the 3 possible permission levels.
So for our small bitbucket instance i get ~3 groups, ~15 projects and ~25 repos, so overall ~115 verdaccio groups 😱 
What can we do here?

**Comment by juanpicado** [comment]
@ViceIce @haritonstefan I read few months ago if you are using proxies to increase the header size in your (nginx or apache) by default is no able to handle such big header JWT size. Check other tickets, answer is over there.

**Comment by ViceIce** [comment]
@juanpicado verdaccio is sending the 400, even without any proxy between.

**Comment by juanpicado** [comment]
In such case, then would be great if you share some logging. As far I know Verdaccio does only return 400 in one case (login) and is not related with your issue.

**Comment by ViceIce** [comment]
Ok, I'll try to create a reproducible test config

**Comment by ViceIce** [comment]
https://nodejs.org/api/errors.html#errors_hpe_header_overflow

Looks like the default max header size is 8kb

see https://github.com/ViceIce/verdaccio-bug for reproducable

**Comment by ViceIce** [comment]
using `roleTypes` reduces the number of groups now:

```yml
auth:
  bitbucket-server:
    url: "http://server.bitbucket:7990"
    allow: "stash-users"
    roleTypes: ['groups']
```
