### ISSUE TITLE
Web not being correctly disabled.

### ISSUE THREAD

**Issue by Tacklebox** [verdaccio/verdaccio#1540]
**Describe the bug**
Setting
```
web:
  enabled: false
```
at the end of  config.yaml is not disabling the web interface.

**To Reproduce**

Navigate to the web interface in a browser

**Expected behavior**
No web interface available.

**Screenshots**
![image](https://user-images.githubusercontent.com/5867784/67795191-1db61f00-fa3b-11e9-9a4d-faf98e95e419.png)

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio/verdaccio   4   a53fabc46052        2 months ago        123MB
 - Docker commands [e.g. docker pull ...]
 - Docker Version: Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: /verdaccio/storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 2d
packages:
  '@my-company/*':
    access: $authenticated
    publish: $authenticated
    unpublish: admin
  '**':
    access: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
web:
  enabled: false
```

**Environment information**
verdaccio --info:
Environment Info:

  System:
    OS: Linux 4.14 Alpine Linux undefined
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

verdaccio --version:
  4.2.1
