### ISSUE TITLE
Yarn: Tarball is not in network and can not be located in cache

### ISSUE THREAD

**Issue by Burnsy** [verdaccio/verdaccio#1545]
**Describe the bug**
Yarn erroring saying 
`error "/@tapkit%2ftailwind.macro/-/tailwind.macro-1.0.2.tgz": Tarball is not in network and can not be located in cache (["/@tapkit%2ftailwind.macro/-/tailwind.macro-1.0.2.tgz","/Users/christopher/Library/Caches/Yarn/v6/npm-@tapkit-tailwind-macro-1.0.2-0eef92f0e35fb65f23fb8b62486e0805560fd4b6-integrity/node_modules/@tapkit/tailwind.macro/.yarn-tarball.tgz"])
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

I tried installing it with npm as-well and it succeeds so it means it must be an error with yarn

**To Reproduce**

**Expected behavior**

Yarn installs packages off private repo. 

**Docker-compose.yml**
```
  tapkit-npm:
    image: verdaccio/verdaccio
    container_name: npm.tapkit.io
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/config:/verdaccio/conf"
      - "./verdaccio/plugins:/verdaccio/plugins" 
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```

# path to a directory with all packages
storage: ../storage

# path to a directory with plugins to include
plugins: ../plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  title: Tapkit Package Manager 
  primary_color: "#3488be"
  logo: https://res.cloudinary.com/tapkit-limited/image/upload/v1571950937/logo_ka0bcl.png
  gravatar: true 
  sort_packages: asc

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

auth:
  htpasswd:
    file: ./.htpasswd
    max_users: -1

server: 
  keepAliveTimeout: 0

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100

packages:
  "@everfund/*":
    # scoped packages
    access: $authenticated
    publish: $authenticated

  "@tapkit/*":
    # scoped packages
    access: $authenticated
    publish: $authenticated

  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs



# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}

url_prefix: /
```

**Environment information**

**Additional context**
I cannot tell if its a computer thing or a verdaccio bug. any help would be great
