### ISSUE TITLE
Uncaught exception on using yarn upstream

### ISSUE THREAD

**Issue by megazoll** [verdaccio/verdaccio#156]
When I'm trying to use `npm search` it make request to `https://verdaccio.local/-/all`. Verdaccio try to upstream it from `https://registry.yarnpkg.com/-/all` and fails with error:

```shell
http  --> 200, req: 'GET https://registry.yarnpkg.com/-/all' (streaming)
 fatal --- uncaught exception, please report this
Error: Invalid JSON (Unexpected "\u001f" at position 0 in state STOP)
    at Parser.proto.charError (/usr/src/app/node_modules/jsonparse/jsonparse.js:89:16)
    at Parser.proto.write (/usr/src/app/node_modules/jsonparse/jsonparse.js:153:23)
    at Stream.<anonymous> (/usr/src/app/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/usr/src/app/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:387:10)
    at flow (_stream_readable.js:764:26)
    at resume_ (_stream_readable.js:744:3)
```

.npmrc
```ini
//verdaccio.local/:_authToken="token_here"
registry=https://verdaccio.local
always-auth=true
```

config.yml
```yml
# a list of other known repositories we can talk to
uplinks:
  yarnpkg:
    url: https://registry.yarnpkg.com
  npmjs:
    url: https://registry.npmjs.org/
```
