### ISSUE TITLE
Package installation failed

### ISSUE THREAD

**Issue by aiyadingya** [verdaccio/verdaccio#1584]
**Describe the bug**

capture-stack-trace installation failed.

![Installation result](https://cdn.basestonedata.com/img/Jietu20191121-164228.5277792.png)

![log](http://cdn.basestonedata.com/img/Jietu20191121-164252.40744d2ac.png)

If I switch to npm

![Installation result](https://cdn.basestonedata.com/img/Jietu20191121-165052.d8c3fa3f0.png)

I think it may be a problem with verdaccio

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

````
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  taobao:
````

verdaccio/4.0.1
