### ISSUE TITLE
Unable to publish scoped package with nginx

### ISSUE THREAD

**Issue by slhck** [verdaccio/verdaccio#1604]
**Describe the bug**

I cannot publish a scoped package on Verdaccio (with the [GitLab plugin](https://github.com/bufferoverflow/verdaccio-gitlab)) running behind Nginx.

**To Reproduce**

I am publishing a default package with the following `package.json`:

```json
{
  "name": "@example/test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

The error I get is:

```
➜ npm publish --registry https://npmregistry.example.com
npm notice
npm notice 📦  @example/test@1.0.0
npm notice === Tarball Contents ===
npm notice 249B package.json
npm notice === Tarball Details ===
npm notice name:          @example/test
npm notice version:       1.0.0
npm notice package size:  253 B
npm notice unpacked size: 249 B
npm notice shasum:        576cf6c5e8587eb3405f1a6df461bce909535912
npm notice integrity:     sha512-BdiP5FVOv4gbj[...]MMcpwNYls3NXw==
npm notice total files:   1
npm notice
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://npmregistry.example.com/@example%2ftest - must have required permissions: $maintainer at package-scope
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/werner/.npm/_logs/2019-12-02T13_33_26_970Z-debug.log
```

Use the following Nginx config:

```
server {
  listen 80;
  server_name npmregistry.example.com;

  keepalive_timeout 300;
  charset utf-8;
  client_max_body_size 4G;

  location / {
    proxy_pass          http://localhost:4873;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    X-NginX-Proxy true;
    proxy_read_timeout  600;
    proxy_ssl_session_reuse off;
    proxy_redirect off;
  }

  # SSL
  # Enable this once you have a LetsEncrypt cert
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/npmregistry.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npmregistry.example.com/privkey.pem;
  if ($scheme = http) {
    return 301 https://$host$request_uri;
  }
  # END SSL
}
```

**Screenshots**

In the Nginx request log, I see:

```
"PUT /@example%2ftest HTTP/1.1" 403 102 "publish" "npm/6.13.1 node/v13.2.0 linux x64"
```

In Verdaccio log I see:

```
verdaccio_1  |  info <-- 172.18.0.1 requested 'PUT /@example%2ftest'
verdaccio_1  |  http <-- 403, user: null(xx.xx.xx.xx via 172.18.0.1), req: 'PUT /@example%2ftest', error: must have required permissions: $maintainer at package-scope
```

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: 4.3.5
 - Docker Version [e.g. v18.05.0-ce-rc1]: 18.09.7, build 2d0083d
- 

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```yaml
storage: /verdaccio/storage/data

plugins: /verdaccio/plugins

listen:
  - 0.0.0.0:4873

auth:
  gitlab:
    url: https://git.example.com
    authCache:
      enabled: true
      ttl: 300
    publish: $maintainer

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

# access definitions (see https://verdaccio.org/docs/en/best#package-access)
packages:
  '@example/*':
    access: $authenticated
    publish: $authenticated
    gitlab: true
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    gitlab: true
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: info }
  #- {type: file, path: verdaccio.log, level: info}
```

**Environment information**

Environment Info:

  System:
    OS: Linux 5.0 Alpine Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

This is related to https://github.com/verdaccio/verdaccio/issues/1392, but I am using Nginx and not Apache.

The Nginx config file at https://verdaccio.org/docs/en/reverse-proxy#nginx does not indicate to me that I have a misconfiguration. 

In fact, the Docker example config file (https://github.com/verdaccio/docker-examples/blob/master/reverse_proxy/nginx/root_path/conf/nginx/sites-enabled/verdaccio-conf) has a trailing slash for the localhost in `proxy_pass` which to my knowledge should enable URI parsing, which is exactly what I want to prevent.
