### ISSUE TITLE
Search allowed for unauthenticaed users

### ISSUE THREAD

**Issue by megazoll** [verdaccio/verdaccio#162]
I setup access to only authenticated users. When I'm open index page, I see no packages. But when I'm using search it shows me published packages.

```yaml
packages:
  '@*/*':
    # scoped packages
    access:  $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
```
