### ISSUE TITLE
Not proxying packages with unusual versions

### ISSUE THREAD

**Issue by enjunear** [verdaccio/verdaccio#1626]
**Describe the bug**

I have tried to `npm install` on a project, but get an error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for es-abstract@^1.17.0-next.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'array-includes'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-17T11_54_58_562Z-debug.log
```

**To Reproduce**

Steps to reproduce the behaviour:
```bash
mkdir test && cd test
npm init -y
npm i eslint-plugin-import
```

**Expected behavior**

Install succeeds with no errors.
We can see that packages with normal semver version numbers work, but this package relied on a different type of version numbering.

**Screenshots**

On the server
```bash
server: $ docker exec -it verdaccio /bin/sh
verdaccio: $ ls /verdaccio/storage/data/es-abstract
es-abstract-1.13.0.tgz   es-abstract-1.14.2.tgz   es-abstract-1.16.0.tgz   es-abstract-1.16.3.tgz   package.json
```

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio:4.4
 - Docker commands: docker-compose up -d
 - Docker Version 19.03.5

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```yaml
# Based on default docker config file
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: 10

security:
  api:
    jwt:
      sign:
        expiresIn: 90d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true # default: true
    maxage: 90d

packages:
  "@{my-company}/*":
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    # proxy: none for offline

  # '@*/*':
  #   # scoped packages
  #   access: $all
  #   publish: $authenticated
  #   unpublish: $authenticated
  #   proxy: npmjs

  "**":
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
```

**Environment information**

**Debugging output**

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**
