### ISSUE TITLE
Can not start verdaccio with docker-compose, version 4.4.0

### ISSUE THREAD

**Issue by taoabc** [verdaccio/verdaccio#1639]
I'm use verdaccio/verdaccio version 4.4.0 docker image
when execute docker-compose up, It show errors:
```
Attaching to verdaccio
verdaccio    |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio    |  warn --- Verdaccio started
verdaccio    | (node:8) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
verdaccio    |     --> starting at object with constructor 'Timeout'
verdaccio    |     |     property '_idlePrev' -> object with constructor 'TimersList'
verdaccio    |     --- property '_idleNext' closes the circle
verdaccio    |     at JSON.stringify (<anonymous>)
verdaccio    |     at new LocalDatabase (/opt/verdaccio/node_modules/@verdaccio/local-storage/lib/local-database.js:65:20)
verdaccio    |     at LocalStorage._loadStorage (/opt/verdaccio/build/lib/local-storage.js:842:14)
verdaccio    |     at new LocalStorage (/opt/verdaccio/build/lib/local-storage.js:47:31)
verdaccio    |     at Storage.init (/opt/verdaccio/build/lib/storage.js:64:25)
verdaccio    |     at _default (/opt/verdaccio/build/api/index.js:126:17)
verdaccio    |     at startVerdaccio (/opt/verdaccio/build/lib/bootstrap.js:60:22)
verdaccio    |     at init (/opt/verdaccio/build/lib/cli.js:78:35)
verdaccio    |     at Object.<anonymous> (/opt/verdaccio/build/lib/cli.js:111:3)
verdaccio    |     at Module._compile (internal/modules/cjs/loader.js:959:30)
verdaccio    | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
verdaccio    | (node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
verdaccio exited with code 0
```
my docker-compose.yml file:
```
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.3.5
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "80:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
networks:
  node-network:
    driver: bridge
```

my config file:
```
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
web:
  title: TAL NPM
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: 3 
uplinks:
  taobao:
    url: https://registry.npm.taobao.org/
packages:
  '@peiyou/*':
    access: $all
    publish: peiyou-ci peiyou admin
    unpublish: admin peiyou
    storage: peiyou
    proxy: taobao
  '**':
    access: $all
    publish: admin
    unpublish: admin
    storage: public
    proxy: taobao
middlewares:
  audit:
    enabled: true
logs:
  - { type: stdout, format: pretty, level: http }
  - { type: rotating-file, format: json, path: /verdaccio/storage/logs/log.jsonl, level: http, options: {period: 1d, count: 30} }
```

But everything is ok when using 4.3.5
