### ISSUE TITLE
Login does not redirect - docker

### ISSUE THREAD

**Issue by marabesi** [verdaccio/verdaccio#1641]
**Describe the bug**

Once logged in using the latest version available on docker, the user is not redirected to the package list. The same happens when the user  tries to logout. Both approaches require a page refresh (F5) for the redirection to work.

**To Reproduce**

1. Make sure to have docker installed, I used the macos version.
2. pull the image with the command (docker pull verdaccio/verdaccio)
3. start a new container:
```sh
V_PATH=/path/for/verdaccio; docker run -it --rm --name verdaccio \
  -p 4873:4873 \
  -v $V_PATH/conf:/verdaccio/conf \
  -v $V_PATH/storage:/verdaccio/storage \
  -v $V_PATH/plugins:/verdaccio/plugins \
  verdaccio/verdaccio
```
4. Add a new user through the command `npm adduser --registry http://0.0.0.0:4873` - and fill in the required fields
5. Open a new tab on your browser and access the web app - `http://0.0.0.0:4873`
6. Use the credentials from the step 4 to login in the web app

**Expected behavior**
The user should be redirected to the package list, once the login has been made.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: none
 - Docker commands: 
```sh
docker pull verdaccio/verdaccio) && 
V_PATH=/path/for/verdaccio; docker run -it --rm --name verdaccio \
  -p 4873:4873 \
  -v $V_PATH/conf:/verdaccio/conf \
  -v $V_PATH/storage:/verdaccio/storage \
  -v $V_PATH/plugins:/verdaccio/plugins \
  verdaccio/verdaccio
```
 - Docker Version: 2.1.7.0 (41561) edge - Engine: 19.03.5

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```yaml
storage: ../storage
max_users: -1
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
web:
  enable: true
  title: Verdaccio
  primary_color: "#4b5e40"
  scope: "*"
  sort_packages: asc | desc
```

**Environment information**

Docker command executed: `docker exec -it verdaccio bin/verdaccio --info`

```
Environment Info:

  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
```
