### ISSUE TITLE
Loading upstream tarball doesn't respect package.proxy array

### ISSUE THREAD

**Issue by Beanow** [verdaccio/verdaccio#1642]
**Describe the bug**

Having multiple uplinks point to the same registry, the package.proxy array gets ignored.
Instead we'll walk through the uplinks and select the last one in the list that can serve the URL we've found for our upstream tarball.

**To Reproduce**

```yml
storage: ./storage

uplinks:
  cachednpm:
    url: https://registry.npmjs.org/
    cache: true
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  '**':
    access: $all
    publish:
    proxy: cachednpm
```

1. Run with above config (listening on localhost)
2. Try requesting `http://localhost:4873/@verdaccio/streams/-/streams-8.5.2.tgz`
3. Notice that `./storage/@verdaccio/streams/streams-8.5.2.tgz` does not exist

The uplink chosen here was `npmjs`, not `cachednpm`.

**Expected behavior**

Making the upstream request should respect the packages.proxy array.
In this example, selecting `cachednpm` for it's uplink, causing it to cache the tarball.

**Environment information**

```
Verdaccio version: 4.4.1
System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
```

**Additional context**

I believe the culprit here is:

https://github.com/verdaccio/verdaccio/blob/32aabca6412afdd19a2603205d661f00a667088f/src/lib/storage.ts#L207-L211

The `isUplinkValid` check will be true for both uplinks. So the last one in the array will be selected.
Perhaps it should be using `hasProxyTo` from `src/lib/config-utils.ts`?

**Comment by sergiohgz** [comment]
In the config above, every package (denoted by `'**'` are requested from cachednpm uplink, so it will be retrieved from cache.

**Comment by Beanow** [comment]
> In the config above, every package (denoted by `'**'` are requested from cachednpm uplink, so it will be retrieved from cache.

That's what I would expect. But it doesn't :smile:

**Comment by nothingismagick** [comment]
Its the for loop - it doesn't exit at the first resolution, like you mentioned @Beanow - maybe the "workaround" is to have the one you really want to be last in the collection?

**Comment by sergiohgz** [comment]
Try setting a specific package (like 'react') to be taken from cachednpm and other without cache. Then, paste results and check if the storage contains cached package.

**Comment by Beanow** [comment]
I've hacked in a log (in `build/lib/storage.js`), just after the for-loop I linked.

```js
console.log('DECIDED ON UPLINK:', uplink.upname);
```

This outputs `DECIDED ON UPLINK: npmjs`
Notice I've not added `npmjs` as proxy for _any_ package at all.

**Comment by Beanow** [comment]
Did you mean something like this @sergiohgz?

```yml
uplinks:
  cachednpm:
    url: https://registry.npmjs.org/
    cache: true
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  'statuses':
    access: $all
    proxy: cachednpm
  '**':
    access: $all
    proxy: npmjs
```

1. Request `http://localhost:4873/@verdaccio/streams/-/streams-8.5.2.tgz`
2. Request `http://localhost:4873/statuses/-/statuses-1.5.0.tgz`

```
$ tree ./storage
./storage
├── statuses
│   └── package.json
└── @verdaccio
    └── streams
        └── package.json
```
