### ISSUE TITLE
Meaning of a "proxy: npmjs"? 

### ISSUE THREAD

**Issue by qnnguyen17** [verdaccio/verdaccio#1675]
Hi! When we specify `proxy: npmjs` for some group of packages, does this mean that `npm install`ing that package will make the public NPM registry serve up the traffic directly to the client? Or will the package data go through Verdaccio first before being forwarded back to the client? This is an important consideration for my use case of Verdaccio, since we want to avoid having to handle traffic for public NPM packages ourselves.

**Comment by juanpicado** [comment]
hi @qnnguyen17 

When you define `proxy` in some of your `packages` section means if the package the package manager is requesting is not found in the *cache* will look up in URL of the `uplink` specified in the *proxy* section. The `proxy` even might be multiple eg: `proxy: npmjs private`.

```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  private:
    url: https://registry.private.org/
packages:
  '@private/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: private
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
```

That being said, Verdaccio acts as a proxy, so the package manager will request to Verdaccio by demand will increase the cache content for future request, saving bandwidth and reducing the latency. The package managers ( npm, yarn or pnpm) can only points to one registry at the time, thus Verdaccio will the responsable to serve all the request streaming tarballs and packuments to your computer.

Hope this helps you to understand how the `proxy` works.
