### ISSUE TITLE
Environment variables support in configuration file

### ISSUE THREAD

**Issue by BlackGad** [verdaccio/verdaccio#1681]
**Is your feature request related to a problem?**
Cannot redirect storage and plugins folders to OS specific path (Windows OS, **%ALLUSERSPROFILE%**)

**Describe the solution you'd like**
Ability to specify environment variable link in path options (storage, plugins etc.). 
Will be glad to see any variable format (%var%, $(var), %(var) etc)

Example:

```yaml
# path to a directory with all packages
storage: %environment_variable%/storage
# path to a directory with plugins to include
plugins: %environment_variable%/plugins
```

**Describe alternatives you've considered**
Alternatives are:
- Respect working directory (merge path from configuration file with current directory rather than configuration file location)
- Pass configuration keys via command line `verdaccio --storage <value>` or `verdaccio --option storage=<value>`

**Additional context**
Seems feature related to another issues:
- https://github.com/verdaccio/verdaccio/issues/1141
- https://github.com/verdaccio/verdaccio/issues/1666
- https://github.com/verdaccio/verdaccio/issues/1621

Thank you a lot for great solution!
