### ISSUE TITLE
Verdaccio fatal exception and crash when log rotate signal event is called.

### ISSUE THREAD

**Issue by chuang93** [verdaccio/verdaccio#1709]
**Describe the bug**
Verdaccio throws fatal exception because the logger implementation (bunyan) is used incorrectly, so when the signal to rotate logs is called the server will crash.

**To Reproduce**
1. Install a verdaccio instance on a linux machine. 
2. Use logrotate to handle creating new log files for the verdaccio logs. 
3. when the rotation policy is applied verdaccio will crash and throw the below error.

**Expected behavior**
Verdaccio crashes and has error in the log as found in the debugging output section. Restarting Verdaccio will allow server to start up again.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: ./storage
plugins: ./plugins

listen:
 - http://localhost:4873

web:
  title: NPM Registry
auth:
   activedirectory:
     url: [LDAP URL]
     baseDN: [BASEDN]
     domainSuffix: [SUFFIX]
     groupName: 'developers'

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:

  '@company/*':
    access: developers
    publish: developers
    unpublish: developers

  '@*/*':
    # scoped packages
    access: $all
    proxy: npmjs

  '**':
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
  - {type: file, path: ./verdaccio.log, level: info}
```
**Environment information**

 System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 8.12.0 - /usr/local/node/bin/node
    npm: 6.4.1 - /usr/local/node/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 67.0.4
    Safari: 12.1.1
  npmGlobalPackages:
    verdaccio: 4.4.2

**Debugging Output**

fatal--- uncaught exception, please report this
TypeError: Logger.reopenFileStreams is not a function
    at process.<anonymous> (/usr/local/node-8.12.0/lib/node_modules/verdaccio/build/lib/logger.js:170:12)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at processEmit [as emit] (/usr/local/node-8.12.0/lib/node_modules/verdaccio/node_modules/signal-exit/index.js:155:32)
    at Signal.wrap.onsignal (internal/process.js:197:44)

**Additional context**

I believe that it is crashing because of the code in /verdaccio/build/lib/logger.js (Line 170):

    Logger.reopenFileStreams();

This is referencing the bunyan logger module and not the instance of the logger object actually created, thus throwing the error. It should be a simple fix to change to call method on the actual logger object:

    logger.reopenFileStreams();

We have patched and tested this on our instance of verdaccio and it appears to fix the issue.
Any feedback or changes to fix would be greatly appreciated!
