### ISSUE TITLE
Method to access public registry via proxy

### ISSUE THREAD

**Issue by agpreynolds** [verdaccio/verdaccio#171]
#### My reason:

Hello, i'm not sure if this is an issue or just a feature I can't find but is it be possible to set a proxy configuration to access the public repository

When not using verdaccio I can edit the npm config to add my proxy configuration and access the public repo fine, however once I run verdaccio and edit the registry value in the config I am unable to connect.

I am getting 504 Gateway timeout errors

#### Additional information:
	
 - `$ npm --verbose` prints:
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose' ]
npm info using npm@4.0.5
npm info using node@v7.4.0

 - `$ npm config get registry` prints:
http://localhost:4873/

 - Verdaccio terminal output
 warn  --- config file  - C:\Users\areynold\AppData\Roaming\verdaccio\config.yaml
 warn  --- http address - http://localhost:4873/

 - Windows

 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
```yaml
# path to a directory with all packages
storage:  \\10.62.113.100\share\verdaccio\node_modules\verdaccio\conf\storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
```

**Comment by jachstet-sea** [comment]
Did you try setting the environment variables "http_proxy" and "https_proxy" before running verdaccio? That works fine for us.

**Comment by agpreynolds** [comment]
Yeah have set both of those, tried with both the normal config, and the global config

**Comment by jachstet-sea** [comment]
I was talking about environment variables, not npm config variables. Does the command `set | grep -i proxy` (linux) or `set | findstr proxy` (windows) return something?

**Comment by agpreynolds** [comment]
Sorry my mistake, i've updated the environment variables and set | findstr proxy now returns values for both the http_proxy and https_proxy.

However... I still get the 504 when running npm install through verdaccio

**Comment by Meeeeow** [comment]
![snipaste20170427_163122](https://cloud.githubusercontent.com/assets/19658647/25474772/0399b3a2-2b67-11e7-8d53-c6b6459045d1.png)

set `https_proxy: http://your-proxy-url` in configure file works for me, but set environment variable by command will not work.

I will look into it later

**Comment by agpreynolds** [comment]
So i'm now having a very similar problem. Getting 403 responses when running npm install through verdaccio. 

`Error: fetch failed with status code 403`

Works fine when setting the registry back to default value "registry.npmjs.org"

Any advice?

**Comment by agpreynolds** [comment]
Some more information although i'm slightly more confused. I'm also not convinced this is an issue with verdaccio anymore, possibly something with npm itself

After spending a while trying to output to the verdaccio logs and them not showing up I tried something basic. I turned verdaccio off, left the config the same and ran npm install again. Exactly the same thing happened and all of my packages failed with a 403. This leads me to think that the requests are not hitting verdaccio at all, this would also account for the lack of log activity.

My npm local config is as default apart from:
`registry=http://localhost:4873/`

My npm global config contains only default values

My verdaccio config.yaml looks like:
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

http_proxy: http://proxy:8080/
https_proxy: http://proxy:8080/

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: http://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  #- {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: trace}
```

I suspect this may not be an issue for you guys, but I thought leaving the information here may help if someone else hits the same thing
