### ISSUE TITLE
How to use custom web api for authentication

### ISSUE THREAD

**Issue by Abishake968** [verdaccio/verdaccio#1713]
I use verdaccio 4.4.2 version how to give custom web api in config file and autheticate users when npm login in verdaccio server.

**Comment by juanpicado** [comment]
Would you elaborate more your scenario? I don’t get it. Be extend if you can :)

**Comment by Abishake968** [comment]
Can I possible to authenticate by give custom web-api  in auth section of config.yaml file?

If I give cmd "npm login --registry 'localhost'" then give username and password it's get authenticate from given custom api in config.yaml file.

**Comment by juanpicado** [comment]
My apologies, but I still don't get it. I'd recommend providing some comprehensive examples or something more visual in case you don't find the words to explain your question.

**Comment by Abishake968** [comment]
**Describe the bug**
Authentication is not done by give web-api link in configuration file.

**To Reproduce**
In config.yaml file, type following line in **auth** section and give following cmd line in command prompt.

**Config.yaml file:**
auth:
  delegated-auth:
    url: my api link
    user_key: username 
    pwd_key: password 

**cmd:**
>verdaccio
>npm login --register localhost:4873

give Username , Password and EmailID then given username and password is not authenticated from given api link in auth section from config.yaml file.



**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: ./storage
plugins: ./plugins
web:
  title: Verdaccio
  primary_color: "#add8e6"
auth:
  delegated-auth:
    url: my api link
    user_key: username 
    pwd_key: password 
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $REPO_WRITE
    unpublish: $authenticated
    proxy: npmjs
  '**':
    publish: $REPO_WRITE
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
logs:
  - { type: stdout, format: pretty, level: http }
listen: 
     - 0.0.0.0:4873
     
```
