### ISSUE TITLE
Package access doesn't follow the rules in config.yaml

### ISSUE THREAD

**Issue by c4sh** [verdaccio/verdaccio#173]
#### My reason:

I have been trying to limit access to a single user and have been able to do that with the  max_users: -1 setting after logging one user in (now I can only login to my registry with that one user).

Then I wanted to avoid other users from installing the package. I set package access only for `$authenticated` in my config.yaml.

But still **a not-authenticated user can install my package** by accessing the registry and doing:
` npm install name_of_package`

I would suppose "access" means being able to retrieve the content of the package? Or am I wrong?

#### Steps to reproduce:
My config.yaml packages configuration looks like this:
```
 packages:
 	'**':
    	access: $authenticated
    	publish: $authenticated
```

My whole config.yaml file:

```
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}

listen:
  - 0.0.0.0:4873  # listen on all addresses (INADDR_ANY)
```

**Comment by juanpicado** [comment]
@c4sh Could you define `verdaccio` version?

**Comment by c4sh** [comment]
Version is 2.1.5.

**Comment by Meeeeow** [comment]
I can't reproduce this issue, did you try restart verdaccio after edit configure file?

**Comment by c4sh** [comment]
Yes I did restart verdaccio after changing config.yaml .

**Comment by Meeeeow** [comment]
I can't figure out what's happed with your verdaccio, here is my configure file:
```yaml
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated

    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
```

I got 403 forbidden after remove auth information from `.npmrc`
