### ISSUE TITLE
yarn2 Support (login)

### ISSUE THREAD

**Issue by jeffrson** [verdaccio/verdaccio#1737]
**Describe the bug**
I'm trying yarn2. While `yarn npm login` works with the default registry, when I put
`npmRegistryServer: "https://verdaccio:4873"` in my .yarnrc.yml, I get a http 409 error:

> ➤ YN0001: HTTPError: Response code 409 (Conflict)
>     at EventEmitter.<anonymous> (C:\src\y2\.yarn\releases\yarn-berry.js:24:327728)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ➤ YN0000: Failed with errors in 4.09s

**To Reproduce**

Have a verdaccio installation that requires login.

1. yarn set version berry
2. echo "npmRegistryServer: "https://verdaccio:4873" >> .yarnrc.yml (with the actual address)
3. yarn npm login - enter username and password

**Expected behavior**
No error.

**Screenshots**
None

**Environment information**

node 13.9
yarn 2.0rc29

**Comment by juanpicado** [comment]
Hi, 

Thanks for this cutting-edge issue 🙃

It is a Verdaccio issue or yarn v2 issue 🤔?   Where is the error ? 

If is failing in the served side then we need some logs.

**Comment by jeffrson** [comment]
Since yarn2 works with registry.yarnpkg.com I was blaming verdaccio. Here is a test:

conf.yml
```
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

security:
  api:
    jwt:
      sign:
        expiresIn: 30d
        notBefore: 0
  web:
    sign:
      expiresIn: 7d

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: file, path: verdaccio.log, level: trace}
```

Verdaccio installed globallly, run by `verdaccio -c conf.yml`. Then I change to an empty folder (c:\y2), initialize yarn2 (`yarn set version berry`) and store these two files:

.npmrc
```
registry=http://localhost:4873
```

.yarnrc.yml
```
yarnPath: "C:\\y2\\.yarn\\releases\\yarn-berry.js"

unsafeHttpWhitelist:
  - "localhost"

npmRegistryServer: "http://localhost:4873"
```

Then I create a user with `npm login`. Finally I try to login as that user with `yarn2 npm login`. Here's the log: [verdaccio_yarn2.log](https://github.com/verdaccio/verdaccio/files/4300048/verdaccio_yarn2.log)
