### ISSUE TITLE
Docker compose gives error from documenation 

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#1743]
**Describe the bug**

verdaccio    |  fatal--- cannot open config file /verdaccio/conf/config.yaml: Error: CONFIG: it does not look like a valid config file

**To Reproduce**

https://verdaccio.org/docs/en/docker#using-docker-compose
Use the docker compose section 

docker-compose.yaml

```yaml
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"  
networks:
  node-network:
    driver: bridge

```
