### ISSUE TITLE
Unable to retrieve packages while offline

### ISSUE THREAD

**Issue by agpreynolds** [verdaccio/verdaccio#177]
#### My reason:

I'm not sure if the way i'm attempting to use verdaccio is an intended use case so I will start by explaining my setup:

Internet Connected Developer Laptop
- Global installation of verdaccio
- Ran npm install

Offline CI Server
- Verdaccio installed as windows service
- Config updated to remove all references to official registry
- Storage directory replaced with storage from my laptop

I was hoping that when running npm install on the Offline server it would be able to install packages from the cache.

Unfortunately it still seems to be attempting to connect to the official registry, this time using the ip address 151.101.60.162:443.

####  App Version:	
2.1.4

#### Additional information:
	
 - `$ npm --verbose` prints:
```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.10.2
```

 - `$ npm config get registry` prints:
`http://localhost:4873/`

 - Verdaccio terminal output
```
 warn  --- config file  - C:\Users\areynold\AppData\Roaming\verdaccio\config.yaml
 warn  --- http address - http://localhost:4873/
```
 - Windows
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

```
 - Container:
   - [x] I use local environment
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS.
