### ISSUE TITLE
Url encoded problem

### ISSUE THREAD

**Issue by simonfr** [verdaccio/verdaccio#1777]
**Describe the bug**
When I try to publish i get this :
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://domain/@scope%2fpackage - no such package available
npm ERR! 404 
npm ERR! 404  '@scope/package@0.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

In logs I've this :
```
 http <-- 404, user: user(*.*.*.* via *.*.*.*), req: 'PUT /@scope%2fpackage', error: no such package available
 http <-- 404, user: user(*.*.*.* via *.*.*.*), req: 'PUT /@scope%2fpackage', error: no such package available
```

**Expected behavior**
It should push correctly package

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: 4.5.1
 - Docker Version: 19.03.8
 - Traefik Version: v2.2.0

**Environment informations**
It runs behind traefik reverse proxy

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
```
