### ISSUE TITLE
Web GUI shows blank page

### ISSUE THREAD

**Issue by patrickjane** [verdaccio/verdaccio#1779]
I have just installed verdaccio using npm (non-global installation). After installation I changed the listen-IP address, then started the server.

I can navigate to http://my-ip:4873, but all I get is a blank page. In firefox developer tools I can see it successfully loads the index.html & the javascript files, but the page is blank (no blocker addons involved).

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```

storage: /storage/data/verdaccio
plugins: ./plugins

listen:
  - 0.0.0.0:4873

web:
  enable: true
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
```

**Environment information**

```
[verdaccio@deimos ~/node_modules/verdaccio]$ ./bin/verdaccio --info

Environment Info:

  System:
    OS: freebsd
    CPU: (6) x64 Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
```

This is what I get in the log when navigating to the web GUI:

```
[verdaccio@deimos ~/node_modules/verdaccio]$ ./bin/verdaccio
 warn --- config file  - /home/verdaccio/.config/verdaccio/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.5.1
 http <-- 200, user: null(10.0.60.104), req: 'GET /', bytes: 0/588
 http <-- 200, user: null(10.0.60.104), req: 'GET /', bytes: 0/588
 http <-- 304, user: null(10.0.60.104), req: 'GET /-/static/0.style.b3d2b69b057068c678ca.css', bytes: 0/0
 http <-- 304, user: null(10.0.60.104), req: 'GET /-/static/0.style.b3d2b69b057068c678ca.css', bytes: 0/0
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/manifest.2450098214ec8cb92096.js', bytes: 0/1608
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/manifest.2450098214ec8cb92096.js', bytes: 0/1608
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/main.2450098214ec8cb92096.js', bytes: 0/30153
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/main.2450098214ec8cb92096.js', bytes: 0/30153
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/vendors.2450098214ec8cb92096.js', bytes: 0/206617
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/vendors.2450098214ec8cb92096.js', bytes: 0/206617
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/2.style.f5bfe8c872c998c962a0.css', bytes: 0/4583
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/2.style.f5bfe8c872c998c962a0.css', bytes: 0/4583
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/5.2450098214ec8cb92096.js', bytes: 0/4481
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/5.2450098214ec8cb92096.js', bytes: 0/4481
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/1.2450098214ec8cb92096.js', bytes: 0/11794
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/1.2450098214ec8cb92096.js', bytes: 0/11794
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/2.2450098214ec8cb92096.js', bytes: 0/14219
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/2.2450098214ec8cb92096.js', bytes: 0/14219
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/6f6560222974090c1ef11e84623ff803.svg', bytes: 0/692
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/6f6560222974090c1ef11e84623ff803.svg', bytes: 0/692
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/favicon.ico', bytes: 0/2054
 http <-- 200, user: null(10.0.60.104), req: 'GET /-/static/favicon.ico', bytes: 0/2054
```

What is wrong here? I have tried Safari, Firefox & Chrome (all latest versions).
