### ISSUE TITLE
getting package without the network > getting 500

### ISSUE THREAD

**Issue by cybermerlin** [verdaccio/verdaccio#1788]
Hi there.
**My task**: _`npm i` + `npm run build` on any Windows machine without the Internet and only with my cached repo._
**My current trouble**: _500 error from Verdaccio + not installed node_modules packages_

----
**My actions**:
- I put verdaccio in my VM without the network (even LAN).
  - windows server 2016
  - user as Administrator
- I copy from another PC verdaccio/storage/*.*.
- I set this config:
```
storage: ./storage
plugins: ./plugins

web:
  title: NPM local repository
  sort_packages: asc
  darkMode: true

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
 npmjs:
   url: https://registry.npmjs.org/
   # timeout: 100ms
   cache: true
   # max_fails: 1
 baduplink:
   url: http://192.168.34.238:4873/
   cache: true

packages:
  'core':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    
  'vue-property-decorator':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
  
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    #proxy: npmjs
    proxy: baduplink
    allow_offline: true

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    #proxy: npmjs
    proxy: baduplink
    allow_offline: true

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
```
- I run `verdaccio -c c:\dev\verdaccio\config.yaml`
- I run `npm set registry HTTP://localhost:4873`
- I run `npm i` In another cmd on this VM when exist some **package.json**
- ok, I tried another command `npm pack --verbose ansi-regex`, but... same trouble
- Almost all packages was install, except some packages, which return strange exception in verdaccio's terminal.

![image](https://user-images.githubusercontent.com/1460479/80541655-36849a80-89b4-11ea-8a13-93c9fc1e8460.png)

(!) I looked at the storage and funded my asked packages directories with .tgz inside.

```
C:\dev\proj>npm pack --verbose ansi-regex
npm info it worked if it ends with ok
npm verb cli [ 'c:\\dev\\node\\node.exe',
npm verb cli   'c:\\dev\\node\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'pack',
npm verb cli   '--verbose',
npm verb cli   'ansi-regex' ]
npm info using npm@6.14.4
npm info using node@v10.15.3
npm verb npm-session e727d8195dbd4528
npm http fetch GET 200 http://localhost:4873/ansi-regex 188ms
npm http fetch GET 304 http://localhost:4873/ansi-regex 63ms (from cache)
npm http fetch GET 500 http://localhost:4873/ansi-regex/-/ansi-regex-5.0.0.tgz 112141ms attempt #3
npm verb stack Error: 500 Internal Server Error - GET http://localhost:4873/ansi-regex/-/ansi-regex-5.0.0.tgz
npm verb stack     at res.buffer.catch.then.body (c:\dev\node\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:68:7)
npm verb statusCode 500
npm verb pkgid ansi-regex@latest
npm verb cwd C:\dev\ncuyao-client
npm verb Windows_NT 10.0.14393
npm verb argv "c:\\dev\\node\\node.exe" "c:\\dev\\node\\node_modules\\npm\\bin\\npm-cli.js" "pack" "--verbose" "ansi-regex"
npm verb node v10.15.3
npm verb npm  v6.14.4
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET http://localhost:4873/ansi-regex/-/ansi-regex-5.0.0.tgz
npm verb exit [ 1, true ]
npm timing npm Completed in 113499ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\dev\npm-cache\_logs\2020-04-28T21_47_08_416Z-debug.log
```
