### ISSUE TITLE
Trying to get https working with dockerfile

### ISSUE THREAD

**Issue by mattoni** [verdaccio/verdaccio#182]
Hi there,

 Trying to get https working using the dockerfile to no avail:

```
warn --- invalid address - "https://my-url.com:4873/", we expect a port (e.g. "4873"), host:port (e.g. "localhost:4873") or full url (e.g. "http://localhost:4873/")
```
The container then dies. I had to override the dockerfile command and edited it to remove the `--listen` argument so that it used the config to do it. If I change it at all from 0.0.0.0:4873 it fails to start.

**Comment by arsdehnel** [comment]
Are you just running this publicly available? Seems like you'd likely want something in front of it terminating the SSL but maybe that's just my approach. If you do that then this operates off non-ssl and should be alright.

**Comment by mattoni** [comment]
>  Seems like you'd likely want something in front of it terminating the SSL
Not quite sure what you mean by that. It supports SSL from the looks of it, but it won't actually let me serve out the certs.

**Comment by juanpicado** [comment]
@mattoni Can you describe your set up? How Can I reproduce it?

**Comment by mattoni** [comment]
It's been awhile since I've messed with this, but I've got certificates being installed into a /tls directory with the following config:

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

listen:
  - https://npm-registry.cycle.io:4873

https:
  cert: /tls/current.chain
  key: /tls/current.key

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 10

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '@platform/*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

and running it with the following args:
`/usr/src/app/bin/verdaccio --config /verdaccio/conf/config.yaml --listen 0.0.0.0:4873`

If i change listen at all, the container will crash so I can't get it to run https.
