### ISSUE TITLE
$nobody access rule or whitelist users

### ISSUE THREAD

**Issue by suenot** [verdaccio/verdaccio#1825]
I didn't find about how to close access to publish to somebody not from team.
```yml
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
```
Situation: I use ```@babel/plugin-proposal-decorators``` in my project. Hacker push ```@babel/plugin-proposal-decorators``` package with violence to my register. And then my project pull this violence code... This is a hole in security. Need mechanism to close access to people not in whitelist to push any projects in register.

**Comment by juanpicado** [comment]
You might achieve that creating your own auth plugin, or extending another one. Have you considered that?

**Comment by suenot** [comment]
I found ```undefined``` access rule in documentation and access by username.
```yml
packages:
  '@my_group/*':
    access: $developer
    publish: $developer
    gitlab: true
  '**':
    access: $all
    publish: 
    proxy: npmjs
```
In [documentation](https://verdaccio.org/docs/en/packages) in list of available access options:
```
The list internal groups handled by verdaccio are:

'$all', '$anonymous', '@all', '@anonymous', 'all', 'undefined', 'anonymous'
```

I found ```undefined``` is equivalent to ```$nobody```. It is 100% not try to find user on npm with nam e ```undefined``` or ```anonymous``` and add access to this user?
Those users are existing:
```
https://www.npmjs.com/~undefined
https://www.npmjs.com/~anonymous
```
