### ISSUE TITLE
https without self-sign ssl doesn't work

### ISSUE THREAD

**Issue by benliu723** [verdaccio/verdaccio#1835]
I encounted a problem with ssl certificate. I have my own key(.key) and certificate file(.crt). My verdaccio config is showing blow:

```
https:
  key: /home/test/.config/verdaccio/mykey.key
  cert: /home/test/.config/verdaccio/mycrt.crt
  ca:
```

while i start server, i got those error:
> fatal--- You have enabled HTTPS and need to specify either 
> "https.key", "https.cert" and "https.ca" or 
> "https.pfx" and optionally "https.passphrase" to run https server

here is the screenshot:
![image](https://user-images.githubusercontent.com/1772367/84344902-8d4dd880-abde-11ea-9ed5-d292c2539942.png)

looks like ca is mandatory. however my server is not a self-sign ssl server.

LOOKING FORWARD FOR YOUR REPLY and Thanks in advance for any help.
