### ISSUE TITLE
Hope to improve the push information mechanism

### ISSUE THREAD

**Issue by crper** [verdaccio/verdaccio#1848]
Now the configuration of notify can support webhooks, is very practical.
But there is no concept of thrttole and delay.

For example, I used the webhooks, of some enterprises to limit up to 20 entries per minute.
In this case, I have to set a message delay push, such push a message must 4 seconds.

It is also hoped that endpoint supports arrays, which can be pushed to several regions by webhook at one time.

```yaml
  'frontend-dingtalk':
     method: POST
     headers: [{'Content-Type': 'application/json;charset=utf-8'}]
     endpoint: [webhooks1url,webhook2url,webhook3url]
	 throttle: 4s # 4s execute one , default 0(Immediately)
     content: ""
```

There is also the package information obtained by the template.
I hope to be able to expose the update time of the package release to the availability of variables..

I can't get the time.modified directly.

thanks
