### ISSUE TITLE
Cannot Start Verdaccio After Upgrade to 2.1.5

### ISSUE THREAD

**Issue by Zwergenpunk** [verdaccio/verdaccio#189]
#### My issue:

I cannot start verdaccio anymore after upgrade to 2.1.5 (works finde with 2.1.4)

#### Steps to reproduce:

verdaccio

####  App Version:	

verdaccio:  2.1.5
npm: 4.5.0
node: 6.10.0

####  Config file:	

```
# path to a directory with all packages
storage: /home/user/.local/share/verdaccio/storage

auth:
  htpasswd:
    file: ./htpasswd


# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

listen:
 - https://npm.myDomain.com:4873/

https:
   key: /home/user/.config/verdaccio/git.myDomain.key
   cert: /home/user/.config/verdaccio/git.myDomain.crt

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
#  - {type: file, path: verdaccio.log, level: info}
```

### Additional verbose log:
```
verdaccio
warn  --- config file  - /home/user/.config/verdaccio/config.yaml
fatal --- cannot create server: path must be a string or Buffer
```
