### ISSUE TITLE
Verdaccio (Helm) - htpasswd permission denied

### ISSUE THREAD

**Issue by ivj94** [verdaccio/verdaccio#1989]
**Describe the bug**
I installed verdaccio helm chart with my custom configuration yaml file. I tried to ssh into the pod and create /verdaccio/storage/htpasswd with user records but I don't have the permission to create a file inside /storage directory.

**To Reproduce**
1. Create custom config.yaml

2. Create configmap:
`kubectl create configmap verdaccio-config --from-file ./config.yaml`

3. Install Verdaccio Helm Chart:
`helm install verdaccio --set customConfigMap=verdaccio-config verdaccio/verdacio`

4. I ssh into the pod and wanted to create /verdaccio/storage/htpasswd file but I got 'permission denied'. I also tried to run chown command on the folder but I couldn't as I do not have enough privilege.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@my-scope/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
```
