### ISSUE TITLE
Mixed Content error when serving using iisnode + https

### ISSUE THREAD

**Issue by dariodotcom** [verdaccio/verdaccio#2003]
**Describe the bug**
Verdaccio UI served via HTTPS using IISNode requests some JS and CSS over HTTP. Those requests are blocked by chrome (v.86), so the web application does not work.

I tried to use `url_prefix` as described [here](https://github.com/verdaccio/verdaccio/issues/622), this fixes the mixed content but breaks urls within the app, as per [this PR](https://github.com/verdaccio/verdaccio/pull/1299)

**To Reproduce**
- Install Verdaccio on IIS using the [documentation](https://verdaccio.org/docs/en/iss-server)
- Configure an HTTPS binding on IIS
- Open the site in HTTPS in Chrome

**Expected behavior**
The application should open normally.

**Screenshots**
These are the errors logged by dev tools:

![errors](https://user-images.githubusercontent.com/1570989/99234146-739b6780-27f4-11eb-9841-754f7fed043c.png)

These are the resources requested via HTTP:

![resources](https://user-images.githubusercontent.com/1570989/99234306-a80f2380-27f4-11eb-8cc6-d808dbae5fb0.png)

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  title: NPM registry
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # convert your UI to the dark side
  # darkMode: true

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: ./htpasswd
    # Disables registration.
    # To configure users, go to https://hostingcanada.org/htpasswd-generator/, generate a username/password file, and add it to ./htpasswd
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false
#  # support for the new v1 search endpoint, functional by incomplete read more on ticket 1732
#  search: false

# This affect the web and api (not developed yet)
#i18n:
#web: en-US

#Allows publishing when remote server is offline
publish:
  allow_offline: true

http_proxy: http://proxy_addr:9090
https_proxy: http://proxy_addr:9090
```

**Environment information**
```
  System:
    OS: Windows Server 2016 10.0.14393
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Debugging output**
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '-ddd'
npm verb cli ]
npm info using npm@6.14.6
npm info using node@v12.18.4
```

 - `$ npm config get registry` prints: https://registry.npmjs.org/
