### ISSUE TITLE
npm install allowed for unauthorized users

### ISSUE THREAD

**Issue by igrcic** [verdaccio/verdaccio#201]
Hi everyone,

we have been running verdaccio for some time now and everything was running ok.

Now we have to add some restricted packages to our repository so i set up some scopes and assigned packages to it. It seems thateverything is working fine, the user has to be authorized in order to publish the package or to see it in the web gui. The problem is that all users can `npm install` the scoped package. 

I have even tried to put access: `$authenticated`  for all packages, but to no avail.

What should one do in order to make the package private (disable access to non authorized users?)

Thank you,

####  App Version:	
`v2.1.7 `

####  Config file:	
```yaml
packages:
  '@ngp/*':
    access: $authenticated
    publish: $authenticated     
    storage: ./scoped_storage   
  '*':  
    access: $authenticated 
    publish: $authenticated 
    proxy: npmjs 
```
