### ISSUE TITLE
static files not loading when using verdaccio with nginx reverse proxy on docker

### ISSUE THREAD

**Issue by janekbordo** [verdaccio/verdaccio#2029]
Hi, 

I have an issue when trying to run nginx reverse proxy on docker with verdaccio set as one of the apps.
Every static content like js scripts, css files, favicon, etc is not loading properly because of paths probably - error from error log below. It is all causing verdaccio loading as blank page.

`*2 open() "/etc/nginx/html/-/static/main.80161fe0b6bd47fb69c4.js" failed (2: No such file or directory)`

What I see when I enter https://server_name/verdaccio is blank page with 404 errors(from GET https://server_name/-/static/...) in network and console:

![image](https://user-images.githubusercontent.com/24796350/102105108-48c22480-3e2f-11eb-99c5-93308face9b3.png)

I have verdaccio set at /verdaccio location. default.conf nginx file you can find below:

```
server {
    listen 80;
    return 302 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name xxxxxxxx;
    
    ssl_certificate /etc/nginx/ssl/docker-nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/docker-nginx.key;

    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log off;
    error_log /var/log/nginx/error.log error;

    location /verdaccio {
        proxy_pass              http://verdaccio:4873/;
        proxy_set_header Host            $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

}
```
Here is verdaccio's config.yaml : 
```
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  darkMode: true

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all
    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  # - { type: stdout, format: pretty, level: http }
  - { type: stdout, format: pretty, level: trace }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false
#  # support for the new v1 search endpoint, functional by incomplete read more on ticket 1732
#  search: false

# This affect the web and api (not developed yet)
#i18n:
#web: en-
```

and docker-compose.yaml:

```
version: '3.5'

services:
  verdaccio:
    build:
      context: './docker/verdaccio'
    container_name: verdaccio
    environment:
      - VERDACCIO_PORT=${VERDACCIO_PORT}
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - verdaccio-storage:/verdaccio/storage

  nginx:
    restart: always
    image: nginx
    build:
      context: './docker/nginx'
    container_name: nginx
    environment:
      - NGINX_PORT:${NGINX_PORT}
    ports:
      - $NGINX_PORT:$NGINX_PORT
      - "443:443"

volumes:
  verdaccio-storage:
```

In my opinion changing paths doesnt work properly as described in the instruction here:
https://verdaccio.org/docs/en/reverse-proxy

Please do some fix to make paths work correctly.
