### ISSUE TITLE
431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by lfire** [verdaccio/verdaccio#2059]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2528719/104882653-6179a900-599e-11eb-94a9-6ea40efc93f2.png)

![image](https://user-images.githubusercontent.com/2528719/104882713-7c4c1d80-599e-11eb-9016-f81f204f3823.png)

![image](https://user-images.githubusercontent.com/2528719/104882742-8e2dc080-599e-11eb-8710-c46481ab0f04.png)

![image](https://user-images.githubusercontent.com/2528719/104882963-e795ef80-599e-11eb-9564-858aa8220afb.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

listen: 0.0.0.0:4873

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  enable: true
  title: npm
  # logo: /mnt/software/verdaccio/logo40.svg
  primary_color: "#0893DC"
  gravatar: true
  sort_packages: asc

auth:
  gitlab:
    url: http://192.168.44.10:8088
    #htpasswd:
    #file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  taobao:
    url: https://registry.npm.taobao.org/
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    # access: $authenticated
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    #proxy: npmjs
    proxy: taobao npmjs
    gitlab: true

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    #proxy: npmjs
    proxy: taobao npmjs
    gitlab: true

# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 60

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: trace }
  #- {type: file, path: verdaccio.log, level: info}
```

**Environment information**

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:
