### ISSUE TITLE
`npm token create` doesn't work

### ISSUE THREAD

**Issue by deathgaze** [verdaccio/verdaccio#2060]
**Describe the bug**

`npm token create --registry http://localhost:4873` doesn't work.

**To Reproduce**
```bash
$ npm install -g verdaccio
$ verdaccio
# in new shell
$ npm adduser --registry http://localhost:4873
Username: ksefchik
Password:
Email: (this IS public) kirk.sefchik@someplace.com
Logged in as ksefchik on http://localhost:4873/.
$ npm token create --registry http://localhost:4873
npm password:
npm ERR! code E404
npm ERR! 404 Not Found - POST http://localhost:4873/-/npm/v1/tokens

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ksefchik/.npm/_logs/2021-01-18T21_35_16_509Z-debug.log
```

**Expected behavior**
I expect a token to be created consistent with normal NPM behavior on the official NPM registry so that it can be consumed in my CI/CD workflow.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /Users/ksefchik/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: /Users/ksefchik/.local/share/verdaccio/plugins

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # convert your UI to the dark side
  # darkMode: true

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: /Users/ksefchik/.local/share/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $all
    unpublish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false
#  # support for the new v1 search endpoint, functional by incomplete read more on ticket 1732
#  search: false

# This affect the web and api (not developed yet)
#i18n:
#web: en-US

```

**Environment information**

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    npm: 7.0.14 - ~/.nvm/versions/node/v15.3.0/bin/npm
  Virtualization:
    Docker: 20.10.2 - /usr/local/bin/docker
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 72.0.1
    Safari: 14.0.1
  npmGlobalPackages:
    verdaccio: 4.10.0
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
```
 warn --- config file  - /Users/ksefchik/.config/verdaccio/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://localhost:4873/ - verdaccio/4.10.0
(node:96230) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 http <-- 404, user: ksefchik(127.0.0.1), req: 'POST /-/npm/v1/tokens', bytes: 60/155
```
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
```
warn --- config file  - /Users/ksefchik/.config/verdaccio/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +1ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +1ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/ksefchik/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "env" to 'production' +0ms
  express:router use '/' query +1ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +0ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' errorReportingMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' compression +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/favicon.ico' +0ms
  express:router:layer new '/favicon.ico' +0ms
  express:router:route get '/favicon.ico' +0ms
  express:router:layer new '/' +0ms
 warn --- Plugin successfully loaded: verdaccio-audit
  express:router:route new '/audits' +15ms
  express:router:layer new '/audits' +1ms
  express:router:route post '/audits' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/audits/quick' +0ms
  express:router:layer new '/audits/quick' +0ms
  express:router:route post '/audits/quick' +0ms
  express:router:layer new '/' +0ms
  express:router use '/-/npm/v1/security' router +0ms
  express:router:layer new '/-/npm/v1/security' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +0ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' encodeScopePackage +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/whoami' +0ms
  express:router:layer new '/whoami' +0ms
  express:router:route get '/whoami' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/whoami' +0ms
  express:router:layer new '/-/whoami' +37ms
  express:router:route get '/-/whoami' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:version?' +0ms
  express:router:layer new '/:package/:version?' +0ms
  express:router:route get '/:package/:version?' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/:package/:version?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:scopedPackage/-/:scope/:filename' +0ms
  express:router:layer new '/:scopedPackage/-/:scope/:filename' +0ms
  express:router:route get '/:scopedPackage/-/:scope/:filename' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/:scopedPackage/-/:scope/:filename' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename' +0ms
  express:router:layer new '/:package/-/:filename' +3ms
  express:router:route get '/:package/-/:filename' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/:package/-/:filename' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/npm/v1/user' +0ms
  express:router:layer new '/-/npm/v1/user' +0ms
  express:router:route get '/-/npm/v1/user' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/npm/v1/user' +0ms
  express:router:layer new '/-/npm/v1/user' +0ms
  express:router:route post '/-/npm/v1/user' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/all(/since)?' +0ms
  express:router:layer new '/-/all(/since)?' +0ms
  express:router:route get '/-/all(/since)?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/:org_couchdb_user' +0ms
  express:router:layer new '/-/user/:org_couchdb_user' +0ms
  express:router:route get '/-/user/:org_couchdb_user' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/:org_couchdb_user/:_rev?/:revision?' +0ms
  express:router:layer new '/-/user/:org_couchdb_user/:_rev?/:revision?' +0ms
  express:router:route put '/-/user/:org_couchdb_user/:_rev?/:revision?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/token/*' +0ms
  express:router:layer new '/-/user/token/*' +0ms
  express:router:route delete '/-/user/token/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/_session' +0ms
  express:router:layer new '/_session' +0ms
  express:router:route post '/_session' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/_session' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:tag' +0ms
  express:router:layer new '/:package/:tag' +0ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route delete '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +0ms
  express:router:route get '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/-/package/:package/dist-tags' +0ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/:package/:_rev?/:revision?' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-rev/*' +0ms
  express:router:layer new '/:package/-rev/*' +0ms
  express:router:route delete '/:package/-rev/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/:package/-rev/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/:package/-/:filename/-rev/:revision' +0ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename/*' +0ms
  express:router:layer new '/:package/-/:filename/*' +0ms
  express:router:route put '/:package/-/:filename/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/-/:filename/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/-/:filename/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:version/-tag/:tag' +1ms
  express:router:layer new '/:package/:version/-tag/:tag' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/ping' +0ms
  express:router:layer new '/-/ping' +0ms
  express:router:route get '/-/ping' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/_view/starredByUser' +0ms
  express:router:layer new '/-/_view/starredByUser' +0ms
  express:router:route get '/-/_view/starredByUser' +0ms
  express:router:layer new '/' +0ms
  express:router use '/' router +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' setSecurityWebHeaders +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/static/*' +1ms
  express:router:layer new '/-/static/*' +0ms
  express:router:route get '/-/static/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/web/:section/*' +0ms
  express:router:layer new '/-/web/:section/*' +0ms
  express:router:route get '/-/web/:section/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router use '/' router +0ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' setSecurityWebHeaders +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/packages' +0ms
  express:router:layer new '/packages' +0ms
  express:router:route get '/packages' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/package/readme/(@:scope/)?:package/:version?' +0ms
  express:router:layer new '/package/readme/(@:scope/)?:package/:version?' +0ms
  express:router:route get '/package/readme/(@:scope/)?:package/:version?' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/package/readme/(@:scope/)?:package/:version?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/sidebar/(@:scope/)?:package' +0ms
  express:router:layer new '/sidebar/(@:scope/)?:package' +1ms
  express:router:route get '/sidebar/(@:scope/)?:package' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/sidebar/(@:scope/)?:package' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/search/:anything' +0ms
  express:router:layer new '/search/:anything' +0ms
  express:router:route get '/search/:anything' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/login' +0ms
  express:router:layer new '/login' +0ms
  express:router:route post '/login' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/reset_password' +0ms
  express:router:layer new '/reset_password' +0ms
  express:router:route put '/reset_password' +0ms
  express:router:layer new '/' +0ms
  express:router use '/-/verdaccio/' router +0ms
  express:router:layer new '/-/verdaccio/' +0ms
  express:router:route new '/*' +0ms
  express:router:layer new '/*' +0ms
  express:router:route get '/*' +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' final +0ms
  express:router:layer new '/' +0ms
 warn --- http address - http://localhost:4873/ - verdaccio/4.10.0
  express:router dispatching POST /-/npm/v1/tokens +9s
  express:router query  : /-/npm/v1/tokens +1ms
  express:router expressInit  : /-/npm/v1/tokens +0ms
  express:router corsMiddleware  : /-/npm/v1/tokens +0ms
  express:router <anonymous>  : /-/npm/v1/tokens +1ms
  express:router errorReportingMiddleware  : /-/npm/v1/tokens +1ms
  express:router <anonymous>  : /-/npm/v1/tokens +0ms
  express:router compression  : /-/npm/v1/tokens +0ms
  express:router router  : /-/npm/v1/tokens +0ms
  express:router dispatching POST /-/npm/v1/tokens +0ms
  express:router <anonymous>  : /-/npm/v1/tokens +0ms
(node:96247) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
  express:router jsonParser  : /-/npm/v1/tokens +11ms
  express:router <anonymous>  : /-/npm/v1/tokens +12ms
  express:router encodeScopePackage  : /-/npm/v1/tokens +0ms
  express:router router  : /-/npm/v1/tokens +1ms
  express:router dispatching POST /-/npm/v1/tokens +0ms
  express:router <anonymous>  : /-/npm/v1/tokens +0ms
  express:router setSecurityWebHeaders  : /-/npm/v1/tokens +1ms
  express:router <anonymous>  : /-/npm/v1/tokens +0ms
  express:router final  : /-/npm/v1/tokens +0ms
```
 - `$ npm -ddd` prints:
```
npm verb cli [
npm verb cli   '/Users/ksefchik/.nvm/versions/node/v15.3.0/bin/node',
npm verb cli   '/Users/ksefchik/.nvm/versions/node/v15.3.0/bin/npm',
npm verb cli   '-ddd'
npm verb cli ]
npm info using npm@7.0.14
npm info using node@v15.3.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/ksefchik/.nvm/versions/node/v15.3.0/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/Users/ksefchik/.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/Users/ksefchik/.nvm/versions/node/v15.3.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm verb npm-session 9d63cbb1737853c5
npm timing npm:load Completed in 19ms
```
 - `$ npm config get registry` prints:
```
https://registry.npmjs.org/
```
 - NPM debug log contents:
```
0 verbose cli [
0 verbose cli   '/Users/ksefchik/.nvm/versions/node/v15.3.0/bin/node',
0 verbose cli   '/Users/ksefchik/.nvm/versions/node/v15.3.0/bin/npm',
0 verbose cli   'token',
0 verbose cli   'create',
0 verbose cli   '--registry',
0 verbose cli   'http://localhost:4873'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/ksefchik/.nvm/versions/node/v15.3.0/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:project Completed in 0ms
9 timing config:load:file:/Users/ksefchik/.npmrc Completed in 1ms
10 timing config:load:user Completed in 1ms
11 timing config:load:file:/Users/ksefchik/.nvm/versions/node/v15.3.0/etc/npmrc Completed in 1ms
12 timing config:load:global Completed in 1ms
13 timing config:load:cafile Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:setUserAgent Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 7ms
18 verbose npm-session 4713fc4e73322d10
19 timing npm:load Completed in 14ms
20 info token creating
21 http fetch POST 404 http://localhost:4873/-/npm/v1/tokens 56ms
22 timing command:token Completed in 3619ms
23 verbose stack Error: 404 Not Found - POST http://localhost:4873/-/npm/v1/tokens
23 verbose stack     at /Users/ksefchik/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
23 verbose stack     at async Function.pulseWhile [as withPromise] (/Users/ksefchik/.nvm/versions/node/v15.3.0/lib/node_modules/npm/lib/utils/pulse-till-done.js:39:12)
24 verbose statusCode 404
25 verbose cwd /Users/ksefchik
26 verbose Darwin 19.6.0
27 verbose argv "/Users/ksefchik/.nvm/versions/node/v15.3.0/bin/node" "/Users/ksefchik/.nvm/versions/node/v15.3.0/bin/npm" "token" "create" "--registry" "http://localhost:4873"
28 verbose node v15.3.0
29 verbose npm  v7.0.14
30 error code E404
31 error 404 Not Found - POST http://localhost:4873/-/npm/v1/tokens
32 verbose exit 1
```
