### ISSUE TITLE
Upload packages (or bulk publish)

### ISSUE THREAD

**Issue by dogoku** [verdaccio/verdaccio#209]
Hi,

I'm trying to use verdaccio on a machine that has no internet access and will never have internet access (yay enterprise), so I need to somehow seed the packages it can serve.

E.g: I can download all the public packages from npm on my dev machine and transfer them manually (zip, tarball). Given the fact that all the information is held on disk, i assume this is possible

Is that something verdaccio supports? I couldn't find any documentation about it.

Thanks

**Comment by juanpicado** [comment]
If you download the packages in your dev machine (with internet access ) via `verdaccio`, you have to just copy and paste the storage folder to the (no internet access) machine. I'm not pretty sure how you think download your packages.

**Comment by dogoku** [comment]
Well, that's actually a separate issue I'm facing. 

verdaccio isn't able to reach npm registry, due to it not reading the ssl certificate. I went through the full config yaml and couldn't find any way of specifying a certificate file

**Comment by dogoku** [comment]
Sorry, closed by accident (fat fingers on phone). 

Because of the certificate issue, I had to remove the npmjs uplink, otherwise I can't even publish private packages

**Comment by juanpicado** [comment]
Mmmm that's weird .. I have
```
# a list of other known repositories we can talk to
uplinks:
 npmjs:
   url: https://registry.npmjs.org/
 yarn:
   url: https://registry.yarnpkg.com/
``` 
this on mine and I do not have any issue. It seems related with #187
**documentation:** I'm working to improve it or basically creating one due the current one does not help until you read the code.

**Comment by dogoku** [comment]
I didn't think of changing the npm registry url to `http` instead of `https`
That goes through since it doesn't need the certifacate, thanks for linking #187 

So, back to my original question. With the npm working via verdaccio, i can zip the `.storage` folder and upload it manually to the other machine and that should (hopefully) work.

I'll give it a go and close the issue if all goes well

**Comment by juanpicado** [comment]
Cool. Remember to copy as well the database if you host private modules, otherwise they will not found by the other verdaccio.

**Comment by Meeeeow** [comment]
@juanpicado May we should recommend save private and public package in different storage for backup?

**Comment by juanpicado** [comment]
@Meeeeow unless we change the LocalStorage there is no way, is that what you mean?.

**Comment by Meeeeow** [comment]
@juanpicado nope, just suggest new user use configure like this:
```yaml
storage: /mnt/vdc/verdaccio/cache
packages:
  '@private/*':
    #Private Package
    access: $authenticated
    publish: $authenticated
    storage: /mnt/vdc/verdaccio/packages

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
```
