### ISSUE TITLE
Is anonymous publishing allowed?

### ISSUE THREAD

**Issue by mattwwarren** [verdaccio/verdaccio#212]
#### My reason:
We recently switched to sinopia to verdaccio (had an issue with scoped packages and discovered sinopia was dead) and we were able to move to a private network server.

In an attempt to make my developers' lives easier, I thought I could set $all for access and publish in our config. But it would seem no one can publish packages at the moment.

#### Steps to reproduce:

Using the config below, attempt to publish a package.

####  App Version:	

Current docker release

####  Config file:	
```
# path to a directory with all packages
storage: /verdaccio/storage
max_body_size: 10mb

auth:

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
```
