### ISSUE TITLE
npm adduser gives 409 error

### ISSUE THREAD

**Issue by webcoderkz** [verdaccio/verdaccio#2128]
**Describe the bug**

**To Reproduce**
 - `npm adduser --registry http://myURL:4873/`

**Expected behavior**
User successfully created

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  title: Verdaccio
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $all, $anonymous
    unpublish: $all, $anonymous

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

server:
  keepAliveTimeout: 60

listen: 0.0.0.0:4873

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}


```

**Environment information**

```
Environment Info:

  System:
    OS: Windows Server 2016 10.0.14393
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111

```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 ```
$ NODE_DEBUG=request ./node_modules/verdaccio/bin/verdaccio
 warn --- config file  - C:\work\rnkb\verdaccio\config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.11.3
```
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 ```
$ DEBUG=express ./node_modules/verdaccio/bin/verdaccio
 warn --- config file  - C:\work\rnkb\verdaccio\config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.11.3
```
 - `$ npm config get registry` prints: http://myURL:4873/
