### ISSUE TITLE
Port cannot be overridden via configuration file in Docker

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#213]
#### My reason:

The Docker file define the port is defined in the Dockerfile but is not possible to override via configuration file.
```docker
CMD ["/usr/src/app/bin/verdaccio", "--config", "/verdaccio/conf/config.yaml", "--listen", "0.0.0.0:4873"]
````
The following is ignored by `verdaccio`

#### Steps to reproduce:

(Ensure docker daemon is running)

1. Create folder and custom configuration file with a listener different than 4873.
2. Run
```bash
docker run -it --rm --name verdaccio -p 4873:4873 -v /Users/user/docker/conf:/verdaccio/conf verdaccio/verdaccio
````

####  App Version:	
v2.2.0 (Docker latest)

####  Config file:	

```yaml
# path to a directory with all packages
storage: /verdaccio/storage
max_body_size: 10mb

auth:

listen:
  - localhost:5557
# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
````

#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 - Container:
   - [X] I use local environment
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS.

#### Additional verbose log:

````bash
Unable to find image 'verdaccio/verdaccio:latest' locally
latest: Pulling from verdaccio/verdaccio
8b87079b7a06: Pull complete 
a3ed95caeb02: Pull complete 
1bb8eaf3d643: Pull complete 
3e04171ce2e5: Pull complete 
0b73d3fea769: Pull complete 
639c270113c9: Pull complete 
c9ca6f8bff52: Pull complete 
aebed29b5cd3: Pull complete 
0b5607284d1c: Pull complete 
cfc776838425: Pull complete 
5bb1a117acb0: Pull complete 
414afe27bd58: Pull complete 
b2356dfcf8b4: Pull complete 
Digest: sha256:ea5828ffc93f73a6617eb39acecbc3aff03cad0a50ffdb293848fd63de37c152
Status: Downloaded newer image for verdaccio/verdaccio:latest
Verdaccio doesn't need superuser privileges. Don't run it under root.
 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/2.2.0
````
