### ISSUE TITLE
unpublish is broken with public packages

### ISSUE THREAD

**Issue by Temtaime** [verdaccio/verdaccio#2184]
**Describe the bug**
Verdaccio fails to unpublish a custom version of a package that is available on public registry

Seems to be bound to #1435
Not working on 5.0.1 nor 4.x versions

I assure that the tgz is here and is not removed by verdaccio, but the version is removed from the metadata. So if i cannot publish same version after this bug occuring because of #1964
Also version 20.2.5-build-20349-0313 is not present in the public registry

**To Reproduce**
Push your own version of some package that is available on registry.npmjs.org
Try to unpublish it

**Actual behavior**
$ npm unpublish PUBLIC_PACKAGE@20.2.5-build-20349-0313 --registry http://127.0.0.1:4800
npm ERR! code E404
npm ERR! 404 Not Found - DELETE http://127.0.0.1:4800/PUBLIC_PACKAGE/-/PUBLIC_PACKAGE-20.2.5-build-20349-0313.tgz/-rev/915-10c9ad10d0a03e9a - no such file available
npm ERR! 404
npm ERR! 404  'PUBLIC_PACKAGE@20.2.5-build-20349-0313' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Expected behavior**
Package is unpublished

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
    maxage: 20m
packages:
  '**':
    access: $all
    publish: $all
    proxy: npmjs
max_body_size: 500mb
middlewares:
  audit:
    enabled: true
logs: { type: stdout, level: trace }
i18n:
  web: en-US
```

**Environment information**
Environment Info:
  System:
    OS: Windows 10 10.0.18363
    CPU: (6) ia32 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    npm: 6.14.4 - F:\nn\app\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.18362.449.0)

**Debugging output**
[2021-04-11T15_46_56_926Z-debug.log](https://github.com/verdaccio/verdaccio/files/6292174/2021-04-11T15_46_56_926Z-debug.log)
[verdaccio.log](https://github.com/verdaccio/verdaccio/files/6292176/verdaccio.log)
