### ISSUE TITLE
Verdaccio not working as expected after path mapping in a GCE Ingress controller

### ISSUE THREAD

**Issue by RossVertizan** [verdaccio/verdaccio#2234]
**Describe the bug**

At the outset, let me state that I don't claim to be an expert in Verdaccio, Google Kubernetes Engine or Kubernetes.  However, I have spent significant time working through the available resources and I still don't see what I expect.

I am trying to setup Verdaccio to run in my GKE cluster for use by remote colleagues.  I already have my main app running there, so I want to map a path to the Verdaccio port number.  I have done this using the GKE Ingress controller.  This is the (slightly modified) YAML:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ip-address"
    networking.gke.io/managed-certificates: "certificate"
    networking.gke.io/v1beta1.FrontendConfig: "ingress-security-config"
spec:
 rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: my_service
              servicePort: 5000
          - path: /verdaccio/*
            backend:
              serviceName: verdaccio-service
              servicePort: 4873
```
I have taken the configuration for the ConfigMap, Deployment, PVC and Service from [here](https://github.com/papezt/verdaccio-examples).

What I expect to see is that when I go to https://my.domain.com/verdaccio/ that I will see the Verdaccio WebUI.  This situation is covered in the [reverse proxy setup](https://verdaccio.org/docs/en/reverse-proxy).

In the configmap I am specifying url_prefix:
```yaml
url_prefix: /verdaccio/
```
and in the deployment I am setting the VERDACCIO_PUBLIC_URL:
```yaml
 env:
    - name: VERDACCIO_PUBLIC_URL
      value: "https://my.domain.com"
```
 I have not done any of the header manipulation mentioned in the [reverse proxy setup](https://verdaccio.org/docs/en/reverse-proxy).  Partly because I don't know how to and partly because this only seems to be necessary to change the path to static assets.

With this configuration, I expect to see the Verdaccio Web UI when I go to https://my.domain.com/verdaccio/, but what I see is JSON and when I look in the logs I can see that a GET request is being made to the npmjs registry and the JSON relates to the return value from that GET request.  If I try and publish to the url, again I see that a GET request goes to npmjs.

If I switch Verdaccio to be mapped to the root of my domain (i.e. switch it with my app), then it works as expected, I can login and publish to the service.  It is as soon as I change that mapping back that I get this result.  I have tried with Verdaccio Docker images for version 5.0.4 and also 4.12, so  I think this is not a V5 only issue.  I have looked at #2190, but I am not certain that this is the same issue.

**To Reproduce**
On a GKE cluster create a ConfigMap, Deployment, PVC and Service using the examples [here](https://github.com/papezt/verdaccio-examples).  

Configure the ingress controller as shown above to map the Verdaccio port to the path /verdaccio/*

Set the url_prefix in the ConfigMap and the VERDACCIO_PUBLIC_URL in the Deployment as shown above.

**Expected behavior**

Expect to see the Verdaccio WebUI at the path https://my.domain.com/verdaccio/

**Screenshots**

Not applicable

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

This is the YAML for the ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio
  labels:
    app: verdaccio
data:
  config.yaml: |-
    #
    # This is the config file used for the docker images.
    # It allows all users to do anything, so don't use it on production systems.
    #
    # Do not configure host and port under `listen` in this file
    # as it will be ignored when using docker.
    # see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
    #
    # Look here for more config file examples:
    # https://github.com/verdaccio/verdaccio/tree/master/conf
    #
    # path to a directory with all packages
    storage: /verdaccio/storage
    # path to a directory with plugins to include
    plugins: /verdaccio/plugins
    web:
      # WebUI is enabled as default, if you want disable it, just uncomment this line
      enable: true
      title: Verdaccio
    url_prefix: /verdaccio/
    auth:
      htpasswd:
        file: /verdaccio/conf/htpasswd
        # Maximum amount of users allowed to register, defaults to "+infinity".
        # You can set this to -1 to disable registration.
        max_users: -1
    # a list of other known repositories we can talk to
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    packages:
      '@*/*':
        # scoped packages
        access: $all
        publish: $authenticated
        proxy: npmjs
      '**':
        # allow all users (including non-authenticated users) to read and
        # publish all packages
        #
        # you can specify usernames/groupnames (depending on your auth plugin)
        # and three keywords: "$all", "$anonymous", "$authenticated"
        access: $all
        # allow all known users to publish packages
        # (anyone can register by default, remember?)
        publish: $authenticated
        # if package is not available locally, proxy requests to 'npmjs' registry
        proxy: npmjs
    # To use `npm audit` uncomment the following section
    middlewares:
      audit:
        enabled: false
    # log settings
    logs:
      - {type: stdout, format: pretty, level: http}
      #- {type: file, path: verdaccio.log, level: info}
  htpasswd: |-
    x1:###
    x2:###
```

**Environment information**
```env
VERDACCIO_PUBLIC_URL: "https://my.domain.com"
```

**Comment by juanpicado** [comment]
Thaks for such detailed ticket. It seems might be #https://github.com/verdaccio/verdaccio/issues/2190 , let's see when is fixed we you can very if works as expected, I recall GC seems to requires lower case https://cloud.google.com/storage/docs/xml-api/reference-headers headers, we will see. 

:) I'm not an expect in either of those technilogies,  just assuming at this point.

**Comment by juanpicado** [comment]
@RossVertizan there is a solution here https://github.com/verdaccio/verdaccio/issues/2190 you can give a try.

**Comment by RossVertizan** [comment]
@juanpicado I have tried to get the ```jota-fix-2190``` tag of the Docker container working in my Kubernetes cluster, for it to work behind the Ingress controller the container needs to have a liveness and a readiness probe which are defined as part of the "deployment", in the example that I followed, the [deployment](https://github.com/papezt/verdaccio-examples/blob/master/kubernetes-pvc-htpasswd/deployment.yaml) defines these with a path of ```/-/ping```.  The liveness probe is there so that the Ingress controller knows that the backend (the running instance of the deployment - the pod) is alive and the readiness probe so that it knows that it is available to take requests (i.e. ready).  For the probes to be successful they must return an http 200 to the defined request, but I am not seeing that.  Consequently, I am failing to get the pod to start correctly, it keeps restarting, meaning I can't check the fix.

If I run up a Docker image on my local machine and go to ```http://localhost:4873/-/ping``` I see a 304 and then a 403:
```shell
 http --- 172.17.0.1 requested 'GET /-/ping'
 http --- 304, user: null(172.17.0.1), req: 'GET /-/ping', bytes: 0/0
 http --- 172.17.0.1 requested 'GET /favicon.ico'
 http --- 403, user: null(172.17.0.1), req: 'GET /favicon.ico', error: invalid package
```
Do you recognise the /-/ping that was being used previously as the endpoint for the liveness/readiness checks?  Is there an endpoint that I can use as a health check that will simply reply with e.g. "I'm alive"?

If I go to ```http://localhost:4873/ping```, I see:
```shell
 http --- 172.17.0.1 requested 'GET /ping'
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for ping
 info --- making request: 'GET https://registry.npmjs.org/ping'
 http --- 200, req: 'GET https://registry.npmjs.org/ping' (streaming)
 http --- 200, req: 'GET https://registry.npmjs.org/ping', bytes: 0/35368
 http --- 200, user: null(172.17.0.1), req: 'GET /ping', bytes: 0/8584
 http --- 172.17.0.1 requested 'GET /favicon.ico'
 http --- 403, user: null(172.17.0.1), req: 'GET /favicon.ico', error: invalid package
```
In each case, the last received message is a 403, which may be causing the problem.  However, as can be seen above, when I go to  ```http://localhost:4873/ping```, it makes a request to npmjs and gets details of the ping package, it seems therefore that there is an endpoint of the form ```http://<verdaccio_server>/<packagename>```.

So, what I was seeing was this behaviour.  I am using the GCE Ingress controller (and my understanding has improved since first posting this issue).  When I map to Verdaccio using ```/verdaccio``` in the path (as described originally), that gets passed through to the server unmodified, so the server sees a request to ```http://<mydomain>/verdaccio/```, and the ```verdaccio``` section is being interpreted as the name of the package to go and get details for.

My understanding from [here](https://verdaccio.org/docs/en/reverse-proxy#sub-directory), was that setting the URL prefix was the way to tell Verdaccio to ignore that part of the URL, though now that I look at it again, this would strictly be a URL suffix.  Have I misunderstood the use of the URL prefix, if not, is there any possibility it is not working?

Sorry for the long post, I hope this makes sense to you.  I'd love to get this working.

**Comment by juanpicado** [comment]
> In each case, the last received message is a 403, which may be causing the problem. However, as can be seen above, when I go to http://localhost:4873/ping, it makes a request to npmjs and gets details of the ping package, it seems therefore that there is an endpoint of the form http://<verdaccio_server>/<packagename>.


About the `http --- 403, user: null(172.17.0.1), req: 'GET /favicon.ico', error: invalid package` I'll look into that, I've also noticed and should be fixable.

> http://localhost:4873/ping

If you hit on ping, you are hitting a package named ping, instead `https://registry.verdaccio.org/-/ping` `/-/ping`.

> My understanding from here, was that setting the URL prefix was the way to tell Verdaccio to ignore that part of the URL,

It is just the opposite, if you are using `url_prefix` is because you are willing to use a sub directory.

**Comment by RossVertizan** [comment]
Thanks for these comments.  Sorry to be thick but could you expand on the use of url_prefix?  

My understanding was that if I define url_prefix then the Verdaccio "root" would be found at ```http://<verdaccio_server>/<url_prefix>```, essentially meaning that Verdaccio is in a sub-directory and in order to hit the package query end point I would then need to do ```http://<verdaccio_server>/<url_prefix>/<packagename>```, meaning that when I map through the ingress controller to a different path that the url_prefix path would effectively be ignored in terms of the operation of Verdaccio.  Maybe rather convoluted thinking, but that was my understanding.

**Comment by juanpicado** [comment]
> My understanding was that if I define url_prefix then the Verdaccio "root" would be found at http://<verdaccio_server>/<url_prefix>, essentially meaning that Verdaccio is in a sub-directory and in order to hit the package query end point I would then need to do http://<verdaccio_server>/<url_prefix>/<packagename>,

As you describes, your thinking is correct at this point. The `url_prefix` affects fundamentally a way to override the path other than root. I'd omit examples since I'd guess you understand the usage of the property. This property is only useful if you do reverse proxy in your side and only affect the UI and the metadata is being returned on fetch a package json, but does not affect the server itself (https://github.com/verdaccio/verdaccio/pull/963).
Here more details https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#url_prefix-improved-behavior

> I map through the ingress controller to a different path that the url_prefix path would effectively be ignored in terms of the operation of Verdaccio.

This is the part I get lost, my understanding of Kubernetes still is a basic level, so I'm afraid I'm not much helpful here.

Anyhow, here I can share https://github.com/verdaccio/charts/issues/63 and https://github.com/verdaccio/charts/issues/62  where the community discuss topics related K8s and Helm, I guess they might help you faster than me.

**Comment by RossVertizan** [comment]
Thank you, you have confirmed my understanding.  Don't worry about the Ingress stuff, I think this is just a strange way I thought about it.  I have an Ingress controller that has three different services hanging off it. All traffic comes in on port 443 (https) and traffic that matches a path of ```/verdaccio/*``` in the url gets mapped to port 4873, and in my case traffic that comes in and matches a path of  ```/sio/*``` gets mapped to port 8083 (just another service you don't need to know about, but to give the full example) and anything else gets mapped to port 5000.  Each of these ports have separate http end points, and using the path as a way of identifying what should go where seems to be the common way of doing it (I'm not aware of other approaches).  With the Google Cloud Ingress Controller, the end point receives the full URL, hence the need to be able to tell the app that the URL will look a little different than normal.  With Nginx (an alternate Ingress solution), there are options that allow the url_prefix part to be removed so that the app just sees the base URL (domain name).

So, what I see is that the url_prefix does not appear to be being honoured, in that if I have a url_prefix of ```/verdaccio/```, I get details about the Verdaccio package.

If the favicon.ico fix is possible, I'll take a look at it again, when I can get the deployment to start.

Thanks for your quick answers.

**Comment by RossVertizan** [comment]
@juanpicado I just want to give you an update on where I am with this.

Firstly, just let me re-cap, because my understanding has continued to improve.  I am setting up a Kubernetes cluster with a single GCE (not Nginx) ingress controller that controls access to multiple backend services.  So to use the example that I gave in the first post, if I have two services, ```my_service``` and ```verdaccio_service```, and my domain is ```https://my.domain.com```.  Then the approach that I have been taking is to select the backend service based on the URL path.  In the example I gave, any query which matches ```https://my.domain.com/verdaccio/``` gets routed to the Verdaccio service, and everything else (that matches just ```https://my.domain.com/``` gets routed to ```my_service```.  So, this means that when I want to access just the root of Verdaccio (i.e. the ```route.get("/", ...)``` endpoint, I have to put in the URL ```https://my.domain.com/verdaccio/```, unfortunately, Verdaccio then interprets this as the ```route.get('/:package/:version?'```  endpoint (in package.js) and then shows me the details for the Verdaccio package.  

Unfortunately, the url_prefix option does not help me out with this as previously discussed.  This is only a problem with the GCE Ingress controller because in Nginx it is possible to "rewrite" the Url that is passed to the service so that Verdaccio would see a "rewritten" URL of  ```https://my.domain.com/```.  Amazingly, the GCE Ingress controller still does not have this capability despite there being an [issue](https://github.com/kubernetes/ingress-gce/issues/109) open for a long time.  The problem I have described here is also exactly the same as the issue raised in #963.  I am sorry I didn't read that issue more when you referenced it previously.  I have looked at porting that change to the latest version  (#963 was built on v3), but I came unstuck for two reasons:
1. I couldn't see how to inject the config file into the development environment
2. I started to wonder if there was any difference between ```url_prefix``` and ```base_path``` implemented in the PR from #963.  I think I started wondering what ```url_prefix``` does for us.

But, I have come up with a different solution that works and I have running, and it's one of those things that I'm embarrassed that I didn't think of it sooner.  Rather than selecting the backend service based on the URL path, I am selecting it by the domain name.  So, I have simply modified the DNS records for my domain and created a new sub-domain.  For the sake of the continuity of the example let's call it ```pkgs.my.domain.com``` and now I have an ingress file that looks like this:
```yaml
rules:
    - host: my.domain.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: my_service
              servicePort: 5000
    - host: pkgs.my.domain.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: verdaccio-service
              servicePort: 4873
```

With this scheme, the path of the URL has not changed and Verdaccio works as expected.

This is a scheme which I believe should be generally possible and hopefully will help others who read this issue.

So, you can decide what you would like to do with this.  I am happy for you to close this issue with the above as a workaround solution, but maybe it is worth clarifying the purpose of the ```url_prefix``` which is not clear to me now.  I am happy to help out with a resolution.

I will change the title to make this issue easier for others to find.
