### ISSUE TITLE
Restrict access to specific package version via config.yaml

### ISSUE THREAD

**Issue by radubrehar** [verdaccio/verdaccio#226]
`config.yaml` gives quite granular access to packages, so I can specify which packages can be accessed by which people, which is really great. So i have something like:

```yaml
packages:
   '@scope/pkg':
      access: user1, user2
```

**My question is**: can I further control the users that have access to specific package versions (or package version ranges)?

Something like:

```yaml
packages:
   '@scope/pkg@1.0.1':
      access: user1
   '@scope/pkg@1.0.0':
      access: user1, user2
```

I've tried this, but doesn't seem to be working.
