### ISSUE TITLE
Verdaccio 5.1.0 hosted on IIS not working over https anymore

### ISSUE THREAD

**Issue by pavelbednar** [verdaccio/verdaccio#2311]
**Describe the bug**
After upgrade from verdaccio 4.x.x to 5.1.0 webpage hosted on IIS is not showing packages. It work when approaching over HTTP. But if user goes to HTTPS version verdaccio shows empty repository with information how to add packages.

When verdaccio is served on `https://npm.company.org` it tries to access its api via HTTP request. I.E. `http://npm.company.org/-/verdaccio/packages`. The request is stopped beause CSP no mixed content is allowed and no data is returned. 
In same configuration in 4.x.x it worked beause it sent api request via HTTPS. Configuration is same, only `npm install verdaccio@5.1.0` was called to upgrade.

**To Reproduce**
[1] Configure app as in documentation (https://verdaccio.org/docs/en/iss-server
[2] In IIS Manager create New site for npm repo with http binding to port 80 and htts binding to port 443
[3] start the application

**Expected behavior**
When oppening page over HTTPS protocol it should do HTTPS request to verdaccio API

**Screenshots**

**config.yaml**
```yaml
storage: ./storage
plugins: ./plugins
url_prefix: /


auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
    cache_path: ./cache
```
**start.js**
```js
process.argv.push('-l', 'unix:' + process.env.PORT, '-c', './config.yaml'); 
require('./node_modules/verdaccio/build/lib/cli.js');
```

**Environment information**
Tested on Windows Server with latest IIS, also in latest updated Win10 with local IIS.
Tested in latest Chrome. Firefox has same CSP problem but it allows request to continue, thus Firefox shows packages even on HTTPS but it has same as chrome in console.

I tried to adjust IIS CSP header, upgrade insecure request and allow connect-src and script-src to HTTP but it didnt help.
