### ISSUE TITLE
npm audit fails with 500 server error on nightly build

### ISSUE THREAD

**Issue by simon-lorenz** [verdaccio/verdaccio#2335]
**Your Environment**
  
 * **verdaccio version**: `v6.0.0-6-next.17`
 * **node version**: `14.17.2` & `16.3.0` locally, `14.16.1` inside of the container
 * **package manager**: `npm@6` & `npm@7`
 * **os**: linux
 * **platform**: docker (`nightly-master@f48b67b2111e`)

**Describe the bug**

`npm audit` fails with `500 Internal Server Error`.

npm `7.19.1` & node `16.3.0`:

![image](https://user-images.githubusercontent.com/34041551/125994761-33742d2a-181e-4889-a1e1-4af332f9289f.png)

npm `6.14.13 & node `14.17.2`:

![image](https://user-images.githubusercontent.com/34041551/125994782-e388f36b-1657-4dd3-aa1c-09915cd4ce36.png)

Container logs:

![image](https://user-images.githubusercontent.com/34041551/125994932-1bed71bb-95da-454d-91df-600875641050.png)

**To Reproduce**

```bash
docker run --rm -p 4873:4873 --name verdaccio -d verdaccio/verdaccio:nightly-master@sha256:f48b67b2111e90eacb030c40d89e677e3aab60ce807b041aa8cf1f39af39d0bb
mkdir verdaccio-audit-test
cd verdaccio-audit-test
npm init -y
echo 'registry=http://localhost:4873' >> .npmrc
npm install lodash
npm audit
``` 

**Expected behavior**

`npm audit` should work.

**Screenshots, server logs, package manager log**

See above.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

Default docker image configuration.

**Environment information**

```text
Environment Info:
  System:
    OS: Linux 5.8 Alpine Linux undefined
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
  Binaries:
    npm: 6.14.12 - /usr/local/bin/npm
```

**Debugging output**

See logs above (I couldn't get the extensive logging output to work, sorry).

- `$ npm config get registry` prints: http://localhost:4873/

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by DanielRuf** [comment]
> Default docker image configuration.

Not sure about that, can you share the current verdaccio config?
It should contain a setting for `audit` and should be set to `true`.

**Comment by DanielRuf** [comment]
See also https://verdaccio.org/docs/fr-fr/configuration#audit

**Comment by DanielRuf** [comment]
See also https://verdaccio.org/docs/en/configuration#audit

**Comment by simon-lorenz** [comment]
> > Default docker image configuration.
> 
> Not sure about that, can you share the current verdaccio config?
> It should contain a setting for `audit` and should be set to `true`.

Sure, here's the complete file (audit seems to be enabled):

<details>
  <summary>config.yaml</summary>
  
```yaml
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # darkMode: true

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

middlewares:
  audit:
    enabled: true

# log settings
# log settings
logs:
  # Logger as STDOUT
  { type: stdout, format: pretty, level: http }
  # Logger as STDOUT as JSON
  # { type: stdout, format: json, level: http }
  # Logger as STDOUT as JSON
  # { type: stdout, format: pretty-timestamped, level: http }
  # Logger as STDOUT as custom prettifier
  # { type: stdout, plugin: { dest: '@verdaccio/logger-prettify' : options: { foo: 1, bar: 2}}, level: http }
  # Logger as file
  # { type: file, path: verdaccio.log, level: http}
  # FIXME: this should be documented
# More info about log rotation https://github.com/pinojs/pino/blob/master/docs/help.md#log-rotation

flags:
  # support for npm token command
  token: false
  # support for the new v1 search endpoint, functional by incomplete read more on ticket 1732
  search: false
# This affect the web and api (not developed yet)
#i18n:
#web: en-US
```
</details>

**Comment by DanielRuf** [comment]
> ```yaml
> plugins: /verdaccio/plugins
> ```

Does the folder include plugins like `audit`?
Not sure if there are parts missing in the nightly build like the audit plugin or if this is currently broken.

**Comment by juanpicado** [comment]
Since I was already debugging (other different topic) I just quick look. We are not logging the error and fails due DNS or stuff like that, not sure why, because verdaccio 5 works fine.
```
info <-- 127.0.0.1 requested 'POST /-/npm/v1/security/audits/quick'
--> FetchError: request to https://registry.npmjs.org/-/npm/v1/security/audits failed, reason: Hostname/IP does not match certificate's altnames: Host: https. is not in the cert's altnames: DNS:ssl1044720.cloudflaressl.com, DNS:*.npmjs.org, DNS:npmjs.org
    at ClientRequest.<anonymous> (/xxxxx/verdaccio/node_modules/.pnpm/node-fetch@2.6.1/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ERR_TLS_CERT_ALTNAME_INVALID',
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
 http <-- 500, user: null(127.0.0.1), req: 'POST /-/npm/v1/security/audits/quick', bytes: 295/0
````

**Comment by juanpicado** [comment]
Ah, I remember, we replaced `request` #1976  with `node-fetch` some time ago.

**Comment by simon-lorenz** [comment]
> > ```yaml
> > plugins: /verdaccio/plugins
> > ```
> 
> Does the folder include plugins like `audit`?
> Not sure if there are parts missing in the nightly build like the audit plugin or if this is currently broken.

Hmm, this directory is indeed empty. But this is also the case for `verdaccio:4` and `verdaccio:5`:

![image](https://user-images.githubusercontent.com/34041551/126001059-2a0e01e7-311d-4d5e-85c9-c27144f4dfd2.png)

**Comment by DanielRuf** [comment]
> > 
> 
> Hmm, this directory is indeed empty. But this is also the case for `verdaccio:4` and `verdaccio:5`:

That's probably fine, the audit plugin is now integrated, I forgot that.

@juanpicado has probably found the issue which may be caused by the change of the mentioned library.

**Comment by simon-lorenz** [comment]
> 'ERR_TLS_CERT_ALTNAME_INVALID',

> Ah, I remember, we replaced ( as effort for #1807 ) request #1976 with node-fetch some time ago. Should be easy to fix, just look into node-fetch docs I guess.

So if I understand correctly, `node-fetch` is more strict with ssl certificates than `request` and thus the request fails? I tried changing the configuration from 

```yaml
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

[...]

middlewares:
  audit:
    enabled: true
```

to

```yaml
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    strict_ssl: false

[...]

middlewares:
  audit:
    enabled: true
    strict_ssl: false
```

but this didn't work. Neither did changing `https://registry.npmjs.org/` to `http://registry.npmjs.org/`.
