### ISSUE TITLE
dist.tarball points to http instead of https

### ISSUE THREAD

**Issue by radubrehar** [verdaccio/verdaccio#234]
#### My reason:

Although using the registry with SSL, in the package.json that describes all the versions of a package (in the storage directory) I still get dist.tarball pointing to http instead of https
```json
 "dist": {
    "shasum": "4d2c8bcc24c92531270815b8be372ab0ea104e3c",
    "tarball": "http://registry.xxxx.io/@scope/package-name/-/@scope/package-name-0.2.5.tgz"
}
```

Also see https://github.com/npm/npm/issues/11471 and http://blog.npmjs.org/post/142077474335/npm-registry-is-now-fully-https
 which might be related

I'm serving the verdaccio registry through a nginx SSL proxy.

Any pointers?

**Comment by juanpicado** [comment]
@radubrehar it would be helpful
*  your configuration
and perhaps more questions based on that

**Comment by Meeeeow** [comment]
Hello, I can't reproduce this issue, could your provide your nginx config and verdaccio config?

**Comment by radubrehar** [comment]
My config.yaml is:

```yaml
storage: ./storage

web:
  enable: false

https:

listen: 127.0.0.1:4873
auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 6

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:

  '@private/private':
    access: admin user
    publish: admin

# log settings
logs:
  - {type: file, path: ./logs/http.log, format: json, level: http}
  - {type: file, path: ./logs/info.log, format: json, level: info}
```

My nginx relevant portion:

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	# SSL configuration
	server_name registry.xxxx.io;

	location / {
          proxy_pass http://127.0.0.1:4873/;
          proxy_set_header Host $host:$server_port;
          proxy_read_timeout 90;
          proxy_set_header X-Forwarded-For $remote_addr;
	}

    listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/registry.xxxx.io/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/registry.xxxx.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot


    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

}
```
