### ISSUE TITLE
Wrong volume spec in docker-compose.yml

### ISSUE THREAD

**Issue by OnkelTem** [verdaccio/verdaccio#2342]
Here:
https://github.com/verdaccio/verdaccio/blob/26873682b84f08f0fd73702ee7dbb082b0eea67e/docker-compose.yaml#L11

```
version: '2.1'
services:
  verdaccio:
    build: .
    container_name: verdaccio
    environment:
      - VERDACCIO_PORT
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - verdaccio-storage:/verdaccio/storage
volumes:
  verdaccio:
    driver: local
```

the volume is declared as `verdaccio`, while in the `services` section it's called `verdaccio-storage`.
