### ISSUE TITLE
Getting "error: bad uplink status code: 401" with GitHub packages.

### ISSUE THREAD

**Issue by Uruael** [verdaccio/verdaccio#2438]
**Your Environment**
  
 * **verdaccio version**: 5.1.4
 * **node version** [12.x.x, 14.x.x]: 14.17.5
 * **package manager**: [npm@7, pnpm@6, yarn@2] yarn@1.2
 * **os**: [mac, windows@10, linux] linux
 * **platform**: [npm, docker, helm, other] docker

**Describe the bug**

Hi! As a team we're publishing development packages on gitlab and release packages on github. Using Verdaccio to access packages under the same scope from github and gitlab, it succesfully gets the gitlab package but can't get the github package (error: bad uplink status code: 401). Packages on GitHub are versioned differently from those published on GitLab. In logs below we're trying to get release version of artifact-backend-api (GitHub) and backend-api (GitLab).

**To Reproduce**

We've set up Verdaccio in docker to use it as service on our server in the future (this config is running locally to test Verdaccio). After that we are running `npm ci` with `.npmrc` pointing to `@org-io:registry=http://localhost:4873`.

docker-compose.yaml: 
```
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:      
      - "./storage:/verdaccio/storage"     
      - "./config:/verdaccio/conf"      
      - "./plugins/node_modules:/verdaccio/plugins"  
networks:
  node-network:
    driver: bridge

```

**Expected behavior**

Successfully get both npm packages

**Screenshots, server logs, package manager log**
Logs from docker:

```
info --- making request: 'GET https://npm.pkg.github.com/org-io/@org-io%2Forg-back-end-api'
verdaccio    |  info --- making request: 'GET https://gitlab.example.com/api/v4/projects/31/packages/npm/@org-io%2Forg-back-end-api'
verdaccio    |  http --- 200, req: 'GET https://gitlab.example.com/api/v4/projects/31/packages/npm/@org-io%2Forg-back-end-api' (streaming)
verdaccio    |  http --- 200, req: 'GET https://gitlab.example.com/api/v4/projects/31/packages/npm/@org-io%2Forg-back-end-api', bytes: 0/524
verdaccio    |  http --- 200, req: 'GET https://npm.pkg.github.com/org-io/@org-io%2Forg-back-end-api' (streaming)
verdaccio    |  http --- 200, req: 'GET https://npm.pkg.github.com/org-io/@org-io%2Forg-back-end-api', bytes: 0/6416
verdaccio    |  http --- 200, user: null(192.168.160.1), req: 'GET /@org-io%2forg-back-end-api', bytes: 0/2051
verdaccio    |  http --- 192.168.160.1 requested 'GET /@org-io%2forg-artifact-backend-api/-/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
verdaccio    |  info --- auth/allow_action: access granted to: undefined
verdaccio    |  info --- allowed access for @org-io/org-artifact-backend-api
verdaccio    |  info --- making request: 'GET https://npm.pkg.github.com/download/@org-io/org-artifact-backend-api/2.0.0/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
verdaccio    |  http --- 500, user: null(192.168.160.1), req: 'GET /@org-io%2forg-artifact-backend-api/-/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', error: bad uplink status code: 401
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: /verdaccio/storage

uplinks:
  github:
    url: https://npm.pkg.github.com/
    cache: false
    auth:      
      type: bearer      
      token: "xxxxx"
  gitlab:
    url: https://gitlab.example.com/api/v4/projects/X/packages/npm/
    auth:      
      type: bearer      
      token: "xxxxx"
  npmjs:
    url: https://registry.npmjs.org/ 

packages:
  '@org-io/*':
    access: $all
    publish: $all
    proxy: gitlab github
  '**':
    access: $all
    publish: $all
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: trace}
```

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Does the same token works with a normal curl ? At the end is just a get request.

**Comment by Uruael** [comment]
Sending the request using curl with the same token works. I did manage to download the tgz.

It seems that is not only the problem with accessing github packages. I swapped `github` and `gitlab` uplinks:
```
uplinks:
  gitlab:
    url: https://gitlab.example.com/api/v4/projects/X/packages/npm/
    auth:      
      type: bearer      
      token: "xxxxx"
  github:
    url: https://npm.pkg.github.com/
    auth:      
      type: bearer      
      token: "xxxxx"
  npmjs:
    url: https://registry.npmjs.org/ 
```

And there is the same problem, but with gitlab this time:
```
verdaccio    |  info --- making request: 'GET https://npm.pkg.github.com/@org-io%2Forg-back-end-api'
verdaccio    |  http --- 200, req: 'GET https://npm.pkg.github.com/@org-io%2Forg-back-end-api' (streaming)
verdaccio    |  http --- 200, req: 'GET https://npm.pkg.github.com/@org-io%2Forg-back-end-api', bytes: 0/6416
verdaccio    |  http --- 200, req: 'GET https://gitlab.example.com/api/v4/projects/31/packages/npm/@org-io%2Forg-back-end-api' (streaming)
verdaccio    |  http --- 200, req: 'GET https://gitlab.example.com/api/v4/projects/31/packages/npm/@org-io%2Forg-back-end-api', bytes: 0/524
verdaccio    |  http --- 200, user: null(172.18.0.1), req: 'GET /@org-io%2forg-back-end-api', bytes: 0/2043
verdaccio    |  http --- 172.18.0.1 requested 'GET /@org-io%2forg-artifact-backend-api/-/org-artifact-backend-api-2.0.0-PR.11.1111111.tgz'
verdaccio    |  info --- auth/allow_action: access granted to: undefined
verdaccio    |  info --- allowed access for @org-io/org-artifact-backend-api
verdaccio    |  info --- making request: 'GET https://gitlab.example.com/api/v4/projects/31/packages/npm/@org-io/org-artifact-backend-api/-/@org-io/org-artifact-backend-api-2.0.0-PR.11.1111111.tgz'
verdaccio    |  http --- 500, user: null(172.18.0.1), req: 'GET /@org-io%2forg-artifact-backend-api/-/org-artifact-backend-api-2.0.0-PR.11.1111111.tgz', error: bad uplink status code: 401
```

**Comment by juanpicado** [comment]
I will take a closer look to this over the week. It did work for me in several demos, but let's see.

**Comment by pt228t** [comment]
I have been facing a similar issue while accessing the github packages. Has there been a resolution yet for this?

**Comment by sambernet** [comment]
We seem to be also currently affected by this, when accessing an external but authenticated uplink registry (https://npm.fontawesome.com). I have hit this with the current 5.26.2 version.

The uplink is configured as:

```
uplinks:
    fontawesome:
        url: https://npm.fontawesome.com
        auth:
            type: bearer
            token: 'xyz'
```

A direct request works fine when done in curl with the very same token used, for example like this:

```
curl -vvv -H "Authorization: Bearer xyz" https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/6.2.1/fontawesome-pro-6.2.1.tgz
```
