### ISSUE TITLE
WebUI packages disappeared after restarting the server

### ISSUE THREAD

**Issue by mopinon** [verdaccio/verdaccio#2458]
### Discussed in https://github.com/verdaccio/verdaccio/discussions/2441

<div type='discussions-op-text'>

<sup>Originally posted by **mopinon** September 17, 2021</sup>

**Your Environment**
  
 * **verdaccio version**: 5.1.4
 * **node version** 14.17.6
 * **package manager**: npm@6.14.15
 * **os**: clients: [mac, win10], server: ubuntu
 * **platform**: docker

**Describe the bug**
Packages disappeared from WebUI after restarting the server and update verdaccio 5.1.0 -> 5.1.4, package comes back after upgrading with version history, all packages remained on the server in the folder

_**docker-compose.yaml**_
```yaml
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
    user: "root:root"  
networks:
  node-network:
    driver: bridge

```

**_config.yaml_**
```yaml
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: davs
  '**':
    access: $authenticated
    publish: davs
    proxy: npmjs
logs:
  - { type: stdout, format: pretty, level: http }
```</div>
