### ISSUE TITLE
README not being shown for packages (pnpm 6 only)

### ISSUE THREAD

**Issue by kaiyoma** [verdaccio/verdaccio#2469]
**Your Environment**
 * **verdaccio version**: 5.1.6
 * **node version** [12.x.x, 14.x.x]: 14.15.5
 * **package manager**: pnpm@6
 * **os**: Linux

**Describe the bug**

Verdaccio is not showing the README for packages that I publish to the registry. I can download the tarball directly and verify that the README does exist, but the Verdaccio UI always displays this now:

```
ERROR: No README data found!
```

**To Reproduce**

Publish a package and then open the UI.

**Expected behavior**

The UI should be showing the README.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
# https://github.com/verdaccio/verdaccio/issues/301
server:
  keepAliveTimeout: 0
# path to a directory with all packages
storage: (redacted)
web:
  title: (redacted)
security:
  api:
    legacy: false
    jwt:
      sign:
        expiresIn: 30d
  web:
    legacy: false
    sign:
      expiresIn: 7d
auth:
  htpasswd:
    file: (redacted)
    max_users: -1
  ldap:
    type: ldap
    cache:
      # max credentials to cache (default to 100 if cache is enabled)
      size: 100
      # cache expiration in seconds (default to 300 if cache is enabled)
      expire: 300
    client_options:
      url: (redacted)
      searchBase: (redacted)
      searchFilter: (redacted)
      reconnect: true
# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    maxage: 2h
  fontAwesome:
    url: https://npm.fontawesome.com/
    max_fails: 100
    maxage: 2h
    auth:
      type: bearer
      token_env: FONT_AWESOME_NPM_TOKEN
packages:
  '@arista/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '@fortawesome/*':
    access: $all
    proxy: fontAwesome
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all
    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
# Use `npm audit`
middlewares:
  audit:
    enabled: true
logs: {type: stdout, format: pretty, level: http}
listen: (redacted)
```

**Environment information**

```
Environment Info:
  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  Binaries:
    npm: 6.14.14 - /usr/local/bin/npm
{"level":30,"time":1634060285178,"pid":107,"hostname":"npm-0","msg":"exit caught"}
```

**Debugging output**

Can furnish upon request.

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
