### ISSUE TITLE
Docker Volume broken

### ISSUE THREAD

**Issue by medokin** [verdaccio/verdaccio#248]
#### My reason:

Error: EACCES: permission denied, open '/verdaccio/conf/storage/.sinopia-db.json'

#### Steps to reproduce:

docker run -it --rm --name verdaccio -p 4873:4873 -v /compose/verdaccio/data:/verdaccio verdaccio/verdaccio

####  App Version:	

gt 2.1

####  Config file:	

default

**Comment by juanpicado** [comment]
Relates https://github.com/verdaccio/verdaccio/issues/238

**Comment by medokin** [comment]
2.1 seems to be the last working version.

**Comment by juanpicado** [comment]
Have you tried `2.1.5`?

**Comment by medokin** [comment]
I tried every version.

Well, even 2.1 does not work correctly, there is no error, but the volume is empty.

**Comment by medokin** [comment]
```yaml
verdaccio:
  image: verdaccio/verdaccio:2.1 to latest
  container_name: verdaccio
  ports:
    - "4873:4873"
  volumes:
    - "/compose/verdaccio/data/storage:/verdaccio/storage"
    - "/compose/verdaccio/data/conf:/verdaccio/conf"
  restart: always
~
```

results in:

```bash
Creating verdaccio
Attaching to verdaccio
verdaccio | Verdaccio doesn't need superuser privileges. Don't run it under root.
verdaccio |  fatal--- cannot open config file /verdaccio/conf/config.yaml: ENOENT: no such file or directory, open '/verdaccio/conf/config.yaml'
verdaccio exited with code 0
```
