### ISSUE TITLE
Cache not redownloaded when deleted

### ISSUE THREAD

**Issue by gioragutt** [verdaccio/verdaccio#264]
#### Steps to reproduce:

`pm2 start vedaccio` (not exactly, I give exact path to global node modules bin file, as it doesn't work when I run `pm2 start verdaccio`, gives out node error)
`ng new test-project`
Delete `@angular` in `C:/Users/MyPc/.config/verdaccio/storage`
Delete `node_modules` in `test-project`
`npm install` inside `test-project`
`@angular` folder is not redownloaded in the cache folder, but it does appear in the `node_modules`

####  App Version:	

2.3.1

####  Config file:	
```
(#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info})
```

#### Additional information:

`npm get registry`: `http://localhost:4873/`

I've emptied the `storage` folder, ran `npm install -g @angular/cli`.
`@angular/cli` was indeed updated, checked by `ng -v`. But the storage folder is empty.
