### ISSUE TITLE
Using htpasswd to add users

### ISSUE THREAD

**Issue by sgen** [verdaccio/verdaccio#269]
#### My reason:

I would like to add users via `htpasswd` so I can turn off user registration and add users as necessary via a script or alternative 

####  Config file:	
```yaml
# You can specify listen address (or simply a port).
# If you add multiple values, verdaccio will listen on all of them.
#
# Examples:
#
#listen:
# - localhost:4873            # default value
# - http://localhost:4873     # same thing
# - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
# - https://example.org:4873  # if you want to use https
# - [::1]:4873                # ipv6
# - unix:/tmp/verdaccio.sock    # unix socket
listen: localhost:4873

# Configure HTTPS, it is required if you use "https" protocol above.
#https:
#  key: path/to/server.key
#  cert: path/to/server.crt
#  ca: path/to/server.pem

# if you use nginx with custom path, use this to override links
#url_prefix: https://dev.company.local/verdaccio/

# path to a directory with all packages
storage: /var/lib/verdacciod/storage

auth:
  htpasswd:
    file: /var/lib/verdacciod/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

    # amount of time to wait for repository to respond
    # before giving up and use the local cached copy
    #timeout: 30s

    # maximum time in which data is considered up to date
    #
    # default is 2 minutes, so server won't request the same data from
    # uplink if a similar request was made less than 2 minutes ago
    maxage: 1d

    # if two subsequent requests fail, no further requests will be sent to
    # this uplink for five minutes
    #max_fails: 2
    #fail_timeout: 5m

    # timeouts are defined in the same way as nginx, see:
    # http://wiki.nginx.org/ConfigNotation

    # add/override HTTP headers sent to the uplink server
    # this allows for HTTP Basic auth for example:
    #headers:
    #  authorization: "Basic YourBase64EncodedCredentials=="

    # set this to false to prevent tarballs from this upstream
    # to be stored in the local storage (defaults to true)
    cache: true

packages:
  # uncomment this for packages with "local-" prefix to be available
  # for admin only, it's a recommended way of handling private packages
  #'local-*':
  #  access: admin
  #  publish: admin
  #  # you can override storage directory for a group of packages this way:
  #  storage: 'local_storage'

  '@local/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated

  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
# type: file | stdout | stderr
# level: trace | debug | info | http (default) | warn | error | fatal
#
# parameters for file: name is filename
#  {type: 'file', path: 'verdaccio.log', level: 'debug'},
#
# parameters for stdout and stderr: format: json | pretty | pretty-timestamped
#  {type: 'stdout', format: 'pretty', level: 'debug'},
logs:
  #- {type: stdout, format: pretty, level: http}
  - {type: file, format: pretty, path: /var/log/verdacciod/verdacciod.log, level: info}

web:
  # web interface is disabled by default in 0.x, will be enabled soon in 1.x
  # when all its issues will be fixed
  #
  # set this to `true` if you want to experiment with web ui now;
  # this has a lot of issues, e.g. no auth yet, so use at your own risk
  enable: false

  # title: Verdaccio
  # logo: logo.png
  # template: custom.hbs
  # tagline: "Some <b>HTML</b> enabled tagline that sits between the actual \
#header and the list of packages. You can even add <a \
#href=\"https://github.com\">links</a>!"
```
#### Additional information:

It seems that the crypt3 implementation used by verdaccio differs from the one used by `htpasswd`.

The `htpasswd` entry created by adding a user via `npm add-user --registry http://localhost:4873`:
`sgen:$6GrjG3s8nNGw:autocreated 2017-07-27T18:11:40.603Z`
The `htpasswd` entry created by calling `htpasswd -d /var/lib/verdacciod/htpasswd sgen`
`sgen:O7EOcTLK1TI1U`

Removing the username and comments makes it clear that the result of the hash is completely different:
verdaccio: `$6GrjG3s8nNGw`
htpasswd: `O7EOcTLK1TI1U`

**Comment by sgen** [comment]
Actually it seems the `verdaccio` is generating a malformed SHA512 entry. The leading `$6` of the password section of  the entry looks alot like the leading `$6$` used to denote the use of the SHA512 hash. It might not even be using `crypt3`

**Comment by metodribic** [comment]
Any information on this I would also like to lock the the registration and add the users manually but I cannot figure it out how to properly generate passwords?

**Comment by ayusharma** [comment]
@metodribic You can generate username & password combination here 
http://www.htaccesstools.com/htpasswd-generator/

Write generated combination in `htpasswd` file.

Also, disable registrations 
```
auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: -1
```

**Comment by metodribic** [comment]
@ayusharma I did all that but it didn't work. Must have done something wrong. Will try it again. Thanks.

**Comment by metodribic** [comment]
Apparently this is not working for me but I noticed I'm running v2.1.0 which is fairly old. Could be this the case why is this not working?

**Comment by ayusharma** [comment]
I don't think the version is a problem. I am sharing the format of mine `htpasswd` file

```
ayusharma:$apr1$yUAhp97Z$dt.qKcx41l5qletFlrDr11
```

and make sure file path below relative to `config.yaml` file. 
```
auth:
  htpasswd:
    file: ./htpasswd 
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: -1
```
This config is working for me. We have registered more than 20 users manually. 

Try this.

**Comment by metodribic** [comment]
Strange, I have it the same. This is the line I pasted in `htpasswd`

```
test:$apr1$5eEMo5/.$9Qqk0LX.H64Hko83CUprf0
```
and this is `config.yaml`
```
auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 100
    max_users: -1
```

Even if try to restart verdaccio after adding the line in htpasswd login does not work. In terminal it says 409 Conflict (user already exist) and on webpage it does nothing.
