### ISSUE TITLE
Web UI access issue

### ISSUE THREAD

**Issue by amirmohsen** [verdaccio/verdaccio#273]
#### My reason:
The web ui doesn't seem to respect access rules. I can still see my packages even when I am not logged in.

#### Steps to reproduce:
Use the config specified below.
Platform: Ubuntu 16.10 x64
It's running behind nginx.

####  App Version:	
v2.3.1

####  Config file:	
```yml
listen: 'https://MY_REGISTRY_DOMAIN/'

url_prefix: 'https://MY_REGISTRY_DOMAIN'

storage: ./storage`

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
```

#### Additional information:
I am using this as a completely private registry which is why I need it to be entirely closed to both access and publish by unauthenticated users. I have also disabled registration as you can see.
