### ISSUE TITLE
After docker-compose is started, access via domain name, web UI base href displays ip

### ISSUE THREAD

**Issue by faner11** [verdaccio/verdaccio#2730]
* **verdaccio version**: 5.2.2
 * **os**: linux
 * **platform**: docker
 * **docker-compose**： 1.29.2
 
After docker-compose is started for a period of time, it is accessed through the domain name. The base herf of the web page is displayed as ip. After docker-compose restart, it returns to normal, but it will become ip again after a period of time.

![image](https://user-images.githubusercontent.com/26560612/144384862-d85bf52a-55ef-4f52-bb99-92df9af15cac.png)
```
// docker-compose.yaml
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "80:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
networks:
  node-network:
    driver: bridge   
```
