### ISSUE TITLE
Metadata missing from proxied packages

### ISSUE THREAD

**Issue by lyptt** [verdaccio/verdaccio#285]
#### My reason:

When installing https://github.com/standard/standard, the resulting package is broken as it expects package metadata to exist, and crashes when it doesn't.

#### Steps to reproduce:

- Configure Verdaccio to proxy packages and not cache them
- Configure npm to use Verdaccio as a registry

From a new folder:
- npm init
- npm install --save standard
- ./node_modules/standard

Observe an error occurs complaining about undefined

####  App Version:	
2.3.4 and master
####  Config file:	
```yaml
storage: /Users/Me/Desktop/storage

auth:
  htpasswd:
    file: /Users/Me/Desktop/storage/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
listen:
 - 0.0.0.0:4873
```

#### Additional information:
 - OS X/macOS, or Linux:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
