### ISSUE TITLE
Unable to install non-scoped packages with Yarn

### ISSUE THREAD

**Issue by lyptt** [verdaccio/verdaccio#287]
#### My reason:

This seems to be a similar issue to #74, however this occurs when using Verdaccio in proxy mode without caching, for any NPM package (not just our own published ones).

The full error is:

```
error An unexpected error occurred: "https://${NPM_REPO_URL}/request: 
  unregistered users are not allowed to access package request".
```

I've tried replicating the config changes from #74 to add a yarn entry to the config file, but with or without this we get the same issue.

#### Steps to reproduce:

`npm install` a package locally when configured to use a Verdaccio registry
Run `yarn`

####  App Version:	
2.3.4

####  Config file:	
```yaml
storage: /data

auth:
  htpasswd:
    file: /opt/vhtpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
  yarnpkg:
    url: https://registry.yarnpkg.com
    cache: false

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  'foo-*':
    access: $authenticated
    publish: $authenticated
    proxy: yarn

logs:
  - {type: stdout, format: pretty, level: http}
listen:
 - 0.0.0.0:4873
```

#### Additional information:

 - Container:
   - I use local environment
