### ISSUE TITLE
npm install jsdoc failes

### ISSUE THREAD

**Issue by faandi** [verdaccio/verdaccio#289]
#### My reason:

Installing jsdoc via verdaccio registry fails with the following error message:

```
npm install jsdoc
npm ERR! fetch failed https://npm.msgis.net/babylon/-/babylon-7.0.0-beta.0-ranges.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

It works if I switch back from my verdaccio registry to the official npmjs registry.

#### Steps to reproduce:

`npm install jsdoc`

####  App Version:	

```
verdaccio --version
2.3.4                        
```

```
npm --version
3.10.10
```
```
node --version
v6.11.1
```

####  Config file:	

```yaml
storage: ./storage 
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 2
uplinks:
  npmjs:
    url: https://registry.npmjs.org/ 
packages:
  '**':
    access: developer
    publish: developer
    proxy: npmjs
url_prefix: https://my.internal.domain
listen:
 - 0.0.0.0:4873
logs:
  - {type: stdout, format: pretty, level: http}
```

#### Additional information:

verdaccio log:

```
....
http <-- 200, user: developer(XX.XX.XX.XX via XX.XX.XX.XX), req: 'GET /babylon', bytes: 0/20543
http <-- 404, user: developer(XX.XX.XX.XX via XX.XX.XX.XX), req: 'GET /babylon/-/babylon-7.0.0-beta.0-ranges.tgz', error: file doesn't exist on uplink
....
```
