### ISSUE TITLE
Allow specific accounts to npm publish

### ISSUE THREAD

**Issue by c0debreaker** [verdaccio/verdaccio#297]
I completed setting up our verdaccio server. It's working great! However, I want to make it more secure in such a way that only our team can `npm publish` to it. How can we achieve this?

Thanks!

**Comment by juanpicado** [comment]
Please, read this and let us know whether it helps you or not. https://github.com/verdaccio/verdaccio/blob/master/wiki/packages.md

**Comment by c0debreaker** [comment]
Thank you! I'll close the ticket for now.

**Comment by c0debreaker** [comment]
Below is my config.yaml. I am not sure why I am able to publish a package to my verdaccio server from my laptop if I didn't create accounts on the verdaccio server. What I would like to happen is to only allow created accounts on the verdaccio server to be able to publish packages. Is there something wrong in my configuration?

```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

listen:

logs:
  - {type: stdout, format: pretty, level: http}
```
