### ISSUE TITLE
Unexpected EOF while installing/downloading large packages

### ISSUE THREAD

**Issue by yogeshwar-20** [verdaccio/verdaccio#301]
#### My reason:

Installing larger packages ([this one](https://www.npmjs.com/package/react-native-awesome-card-io) in this scenario) fails consistently from verdaccio with an unexpected EOF. The package is published to the local verdaccio server, not a redirection to the public registry. It installs fine from the public registry at https://registry.npmjs.org.

Even a simple wget ends abruptly
```
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  X-Powered-By: verdaccio/2.3.4
  Access-Control-Allow-Origin: *
  Content-Type: application/octet-stream
  Content-Length: 137211454
  X-Status-Cat: http://flic.kr/p/aVuVsF
  Date: Mon, 21 Aug 2017 11:43:35 GMT
  Connection: keep-alive
Length: 137211454 (131M) [application/octet-stream]
Saving to: ‘react-native-awesome-card-io-0.6.6.tgz.2’

react-native-awesome-card-io-0.6.6.tgz.2        65%[======================================================================>                                      ]  85.73M  13.6MB/s    in 6.1s    

2017-08-21 17:15:23 (14.1 MB/s) - Connection closed at byte 89897191. Retrying.
```

#### Steps to reproduce:
- Publish the package to Verdaccio
- Try installing it with yarn or npm

Issue is occurring when running the latest docker image, or on the host system with verdaccio installed through npm. Issue has persisted on both a Linux host and a macOS host.

It seems to occur on an erratic timeout basis (~7-10 seconds) because the download completes successfully if the download speed is high enough. The byte at which the connection closes is also not constant.
####  App Version:	
2.3.4

####  Config file:	
Default config file with only max_body_size increased to 300mb allow publishing packages of this size.

**Comment by juanpicado** [comment]
I will take a look it along the week.

**Comment by juanpicado** [comment]
Sorry, but I couldn't reproduce it. I doubt is an issue with `verdaccio` itself. 

```
➜ npm install react-native-awesome-card-io                                         
npm WARN saveError ENOENT: no such file or directory, open '/Users/jpicado/projects/hello_world_npm/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/jpicado/projects/hello_world_npm/package.json'
npm WARN hello_world_npm No description
npm WARN hello_world_npm No repository field.
npm WARN hello_world_npm No README data
npm WARN hello_world_npm No license field.

+ react-native-awesome-card-io@0.6.9
updated 1 package in 16.797s
````

I tried multiple ways to simulate network latency, packages drop, uplink delays etc. I would you suggest clean your cache or review your local environment. My tests were from a local Docker container and `v2.3.6`.

I'll close this, feel free to reopen if the issue persists and try to provide more verbose output.

**Comment by yogeshwar-20** [comment]
Alright, thanks for your time! Already tried cleaning cache and fresh installs and there's nothing obvious that stands out in the local environment, but will dig deeper to try and identify the issue.

**Comment by cesarfd** [comment]
I've reproduced the same issue in this case with [geoip-lite](https://www.npmjs.com/package/geoip-lite) which is a fairly large package (~30MiB). It doesn't work no matter what I try, even after `npm cache clean --force`. I have verdaccio 2.3 running in an aws hosted Docker container.

It works perfectly with the standard npm registry.

This is the npm log:

```
1777 http fetch GET 200 https://npm.foo.bar/geoip-lite/-/geoip-lite-1.2.1.tgz 12714ms
1778 silly fetchPackageMetaData error for geoip-lite@~1.2 unexpected end of file
1779 verbose stack Error: unexpected end of file
1779 verbose stack     at Gunzip.zlibOnError (zlib.js:152:15)
1780 verbose cwd /Users/me/work/my-project
1781 verbose Darwin 16.7.0
1782 verbose argv "/Users/me/.nvm/versions/node/v8.5.0/bin/node" "/Users/me/.nvm/versions/node/v8.5.0/bin/npm" "i"
1783 verbose node v8.5.0
1784 verbose npm  v5.3.0
1785 error code Z_BUF_ERROR
1786 error errno -5
1787 error unexpected end of file
1788 verbose exit [ -5, true ]
```

`geoip-lite-1.2.1.tgz` is consistently well downloaded in verdaccio, though.

**Comment by yogeshwar-20** [comment]
Fwiw we weren't able to identify the actual cause, we were able to work around it however by setting up an nginx reverse proxy to verdaccio on the same host machine and accessing the registry through the proxy.

**Comment by cesarfd** [comment]
Thanks for the help, @yogeshwar-20 . Did you use any specific setting? Timeouts or anything like that? I tried with a squid proxy with no luck.

**Comment by yogeshwar-20** [comment]
Only keepalive and proxypass.

**Comment by pward123** [comment]
Running into the same issue when trying to pull ares-webos-sdk (> 42mb)

**Comment by juanpicado** [comment]
We need to find a perfect way to reproduce this properly. I didn't have success in my last try.

**Comment by pward123** [comment]
Putting it behind an nginx proxy did fix the problem for me

**Comment by alonl** [comment]
We're having the exact same issue. Our local (in Docker) Verdaccio currently hosts only one private package, and it fails both with `npm install` / `yarn install` and even simply `curl` for downloading the package's `.tgz` file.

@juanpicado Can you please re-open this issue? It really blocks us from using Verdaccio at the moment. :(

**Comment by juanpicado** [comment]
Sure, no problem

**Comment by juanpicado** [comment]
@alonl It doesn't work with @pward123 workaround?

**Comment by alonl** [comment]
> @alonl It doesn't work with @pward123 workaround?
Haven't tried yet.

**Comment by alonl** [comment]
@juanpicado one interesting verdict I've just found:
* Every time, the connection terminates after exactly 6.0 - 6.6 seconds. Maybe there is some session timeout configured somewhere? Maybe in the Docker configuration? See these attempts of `wget` (until it finally succeeded in less than 6.2 seconds) below:
```
> wget http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz

--2017-10-03 21:16:38--  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Resolving verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)... 10.3.244.141
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   39%[==============================================>                                                                        ] 974.39K   191KB/s    in 6.2s   

2017-10-03 21:16:45 (158 KB/s) - Connection closed at byte 997776. Retrying.

--2017-10-03 21:16:46--  (try: 2)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   35%[=========================================>                                                                             ] 872.50K   149KB/s    in 6.2s   

2017-10-03 21:16:53 (141 KB/s) - Connection closed at byte 997776. Retrying.

--2017-10-03 21:16:55--  (try: 3)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   38%[============================================>                                                                          ] 942.63K   178KB/s    in 6.2s   

2017-10-03 21:17:02 (153 KB/s) - Connection closed at byte 997776. Retrying.

--2017-10-03 21:17:05--  (try: 4)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   99%[=====================================================================================================================> ]   2.39M   460KB/s    in 6.1s   

2017-10-03 21:17:12 (398 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:17:16--  (try: 5)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   67%[===============================================================================>                                       ]   1.63M   284KB/s    in 6.6s  
 

2017-10-03 21:17:24 (251 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:17:29--  (try: 6)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   74%[=======================================================================================>                               ]   1.80M   317KB/s    in 6.8s   

2017-10-03 21:17:37 (269 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:17:43--  (try: 7)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   33%[=======================================>                                                                               ] 832.80K   144KB/s    in 6.5s   

2017-10-03 21:17:50 (128 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:17:57--  (try: 8)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   32%[=====================================>                                                                                 ] 789.14K   128KB/s    in 6.6s   

2017-10-03 21:18:05 (120 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:18:13--  (try: 9)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   42%[=================================================>                                                                     ]   1.03M   177KB/s    in 6.3s  
 

2017-10-03 21:18:20 (167 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:18:29--  (try:10)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                   45%[=====================================================>                                                                 ]   1.10M   231KB/s    in 6.0s   

2017-10-03 21:18:36 (186 KB/s) - Connection closed at byte 2505891. Retrying.

--2017-10-03 21:18:46--  (try:11)  http://verdaccio.infra.svc.cluster.local/some-package/-/some-package-5.0.0.tgz
Connecting to verdaccio.infra.svc.cluster.local (verdaccio.infra.svc.cluster.local)|10.3.244.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2522568 (2.4M) [application/octet-stream]
Saving to: ‘some-package-5.0.0.tgz’

some-package-5.0.0.tgz                                  100%[======================================================================================================================>]   2.41M   446KB/s    in 6.1s   

2017-10-03 21:18:53 (404 KB/s) - ‘some-package-5.0.0.tgz’ saved [2522568/2522568]
```

**Comment by juanpicado** [comment]
I'm not aware of any timeout, but I'll try to dig a bit and see what I find out. Since I'm not a Docker expert 😥  would be great anyone else dig as well in order to fix this issue.

**Comment by alonl** [comment]
For now I couldn't reproduce locally, even when running in Docker :(

**Comment by juanpicado** [comment]
Yes, locally works perfectly. I wonder if any factor might be causing this issue.

**Comment by alonl** [comment]
Nginx seems so solve the problem for me as well. Thanks @pward123.

**Comment by alonl** [comment]
@juanpicado I have a belief that this issue is somehow related to the stream buffering, since the difference (that I see) between with/without nginx is that nginx buffers the response.
From my nginx logs:
```
23:46:09 [warn] 7#7: *90 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/01/0000000011 while reading upstream, client: 10.0.42.13, server: , request: "GET /some-package/-/some-package-5.3.0.tgz HTTP/1.1", upstream: "http://127.0.0.1:4873/some-package/-/some-package-5.3.0.tgz", host: "verdaccio.infra.svc.cluster.local" 
```

**Comment by juanpicado** [comment]
@alonl I don't get it

**Comment by ayusharma** [comment]
We are also using Verdaccio to maintain the private registry.  I tried to figure out this issue but unable to reproduce it.

Sharing conf files. Hope this help. 

** We are not using verdaccio with docker.   **

Verdaccio version: `2.3.6`

Verdaccio config:
```
# path to a directory with all packages
storage: ./storage

# a list of users
#
# This is deprecated, use auth plugins instead (see htpasswd below).
# users:
  # admin:
    # crypto.createHash('sha1').update(pass).digest('hex')
    # password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false

  title: Registry

  #logo: logo.png

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    #url: http://localhost:5984/registry
    url: https://registry.npmjs.org/

    # amount of time to wait for repository to respond
    # before giving up and use the local cached copy
    #timeout: 30s

    # maximum time in which data is considered up to date
    #
    # default is 2 minutes, so server won't request the same data from
    # uplink if a similar request was made less than 2 minutes ago
    #maxage: 2m

    # if two subsequent requests fail, no further requests will be sent to
    # this uplink for five minutes
    #max_fails: 2
    #fail_timeout: 5m

    # timeouts are defined in the same way as nginx, see:
    # http://wiki.nginx.org/ConfigNotation

    # add/override HTTP headers sent to the uplink server
    # this allows for HTTP Basic auth for example:
    #headers:
    #  authorization: "Basic YourBase64EncodedCredentials=="

    # set this to false to prevent tarballs from this upstream
    # to be stored in the local storage (defaults to true)
    #cache: false

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  # uncomment this for packages with "local-" prefix to be available
  # for admin only, it's a recommended way of handling private packages
  #'local-*':
  #  access: admin
  #  publish: admin
  #  # you can override storage directory for a group of packages this way:
  #  storage: 'local_storage'

  '**':
    # allow all users to read packages (including non-authenticated users)
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow 'admin' to publish packages
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

#####################################################################
# Advanced settings
#####################################################################

## Special packages publish configurations
#publish:
## This will allow the publisher to publish packages even if any uplink is down.
#  allow_offline: true

# if you use nginx with custom path, use this to override links
#url_prefix: https://dev.company.local/verdaccio/

# You can specify listen address (or simply a port).
# If you add multiple values, verdaccio will listen on all of them.
#
# Examples:
#
#listen:
# - localhost:4873            # default value
# - http://localhost:4873     # same thing
# - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
# - https://example.org:4873  # if you want to use https
# - [::1]:4873                # ipv6
# - unix:/tmp/verdaccio.sock    # unix socket

# Configure HTTPS, it is required if you use "https" protocol above.
#https:
#  key: path/to/server.key
#  cert: path/to/server.crt
#  ca: path/to/server.pem

# type: file | stdout | stderr
# level: trace | debug | info | http (default) | warn | error | fatal
#
# parameters for file: name is filename
#  {type: 'file', path: 'verdaccio.log', level: 'debug'},
#
# parameters for stdout and stderr: format: json | pretty | pretty-timestamped
#  {type: 'stdout', format: 'pretty', level: 'debug'},
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

# you can specify proxy used with all requests in wget-like manner here
# (or set up ENV variables with the same name)
#http_proxy: http://something.local/
#https_proxy: https://something.local/
#no_proxy: localhost,127.0.0.1

# maximum size of uploaded json document
# increase it if you have "request entity too large" errors
#max_body_size: 1mb

# Notify Settings
# Notify was built primarily to use with Slack's Incoming
# webhooks, but will also deliver a simple payload to
# any endpoint. Currently only active for publish / create
# commands.
notify:
  # Choose a method. Technically this will accept any HTTP
  # request method, but probably stick to GET or POST
  method: POST
  # Only run this notification if the package name matches the regular
  # expression
  packagePattern: ^(.*)$
  # Any flags to be used with the regular expression
  packagePatternFlags: i
  # If this endpoint requires specific headers, set them here
  # as an array of key: value objects.
  headers: [{'Content-type': 'application/x-www-form-urlencoded'}]
  # set the URL endpoint for this call
  endpoint: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXX
  # Finally, the content you will be sending in the body.
  # This data will first be run through Handlebars to parse
  # any Handlebar expressions. All data housed in the metadata object
  # is available for use within the expressions.
  # content: ' {{ handlebar-expression }}'
  # For Slack, follow the following format:
  content: '{ "text": "Package *{{ name }}* published to version *{{ dist-tags.latest }}*", "username": "Verdaccio", "icon_emoji": ":package:" }'

  # Multiple notification endpoints can be created by specifying a collection
  'example-package-1':
    method: POST
    # Only run this notification if the package name matches the regular
    # expression
    packagePattern: ^example-package-regex$
    # Any flags to be used with the regular expression
    # since verdaccio 2.2.2 this property has been disabled read #108
    # it will be re-enabled after 2.5.0
    # packagePatternFlags: i
    # If this endpoint requires specific headers, set them here
    # as an array of key: value objects.
    # headers supports as well a literal object
    headers: {'Content-type': 'application/x-www-form-urlencoded'}
    # set the URL endpoint for this call
    endpoint: https://hooks.slack.com/...
    # Finally, the content you will be sending in the body.
    # This data will first be run through Handlebars to parse
    # any Handlebar expressions. All data housed in the metadata object
    # is available for use within the expressions.
    content: ' {{ handlebar-expression }}'
    # For Slack, follow the following format:
    # content: '{ "text": "Package *{{ name }}* published to version *{{ dist-tags.latest }}*", "username": "Verdaccio", "icon_emoji": ":package:" }'
```

Our nginx conf as follows:

```
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;
    client_max_body_size 20M;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        # root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
		proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:4873/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

# Settings for a TLS enabled server.
#
#    server {
#        listen       443 ssl http2 default_server;
#        listen       [::]:443 ssl http2 default_server;
#        server_name  _;
#        root         /usr/share/nginx/html;
#
#        ssl_certificate "/etc/pki/nginx/server.crt";
#        ssl_certificate_key "/etc/pki/nginx/private/server.key";
#        ssl_session_cache shared:SSL:1m;
#        ssl_session_timeout  10m;
#        ssl_ciphers HIGH:!aNULL:!MD5;
#        ssl_prefer_server_ciphers on;
#
#        # Load configuration files for the default server block.
#        include /etc/nginx/default.d/*.conf;
#
#        location / {
#        }
#
#        error_page 404 /404.html;
#            location = /40x.html {
#        }
#
#        error_page 500 502 503 504 /50x.html;
#            location = /50x.html {
#        }
#    }

}
```
Installation output: 

```
npm install react-native-awesome-card-io

> bson@0.2.22 install /Users/ayush/innovaccer/datashop/node_modules/connect-mongo/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o

> kerberos@0.0.11 install /Users/ayush/innovaccer/datashop/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o

> fsevents@1.1.2 install /Users/ayush/innovaccer/datashop/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ayush/innovaccer/datashop/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> datashop-core@1.0.7-3 postinstall /Users/ayush/innovaccer/datashop/node_modules/datashop-core
> node tools/scripts/postinstall.js

Auto installing package dependencies
datashop-core@1.0.7-3 /Users/ayush/innovaccer/datashop/node_modules/datashop-core
├─┬ metalogger@2.0.0
│ ├── callsite@1.0.0
│ ├─┬ config@1.26.2
│ │ ├── json5@0.4.0
│ │ └── os-homedir@1.0.2
│ ├── optional@0.1.4
│ └── yaml@0.3.0
├─┬ morgan@1.5.3
│ └── basic-auth@1.0.4
└─┬ request@2.83.0
  ├── aws-sign2@0.7.0
  ├── aws4@1.6.0
  ├── caseless@0.12.0
  ├─┬ combined-stream@1.0.5
  │ └── delayed-stream@1.0.0
  ├── extend@3.0.1
  ├── forever-agent@0.6.1
  ├─┬ form-data@2.3.1
  │ ├── asynckit@0.4.0
  │ ├── combined-stream@1.0.5  deduped
  │ └── mime-types@2.1.17  deduped
  ├─┬ har-validator@5.0.3
  │ ├─┬ ajv@5.2.3
  │ │ ├── co@4.6.0
  │ │ ├── fast-deep-equal@1.0.0
  │ │ ├── json-schema-traverse@0.3.1
  │ │ └─┬ json-stable-stringify@1.0.1
  │ │   └── jsonify@0.0.0
  │ └── har-schema@2.0.0
  ├─┬ hawk@6.0.2
  │ ├─┬ boom@4.3.1
  │ │ └── hoek@4.2.0  deduped
  │ ├─┬ cryptiles@3.1.2
  │ │ └─┬ boom@5.2.0
  │ │   └── hoek@4.2.0  deduped
  │ ├── hoek@4.2.0
  │ └─┬ sntp@2.0.2
  │   └── hoek@4.2.0  deduped
  ├─┬ http-signature@1.2.0
  │ ├── assert-plus@1.0.0
  │ ├─┬ jsprim@1.4.1
  │ │ ├── assert-plus@1.0.0  deduped
  │ │ ├── extsprintf@1.3.0
  │ │ ├── json-schema@0.2.3
  │ │ └─┬ verror@1.10.0
  │ │   ├── assert-plus@1.0.0  deduped
  │ │   ├── core-util-is@1.0.2
  │ │   └── extsprintf@1.3.0  deduped
  │ └─┬ sshpk@1.13.1
  │   ├── asn1@0.2.3
  │   ├── assert-plus@1.0.0  deduped
  │   ├─┬ bcrypt-pbkdf@1.0.1
  │   │ └── tweetnacl@0.14.5  deduped
  │   ├─┬ dashdash@1.14.1
  │   │ └── assert-plus@1.0.0  deduped
  │   ├─┬ ecc-jsbn@0.1.1
  │   │ └── jsbn@0.1.1  deduped
  │   ├─┬ getpass@0.1.7
  │   │ └── assert-plus@1.0.0  deduped
  │   ├── jsbn@0.1.1
  │   └── tweetnacl@0.14.5
  ├── is-typedarray@1.0.0
  ├── isstream@0.1.2
  ├── json-stringify-safe@5.0.1
  ├─┬ mime-types@2.1.17
  │ └── mime-db@1.30.0
  ├── oauth-sign@0.8.2
  ├── performance-now@2.1.0
  ├── qs@6.5.1
  ├── safe-buffer@5.1.1
  ├── stringstream@0.0.5
  ├─┬ tough-cookie@2.3.3
  │ └── punycode@1.4.1
  ├─┬ tunnel-agent@0.6.0
  │ └── safe-buffer@5.1.1  deduped
  └── uuid@3.1.0

    Dependencies installed for package api

> bson@0.2.22 install /Users/ayush/innovaccer/datashop/node_modules/datashop-core/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o

> kerberos@0.0.11 install /Users/ayush/innovaccer/datashop/node_modules/datashop-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
datashop-core@1.0.7-3 /Users/ayush/innovaccer/datashop/node_modules/datashop-core
├─┬ connect-mongo@0.4.2
│ └─┬ mongodb@1.4.40
│   ├─┬ bson@0.2.22
│   │ └── nan@1.8.4
│   ├─┬ kerberos@0.0.11
│   │ └── nan@1.8.4  deduped
│   └─┬ readable-stream@2.3.3
│     ├── core-util-is@1.0.2
│     ├── inherits@2.0.3
│     ├── isarray@1.0.0
│     ├── process-nextick-args@1.0.7
│     ├── safe-buffer@5.1.1  deduped
│     ├─┬ string_decoder@1.0.3
│     │ └── safe-buffer@5.1.1  deduped
│     └── util-deprecate@1.0.2
├─┬ connect-redis@2.5.1
│ ├─┬ debug@1.0.5
│ │ └── ms@2.0.0
│ └── redis@0.12.1
├─┬ cookie-parser@1.4.3
│ ├── cookie@0.3.1
│ └── cookie-signature@1.0.6
├─┬ express@4.16.1
│ ├─┬ accepts@1.3.4
│ │ ├─┬ mime-types@2.1.17
│ │ │ └── mime-db@1.30.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├─┬ body-parser@1.18.2
│ │ ├── bytes@3.0.0
│ │ ├── content-type@1.0.4  deduped
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ ├── depd@1.1.1
│ │ ├─┬ http-errors@1.6.2
│ │ │ ├── depd@1.1.1
│ │ │ ├── inherits@2.0.3  deduped
│ │ │ ├── setprototypeof@1.0.3
│ │ │ └── statuses@1.3.1  deduped
│ │ ├── iconv-lite@0.4.19
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ ├── qs@6.5.1  deduped
│ │ ├─┬ raw-body@2.3.2
│ │ │ ├── bytes@3.0.0  deduped
│ │ │ ├── http-errors@1.6.2  deduped
│ │ │ ├── iconv-lite@0.4.19  deduped
│ │ │ └── unpipe@1.0.0  deduped
│ │ └── type-is@1.6.15  deduped
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.4
│ ├── cookie@0.3.1  deduped
│ ├── cookie-signature@1.0.6  deduped
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.1
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.0
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ ├── encodeurl@1.0.1  deduped
│ │ ├── escape-html@1.0.3  deduped
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ ├── parseurl@1.3.2  deduped
│ │ ├── statuses@1.3.1  deduped
│ │ └── unpipe@1.0.0
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.2
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@2.0.2
│ │ ├── forwarded@0.1.2
│ │ └── ipaddr.js@1.5.2
│ ├── qs@6.5.1
│ ├── range-parser@1.2.0
│ ├── safe-buffer@5.1.1
│ ├─┬ send@0.16.1
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0  deduped
│ │ ├── depd@1.1.1
│ │ ├── destroy@1.0.4
│ │ ├── encodeurl@1.0.1  deduped
│ │ ├── escape-html@1.0.3  deduped
│ │ ├── etag@1.8.1  deduped
│ │ ├── fresh@0.5.2  deduped
│ │ ├── http-errors@1.6.2  deduped
│ │ ├── mime@1.4.1
│ │ ├── ms@2.0.0
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ ├── range-parser@1.2.0  deduped
│ │ └── statuses@1.3.1  deduped
│ ├─┬ serve-static@1.13.1
│ │ ├── encodeurl@1.0.1  deduped
│ │ ├── escape-html@1.0.3  deduped
│ │ ├── parseurl@1.3.2  deduped
│ │ └── send@0.16.1  deduped
│ ├── setprototypeof@1.1.0
│ ├── statuses@1.3.1
│ ├─┬ type-is@1.6.15
│ │ ├── media-typer@0.3.0
│ │ └── mime-types@2.1.17  deduped
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├─┬ express-session@1.15.6
│ ├── cookie@0.3.1  deduped
│ ├── cookie-signature@1.0.6  deduped
│ ├── crc@3.4.4
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.1
│ ├── on-headers@1.0.1
│ ├── parseurl@1.3.2  deduped
│ ├─┬ uid-safe@2.1.5
│ │ └── random-bytes@1.0.0
│ └── utils-merge@1.0.1  deduped
├─┬ express-validator@2.21.0
│ ├── bluebird@3.4.7
│ ├── lodash@4.16.6
│ └── validator@5.7.0
├─┬ gridfs-stream@1.1.1
│ └── flushwritable@1.0.0
├─┬ isusableobject@1.0.0
│ └── lodash@4.17.4
├─┬ method-override@1.0.2
│ └── methods@1.0.0
├─┬ morgan@1.5.3
│ └── basic-auth@1.0.4
├─┬ passport@0.2.2
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
└─┬ session-file-store@0.0.3
  ├─┬ graceful-fs@3.0.11
  │ └── natives@1.1.0
  └── retry@0.6.1

    Dependencies installed for package server
+ react-native-awesome-card-io@0.7.0
added 1811 packages in 62.956s
```
