### ISSUE TITLE
can not sync the @scope package

### ISSUE THREAD

**Issue by txiaocao** [verdaccio/verdaccio#303]
#### My reason:

can not sync the `@scope` package

#### Steps to reproduce:

start the server `npm run verdaccio`
####  App Version:	
2.3.6

####  Config file:	
```yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/rlidwka/sinopia/tree/master/conf
#

# path to a directory with all packages
storage: ./registry

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    allow_access: $all
    allow_publish: $authenticated
    publish: $authenticated

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: sinopia.log, level: info}

listen:
  - 0.0.0.0:4873

#### Additional information:
```
npm install `@types/mysql`
#### Additional verbose log:
npm ERR! code E404
npm ERR! 404 Not Found: @types/mysql@0.0.31

**Comment by juanpicado** [comment]
@txiaocao please follow the format on creating the issue, otherwise, it's hard to help. 1. settings, config file, verdaccio version, etc.

**Comment by aszmyd** [comment]
@txiaocao are You sure it tries to to install from You'r local repo?
Run this to check:

```npm config get registry```
```npm whoami```

**Comment by cmdelatorre** [comment]
In the `packages` section, changing `'*'` to `'**'` solves it (which is the default configuration actually)

**Comment by txiaocao** [comment]
thanks all. because  config.yaml `packages.proxy` undefined, add proxy: npmjs is ok
```
packages:
  '@*/*':
    # scoped packages
    access: $all
    allow_access: $all
    allow_publish: $authenticated
    publish: $authenticated
    proxy: npmjs
```
