### ISSUE TITLE
can't auth to prod via local.headers: verdaccio.local to verdaccio.prod to npm 

### ISSUE THREAD

**Issue by Falieson** [verdaccio/verdaccio#304]
# ISSUE
When I try to install a package that verdi.local can't find it when it asks verdi.prod . verdi.prod responds with:
```
0|wps-npm  |  http <-- 403, user: undefined($homeip), req: 'GET /base64', error: unregistered users are not allowed to access package base64
```

**I thought having the headers, Authorization in my verdi.local would fix this?**

## .NPMRC CONFIG
```
email=florian.mettetal@$domain.com
always-auth=true
registry=http://localhost:4873/
//$prod/:_authToken="LX4oULtJAAQt4WaqZiXzO/gRMU68WbY5OBwoMqC2cQ="
```

## VERDACCIO SETUP

verdi.local --> verdi.prod --> npm.official

I don't just use @scoped packages, I also use pre-releases of packages like `prettier 1.6.0` (which comes with --config option, that 1.5.x doesn't)

My circleci server is configured to use verdi.prod
I especially love using verdi.local for offline development

**verdi.local**
```
uplinks:
  prod:
    url: http://$prod:4873/
    headers:
       Authorization: "Basic LX4oULtJAAQt4WaqZiXzO/gRMU68WbY5OBwoMqC2cQ="
```
I'm using the token from ~/.npmrc that is received from verdi.prod by doing
```npm adduser --registry  http://$prod:4873```

**verdi.prod**
```
storage: ./storage

listen: 0.0.0.0:4873

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
```

**Comment by juanpicado** [comment]
Follow up of https://gitter.im/verdaccio/questions?at=599dacb2a7b406262dbc6762

**Comment by juanpicado** [comment]
@Falieson according to my test your set up has an issue

```yaml
uplinks:
  prod:
    url: http://0.0.0.0:4873/
    headers:
      authorization: Bearer 5WXoet5VYxOnUwv8aADlPA==
```
If you go deaper into `npm/pacote` they don't use `Basic`, they use `Bearer` as authorization prefix header. It works for me, try and let me know whether works or not.
