### ISSUE TITLE
Add support for scoped plugin packages

### ISSUE THREAD

**Issue by kuoruan** [verdaccio/verdaccio#3047]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Add support for scoped package (eg. `@google/verdaccio-google-auth-ui`) as the plugin package name.

**Describe alternatives you've considered**
The config can be like:

```yml
auth:
  google-auth-ui@google:
    foo: bar
```

or:

```yml
auth:
  google-auth-ui:
    _scope: google # add prefix underline
    foo: bar
```

Leave blank can compatible with plugin named `verdaccio-google-auth-ui`

**Comment by edclement** [comment]
Maybe the below link will be helpful for you until something like what you're proposing is implemented. This is how we handle installing our plugin which is scoped under `@xlts.dev`.

https://github.com/xlts-dev/verdaccio-prometheus-middleware#installation

**Comment by juanpicado** [comment]
There was a first try already https://github.com/verdaccio/verdaccio/pull/1868

**Comment by juanpicado** [comment]
Second try https://github.com/verdaccio/verdaccio/pull/1868#issuecomment-1154425027
PR: https://github.com/verdaccio/verdaccio/pull/3227

**Comment by juanpicado** [comment]
From v5.12.0 would be like this

```
middlewares:
  audit:
    enabled: true
  '@xlts.dev/verdaccio-prometheus-middleware':
      metricsPath: /custom/path/metrics    
```
