### ISSUE TITLE
npm set registry - ERR! Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [verdaccio/verdaccio#305]
#### My reason:
Getting *`npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Suriyaa\.npmrc'` error* after running **`npm set registry http://localhost:4873/`** command.

#### Steps to reproduce:
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Suriyaa>npm set registry http://localhost:4873/
npm ERR! path C:\Users\Suriyaa\.npmrc
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Suriyaa\.npmrc'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Users\Suriyaa\.npmrc'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, open \'C:\\Users\\Suriyaa\\.npmrc\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Suriyaa\\.npmrc' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Suriyaa\AppData\Roaming\npm-cache\_logs\2017-08-25T16_23_51_869Z-debug.log

C:\Users\Suriyaa>
```

####  App Version:	
```
C:\Users\Suriyaa>verdaccio --version
2.3.6
```

####  Config file:	
```
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

#### Additional information:
 - `$ npm --verbose` prints:
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\System32>npm --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Suriyaa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose' ]
npm info using npm@5.3.0
npm info using node@v6.11.0

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s, se,
    search, set, shrinkwrap, star, stars, start, stop, t, team,
    test, tst, un, uninstall, unpublish, unstar, up, update, v,
    version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Suriyaa\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.3.0 C:\Users\Suriyaa\AppData\Roaming\npm\node_modules\npm

C:\Windows\System32>
```
 - `$ npm config get registry` prints:
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\System32>npm config get registry
https://registry.npmjs.org/

C:\Windows\System32>
```
 - Verdaccio terminal output: no errors
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Container:
   - I use local environment

#### Additional verbose log:
In `C:\Users\Suriyaa\AppData\Roaming\npm-cache\_logs\2017-08-25T16_29_08_440Z-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Suriyaa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'set',
1 verbose cli   'registry',
1 verbose cli   'http://localhost:4873/' ]
2 info using npm@5.3.0
3 info using node@v6.11.0
4 info config set "registry" "http://localhost:4873/"
5 verbose stack Error: EPERM: operation not permitted, open 'C:\Users\Suriyaa\.npmrc'
5 verbose stack     at Error (native)
6 verbose cwd C:\Windows\System32
7 verbose Windows_NT 10.0.15063
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Suriyaa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "set" "registry" "http://localhost:4873/"
9 verbose node v6.11.0
10 verbose npm  v5.3.0
11 error path C:\Users\Suriyaa\.npmrc
12 error code EPERM
13 error errno -4048
14 error syscall open
15 error Error: EPERM: operation not permitted, open 'C:\Users\Suriyaa\.npmrc'
15 error     at Error (native)
15 error  { Error: EPERM: operation not permitted, open 'C:\Users\Suriyaa\.npmrc'
15 error     at Error (native)
15 error   stack: 'Error: EPERM: operation not permitted, open \'C:\\Users\\Suriyaa\\.npmrc\'\n    at Error (native)',
15 error   errno: -4048,
15 error   code: 'EPERM',
15 error   syscall: 'open',
15 error   path: 'C:\\Users\\Suriyaa\\.npmrc' }
16 error Please try running this command again as root/Administrator.
17 verbose exit [ -4048, true ]
```
