### ISSUE TITLE
Force light theme

### ISSUE THREAD

**Issue by plashenkov** [verdaccio/verdaccio#3051]
Hi!

Currently we have an option to force the dark theme (`darkMode: true`). But we have no option to force the light theme. The `darkMode: false` option doesn't force the light theme. It just leaves the behavior as is, i.e. theme autoselecting.

It would be nice if the `darkMode: false` forced the light theme, while, for example, `darkMode: "auto"` turned theme autoselecting (currently this is the default behavior) on.

Thank you!

**Comment by plashenkov** [comment]
Current workaround. `config.yaml`:
```yaml
web:
  metaScripts:
    - "<script>localStorage.darkMode = false</script>"
```
