### ISSUE TITLE
Remove from web section not longer valid properties

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#307]
#### My reason:

Update the `web` section on  `full.yalm` due to not all properties are no longer valid.

```
web:
  enable: true
  title: Verdaccio
  logo: logo.png
  template: custom.hbs
  tagline: "Some <b>HTML</b> enabled tagline that sits between the actual \
                header and the list of packages. You can even add <a \
                href=\"https://github.com\">links</a>!"
```
**template:** was a way to use a custom template, but since we use a based React UI this property is not longer valid.
**tagline:** was a way to inject HTML, for the same reason as *template* is not longer valid.

#### Steps to reproduce:

```
web:
  template: custom.hbs
  tagline: "Some <b>HTML</b> enabled tagline that sits between the actual \
                header and the list of packages. You can even add <a \
                href=\"https://github.com\">links</a>!"
```
Those properties do not have any effect in the UI

####  App Version:	

v2.3.6
