### ISSUE TITLE
Can't adduser on aws ec2 istance

### ISSUE THREAD

**Issue by pietrovismara** [verdaccio/verdaccio#314]
#### My reason:

`adduser` will hang indefinitely after entering username password and email.

#### Steps to reproduce:

When running `npm adduser --registry http://external-aws-ec2.com:4873`. Right now the only ports allowed on the server are 4873 inbound and ssh.

####  App Version:	

2.3.6

####  Config file:	

default

#### Additional information:

Running verdaccio with `DEBUG=express:*` i don't see any request incoming when i confirm my credentials with `adduser` by pressing return.

**Perhaps verdaccio uses a different port for authentication?**

**Comment by juanpicado** [comment]
configuration file is missing

**Comment by pietrovismara** [comment]
It's the default config file:

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

```
