### ISSUE TITLE
Web settings in config.yaml are not applied on 6.x nightly master

### ISSUE THREAD

**Issue by hanc2006** [verdaccio/verdaccio#3174]
**Platform**
 * **version**: verdaccio/verdaccio:nightly-master
 * **platform**: docker

**Describe the bug**
Most of the settings changed in the config.yaml file are not applied.

**To Reproduce**

```yaml
web:
  title: "Custom Title" => works
  darkMode: false => works
  showInfo: false => don't works
  showSettings: false => don't works
  showThemeSwitch: false => don't works
  showFooter: false => don't works
  showSearch: false => don't works
  showRaw: false => don't works
  primary_color: "#0cc" => works
  favicon: https://xxx.ico => don't works
  logo: https://xxxx.com => don't works
  ...
```

**Expected behavior**
The new settings should be applied.
