### ISSUE TITLE
Plugin loader display loading state on logger for each plugin used on conf file

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#321]
#### My reason:

There is no way to know whether any plugin has been loaded. On Docker containers would be really helpful see something in the log.

The expected behaviour would display any kind of verbose about whether the plugin has been loaded or has failed on load.

#### Steps to reproduce:

The following example is an intent to integrate [verdaccio-ldap](https://github.com/Alexandre-io/verdaccio-ldap) plugin. 
https://github.com/verdaccio/docker-examples/tree/master/ldap-verdaccio

####  App Version:	

All

####  Config file:	
```
storage: /verdaccio/storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://verdaccio:389"
      bindDn: "dc=openstack,dc=org"
      bindCredentials: ""
      searchBase: "dc=openstack,dc=org"
      searchFilter: "(cn={{username}})"
      cache: False
      tlsOptions:
        rejectUnauthorized: False

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  #- {type: file, path: verdaccio.log, level: info}

listen:
  - 0.0.0.0:4873
```

#### Additional information:

 - Container:
   - I use local environment
   - I develop / deploy using Docker.

#### Additional verbose log:

```
➜ docker-compose up
Starting ldapverdaccio_verdaccio_1 ... 
Starting ldapverdaccio_verdaccio_1 ... done
Starting ldapverdaccio_ldapserver_1 ... 
Starting ldapverdaccio_ldapserver_1 ... done
Attaching to ldapverdaccio_verdaccio_1, ldapverdaccio_ldapserver_1
ldapserver_1  | 59b6f5e0 @(#) $OpenLDAP: slapd  (Ubuntu) (May 25 2015 13:12:01) $
ldapserver_1  | 	buildd@toyol:/build/buildd/openldap-2.4.31/debian/build/servers/slapd
ldapserver_1  | 59b6f5e0 hdb_db_open: database "dc=nodomain": unclean shutdown detected; attempting recovery.
ldapserver_1  | 59b6f5e0 hdb_db_open: database "dc=openstack,dc=org": unclean shutdown detected; attempting recovery.
ldapserver_1  | 59b6f5e1 slapd starting
ldapserver_1  | 59b6f5e1 bdb(dc=nodomain): BDB0060 PANIC: fatal region error detected; run recovery
verdaccio_1   |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio_1   |  warn --- http address - http://0.0.0.0:4873/ - verdaccio/2.3.6
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/static/main.8c939cd13e9334bbcf2d.js', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/static/logo.png', bytes: 0/0
verdaccio_1   |  http <-- 304, user: undefined(172.22.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0
```
