### ISSUE TITLE
npm token creates duplicate tokens

### ISSUE THREAD

**Issue by kanoshin** [verdaccio/verdaccio#3326]
**Your Environment**
  
 * **verdaccio version**: 5.14.0
 * **node version** [12.x.x, 14.x.x]: 16.16.0
 * **package manager**: npm@8.11.0
 * **os**: mac
 * **platform**: npm

**Describe the bug**

Different runs of `npm token create` command produce duplicate tokens

**To Reproduce**

1. Run `npm token create`
2. Run `npm token create --read-only`
3. Token values and their IDs are going to be identical

**Expected behavior**

Token values are different

**Screenshots, server logs, package manager log**

<img width="688" alt="Screen Shot 2022-08-26 at 12 01 32 PM" src="https://user-images.githubusercontent.com/11817360/186973803-2c79f6ee-16e8-4dc8-9105-d5b359d6be93.png">

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: /Users/kanoshin/.local/share/verdaccio/storage
plugins: ./plugins
web:
  title: Verdaccio
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    auth:
      type: bearer
      token: "XYZ"
packages:
  "@*/*":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
logs: { type: stdout, format: pretty, level: http }

```

**Environment information**

Environment Info:
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    npm: 8.11.0 - /usr/local/bin/npm
  Virtualization:
    Docker: 20.10.14 - /usr/local/bin/docker
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.6.1
  npmGlobalPackages:
    verdaccio: 5.14.0
