### ISSUE TITLE
Since v5.16.0 cannot get tarball file: 404 "file not found"

### ISSUE THREAD

**Issue by vsile** [verdaccio/verdaccio#3517]
**verdaccio version**: 5.16.0 and upper
**node version**: v16.14.0
**package manager**: [npm@8.3.1, yarn@1.22.19]
**os**: linux
**platform**: docker

We had Verdaccio 5.15.4 with Minio storage (RELEASE.2022-10-24T18-35-07Z).
config.yml contains the lines:
```
store:
  minio:
    port: 9000
    region: us-east-1
    endPoint: 10.10.10.10
    accessKey: minioadmin
    secretKey: minioadmin
    useSSL: false
```
It worked fine.

After upgrading to 5.18.0 we get errors on "yarn add @our/package":
```
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://our-verdaccio-site.com/commander/-/commander-9.4.1.tgz: Request failed \"404 Not Found\""
```
If you try to get tarball file with the direct link - https://our-verdaccio-site.com/commander/-/commander-9.4.1.tgz - the same error appears: 404 "file not found".
The file commander-9.4.1.tgz exists in Minio though.

The error appears only since v5.16.0 (I tried 5.16.0, 5.16.1, 5.16.2, 5.16.3, 5.17.0, 5.18.0) 

Debug logs:
```
01.12.2022, 21:09:59 debug--- [Minio] ReadStream<commander/commander-9.4.1.tgz> is opened
01.12.2022, 21:09:59 debug--- [Minio] ReadStream<commander/commander-9.4.1.tgz> received 28174 bytes
01.12.2022, 21:09:59 debug--- [Minio] ReadStream<commander/commander-9.4.1.tgz> is finishing
```

**Comment by juanpicado** [comment]
Could you share a docker compose or something that reproduce how you run minio?

**Comment by vsile** [comment]
Yes, of course.
```
version: "3.8"
services:

  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio
    volumes:
      - /opt/minio:/data
    command:
      - server
      - /data
      - --console-address=:9001
    ports:
      - 9000:9000
      - 9001:9001
    restart: always

networks:
  default:
    name: minio-network
```

**Comment by juanpicado** [comment]
It think is missing the part you run your image, how do you include the plugins etc

**Comment by juanpicado** [comment]
Additionally if you want a playground, you can PR on this repo: https://github.com/verdaccio/e2e-5.x

Create your own docker compose with mini and create a smoke test just like:
https://github.com/verdaccio/e2e-5.x/blob/main/.github/workflows/docker-proxy-nginx-e2e.yml

It's very simple and would be great to have for future releases avoid regressions.

**Comment by vsile** [comment]
Here is verdaccio docker-compose.yml. We have separated minio and verdaccio docker-compose files for some reasons.
```
version: "3.8"
services:

  verdaccio:
    image: verdaccio/verdaccio:5.15.4
    container_name: verdaccio
    volumes:
      - ./verdaccio/config.yaml:/verdaccio/conf/config.yaml
      - ./verdaccio-minio:/verdaccio/plugins/verdaccio-minio
    environment:
      - VERDACCIO_PUBLIC_URL=https://our-verdaccio-site.com
    ports:
      - 4873:4873
    restart: always

networks:
  default:
    name: verdaccio-network
```

It works fine.
After upgrading to 5.18.0 we get error 404 (see above).
