### ISSUE TITLE
Cannot list packages on main screen with verdaccio-aws-s3-storage configured

### ISSUE THREAD

**Issue by stepico-serhii-romaniuk** [verdaccio/verdaccio#3521]
**Your Environment**
 * **verdaccio version**: 5.18.0
 * **node version**: from official docker image `verdaccio/verdaccio:5.18.0`
 * **package manager**: npm, from official docker image `verdaccio/verdaccio:5.18.0`
 * **os**: docker image `verdaccio/verdaccio:5.18.0`
 * **platform**: kubernetes (helm)

**Describe the bug**

After installing chart into kubernetes cluster with preprovisioned aws-s3-storage plugin, application cannot list packages, but can reach them via direct URL.

**To Reproduce**
1. Configuration block from mostly base helm values.
2. Install into cluster with following values,
3. Upload packages into S3 `Verdaccio/storage/` (backup from working old version 4.x.x). Couple GBs.
4. Proceed into UI.

**Expected behavior**
Everything ok on old 4.x.x set up, but...

**Screenshots, server logs, package manager log**
UI reachable, but 0 packages (changed host due security reasons):
![image](https://user-images.githubusercontent.com/115696098/205700955-7f226b7a-2aa1-487a-91f4-4ffca47e3f98.png)

Can reach a package (changed host and package name due security reasons):
![image](https://user-images.githubusercontent.com/115696098/205700339-23ea7300-84c3-4443-ba77-7ff40eca0458.png)

**Configuration files**
Part of very basic values:
```yaml
 configMap: |
  # necessary (see https://github.com/verdaccio/verdaccio/issues/673)
  storage: /verdaccio/storage/data
  
  store:
    aws-s3-storage:
      keyPrefix: Verdaccio/storage/
      bucket: ${bucket}
      region: ${region}
      accessKeyId: ${access_key_id}
      secretAccessKey: ${secret_access_key}

  auth:
    htpasswd:
      file: /verdaccio/storage/htpasswd
      max_users: 4
      algorithm: bcrypt
      rounds: 10

  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
      max_fails: 100

  packages:
    '@*/*':
      access: $all
      publish: $authenticated
      proxy: npmjs

    '**':
      access: $all
      publish: $authenticated
      proxy: npmjs

  middlewares:
    audit:
      enabled: true

  max_body_size: 100m

  server: 
    keepAliveTimeout: 60

  logs: {type: stdout, format: pretty, level: debug}
```
**Dockerfile**
```Dockerfile
FROM verdaccio/verdaccio:5.18.0

ENV NODE_ENV=production
USER root
RUN npm i -g verdaccio-aws-s3-storage@10.3.0

```

**Environment information**
EKS 1.22, Helm 3.8.2, Chart 4.10.3, verdaccio-aws-s3-storage@10.3.0, verdaccio@5.18.0

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- [x] `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:
Pluggin init starts (changed bucket name due security reasons):
```log
verdaccio:plugin:loader loading plugin /usr/local/lib/node_modules/verdaccio/build/plugins/aws-s3-storage
verdaccio:plugin:loader plugin /usr/local/lib/node_modules/verdaccio/build/plugins/aws-s3-storage not found
verdaccio:plugin:loader loading plugin verdaccio-aws-s3-storage
verdaccio:plugin:loader plugin aws-s3-storage is an npm package
erdaccio:plugin:loader plugin is ES6
{"level":30,"time":1670257501552,"pid":8,"hostname":"verdaccio-64b7b6bf68-txp4f","content":"aws-s3-storage","prefix":"verdaccio","msg":"plugin successfully loaded: @{prefix}-@{content}"}
{"level":20,"time":1670257501552,"pid":8,"hostname":"verdaccio-64b7b6bf68-txp4f","keyPrefix":"Verdaccio/storage/","bucket":"MY_BUCKET","msg":"s3: [_getData] bucket: @{bucket} prefix: @{keyPrefix}"}
{"level":20,"time":1670257502155,"pid":8,"hostname":"verdaccio-64b7b6bf68-txp4f","keyPrefix":"Verdaccio/storage/","bucket":"MY_BUCKET","msg":"s3: [_sync] bucket: @{bucket} prefix: @{keyPrefix}"}
{"level":20,"time":1670257502285,"pid":8,"hostname":"verdaccio-64b7b6bf68-txp4f","msg":"s3: [_sync] sucess"}
```
Also found empty response from `/-/verdaccio/data/packages`:
![image](https://user-images.githubusercontent.com/115696098/205701670-0acc747c-c62d-42f6-a846-d9e6036538c7.png)
