### ISSUE TITLE
BUG: error An unexpected error occurred: Request failed 404 Not Found.

### ISSUE THREAD

**Issue by droslean** [verdaccio/verdaccio#3530]
Version: 5.15.4

This happened when we are trying to change the version of a specific package. Our older package is already cached, and when verdaccio tries to get the tarball from the cache it gets 404 because of the version change.

The solution is to manually delete the folder of the package from the cache and try again. That means that Verdaccio can't support multiple versions in the cache. This is a big blocker.

Config:
```yaml
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
web:
  enable: true
  title: Verdaccio
url_prefix: '/'
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
    maxage: 259200m
  yarnpkg:
    url: https://registry.yarnpkg.com/
    cache: true
    maxage: 259200m
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: yarnpkg npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: yarnpkg npmjs
middlewares:
  audit:
    enabled: true
logs:
  - {type: stdout, format: pretty, level: debug}
```

To support multiple version, do we have to enable this somehow in the configuration?
