### ISSUE TITLE
V5.21.1 Doesn't considers logo 

### ISSUE THREAD

**Issue by arathore-gaming** [verdaccio/verdaccio#3612]
For web i have given logo as a .png file but web interface still shows default verdaccio logo.
This was working fine in v5.20.1 for me, issue occurred after upgrading

**Comment by juanpicado** [comment]
Thanks, I was afraid this might happens, could you share your config so I can reproduce ?

**Comment by arathore-gaming** [comment]
Following is the config - 

```YML
# Created by Abhishek Rathore
# TODO: Security, HTTPS

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  enable: true
  title: Ingenuity NPM Repo
  gravatar: true
  darkMode: true
  scope: "@quest"
  showInfo: false
  showSettings: true
  showFooter: true
  showSearch: true
  showDownloadTarball: true
  showRaw: false
  logo: http://10.0.0.217:8082/images/logo.png
  favicon: http://10.0.0.217:8082/images/favicon.ico
  pkgManagers:
    - npm

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000
    # Hash algorithm, possible options are: "bcrypt", "md5", "sha1", "crypt".
    algorithm: bcrypt # by default is crypt, but is recommended use bcrypt for new installations
    # Rounds number for "bcrypt", will be ignored for other algorithms.
    rounds: 10

packages:
  '@quest/*':
    # scoped packages
    access: $authenticated
    publish: arathore
    unpublish: arathore

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true
    
security:
  api:
    jwt:
      sign:
        expiresIn: 360d
        notBefore: 1
    web:
      sign:
        expiresIn: 360d

# log settings
logs: { type: file, path: verdaccio.log, format: pretty-timestamped, level: http }

listen: 0.0.0.0:4873

# experiments:
#  # support for npm token command
#   token: false
#  # support for the new v1 search endpoint, functional by incomplete read more on ticket 1732
#   search: false
#  # disable writing body size to logs, read more on ticket 1912
#   bytesin_off: false
```
