### ISSUE TITLE
in the docker-compse file should set  `user: 1000:1000`  ,to avoid  `permission denied, mkdir` error  

### ISSUE THREAD

**Issue by luojiyin1987** [verdaccio/verdaccio#3665]
**Your Environment**
  
 * **verdaccio version**: 5.22.0
 * **node version** 18.14.0:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [linux Ubuntu 22.04]
 * **platform**: [docker,]

**Describe the bug**
 when use local mirror , docker log   
```
verdaccio  | info --- config file  - /verdaccio/conf/config.yaml
verdaccio  | info --- "crypt" algorithm is deprecated consider switch to "bcrypt". Read more: https://github.com/verdaccio/monorepo/pull/580
verdaccio  | info --- plugin successfully loaded: verdaccio-htpasswd
verdaccio  | info --- plugin successfully loaded: verdaccio-audit
verdaccio  | warn --- http address - http://0.0.0.0:4873/ - verdaccio/5.22.0
verdaccio  | info <-- 192.168.2.114 requested 'GET /create-next-app'
verdaccio  | info --- auth/allow_action: access granted to: undefined
verdaccio  | info --- allowed access for create-next-app
verdaccio  | http <-- 200, user: null(192.168.2.114), req: 'GET /create-next-app', bytes: 0/0
verdaccio  | info --- making request: 'GET https://registry.npmjs.org/create-next-app'
verdaccio  | http --- ERR, req: 'GET https://registry.npmjs.org/create-next-app', error: read ECONNRESET
verdaccio  | http <-- 503, user: null(192.168.2.114), req: 'GET /create-next-app', error: resource unavailable
verdaccio  | info <-- 192.168.2.114 requested 'GET /create-next-app'
verdaccio  | info --- auth/allow_action: access granted to: undefined
verdaccio  | info --- allowed access for create-next-app
verdaccio  | http <-- 200, user: null(192.168.2.114), req: 'GET /create-next-app', bytes: 0/0
verdaccio  | info --- making request: 'GET https://registry.npmjs.org/create-next-app'
verdaccio  | http --- 200, req: 'GET https://registry.npmjs.org/create-next-app' (streaming)
verdaccio  | http --- 200, req: 'GET https://registry.npmjs.org/create-next-app', bytes: 0/6657692
verdaccio  | error--- unexpected error: EACCES: permission denied, mkdir '/verdaccio/storage/create-next-app'
verdaccio  | Error: EACCES: permission denied, mkdir '/verdaccio/storage/create-next-app'
verdaccio  | http <-- 500, user: null(192.168.2.114), req: 'GET /create-next-app', error: internal server error
^CGracefully stopping... (press Ctrl+C again to force)
```

**To Reproduce**

**Expected behavior**

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**
[Inspiration](https://forums.docker.com/t/docker-noob-asking-for-help-eacces-permission-denied-mkdir-home-wiki/119133)

before docker-compose file 
```
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    container_name: 'verdaccio'
    ports:
      - '4873:4873'
    volumes:
      - './storage:/storage'
      - './config:/verdaccio/conf'
      - './plugins:/plugins'
~                               
```
I   change it  to 
```yaml
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    user: 1000:1000
    container_name: 'verdaccio'
    ports:
      - '4873:4873'
    volumes:
      - './storage:/storage'
      - './config:/verdaccio/conf'
      - './plugins:/plugins'                              
```
it work, no error!!!

I hope this is helpful to newbies。

this is  my config file , it  is in  config folder。
├── config
│   └── config.yaml

```yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /storage
# path to a directory with plugins to include
plugins: /plugins
# print logs
# logs: ./logs

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # convert your UI to the dark side
  # darkMode: true
  #  HTML tags injected after manifest <scripts/>
  # scriptsBodyAfter:
  #    - '<script type="text/javascript" src="https://my.company.com/customJS.min.js"></script>'
  #  HTML tags injected before ends </head>
  #  metaScripts:
  #    - '<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>'
  #    - '<script type="text/javascript" src="https://browser.sentry-cdn.com/5.15.5/bundle.min.js"></script>'
  #    - '<meta name="robots" content="noindex" />'
  #  HTML tags injected first child at <body/>
  #  bodyBefore:
  #    - '<div id="myId">html before webpack scripts</div>'
  #  Public path for template manifest scripts (only manifest)
  #  publicPath: http://somedomain.org/
# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

server:
  # deprecated
  keepAliveTimeout: 60
#  rateLimit:
#    windowMs: 1000
#    max: 10000

middlewares:
  audit:
    enabled: true
listen: 0.0.0.0:4873

# log settings
logs:
  # Logger as STDOUT
  { type: stdout, format: pretty, level: http }
  # Logger as STDOUT as JSON
  # { type: stdout, format: json, level: http }
  # Logger as STDOUT as JSON
  # { type: stdout, format: pretty-timestamped, level: http }
  # Logger as STDOUT as custom prettifier
  # { type: stdout, plugin: { dest: '@verdaccio/logger-prettify' : options: { foo: 1, bar: 2}}, level: http }
  # Logger as file
  # { type: file, path: verdaccio.log, level: http}
  # FIXME: this should be documented
  # More info about log rotation https://github.com/pinojs/pino/blob/master/docs/help.md#log-rotation

# This affect the web and api (not developed yet)
i18n:
  web: en-US
```

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Go ahead, thanks for sharing that, I wasn't aware of that property 🙏

**Comment by luojiyin1987** [comment]
@juanpicado  ,  I hope update the [docment](https://verdaccio.org/docs/docker/)

**Comment by juanpicado** [comment]
@luojiyin1987 looks a great idea, if you need help where to add this info, just update this two files at this repo. 


<img width="362" alt="Screenshot 2023-03-11 at 18 47 43" src="https://user-images.githubusercontent.com/558752/224503817-d9df1306-1fcc-446a-841b-345dfe5ecd14.png">

**Comment by luojiyin1987** [comment]
@juanpicado   I create a PR. the docker-compose.yml  should be :
```yaml
version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    container_name: 'verdaccio'
    ports:
      - '4873:4873'
    volumes:
      - './storage:/storage'
      - './config:/verdaccio/conf'
      - './plugins:/plugins'     
```

I want to know who maintain the docker file , I have some  confusion.
