### ISSUE TITLE
Version 5.22.0 fails to start with enabled `experiments`

### ISSUE THREAD

**Issue by justusbunsi** [verdaccio/verdaccio#3666]
**Your Environment**
  
 * **verdaccio version**: 5.22.0
 * **node version** [12.x.x, 14.x.x]: v18.14.0
 * **package manager**: npm@9.3.1
 * **os**: linux
 * **platform**: docker

**Describe the bug**

Verdaccio 5.22.0 is not able to start when passing a configuration with following changes according to the default configuration:

```diff
- #experiments:
+ experiments:
+   token: true
```

The only change according to the release notes is https://github.com/verdaccio/verdaccio/pull/3658.

**To Reproduce**

- Adjust the default configuration of the repository (`./conf/default.yaml`) according to the diff shown above
- Run `docker run --rm -it -p "4873:4873" -e "DEBUG=verdaccio*" -v "./conf/default.yaml:/verdaccio/conf/config.yaml" verdaccio/verdaccio:5.22.0@sha256:dc43f691adf8629fd66d8fdf0d874d37fdeb772d612b7624d343dd544f1daeed`

**Expected behavior**

Verdaccio starts properly without errors.

**Screenshots, server logs, package manager log**

See debug output below.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

<details>
  <summary>Adjusted default configuration</summary>

Comments have been removed for better readability.

```yaml
storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all

    publish: $authenticated
    unpublish: $authenticated

    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs: { type: stdout, format: pretty, level: http }

experiments:
  token: true

```
</details>

**Environment information**

```
Environment Info:
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (10) x64 Common KVM processor
  Binaries:
    npm: 9.3.1 - /usr/local/bin/npm
  npmGlobalPackages:
    verdaccio: 5.22.0
```

**Debugging output**

```log
  verdaccio:config:parse parse config file /verdaccio/conf/config.yaml +0ms
  verdaccio:config:parse parsing config file: '/verdaccio/conf/config.yaml' +3ms
cannot open config file /verdaccio/conf/config.yaml: false
```

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
