### ISSUE TITLE
E401 error on npm publish to Verdaccio in container

### ISSUE THREAD

**Issue by Medvind2140** [verdaccio/verdaccio#3699]
ENVIRONMENT
verdaccio version: 5.22.1
node version: 19.8.1
package manager: npm 9.5.1
Container installed on Raspberry PI with Docker-compose

BUG
Get an E401 error when trying to: npm publish --registry hostname:port 
See image.

I then tried to do the same on an older Verdaccio version 4.8.1, and there was no problem. 

So the problems seems to be with the latest version. It looks like the  "/" character is converted to %2f in the PUT request that is initiated with npm publish. Is anyone else having this problem?

On server(Pi):
```console 
mkdir verdaccio && cd $_
vim docker-compose.yml 
//see image for config

docker-compose up 
```
On client(Linux)
``` console
mkdir project && cd $_
git init && npm init
vim package.json 
//see image for config

npm adduser --registry host:port
npm login --registry host:port
npm publish --registry host:port
```
**Expected behavior**
- Package published to Verdaccio 
- Instead get 401 error 

![Screenshot from 2023-03-22 18-07-42](https://user-images.githubusercontent.com/36833016/226986952-50c022b7-8067-4498-bd24-cd191ec9c9e4.png)

**Comment by juanpicado** [comment]
what is on the docker-compose.yml  would be helpful

**Comment by johanneslosch** [comment]
> what is on the docker-compose.yml would be helpful

@juanpicado as in the upper part of the screenshot shown

docker-compose.yml
```yml
version: '3.1'
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    restart: always
    user: 1000:1000
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './config:/verdaccio/config'
      - './plugins:/verdaccio/plugins'
networks:
  node-network:
    driver: bridge
```


@Medvind2140 as I was facing the issue, I solved it by logging in with the scope parameter and adding the registry to the package.json (since it should only be exposed to verdaccio in my case), so I could simply run `npm publish`
