### ISSUE TITLE
General cache issue in Verdaccio Web UI

### ISSUE THREAD

**Issue by batuhanisildak-malwation** [verdaccio/verdaccio#3769]
**Your Environment**
  
 * **verdaccio version**: 5.24.1
 * **node version** [18.16.0]:
 * **package manager**: [npm@9.5.1]
 * **os**: [linux]
 * **platform**: [docker]

**Describe the bug**

There is a general cache problem in verdaccio. Sometimes when I login, system doesn't get packages and give me a screen like this:

![cache_1](https://user-images.githubusercontent.com/105045532/234616206-00428647-bb05-4ce0-a5a8-2bb9d6bf623e.png)

Also when I try to logout, it looks like I logged out but I can see the packages. All of the bugs are related to the request cache I assume. Here is the screenshot about the request sent from Verdaccio:

![cache_2](https://user-images.githubusercontent.com/105045532/234618570-0f0af2d9-407b-41dd-93e9-b1a70d98a8f5.png)

You can see it's coming from disk cache.

**To Reproduce**

Just go to the verdaccio website and logout. After refreshing the package I still can see the packages, which shouldn't be the case.

**Expected behavior**

It shouldn't go to the disk cache in every request, it should get the new data coming from the backend.
@juanpicado I couldn't find where to change in codebase but we've been dealing with this problem for 3 months, let's fix this.

**Comment by mbtools** [comment]
Try setting `html_cache` to `false`
https://verdaccio.org/docs/next/webui#configuration

**Comment by batuhanisildak-malwation** [comment]
Here is my config file:
```yaml
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: Private Registry System
  darkMode: true
  html_cache: false
  showThemeSwitch: true
auth:
  auth-memory:
    users:
      team:
        name: ***
        password: team123

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  yarn:
    url: https://registry.yarnpkg.com/


packages:
  '@*/*':
    access: team
    publish: team
    unpublish: team
    proxy: yarn

  '**':
    access: team
    publish: team
    unpublish: team
    proxy: yarn

server:
  keepAliveTimeout: 60

# https://verdaccio.org/docs/configuration#offline-publish
publish:
  allow_offline: false

security:
  api:
    legacy: true
    jwt:
      sign:
        expiresIn: 29d
      verify:
        token: [value]
  web:
    sign:
      expiresIn: 1h # 1 hour by default
    verify:
      token: [value]

max_body_size: 100mb

listen:
  - localhost:4873            # default value
https:
  key: /verdaccio/certs/privkey.pem
  cert: /verdaccio/certs/cert.pem
  ca: /verdaccio/certs/chain.pem

logs: { type: stdout, format: pretty, level: http }
```

you can see that html_cache is set to false, but the bug still occurs.
Can you give a hint @mbtools ?
