### ISSUE TITLE
Web UI Search Pings Proxy

### ISSUE THREAD

**Issue by mlucool** [verdaccio/verdaccio#385]
#### My reason:

When I start typing in the search box on the web UI, it will start searching the proxy. I would expect that when I search on the web UI, it would only be local search becauses the only data that appears on this UI is only ever local. This extra search also slows down the UI's responsiveness.

#### Steps to reproduce:
Set config.yaml to:
```
packages:
  # Stop search from going to npmjs
  'foo-*':
    access: $all
    publish: $authenticated

  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
```
Then go to the UI. If you search for `foo-b` no search data is leaked. If you search for `baz` it will search to npmjs although nothing that I can see in the results come from there. 

Output during `foo-b` search:
```
 http --> 404, req: 'GET https://registry.npmjs.org/foo-bar' (streaming)
 http --> 404, req: 'GET https://registry.npmjs.org/foo-bar', bytes: 0/2
```

####  App Version:	
2.6.3
