### ISSUE TITLE
Scoped packages not showing up in the WebUI

### ISSUE THREAD

**Issue by marekl** [verdaccio/verdaccio#389]
#### My reason:

Publishing a scoped package such as `@company/mypackage` works correctly and allows the package to be installed using `npm`. However the package does not show up anywhere on the WebUI.

#### Steps to reproduce:

* Run verdaccio in a docker container
* Publish a scoped package such as `@company/mypackage`
* Access the webui `http://localhost:8473`
* The package is not displayed in the index and searching for it does not return anything

Publishing the exact same package but without the scope works as expected.

####  App Version:	
verdaccio@2.6.3

####  Config file:
``` yaml
storage: /verdaccio/storage

web:
  enable: true
  title: "Company Verdaccio"

auth:
  ldap:
    type: ldap
    groupNameAttribute: "cn"
    client_options:
      url: "ldaps://ldap.company.com"
      searchBase: "ou=personnel,dc=dir,dc=company,dc=com"
      searchFilter: "(uid={{username}})"
      cache: False
      searchAttributes:
        - memberOf

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}

```

#### Additional information:
Verdaccio runs in a docker container built using the following config:
``` Dockerfile
# Based on: https://github.com/verdaccio/verdaccio/blob/master/Dockerfile
FROM node:8.7.0-alpine
LABEL maintainer="https://github.company.com/user/verdaccio"

RUN apk --no-cache add openssl && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 && \
    chmod +x /usr/local/bin/dumb-init && \
    apk del openssl

ENV APPDIR /usr/local/app

WORKDIR $APPDIR

ADD . $APPDIR

ENV NODE_ENV=production

RUN npm config set registry http://registry.npmjs.org/ && \
    npm install -g verdaccio@latest verdaccio-ldap@latest

RUN mkdir -p /verdaccio/storage /verdaccio/conf

ADD config.yaml /verdaccio/conf/config.yaml

RUN addgroup -S verdaccio && adduser -S -G verdaccio verdaccio && \
    chown -R verdaccio:verdaccio "$APPDIR" && \
    chown -R verdaccio:verdaccio /verdaccio

USER verdaccio

ENV PORT 4873
ENV PROTOCOL http

EXPOSE $PORT

VOLUME ["/verdaccio"]

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]

CMD verdaccio --config /verdaccio/conf/config.yaml --listen $PROTOCOL://0.0.0.0:${PORT}
```

The host is running `macOS 10.12.6`.

**Comment by juanpicado** [comment]
Are you using a Nginx or Apache as a proxy?

**Comment by marekl** [comment]
Nope.

I am running the container standalone for testing.

__Build Command:__
``` bash
docker build -t company-verdaccio .
```

__Run Command:__
``` bash
docker run -it --rm --name company-verdaccio -p 4873:4873 company-verdaccio
```

This is using Docker for Mac.

**Comment by juanpicado** [comment]
I have the same set up and works for me. I'll have to check again.

**Comment by Meeeeow** [comment]
Same here, i can't reproduce this issue with:
```yaml
packages:
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
```
