### ISSUE TITLE
Failed to start verdaccio: Wed, 28 Jun 2023 19:31:31 GMT express deprecated req.host: Use req.hostname instead at node_modules/verdaccio/build/api/endpoint/api/package.js:58:19

### ISSUE THREAD

**Issue by ryanbas21** [verdaccio/verdaccio#3904]
**Your Environment**
  
 * **verdaccio version**: 5.x.x
 * **node version** [12.x.x, 14.x.x]:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [mac, windows@10, linux]
 * **platform**: [npm, docker, helm, other]

verdacio: 5.24.0
node 18.12.1
npm 9.1.1

This is what I did: Installed verdaccio in an nx workspace using their executor.
This installs all dependencies
started my verdaccio server first time
Published a package to verdaccio
went to install npm install --registry=my-registry [package-name] in a new repo

server crashed with this error:

Failed to start verdaccio: Wed, 28 Jun 2023 19:31:31 GMT express deprecated req.host: Use req.hostname instead at node_modules/verdaccio/build/api/endpoint/api/package.js:58:19

I then edited the node_module at that line listed to `hostname` and the server worked fine.

**Expected behavior**

server shouldn't crash!

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
# path to a directory with all packages
storage: ../tmp/local-registry/storage

auth:
  htpasswd:
    file: ./htpasswd

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
   '**':
    access: $all
    publish: $authenticated

    # if package is not available locally, proxy requests to npm registry
    proxy: npmjs

# log settings
logs:
  type: stdout
  format: pretty
  level: http

```
**Environment information**

Environment Info:
  System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/96984_1687891451773/bin/npm
  Virtualization:
    Docker: 20.10.17 - /usr/local/bin/docker
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.58
    Firefox: 114.0.2
    Safari: 16.4

I can do some reinstalls of this after and replicate it but im in the midst of testing for a release so ill add more info if needed as i can later
