### ISSUE TITLE
What caused the package.json file content to be abnormal?

### ISSUE THREAD

**Issue by 89ao** [verdaccio/verdaccio#3913]
**Your Environment**
  
 * **verdaccio version**: v5.21.1
 * **node version** [12.x.x, 14.x.x]:v12.18.4
 * **package manager**: [npm@7, pnpm@6, yarn@2] 6.14.6
 * **os**: [mac, windows@10, linux] CentOS Linux release 7.2 (Final)
 * **platform**: [npm, docker, helm, other] docker

**Describe the bug**

Recently, we found that the metadata information of the local repository is inconsistent with that of the official package.
<img width="848" alt="image" src="https://github.com/verdaccio/verdaccio/assets/5635923/8cc4e44b-7617-484c-8d07-f135683b5f5e">
This caused our users to install packages that did not meet their expectations.

After some debugging ,I found that the package.json file context is like below:
```
        "users": {},
        "dist-tags": {
                "latest": "3.0.0-alpha.7-for-vscode",
                "next": "3.0.0-alpha.9-for-vscode"
        },
```
However, the correct content should actually be:
```
        "dist-tags": {
                "latest": "2.8.8",
                "next": "3.0.0-alpha.12"
        },
```

But once I delete this package.json, the content is correct when it's automatically generated.

**To Reproduce**

 Actually , there are absolutely no reproducible clues available.

**Expected behavior**
1. How to fix all packages.json files?
2. How to solve the problem of "syncing issue"?

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: /repo/npm/verdaccio/storage
http_proxy: http://11.139.240.79:3128
https_proxy: http://11.139.240.79:3128
no_proxy: localhost,127.0.0.1
plugins: ./plugins
url_prefix: /npm/
max_body_size: 10mb

listen:
   -  0.0.0.0:4873

web:
  title: Tencent-NPM

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 4m
    timeout: 10s
    agent_options:
      keepAlive: true
      maxSockets: 40
      maxFreeSockets: 10
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true
server:
  keepAliveTimeout: 60

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
```

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Reproduced, It might be fixed with 6.x versions, I'll check if is fixable on 5.x versions.

**Comment by 89ao** [comment]
thanks @juanpicado

**Comment by mbtools** [comment]
In the case above, local `latest` is `3.0.0-alpha.7-for-vscode` which is larger then the remote `latest` that's `2.8.8`.

The dist-tags in Verdaccio are only updated if the remote dist-tag versions are larger than the local ones (`semver.lte`):

https://github.com/verdaccio/verdaccio/blob/0bd3e8e7e778e7a09402160ac2ca76c92812823a/packages/store/src/lib/storage-utils.ts#L301-L312

The reason for this check is that there might be newer version in Verdaccio that are not on the remote registry. 

I don't see a way to change this behaviour. Suggest closing.

**Comment by 89ao** [comment]
@mbtools thanks for your reply .

But problems is that if the author change the "latest version" to another version,verdaccio seems to not update the metadata.
This is how I reproduced it:
```
1. I uploaded a package to npmjs, which has two versions: 1.1.0 and 2.0.0. The current latest tag points to 2.0.0 by default.
2. On the local client, I executed npm install pkg@latest and confirmed that version 2.0.0 (the latest version) could be installed from the verdaccio node.
3. Since version 2.0.0 has some potential flaws, I needed to point the latest tag to 1.1.0 (which is allowed by npmjs). Therefore, I ran npm dist-tag add pkg@1.1.0 latest and npm publish.
4. When I executed npm view pkg locally, I found that the latest tag still showed 2.0.0 (it didn't update to 1.1.0 like it did on [npmjs.com](https://npmjs.com/)).
```
Up to this point, I believe Verdaccio's behavior is inconsistent with that of [npmjs.com](https://npmjs.com/). Please reconsider whether this issue needs to be fixed. @mbtools @juanpicado

**Comment by mbtools** [comment]
I tried to reproduce it. After `npm dist-tag add pkg@1.1.0 latest`, Verdaccio is updated correctly and `latest` points to `1.1.0`. It works correctly.

When you run `npm publish` afterwards, it will update Verdaccio with a new version, which will a) pull the package from npm and b) update the dist tag to what's in npm. After setting `latest`, don't publish again to Verdaccio.

**Comment by 89ao** [comment]
thanks @mbtools , May I ask what version are you using?

Cause every time I try it ,It's all the same.(Sorry that the `npm publish` was a typo,cause I did't run it.)
--More precisely, I executed dist-tag add on [npmjs.com](https://npmjs.com/), and then ran npm view from Verdaccio.

for example I'm using this package https://www.npmjs.com/package/motor-test-version-change1?activeTab=versions

**Comment by 89ao** [comment]
here is my configuration with verdaccio v5.21.1:
```
# path to a directory with all packages
storage: /opt/verdaccio/storage


# path to a directory with plugins to include
plugins: ./plugins

url_prefix: /npm/

max_body_size: 10mb

listen:
   -  0.0.0.0:4873


web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  enable: false
  title:NPM

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 4m
    timeout: 10s
    agent_options:
      keepAlive: true
      maxSockets: 40
      maxFreeSockets: 10
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true
server:
  keepAliveTimeout: 60

# log settings
log:
  - {type: stdout, format: pretty, level: http}
  #- {type: stdout, format: pretty-timestamped, level: debug}
  #- {type: file, path: verdaccio.log, level: info}
```
