### ISSUE TITLE
npm profile commands giving 404 error (change password via CLI)

### ISSUE THREAD

**Issue by Mindaugas-Jacionis** [verdaccio/verdaccio#392]
#### My reason:  
There is a need to change password for logged user from terminal. `npm` has `profile` for that.  
  
#### Steps to reproduce:  
On localhost setup:  
`npm --registry http://localhost:4873 profile set password`  
This prompts message for current, new & repeat new password. Once you submit all required input. You get `404` error.  

####  App Version:	
```
verdaccio --version
2.6.3
```

####  Config file:	
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /Users/myUser/.local/share/verdaccio/storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@myScope/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: file, path: verdaccio.log, level: info}
```

#### Additional information:

	
- [Log file](https://github.com/verdaccio/verdaccio/files/1430964/2017-10-31T14_05_16_239Z-debug.log)  
 - `npm` registry config: 
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.5.1 node/v8.4.0 darwin x64"

; userconfig /Users/myUser/.npmrc
@nord:registry = "http://localhost:4873/"
password = "myPassword"
registry = "https://registry.npmjs.org/"

; node bin location = /Users/myUser/.nvm/versions/node/v8.4.0/bin/node
; cwd = /Users/myUser
; HOME = /Users/myUser
; "npm config ls -l" to show all defaults.
```
 - Windows, OS X/macOS, or Linux?:  macOS
 - Container:
   - I use local environment  

#### Comments:
- Error ocures no mater if registry is set using `npm set registry http://localhost:4873/` or `npm set @scopeName:registry http://localhost:4873/`
- Any other `profile` command will give 404 as well, i.e. `npm --registry http://localhost:4873/ profile get`

### Context

https://docs.npmjs.com/cli/profile
