### ISSUE TITLE
Token not properly passed to FontAwesome repo

### ISSUE THREAD

**Issue by bartoszhernas** [verdaccio/verdaccio#3970]
**Your Environment**
Installed verdaccio with latest HELM, pod uses "v5.21.1"

Trying to install using PNPM 8.3.0
NODE: v16.20.1

**Describe the bug**
Trying to use Verdaccio to proxy pass auth token to access PRO icons of FontAwesome. Looks like passing of the token is wrong as I am getting 403 errors from FontAwesome which results in 404 errors in Verdaccio

If I add 

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=XXXXXXXXXXXXXXXXXX
```
with the same token to .npmrc, then the installation works just fine

**To Reproduce**
Set up fontawesome uplink and try to fetch pro package

**Expected behavior**

Uplink properly authenticates and package is cached and available

**Screenshots, server logs, package manager log**

PNPM:
```
 ERR_PNPM_FETCH_404  GET https://verdaccio.hern.as/@fortawesome%2Fpro-solid-svg-icons: Not Found - 404
```
Verdaccio trace logs:
```
info --- allowed access for @fortawesome/react-native-fontawesome 
info --- making request: 'GET https://npm.fontawesome.com/@fortawesome%2Freact-native-fontawesome' 
http --- 403, req: 'GET https://npm.fontawesome.com/@fortawesome%2Fpro-solid-svg-icons' (streaming) 
http --- 403, req: 'GET https://npm.fontawesome.com/@fortawesome%2Fpro-solid-svg-icons', bytes: 4/915 
http <-- 404, user: fym(51.158.130.170 via 100.64.2.5), req: 'GET /@fortawesome%2Fpro-solid-svg-icons', error: no such package available 
http --- 403, req: 'GET https://npm.fontawesome.com/@fortawesome%2Fpro-light-svg-icons' (streaming) 
http --- 403, req: 'GET https://npm.fontawesome.com/@fortawesome%2Fpro-light-svg-icons', bytes: 4/915 
http <-- 404, user: fym(51.158.130.170 via 100.64.1.210), req: 'GET /@fortawesome%2Fpro-light-svg-icons', error: no such package available 
http --- 403, req: 'GET https://npm.fontawesome.com/@fortawesome%2Freact-native-fontawesome' (streaming) 
http --- 403, req: 'GET https://npm.fontawesome.com/@fortawesome%2Freact-native-fontawesome', bytes: 4/915 
http <-- 404, user: fym(51.158.130.170 via 100.64.2.137), req: 'GET /@fortawesome%2Freact-native-fontawesome', error: no such package available 
```

```
}
REQUEST make request https://registry.npmjs.org/@hookform%2Fresolvers
REQUEST onRequestResponse https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons 403 {
  server: 'CloudFront',
  date: 'Thu, 10 Aug 2023 16:53:02 GMT',
  'content-type': 'text/html',
  'content-length': '915',
  connection: 'close',
  'x-cache': 'Error from cloudfront',
  via: '1.1 58a361324cd2b1576fcc05c5471b9b12.cloudfront.net (CloudFront)',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-amz-cf-id': 'MPBTHuY_9LMCIgXQjQiMNPxB7hS61UMHb6cUYxnwfoT-nzfVubJ2Sw=='
}
REQUEST reading response's body
REQUEST finish init function https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons
REQUEST response end https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons 403 {
  server: 'CloudFront',
  date: 'Thu, 10 Aug 2023 16:53:02 GMT',
  'content-type': 'text/html',
  'content-length': '915',
  connection: 'close',
  'x-cache': 'Error from cloudfront',
  via: '1.1 58a361324cd2b1576fcc05c5471b9b12.cloudfront.net (CloudFront)',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-amz-cf-id': 'MPBTHuY_9LMCIgXQjQiMNPxB7hS61UMHb6cUYxnwfoT-nzfVubJ2Sw=='
}
REQUEST end event https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons
REQUEST has body https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons 915
REQUEST emitting complete https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons


REQUEST {
  url: 'https://npm.fontawesome.com/@fortawesome%2Fpro-regular-svg-icons',
  method: 'GET',
  headers: {
    Accept: 'application/json;',
    'Accept-Encoding': 'gzip',
    'User-Agent': 'npm (hidden)',
    authorization: 'Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'x-forwarded-for': '51.158.130.170, 100.64.2.137',
    via: '1.1 1d998d42e81d (Verdaccio)',
    'Content-Type': 'application/json'
  },
  body: 'true',
  encoding: null,
  gzip: true,
  timeout: 30000,
  strictSSL: true,
  agentOptions: { keepAlive: true, maxSockets: 40, maxFreeSockets: 10 },
  callback: [Function (anonymous)]
}
```

The weird thing is, if I go bash into container, open node and run this:
```
// request Request 
(function(callback) {
    'use strict';
        
    const httpTransport = require('https');
    const responseEncoding = 'utf8';
    const httpOptions = {
        hostname: 'npm.fontawesome.com',
        port: '443',
        path: '/@fortawesome%2Fpro-regular-svg-icons',
        method: 'GET',
        headers: {"Authorization":"Bearer XXXXXXXXXXXXXX","Accept":"application/json","User-Agent":"npm (hidden)","x-forwarded-for":"51.158.130.170, 100.64.1.210","via":"1.1 1d998d42e81d (Verdaccio)","Content-Type":"application/json"}
    };
    httpOptions.headers['User-Agent'] = 'node ' + process.version;
 
    // Paw Store Cookies option is not supported

    const request = httpTransport.request(httpOptions, (res) => {
        let responseBufs = [];
        let responseStr = '';
        
        res.on('data', (chunk) => {
            if (Buffer.isBuffer(chunk)) {
                responseBufs.push(chunk);
            }
            else {
                responseStr = responseStr + chunk;            
            }
        }).on('end', () => {
            responseStr = responseBufs.length > 0 ? 
                Buffer.concat(responseBufs).toString(responseEncoding) : responseStr;
            
            callback(null, res.statusCode, res.headers, responseStr);
        });
        
    })
    .setTimeout(0)
    .on('error', (error) => {
        callback(error);
    });
    request.write("true")
    request.end();
    

})((error, statusCode, headers, body) => {
    console.log('ERROR:', error); 
    console.log('STATUS:', statusCode);
    console.log('HEADERS:', JSON.stringify(headers));
    console.log('BODY:', body);
});

```
then it all works fine. Same with CURL from my computer 
**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```

  # path to a directory with all packages
  storage: /verdaccio/storage/data

  web:
    # WebUI is enabled as default, if you want disable it, just uncomment this line
    #enable: false
    title: Verdaccio Hern.as

  auth:
    htpasswd:
      # Do not change this path if secrets htpasswd is used.
      file: /verdaccio/storage/htpasswd
      # Maximum amount of users allowed to register, defaults to "+infinity".
      # You can set this to -1 to disable registration.
      max_users: -1

  # a list of other known repositories we can talk to
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
      agent_options:
        keepAlive: true
        maxSockets: 40
        maxFreeSockets: 10
    fortawesome:
      cache: false
      url: https://npm.fontawesome.com/
      auth: 
        type: bearer
        token_env: FA_TOKEN

  packages:
    '@fortawesome/*':
      # scoped packages
      access: $authenticated
      publish: $authenticated
      proxy: fortawesome

    '**':
      access: $authenticated
      publish: $authenticated
      proxy: npmjs

  # To use `npm audit` uncomment the following section
  middlewares:
    audit:
      enabled: true

  # log settings
  log: {type: stdout, format: pretty, level: http}
  # log: {type: file, path: verdaccio.log, level: trace}

```
**Environment information**

```
~ $ verdaccio --info

Environment Info:
  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (4) x64 AMD EPYC 7543 32-Core Processor
  Binaries:
    npm: 9.3.1 - /usr/local/bin/npm
  npmGlobalPackages:
    verdaccio: 5.21.1
```
**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇
