### ISSUE TITLE
Unpublish doesn't work correctly

### ISSUE THREAD

**Issue by arshtepe** [verdaccio/verdaccio#402]
#### Steps to reproduce:
I publish my test repository, with name xmlparser, then i unpublish repository. 
After unpublish repository must be remove, but i have public repository with same name https://www.npmjs.com/package/xmlparser

####  App Version:	
2.6.6

#### Additional information:
 - nodejs 8.9.1, npm 5.5.1
 - Ubuntu 16.04
 - I have no change in my config
 - Container:
   - I use local environment

**Comment by sergeysova** [comment]
@arshtepe That repository not about npmjs.com

**Comment by sergeysova** [comment]
@arshtepe You can override public packages, not delete.

**Comment by juanpicado** [comment]
@cxreg I wonder your comment, Do you override a public repo using an existing version on npmjs ?

**Comment by stefanedberg** [comment]
I'm having a similar issue:

Logging in:

```
$ npm login --registry http://registry.address.com:4873
Username: (myusername) 
Password: (<default hidden>) 
Email: (this IS public) (my@username.com) 
Logged in as myusername on http://registry.address.com:4873/.
```

Trying to unpublish:
```
$ npm unpublish test-package --force --registry http://registry.address.com:4873 --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'unpublish',
npm verb cli   'test-package',
npm verb cli   '--force',
npm verb cli   '--registry',
npm verb cli   'http://registry.address.com:4873',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.1
npm WARN using --force I sure hope you know what you are doing.
npm verb getPublishConfig null
npm verb request uri http://registry.address.com:4873/test-package?write=true
npm verb request no auth needed
npm info attempt registry request try #1 at 12:54:02
npm verb request id 1a412796c2fe7be9
npm http request GET http://registry.address.com:4873/test-package?write=true
npm http 403 http://registry.address.com:4873/test-package?write=true
npm verb headers { 'x-powered-by': 'verdaccio/3.0.0-beta.2',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '83',
npm verb headers   etag: 'W/"53-G0xtsTZ3/w1wBC05mdUesnUbptw"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6jFK',
npm verb headers   date: 'Mon, 12 Mar 2018 11:54:02 GMT',
npm verb headers   connection: 'keep-alive' }
npm info unpublish http://registry.address.com:4873/test-package not published
- test-package
npm verb exit [ 0, true ]
npm info ok 
```

My verdaccio config:
```
...
auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

listen:
  0.0.0.0:4873

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
...
```

http://registry.address.com:4873/#/detail/test-package exists
