### ISSUE TITLE
Getting a EADDRNOTAVAIL error

### ISSUE THREAD

**Issue by napindc** [verdaccio/verdaccio#414]
#### My reason:

I'm trying to start up Verdaccio on a public IP, so that several of my servers can pull from it. But when I start up Verdaccio, it gives the following error: ```fatal --- cannot create server: listen EADDRNOTAVAIL PUBLIC_IP_ADDRESS:8443```. I've also tried with with the 4873 port, but that didn't fix it.

#### Steps to reproduce:

Install verdaccio, 

####  App Version:	
Verdaccio 2.6.6

####  Config file:	
```
listen: 'https://<PUBLIC-FQDN>:8443'
https:
  key: '/path/key'
  cert: '/path/cert'
  ca: /path/ca'
```

#### Additional information:
I've also made sure no node processes were running on the server, via ```ps -ef | grep node```
