### ISSUE TITLE
How would I list multiple uplinks for the same package-pattern?

### ISSUE THREAD

**Issue by UnitedMarsupials** [verdaccio/verdaccio#425]
I'm configuring several Verdaccio servers -- one for each of our datacenters.

They will be used to both:

- host the packages with names matchin `@foo/*`
- act as caching proxy for all _other_ packages (with npmjs.org being the upstream)

We'd like to be able to _publish_ to any of our servers and then be able to download via any other.

To this end I configured the `uplinks` section thus:
```yaml
uplinks:
  'npmjs':
    url: 'https://registry.npmjs.org/'
    cache: true
  'foo_0':
    cache: false
    url:  https://master04.dal5.example.net:4874
  'foo_1':
    cache: false
    url:  https://proxy.nyc.example.net:4874
  'foo_2':
    cache: false
    url:  http://build01.sea01.example.net:4873
```
and the `packages` section as follows:
```yaml
packages:
  '@foo/*':
    access: $all
    publish: $authenticated
    proxy: 'foo*'
  '*':
    access: $all
    publish: $authenticated
    proxy: npmjs
```
The non-foo packages are downloaded from npmjs nicely. But there is no attempt to contact the `foo_`-uplinks for the packages matching `foo*`. What am I doing wrong? Thank you!

**Comment by UnitedMarsupials** [comment]
Ok, answering my own question here, sigh... There is no way, apparently, to provide a proxy-pattern. But the proxy can be a list. The following seems to work:
```yaml
packages:
  '@foo/*':
    access: $all
    publish: $authenticated
    proxy:
      - foo_0
      - foo_1
      - foo_2
  '*':
    access: $all
    publish: $authenticated
    proxy: npmjs
```
The nice thing is, Verdaccio will even keep track of the requests to prevent _circular_ references...
