### ISSUE TITLE
[Web] Markdown language on README is missing monospace styles and coloring

### ISSUE THREAD

**Issue by akasection** [verdaccio/verdaccio#4268]
**Your Environment**
  
 * **verdaccio version**: 5.28.0
 * **node version**: 20.xx
 * **package manager**: pnpm@8
 * **os**: linux
 * **platform**: helm

**Describe the bug**

On published packages with added language type in markdown code README (backticks with specified language), the supposed to be `monospace` and colored is now a plain sans-serif. On markdown code with plain triple backticks, it works normally (see screenshot).

**To Reproduce**

1. Deploy the latest Helm charts with override Verdaccio version 5.28
2. Wait for kube to deploy
3. Open the Web UI/Dashboard and navigate to any published package on previous verdaccio version (4.x) and the readme should have triple backticks with language
4. See if the UI yields the README with broken fonts

**Expected behavior**

The markdown code should be in monospace fonts and colorized.

**Screenshots, server logs, package manager log**

![image](https://github.com/verdaccio/verdaccio/assets/1237295/8d8addc4-be21-4b3f-ac81-91982a09a131)

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: /verdaccio/storage/data
plugins: /verdaccio/storage/plugins

web:
  title: "Bukalapak NPM Repository"
  logo: "https://s4.bukalapak.com/images/logo/single_260x41_10_white_20062016.png"
  primary_color: "#d71149"
  scope: '@bukalapak'

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

packages:
  '@bukalapak/**':
    access: $all
    publish: $all

  '@buka20/**':
    access: $all
    publish: $all

  '**':
    access: $all
    publish: $all

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: json, level: http }

max_body_size: 40mb
```

**Environment information**

```
Environment Info:
  System:
    OS: Linux 5.15 Alpine Linux
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
  Binaries:
    npm: 10.2.3 - /usr/local/bin/npm
  npmGlobalPackages:
    verdaccio: 5.28.0
```

**Comment by akasection** [comment]
Additional info:

On the disk, the package.json on the data folder look like this:
```
"readme": "ESLint configuration for Javascript files.\n\n## How to use\n\n* Set up [CENSORED](https://CENSORED)\n* Install\n```bash\n$ npm install @bukalapak/eslint-config-base -D\n```\n* Extend the config\n```javascript\n{\n  \"extends\": [\n    \"@bukalapak/eslint-config-base\"\n  ]\n}\n```\n* If the project has files other than javascript, add [`import/extensions` setting](https://github.com/benmosher/eslint-plugin-import#importextensions) to the configuration\n```javascript\n{\n  settings: {\n    'import/resolver': {\n      node: {\n        extensions: ['.js', '.vue'], // for vue project\n        extensions: ['.ts'], // for typescript only project\n        // etc…\n      },\n    },\n  },\n}\n```"
```

**Comment by silverwind** [comment]
The monospace font problem is caused by below CSS rule. If I disable it in browser devtools, the monospace rendering is restored.

```css
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
  font-family: "Roboto", Helvetica Neue, Arial, sans-serif;
}
```

As for the colors, it looks like highlight.js does set appropriate HTML classes, but there is no CSS for those classes present on the page.
