### ISSUE TITLE
Should not `*` match `@*/*`?

### ISSUE THREAD

**Issue by UnitedMarsupials** [verdaccio/verdaccio#429]
#### My reason:

I configured the default uplink as documented:
```yaml
uplinks:
  'npmjs':
    url: 'https://registry.npmjs.org/'
    cache: true

packages:
  '*':
    access: $all
    proxy: npmjs
```

This works for most stuff, but not for things like `@types/node`. To be able to process these, I had to add another entry to `packages`:
```yaml
  '@*/*':
    access: $all
    proxy: npmjs
```

If that's intentional, I wonder, what the reasons are. If not, it needs fixing, no?

#### Application version:
2.7.0
