### ISSUE TITLE
on failure - proxy to next uplink

### ISSUE THREAD

**Issue by dkuida** [verdaccio/verdaccio#442]
#### My reason:

Trying to figure that one out.
I use 2.7.1 docker, on 2 machines, what I want is to configure that on the failure of the first uplink, the next one will be retried.
but on the proxy config there is only option to set one uplink., here is my config.

```  

uplinks:
  linux:
    url: http://url:4873/
    auth: 
      type: "bearer"
      token: "sssss=="
    
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: linux
  '**':
    access: $all
    publish: $authenticated
    proxy: linux


```
