### ISSUE TITLE
Getting  EACCES: permission denied, open '/verdaccio/storage/@asyncapi/html-template/package.json.tmp4446934159360625' 

### ISSUE THREAD

**Issue by AayushSaini101** [verdaccio/verdaccio#4449]
**Your Environment**
  
 * **verdaccio version**: 5
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [mac]
 * **platform**: [ docker,]

**Describe the bug:**
* I am getting  EACCES: permission denied, open '/verdaccio/storage/@asyncapi/html-template/package.json.tmp4446934159360625' in the github actions. This is the folder structure and docker-compose.yml for verdaccio.

**Folder Structure:**

<img width="279" alt="image" src="https://github.com/verdaccio/verdaccio/assets/60972989/c4279488-10a2-48c8-9ce2-49bdb078db85">

```
**docker-compose.yml**
version: '3'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: 'verdaccio'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio/conf:/verdaccio/conf:z'
      - './verdaccio/storage:/verdaccio/storage:z'
    networks:
      - mynetwork

  test-project:
    privileged: true
    image: "node:${NODE_IMAGE_TAG}"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ../../:/app
    command: bash /app/test/test-project/test.sh test-project 

networks:
  mynetwork:
    driver: bridge

```
I also checked this issue https://github.com/verdaccio/verdaccio/issues/336#issuecomment-375580151 and set the permission.
<img width="576" alt="Screenshot 2024-01-17 at 1 02 17 PM"  but still getting the error src="https://github.com/verdaccio/verdaccio/assets/60972989/2d5437e7-c39d-447b-9680-749390d26025">

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
