### ISSUE TITLE
Listening to IPv6 yields error message (since colon is used as key-value-separator?)

### ISSUE THREAD

**Issue by fdenzer** [verdaccio/verdaccio#445]
#### My reason:

Listening to [::1]:4873 yields error message `a whitespace character is expected after the key-value separator within a block mapping`

The snippets of the config were taken/modified from https://github.com/verdaccio/verdaccio/blob/master/conf/full.yaml .

#### Steps to reproduce:

See config.yaml

####  App Version:	

2.7.1

####  Config file:	

```yaml
storage: /Users/fd/.local/share/verdaccio/storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
listen:
  - [::1]:4873               # ipv6
logs:
  - {type: stdout, format: pretty, level: http}
```
