### ISSUE TITLE
npm ERR! 404  '@vue-office/docx@1.6.0' is not in this registry

### ISSUE THREAD

**Issue by dodoliu** [verdaccio/verdaccio#4472]
I'm run "npm install", show error :
> npm install
> npm ERR! code E404
> npm ERR! 404 Not Found - GET http://192.168.110.121:4873/@vue-office%2fdocx - no such package available
> npm ERR! 404 
> npm ERR! 404  '@vue-office/docx@1.6.0' is not in this registry.
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!  
> /root/.npm/_logs/2024-01-24T08_22_52_336Z-debug-0.log

/root/.npm/_logs/2024-01-24T08_22_52_336Z-debug-0.log some info:

> 408 timing idealTree:node_modules/svg-baker/node_modules/postcss Completed in 41ms
> 409 silly placeDep node_modules/svg-baker ansi-styles@2.2.1 OK for: chalk@1.1.3 want: ^2.2.1
> 410 silly placeDep ROOT has-ansi@2.0.0 OK for: chalk@1.1.3 want: ^2.0.0
> 411 silly placeDep ROOT strip-ansi@3.0.1 OK for: chalk@1.1.3 want: ^3.0.0
> 412 silly placeDep node_modules/svg-baker/node_modules/chalk supports-color@2.0.0 OK for: chalk@1.1.3 want: ^2.0.0
> 413 silly fetch manifest ansi-regex@^2.0.0
> 414 http fetch GET 200 http://192.168.110.121:4873/ansi-regex 22ms (cache revalidated)
> 415 timing idealTree:node_modules/svg-baker/node_modules/chalk Completed in 42ms
> 416 silly placeDep ROOT ansi-regex@2.1.1 OK for: has-ansi@2.0.0 want: ^2.0.0
> 417 timing idealTree:node_modules/has-ansi Completed in 2ms
> 418 timing idealTree:node_modules/ansi-regex Completed in 0ms
> 419 timing idealTree:node_modules/strip-ansi Completed in 0ms
> 420 timing idealTree:node_modules/svg-baker/node_modules/ansi-styles Completed in 0ms
> 421 timing idealTree:node_modules/svg-baker/node_modules/js-base64 Completed in 0ms
> 422 silly placeDep node_modules/svg-baker has-flag@1.0.0 OK for: supports-color@3.2.3 want: ^1.0.0
> 423 timing idealTree:node_modules/svg-baker/node_modules/supports-color Completed in 1ms
> 424 timing idealTree:node_modules/svg-baker/node_modules/has-flag Completed in 0ms
> 425 timing idealTree:node_modules/svg-baker/node_modules/chalk/node_modules/supports-color Completed in 0ms
> 426 timing idealTree:buildDeps Completed in 4729ms
> 427 timing idealTree:fixDepFlags Completed in 25ms
> 428 timing idealTree Completed in 5612ms
> 429 timing command:install Completed in 5622ms
> 430 verbose stack HttpErrorGeneral: 404 Not Found - GET http://192.168.110.121:4873/@vue-office%2fdocx - no such package available
> 430 verbose stack     at /home/node-v16.15.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:104:15
> 430 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 430 verbose stack     at async Arborist.[nodeFromEdge] (/home/node-v16.15.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1081:19)
> 430 verbose stack     at async Arborist.[buildDepStep] (/home/node-v16.15.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:950:11)
> 430 verbose stack     at async Arborist.buildIdealTree (/home/node-v16.15.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
> 430 verbose stack     at async Promise.all (index 1)
> 430 verbose stack     at async Arborist.reify (/home/node-v16.15.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
> 430 verbose stack     at async Install.exec (/home/node-v16.15.0-linux-x64/lib/node_modules/npm/lib/commands/install.js:159:5)
> 430 verbose stack     at async module.exports (/home/node-v16.15.0-linux-x64/lib/node_modules/npm/lib/cli.js:66:5)
> 431 verbose statusCode 404
> 432 verbose pkgid @vue-office/docx@1.6.0
> 433 verbose cwd /var/jenkins_home/workspace/ALIYUN-SZZKY/Prod-Panna.DeviceBook.Gui
> 434 verbose Linux 3.10.0-1160.el7.x86_64
> 435 verbose argv "/home/node-v16.15.0-linux-x64/bin/node" "/usr/local/bin/npm" "install"
> 436 verbose node v16.15.0
> 437 verbose npm  v8.5.5
> 438 error code E404
> 439 error 404 Not Found - GET http://192.168.110.121:4873/@vue-office%2fdocx - no such package available
> 440 error 404
> 441 error 404  '@vue-office/docx@1.6.0' is not in this registry.
> 442 error 404
> 442 error 404 Note that you can also install from a
> 443 error 404 tarball, folder, http url, or git url.
> 444 verbose exit 1
> 445 timing npm Completed in 5861ms
> 446 verbose unfinished npm timer reify 1706084572572
> 447 verbose unfinished npm timer reify:loadTrees 1706084572578
> 448 verbose code 1
> 449 error A complete log of this run can be found in:
> 449 
>error     /root/.npm/_logs/2024-01-24T08_22_52_336Z-debug-0.log

this package '@vue-office/docx@1.6.0' origin: [https://www.npmjs.com/package/@vue-office/docx](https://www.npmjs.com/package/@vue-office/docx)
or
[https://npmmirror.com/package/@vue-office/docx?version=1.6.0](https://npmmirror.com/package/@vue-office/docx?version=1.6.0)

my verdaccio is runing in docker.

config.yaml:

```
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
web:
  title: Verdaccio
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
uplinks:
  taobao:
    url: https://registry.npm.taobao.org    
  npmjs:
    url: https://registry.npmjs.org/   
packages:
  @*/*:
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taobao
  **:
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: taobao
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
logs: { type: stdout, format: pretty, level: http }
```

verdaccio version: 5.29.0

How to solve this error?
Thanks!
