### ISSUE TITLE
Verdaccio UI not visible

### ISSUE THREAD

**Issue by yashbabariya** [verdaccio/verdaccio#4496]
I deployed the **vardaccio/verdaccio:5** image using deployment in the EKS cluster and served on the ingress load balancer. I can't show the UI page in my domain. When I opened my domain in the web browser the service was done to the pod IP of the server. why did this happen?

this is deployment.yaml file

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-registry
  namespace: default
spec:
  containers:
  - env:
    - name: HOSTNAME
      value: localhost
    image: verdaccio/verdaccio:5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/ping
        port: port
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: test-registry
    ports:
    - containerPort: 4873
      name: port
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/ping
        port: port
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /verdaccio/conf
      name: config
      readOnly: true
    - mountPath: /verdaccio/storage
      name: verdaccio-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6sv7r
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 100
    runAsUser: 10001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      name: test-registry
    name: config
  - name: verdaccio-data
    persistentVolumeClaim:
      claimName: verdaccio-data
  ```

![Screenshot from 2024-02-09 15-59-47](https://github.com/verdaccio/verdaccio/assets/67451545/4a77f888-a433-499f-a20f-c82aa74a4163)
