### ISSUE TITLE
Web UI doesn't work as a sidecar for non-localhost URLs

### ISSUE THREAD

**Issue by ThePlenkov** [verdaccio/verdaccio#4795]
Hi! 

let me please share a simple devcontainer I'm running in Github codespaces:

```yaml
version: '3.8'

services:
  devcontainer:
    # Using a Dockerfile is optional, but included for completeness.
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    # environment:
    #   - VERDACCIO_PUBLIC_URL=http://localhost:4873
```

So it starts my devcontainer and starts verdaccio as a sidecar service. I find it very convenient because it doesn't require adding extra dev dependencies to the project. However it is not possible to use webUI because it still tries to load resources from absolute localhost path
![image](https://github.com/user-attachments/assets/ebcbe165-566f-4413-9cb3-3d046dcd25be)

I'm very wondering how much work would be by changing those absolute paths to relative that's how it can run on any host?

Thank you!

**Comment by ThePlenkov** [comment]
I cannot use `VERDACCIO_PUBLIC_URL` in this case because my codespace URL can be different. Also setting it to empty or dot doesn't help

**Comment by ThePlenkov** [comment]
The solution so far is to create such a file:
```
VERDACCIO_PUBLIC_URL="https://${CODESPACE_NAME}-4873.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
```
and use it as `env_file`:
```
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    env_file:
      - .env
```

However running it locally in VS Code would produce another problem..  So seems like now I need to write a script generating this file on container create based on the environment. Crazy, isn't it?  For something which should out of the box serving static resources on the same host via relative URLs
