### ISSUE TITLE
fix: 404 for publish (#483)

### ISSUE THREAD

**Issue by jjangga0214** [verdaccio/verdaccio#4807]
**Your Environment**
  
 * **verdaccio version**: 5.3.2
 * **node version**: v20.11.0
 * **package manager**: npm@7
 * **os**: mac
 * **platform**: docker

**Describe the bug**

Hi!

When publishing a new package, 404 error occurs.

This was reported from #483 originally, but auto-closed even though it's not fixed.

**To Reproduce**

**docker-compose.yaml**:

```yaml
services:
  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - verdaccio
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - verdaccio:/verdaccio
      - ./config.yaml/:/verdaccio/conf/config.yaml
      - 
networks:
  verdaccio:
    driver: bridge

volumes:
  verdaccio:
```

**404 error while publishing `foo`**:

```sh
➜  npm publish --registry http://localhost:4873/

npm notice
npm notice 📦  foo@2.38.0
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 8.5kB README.md
npm notice 342B  bar
npm notice 3.7kB package.json
npm notice === Tarball Details ===
npm notice name:          foo
npm notice version:       2.38.0
npm notice filename:      foo-2.38.0.tgz
npm notice package size:  5.2 kB
npm notice unpacked size: 13.6 kB
npm notice shasum:        444ab6fda705fbd454aec705c4f42480d1c2132d
npm notice integrity:     sha512-DIqjQAHHcvCjv[...]0slvQKeKJHWbw==
npm notice total files:   4
npm notice
npm notice Publishing to http://localhost:4873/ with tag latest and public access
npm ERR! code E404
npm ERR! 404 Not Found - PUT http://localhost:4873/foo - no such package available
npm ERR! 404
npm ERR! 404  'foo@2.38.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/ocean/.npm/_logs/2024-09-10T00_52_18_628Z-debug-0.log
```

**Expected behavior**

It should work. 

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: ./storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'foo':
     access: $all
     publish: $all
     # no proxy to override possibly existing version on npm. [ref](https://verdaccio.org/docs/en/best#override-public-packages)

  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
```

**Workaround**

Set `user` as `root` (`user: root`).

**docker-compose.yaml**:

```diff
services:
  verdaccio:
    image: verdaccio/verdaccio
+   user: root
    networks:
      - verdaccio
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - verdaccio:/verdaccio
      - ./config.yaml/:/verdaccio/conf/config.yaml
      - 
networks:
  verdaccio:
    driver: bridge

volumes:
  verdaccio:
```
