### ISSUE TITLE
404 no such package available error

### ISSUE THREAD

**Issue by tvb** [verdaccio/verdaccio#483]
command:
```
$ npm publish --registry=http://mydomain.com:5000 --scope=@myscope
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 no such package available : @myscope/mypackage
npm ERR! 404
npm ERR! 404  '@myscope/mypackage' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

config.yaml:
```
packages:
  '@myscope/*':
    #scoped packages
    access: $all
    publish: $authenticated

  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
```
