### ISSUE TITLE
[2.7.2] Unregistered users are not allowed to publish package @myscope/mypackage

### ISSUE THREAD

**Issue by tvb** [verdaccio/verdaccio#487]
First logging in with scope
```
$ npm login --registry=http://mydomain.com:5000/ --scope=@myscope
Username: myuser
Password:
Email: (this IS public) email@mydomain.com
Logged in as myuser to scope @myscope on http://mydomain.com:5000/.
```
Note it says I am logged in successfully and with the scope. Then
```
$ npm publish --registry=http://mydomain.com:5000 --verbose --scope=@myscope
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/8.1.4/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'publish',
npm verb cli   '--registry=http://mydomain.com:5000',
npm verb cli   '--verbose',
npm verb cli   '--scope=@myscope' ]
npm info using npm@5.6.0
npm info using node@v8.1.4
npm verb npm-session 75de2175fb48538d
npm verb publish [ '.' ]
npm info lifecycle @myscope/mypackage@0.0.6~prepublish: @myscope/mypackage@0.0.6
npm info lifecycle @myscope/mypackage@0.0.6~prepare: @myscope/mypackage@0.0.6
npm info lifecycle @myscope/mypackage@0.0.6~prepublishOnly: @myscope/mypackage@0.0.6
npm info lifecycle @myscope/mypackage@0.0.6~prepack: @myscope/mypackage@0.0.6
npm info lifecycle @myscope/mypackage@0.0.6~postpack: @myscope/mypackage@0.0.6
npm verb getPublishConfig { registry: 'http://mydomain.com:5000/' }
npm verb publish registryBase http://mydomain.com:5000/
npm verb request uri http://mydomain.com:5000/@myscope%2fmypackage
npm verb request sending authorization for write operation
npm info attempt registry request try #1 at 8:42:17 PM
npm verb request using bearer token for auth
npm verb request id 3ed01ed57771800b
npm http request PUT http://mydomain.com:5000/@myscope%2fmypackage
npm http 403 http://mydomain.com:5000/@myscope%2fmypackage
npm verb headers { date: 'Tue, 16 Jan 2018 19:42:18 GMT',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '99',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-powered-by': 'verdaccio/2.7.2',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   etag: 'W/"63-fITY+VZxRayHOGnBggUPJbGaap0"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6jFK' }
npm ERR! publish Failed PUT 403
npm verb stack Error: unregistered users are not allowed to publish package @myscope/mypackage : @myscope/mypackage
npm verb stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
npm verb stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at Request.emit (events.js:213:7)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
npm verb stack     at emitOne (events.js:115:13)
npm verb stack     at Request.emit (events.js:210:7)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
npm verb stack     at Object.onceWrapper (events.js:314:30)
npm verb stack     at emitNone (events.js:110:20)
npm verb stack     at IncomingMessage.emit (events.js:207:7)
npm verb stack     at endReadableNT (_stream_readable.js:1047:12)
npm verb stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:161:9)
npm verb statusCode 403
npm verb pkgid @myscope/mypackage
npm verb cwd /myrepo/mypackage
npm verb Darwin 17.3.0
npm verb argv "/usr/local/Cellar/node/8.1.4/bin/node" "/usr/local/bin/npm" "publish" "--registry=http://mydomain.com:5000" "--verbose" "--scope=@myscope"
npm verb node v8.1.4
npm verb npm  v5.6.0
npm ERR! code E403
npm ERR! unregistered users are not allowed to publish package @myscope/mypackage : @myscope/mypackage
npm verb exit [ 1, true ]
```

config.yaml:
```
packages:
  '@myscope/*':
    #scoped packages
    access: $all
    publish: $authenticated

  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    #proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    #proxy: npmjs
```
