### ISSUE TITLE
docker publish fails because fetch request doesnt resolve

### ISSUE THREAD

**Issue by ryanbas21** [verdaccio/verdaccio#5017]
I have a multi stage docker image in a docker-compose. When I attempt to publish to verdaccio, publishes fail because a fetch isn't resolving.

I am on version 6, but this also happened on version 5 of verdaccio.

```
FROM build AS publish

RUN pnpm changeset pre enter beta
RUN pnpm changeset version
RUN NPM_CONFIG_REGISTRY=http://0.0.0.0:4873 pnpm -r publish --tag beta 
RUN pnpm changeset pre exit
```

Running this stage here, I get a failure on the first package (None of the packages exist on `npm` at this time)

```
70.59 npm notice Publishing to http://localhost:4873/ with tag beta and restricted access
140.6 npm error code ECONNREFUSED
140.6 npm error errno ECONNREFUSED
140.6 npm error FetchError: request to http://localhost:4873/@mypackage failed, reason: 
140.6 npm error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
140.6 npm error     at ClientRequest.emit (node:events:518:28)
140.6 npm error     at emitErrorEvent (node:_http_client:101:11)
140.6 npm error     at _destroy (node:_http_client:884:9)
140.6 npm error     at onSocketNT (node:_http_client:904:5)
140.6 npm error     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
140.6 npm error   code: 'ECONNREFUSED',
140.6 npm error   errno: 'ECONNREFUSED',
140.6 npm error   type: 'system'
140.6 npm error }
140.6 npm error
140.6 npm error If you are behind a proxy, please make sure that the
140.6 npm error 'proxy' config is set properly.  See: 'npm help config'
140.6 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-23T18_24_37_665Z-debug-0.log
```

The docker compose file uses the `verdaccio` image.

```
networks:
  npm-network:
    driver: bridge

services:
services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - '4873:4873'
    volumes:
      - ./tmp/local-registry/storage:/verdaccio/storage
      - './.verdaccio:/verdaccio/conf'
      - './.verdaccio/config.yml:/verdaccio/conf/config.yaml'
    environment:
      - VERDACCIO_PORT=4873
      - NPM_CONFIG_LOGLEVEL=info
  packages:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - verdaccio
    environment:
      - NPM_REGISTRY=http://0.0.0.0:4873

    volumes:
      - .:/app
    ports:
      - '3000:3000'

volumes:
  verdaccio-storage:
  verdaccio-config:
  ```

It's a bit of a weird error - my suspicion is that because these packages do not exist, it doesn't resolve after proxying. But i'm not sure _why_ that matters in this case.
