### ISSUE TITLE
npm does not save authToken when authenticating to Verdaccio

### ISSUE THREAD

**Issue by demurgos** [verdaccio/verdaccio#509]
#### My reason:

Hi,
I want to get an auth token to my private registry running Verdaccio, for CI purposes.
When I authenticate with `npm login --registry https//npm.example.com` npm stores my password in clear text instead of saving an auth token.
This worked 2 months ago. Since then I update to the latest version of npm (`5.6.0`) and Verdaccio (`2.7.3`) and I no longer get an auth token.

#### Steps to reproduce:

```
$ npm login --registry https://npm.example.com
Username: demurgos
Password: 
Email: (this IS public) demurgos@example.com
Logged in as demurgos on https://npm.example.com/.
$ cat ~/.npmrc 
//registry.npmjs.org/:_authToken=ffffffff-ffff-ffff-ffff-ffffffffffff
//npm.example.com/:_password="xxxxxxxxxx"
//npm.example.com/:username=demurgos
//npm.example.com/:email=demurgos@demurgos.net
//npm.example.com/:always-auth=false
```

```
$ npm --version
5.6.0
$ verdaccio --version
2.7.3
```

####  App Version:	

I believe that it worked (saved the token instead of password) with `verdaccio@2.5.0` and `npm@5.1.0`.

####  Config file:

```
# path to a directory with all packages
storage: /var/www/example.com/verdaccio/storage/

web:
  enable: true
  title: Example - npm by Verdaccio

auth:
  htpasswd:
    file: /var/www/example.com/example.htpasswd
    # Disable registration
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

# Public root
url_prefix: https://npm.example.com/

listen:
  - localhost:xxxx

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
```

#### Additional information:

`$ npm --verbose` prints:

```
$ npm login --verbose --registry https://npm.example.com
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'login',
npm verb cli   '--verbose',
npm verb cli   '--registry',
npm verb cli   'https://npm.example.com' ]
npm info using npm@5.6.0
npm info using node@v9.4.0
npm verb npm-session 2e8442c56aaa32fb
Username: (demurgos) demurgos
Password: (<default hidden>) 
Email: (this IS public) (demurgos@example.com) demurgos@example.com
npm verb login before first PUT { _id: 'org.couchdb.user:demurgos',
npm verb login   name: 'demurgos',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2018-01-20T18:34:09.575Z' }
npm http request → PUT https://npm.example.com/-/user/org.couchdb.user:demurgos
npm http 409 ← Conflict (https://npm.example.com/-/user/org.couchdb.user:demurgos)
npm info adduser Authorized user demurgos
Logged in as demurgos on https://npm.example.com/.
npm verb exit [ 0, true ]
npm info ok 
```
 
Container: N/A (I use my local environment)
