### ISSUE TITLE
storage plugin cannot be loaded in version 6.1.0, in version 6.0.5 it is working

### ISSUE THREAD

**Issue by ManfredLerner** [verdaccio/verdaccio#5160]
**Your Environment**
  
 * **verdaccio version**: 6.1.0
 * **node version** [12.x.x, 14.x.x]: 22.14.0
 * **package manager**: npm
 * **os**: windows 11
 * **platform**: npm

**Describe the bug**
we want to use the offline-storage-plugin.
with verdaccio version 6.0.5 it is working fine
with verdaccio version 6.1.0, the error is thrown that no ./plugins directory exists.
in the verdaccio folder, where the subfolder storage is located, no plugins folder has been created. this was not neccessary to use the offline-storage plugin

both verdaccio and offline-storage-plugin have been installed with npm install -g ...

**To Reproduce**
simply use this part of the config.yaml:

```yaml
# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

store:
  offline-storage: 

offline: true
```

the rest of the config.yaml file is the default file

Thanks you so much in advance for your help :-)!

**Expected behavior**

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
