### ISSUE TITLE
Storage Subfolder tree not being used by local-storage plugin after updating from Verdaccio 6.1.0 to 6.1.1

### ISSUE THREAD

**Issue by IhToN** [verdaccio/verdaccio#5175]
**Your Environment**
  
 * **verdaccio version**: 6.1.1 / 6.1.0
 * **platform**: docker

**Describe the bug**

An update from Verdaccio 6.1.0 to Verdaccio 6.1.1 docker image "removed" all of the already published packages. After further investigation I found out the issue was because Verdaccio 6.1.1 using Local-Storage was not recognizing the specific storage subfolder that are configured, and tries to load (and publish) against the `/opt/verdaccio/storage` parent folder instead.

**To Reproduce**

Use a scoped config setup such as:
```yaml
storage: /verdaccio/storage

packages: 
  '@test/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    storage: test

  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
    storage: npmjs
```

**Expected behavior**

That scoped @test packages are stored and loaded from `/verdaccio/storage/test/` instead of `/verdaccio/storage/`

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇 

ref https://github.com/verdaccio/verdaccio/issues/5160
