### ISSUE TITLE
Can't see Packages after migration 6.0.5 -> 6.1.2

### ISSUE THREAD

**Issue by TxX8N8LN** [verdaccio/verdaccio#5201]
**Your Environment**

 * **verdaccio version**: 6.1.2
 * **node version** [22.14]:
 * **package manager**: [npm@11.3]
 * **os**: [linux]
 * **platform**: [npm, docker, helm, other]
* **reverse proxy with nginx

**Describe the bug**

Can't see Packages after migration 6.0.5 -> 6.1.2 on web UI.

If i downgrade to 6.0.5 all rework.

**Log**

In the log, i see "user":null on 6.1.2, and good user in 6.0.5.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

``

**Comment by mbtools** [comment]
It's best to post the complete `config.yaml` and the relevant part of the log. 

Do you use a middleware plugin? If yes, you might need #5200 (but in 6.x).

**Comment by TxX8N8LN** [comment]
all the config.yaml :

```
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

listen: 0.0.0.0:4873

# path to a directory with all packages
storage: /var/lib/verdaccio/verdaccio/storage
# path to a directory with plugins to include
plugins: /var/lib/verdaccio/verdaccio/plugins

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: /var/lib/verdaccio/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
log: { type: stdout, format: json, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false
```

log on 6.1.2

```
{"level":25,"time":1744708525980,"pid":521,"hostname":"debian-22","sub":"in","request":{"method":"POST","url":"/-/verdaccio/sec/login"},"user":"GOOD_USER","remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":72,"out":411},"msg":"200, user: GOOD_USER(X.X.X.X via 192.168.0.6), req: 'POST /-/verdaccio/sec/login', bytes: 72/411"}
{"level":30,"time":1744708526010,"pid":521,"hostname":"debian-22","sub":"in","req":{"method":"GET","url":"/-/verdaccio/data/packages","query":{},"params":{},"headers":{"host":"verdaccio.nystek-editions.com","x-real-ip":"X.X.X.X","x-forwarded-for":"X.X.X.X","x-forwarded-proto":"https","x-frame-options":"SAMEORIGIN","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0","accept":"*/*","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br, zstd","referer":"https://verdaccio.nystek-editions.com/","authorization":"<Classified>","x-client":"verdaccio-ui","dnt":"1","sec-gpc":"1","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","if-none-match":"\"58e0494c51d30eb3494f7c9198986bb9\"","priority":"u=4"},"remoteAddress":"192.168.0.6","remotePort":47472},"ip":"192.168.0.6","msg":"192.168.0.6 requested 'GET /-/verdaccio/data/packages'"}
{"level":25,"time":1744708526011,"pid":521,"hostname":"debian-22","sub":"in","request":{"method":"GET","url":"/-/verdaccio/data/packages"},"user":null,"remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":0,"out":0},"msg":"200, user: null(X.X.X.X via 192.168.0.6), req: 'GET /-/verdaccio/data/packages', bytes: 0/0"}

```

log on 6.0.5

```

{"level":25,"time":1744710307831,"pid":1106,"hostname":"debian-22","sub":"in","request":{"method":"POST","url":"/-/verdaccio/sec/login"},"user":"GOOD_USER","remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":64,"out":371},"msg":"200, user: GOOD_USER(X.X.X.X via 192.168.0.6), req: 'POST /-/verdaccio/sec/login', bytes: 64/371"}
{"level":30,"time":1744710307895,"pid":1106,"hostname":"debian-22","sub":"in","req":{"method":"GET","url":"/-/verdaccio/data/packages","query":{},"params":{},"headers":{"host":"verdaccio.nystek-editions.com","x-real-ip":"X.X.X.X","x-forwarded-for":"X.X.X.X","x-forwarded-proto":"https","x-frame-options":"SAMEORIGIN","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0","accept":"*/*","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br, zstd","referer":"https://verdaccio.nystek-editions.com/","authorization":"<Classified>","x-client":"verdaccio-ui","dnt":"1","sec-gpc":"1","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","if-none-match":"\"58e0494c51d30eb3494f7c9198986bb9\"","priority":"u=4"},"remoteAddress":"192.168.0.6","remotePort":36936},"ip":"192.168.0.6","msg":"192.168.0.6 requested 'GET /-/verdaccio/data/packages'"}
{"level":25,"time":1744710307898,"pid":1106,"hostname":"debian-22","sub":"in","request":{"method":"GET","url":"/-/verdaccio/data/packages"},"user":"GOOD_USER","remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":0,"out":0},"msg":"200, user: GOOD_USER(X.X.X.X via 192.168.0.6), req: 'GET /-/verdaccio/data/packages', bytes: 0/0"}
{"level":30,"time":1744710307904,"pid":1106,"hostname":"debian-22","user":"GOOD_USER","msg":"auth/allow_action: access granted to: GOOD_USER"}

```

**Comment by TxX8N8LN** [comment]
config.yaml

```

# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

listen: 0.0.0.0:4873

# path to a directory with all packages
storage: /var/lib/verdaccio/verdaccio/storage
# path to a directory with plugins to include
plugins: /var/lib/verdaccio/verdaccio/plugins

web:
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: /var/lib/verdaccio/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
log: { type: stdout, format: json, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false

``

log on 6.1.2

```
{"level":25,"time":1744708525980,"pid":521,"hostname":"debian-22","sub":"in","request":{"method":"POST","url":"/-/verdaccio/sec/login"},"user":"GOOD_USER","remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":72,"out":411},"msg":"200, user: GOOD_USER(X.X.X.X via 192.168.0.6), req: 'POST /-/verdaccio/sec/login', bytes: 72/411"}
{"level":30,"time":1744708526010,"pid":521,"hostname":"debian-22","sub":"in","req":{"method":"GET","url":"/-/verdaccio/data/packages","query":{},"params":{},"headers":{"host":"HOST","x-real-ip":"X.X.X.X","x-forwarded-for":"X.X.X.X","x-forwarded-proto":"https","x-frame-options":"SAMEORIGIN","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0","accept":"*/*","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br, zstd","referer":"https://HOST/","authorization":"<Classified>","x-client":"verdaccio-ui","dnt":"1","sec-gpc":"1","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","if-none-match":"\"58e0494c51d30eb3494f7c9198986bb9\"","priority":"u=4"},"remoteAddress":"192.168.0.6","remotePort":47472},"ip":"192.168.0.6","msg":"192.168.0.6 requested 'GET /-/verdaccio/data/packages'"}
{"level":25,"time":1744708526011,"pid":521,"hostname":"debian-22","sub":"in","request":{"method":"GET","url":"/-/verdaccio/data/packages"},"user":null,"remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":0,"out":0},"msg":"200, user: null(X.X.X.X via 192.168.0.6), req: 'GET /-/verdaccio/data/packages', bytes: 0/0"}

```

log on 6.0.5

```

{"level":25,"time":1744710307831,"pid":1106,"hostname":"debian-22","sub":"in","request":{"method":"POST","url":"/-/verdaccio/sec/login"},"user":"GOOD_USER","remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":64,"out":371},"msg":"200, user: GOOD_USER(X.X.X.X via 192.168.0.6), req: 'POST /-/verdaccio/sec/login', bytes: 64/371"}
{"level":30,"time":1744710307895,"pid":1106,"hostname":"debian-22","sub":"in","req":{"method":"GET","url":"/-/verdaccio/data/packages","query":{},"params":{},"headers":{"host":"HOST","x-real-ip":"X.X.X.X","x-forwarded-for":"X.X.X.X","x-forwarded-proto":"https","x-frame-options":"SAMEORIGIN","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0","accept":"*/*","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br, zstd","referer":"https://HOST/","authorization":"<Classified>","x-client":"verdaccio-ui","dnt":"1","sec-gpc":"1","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","if-none-match":"\"58e0494c51d30eb3494f7c9198986bb9\"","priority":"u=4"},"remoteAddress":"192.168.0.6","remotePort":36936},"ip":"192.168.0.6","msg":"192.168.0.6 requested 'GET /-/verdaccio/data/packages'"}
{"level":25,"time":1744710307898,"pid":1106,"hostname":"debian-22","sub":"in","request":{"method":"GET","url":"/-/verdaccio/data/packages"},"user":"GOOD_USER","remoteIP":"X.X.X.X via 192.168.0.6","status":200,"bytes":{"in":0,"out":0},"msg":"200, user: GOOD_USER(X.X.X.X via 192.168.0.6), req: 'GET /-/verdaccio/data/packages', bytes: 0/0"}
{"level":30,"time":1744710307904,"pid":1106,"hostname":"debian-22","user":"GOOD_USER","msg":"auth/allow_action: access granted to: GOOD_USER"}

```

**Comment by mbtools** [comment]
Sorry, I can't find what change caused it.

**Comment by juanpicado** [comment]
I'll take a look @TxX8N8LN  if you don't mind please run `DEBUG=verdaccio* verdaccio` and share also relevant log here that would be helpful to debug deeper.

**Comment by TxX8N8LN** [comment]
@juanpicado with debug :

```
{"level":30,"time":1744881662501,"pid":2875,"hostname":"debian-22","sub":"in","req":{"method":"POST","url":"/-/verdaccio/sec/login","query":{},"params":{},"headers":{"host":"HOST","x-real-ip":"88.174.71.150","x-forwarded-for":"88.174.71.150","x-forwarded-proto":"https","x-frame-options":"SAMEORIGIN","content-length":"64","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0","accept":"application/json","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br, zstd","referer":"https://HOST/","content-type":"application/json","origin":"https://HOST","dnt":"1","sec-gpc":"1","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","priority":"u=0"},"remoteAddress":"192.168.0.6","remotePort":41132},"ip":"192.168.0.6","msg":"192.168.0.6 requested 'POST /-/verdaccio/sec/login'"}
  verdaccio:middleware:error error report middleware start +26s
  verdaccio:middleware:error error report middleware end (skip next layer) next() +0ms
  verdaccio:auth jwt, authentication header is missing +26s
  verdaccio:middleware:encode encodeScopePackage: '/-/verdaccio/sec/login' (unchanged) +26s
  verdaccio:auth jwt, authentication header is missing +7ms
  verdaccio:auth jwt, authentication header is missing +0ms
  verdaccio:auth authenticating 'USER' +1ms
  verdaccio:plugin:htpasswd authenticate USER +58s
  verdaccio:plugin:htpasswd reload users +0ms
  verdaccio:plugin:htpasswd path: /var/lib/verdaccio/verdaccio/htpasswd +0ms
{"level":25,"time":1744881662509,"pid":2875,"hostname":"debian-22","sub":"in","request":{"method":"POST","url":"/-/verdaccio/sec/login"},"user":null,"remoteIP":"88.174.71.150 via 192.168.0.6","status":200,"bytes":{"in":64,"out":0},"msg":"200, user: null(88.174.71.150 via 192.168.0.6), req: 'POST /-/verdaccio/sec/login', bytes: 64/0"}
  verdaccio:plugin:htpasswd reload users total: 0 +1ms
  verdaccio:plugin:htpasswd reloaded +0ms
  verdaccio:auth authentication for user 'USER' was successfully. Groups: [ 'USER' ] +6ms
  verdaccio:auth jwt encrypt 'USER' +0ms
  verdaccio:auth:token:jwt sign jwt token +0ms
  verdaccio:auth:token:jwt signed jwt token successfully +2ms
  verdaccio:middleware:error error handler init +17ms
  verdaccio:middleware:error no error to report, jump next layer +0ms
  verdaccio:middleware:final set json type header support +26s
  verdaccio:middleware:final set etag header 080d7b94c06ab566658785254881c36d +1ms
{"level":25,"time":1744881662520,"pid":2875,"hostname":"debian-22","sub":"in","request":{"method":"POST","url":"/-/verdaccio/sec/login"},"user":"USER","remoteIP":"88.174.71.150 via 192.168.0.6","status":200,"bytes":{"in":64,"out":371},"msg":"200, user: USER(88.174.71.150 via 192.168.0.6), req: 'POST /-/verdaccio/sec/login', bytes: 64/371"}
{"level":30,"time":1744881662548,"pid":2875,"hostname":"debian-22","sub":"in","req":{"method":"GET","url":"/-/verdaccio/data/packages","query":{},"params":{},"headers":{"host":"HOST","x-real-ip":"88.174.71.150","x-forwarded-for":"88.174.71.150","x-forwarded-proto":"https","x-frame-options":"SAMEORIGIN","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0","accept":"*/*","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br, zstd","referer":"https://HOST/","authorization":"<Classified>","x-client":"verdaccio-ui","dnt":"1","sec-gpc":"1","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","if-none-match":"\"58e0494c51d30eb3494f7c9198986bb9\"","priority":"u=4"},"remoteAddress":"192.168.0.6","remotePort":41148},"ip":"192.168.0.6","msg":"192.168.0.6 requested 'GET /-/verdaccio/data/packages'"}
  verdaccio:middleware:error error report middleware start +29ms
  verdaccio:middleware:error error report middleware end (skip next layer) next() +0ms
  verdaccio:auth api middleware using legacy auth token +32ms
  verdaccio:auth handle legacy api middleware +0ms
  verdaccio:auth api middleware has a secret? true +1ms
  verdaccio:auth api middleware authorization true +0ms
  verdaccio:auth:utils getMiddlewareCredentials init +26s
  verdaccio:auth:utils is legacy +0ms
  verdaccio:auth:utils parseAESCredentials init +0ms
  verdaccio:auth:utils legacy header bearer +0ms
  verdaccio:auth:utils secret length 32 +0ms
  verdaccio:auth:utils is legacy unsecure false +0ms
  verdaccio:auth:utils legacy secure enabled +0ms
  verdaccio:auth:token:legacy aesDecrypt init +45s
  verdaccio:auth:utils parse legacy credentials failed +1ms
  verdaccio:auth api middleware credentials undefined +1ms
  verdaccio:auth legacy invalid header +0ms
  verdaccio:middleware:encode encodeScopePackage: '/-/verdaccio/data/packages' (unchanged) +41ms
  verdaccio:auth api middleware using legacy auth token +0ms
  verdaccio:auth handle legacy api middleware +0ms
  verdaccio:auth api middleware has a secret? true +0ms
  verdaccio:auth api middleware authorization true +0ms
  verdaccio:auth:utils getMiddlewareCredentials init +0ms
  verdaccio:auth:utils is legacy +1ms
  verdaccio:auth:utils parseAESCredentials init +0ms
  verdaccio:auth:utils legacy header bearer +0ms
  verdaccio:auth:utils secret length 32 +0ms
  verdaccio:auth:utils is legacy unsecure false +0ms
  verdaccio:auth:utils legacy secure enabled +0ms
  verdaccio:auth:token:legacy aesDecrypt init +2ms
  verdaccio:auth:utils parse legacy credentials failed +0ms
  verdaccio:auth api middleware credentials undefined +1ms
  verdaccio:auth legacy invalid header +0ms
  verdaccio:auth api middleware using legacy auth token +1ms
  verdaccio:auth handle legacy api middleware +0ms
  verdaccio:auth api middleware has a secret? true +0ms
  verdaccio:auth api middleware authorization true +0ms
  verdaccio:auth:utils getMiddlewareCredentials init +1ms
  verdaccio:auth:utils is legacy +0ms
  verdaccio:auth:utils parseAESCredentials init +0ms
  verdaccio:auth:utils legacy header bearer +0ms
  verdaccio:auth:utils secret length 32 +0ms
  verdaccio:auth:utils is legacy unsecure false +0ms
  verdaccio:auth:utils legacy secure enabled +0ms
  verdaccio:auth:token:legacy aesDecrypt init +2ms
  verdaccio:auth:utils parse legacy credentials failed +1ms
  verdaccio:auth api middleware credentials undefined +1ms
  verdaccio:auth legacy invalid header +0ms
  verdaccio:plugin:local-storage storage path selected:  /var/lib/verdaccio/verdaccio/storage +26s
  verdaccio:plugin:local-storage storage absolute path:  /var/lib/verdaccio/verdaccio/storage/@PACKAGE/test-verdaccio +0ms
  verdaccio:plugin:local-storage:fs read a package '@PACKAGE/test-verdaccio' +26s
  verdaccio:plugin:local-storage:fs reading the file: '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/test-verdaccio/package.json' +0ms
  verdaccio:plugin:local-storage get full list of packages (6) has been fetched +1ms
{"level":25,"time":1744881662553,"pid":2875,"hostname":"debian-22","sub":"in","request":{"method":"GET","url":"/-/verdaccio/data/packages"},"user":null,"remoteIP":"88.174.71.150 via 192.168.0.6","status":200,"bytes":{"in":0,"out":0},"msg":"200, user: null(88.174.71.150 via 192.168.0.6), req: 'GET /-/verdaccio/data/packages', bytes: 0/0"}
  verdaccio:plugin:local-storage:fs read file '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/test-verdaccio/package.json' succeed +1ms
  verdaccio:plugin:local-storage:fs read storage file '@PACKAGE/test-verdaccio' has succeed +0ms
  verdaccio:plugin:local-storage storage path selected:  /var/lib/verdaccio/verdaccio/storage +0ms
  verdaccio:plugin:local-storage storage absolute path:  /var/lib/verdaccio/verdaccio/storage/@PACKAGE/nooks +0ms
  verdaccio:plugin:local-storage:fs read a package '@PACKAGE/nooks' +0ms
  verdaccio:plugin:local-storage:fs reading the file: '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/nooks/package.json' +0ms
  verdaccio:plugin:local-storage:fs read file '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/nooks/package.json' succeed +1ms
  verdaccio:plugin:local-storage:fs read storage file '@PACKAGE/nooks' has succeed +0ms
  verdaccio:plugin:local-storage storage path selected:  /var/lib/verdaccio/verdaccio/storage +1ms
  verdaccio:plugin:local-storage storage absolute path:  /var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-back +0ms
  verdaccio:plugin:local-storage:fs read a package '@PACKAGE/hamelin-back' +0ms
  verdaccio:plugin:local-storage:fs reading the file: '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-back/package.json' +0ms
  verdaccio:plugin:local-storage:fs read file '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-back/package.json' succeed +1ms
  verdaccio:plugin:local-storage:fs read storage file '@PACKAGE/hamelin-back' has succeed +2ms
  verdaccio:plugin:local-storage storage path selected:  /var/lib/verdaccio/verdaccio/storage +3ms
  verdaccio:plugin:local-storage storage absolute path:  /var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-front +0ms
  verdaccio:plugin:local-storage:fs read a package '@PACKAGE/hamelin-front' +0ms
  verdaccio:plugin:local-storage:fs reading the file: '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-front/package.json' +0ms
  verdaccio:plugin:local-storage:fs read file '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-front/package.json' succeed +1ms
  verdaccio:plugin:local-storage:fs read storage file '@PACKAGE/hamelin-front' has succeed +0ms
  verdaccio:plugin:local-storage storage path selected:  /var/lib/verdaccio/verdaccio/storage +1ms
  verdaccio:plugin:local-storage storage absolute path:  /var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-form-back +1ms
  verdaccio:plugin:local-storage:fs read a package '@PACKAGE/hamelin-form-back' +1ms
  verdaccio:plugin:local-storage:fs reading the file: '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-form-back/package.json' +0ms
  verdaccio:plugin:local-storage:fs read file '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-form-back/package.json' succeed +0ms
  verdaccio:plugin:local-storage:fs read storage file '@PACKAGE/hamelin-form-back' has succeed +1ms
  verdaccio:plugin:local-storage storage path selected:  /var/lib/verdaccio/verdaccio/storage +1ms
  verdaccio:plugin:local-storage storage absolute path:  /var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-form-front +0ms
  verdaccio:plugin:local-storage:fs read a package '@PACKAGE/hamelin-form-front' +0ms
  verdaccio:plugin:local-storage:fs reading the file: '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-form-front/package.json' +0ms
  verdaccio:plugin:local-storage:fs read file '/var/lib/verdaccio/verdaccio/storage/@PACKAGE/hamelin-form-front/package.json' succeed +1ms
  verdaccio:plugin:local-storage:fs read storage file '@PACKAGE/hamelin-form-front' has succeed +0ms
  verdaccio:auth allow access for '@PACKAGE/test-verdaccio' +9ms
  verdaccio:auth:utils allow_action "access": groups [ '$all', '$anonymous', '@all', '@anonymous' ] +9ms
  verdaccio:auth:utils allow_action "access": groupAccess [ '$authenticated' ] +0ms
  verdaccio:auth:utils package "undefined" has permission "false" +0ms
  verdaccio:auth forbidden access for '@PACKAGE/test-verdaccio'. Error: 'authorization required to access package @PACKAGE/test-verdaccio' +0ms
  verdaccio:auth allow access for '@PACKAGE/nooks' +1ms
  verdaccio:auth:utils allow_action "access": groups [ '$all', '$anonymous', '@all', '@anonymous' ] +1ms
  verdaccio:auth:utils allow_action "access": groupAccess [ '$authenticated' ] +0ms
  verdaccio:auth:utils package "undefined" has permission "false" +0ms
  verdaccio:auth forbidden access for '@PACKAGE/nooks'. Error: 'authorization required to access package @PACKAGE/nooks' +0ms
  verdaccio:auth allow access for '@PACKAGE/hamelin-back' +0ms
  verdaccio:auth:utils allow_action "access": groups [ '$all', '$anonymous', '@all', '@anonymous' ] +0ms
  verdaccio:auth:utils allow_action "access": groupAccess [ '$authenticated' ] +0ms
  verdaccio:auth:utils package "undefined" has permission "false" +1ms
  verdaccio:auth forbidden access for '@PACKAGE/hamelin-back'. Error: 'authorization required to access package @PACKAGE/hamelin-back' +1ms
  verdaccio:auth allow access for '@PACKAGE/hamelin-front' +0ms
  verdaccio:auth:utils allow_action "access": groups [ '$all', '$anonymous', '@all', '@anonymous' ] +0ms
  verdaccio:auth:utils allow_action "access": groupAccess [ '$authenticated' ] +0ms
  verdaccio:auth:utils package "undefined" has permission "false" +0ms
  verdaccio:auth forbidden access for '@PACKAGE/hamelin-front'. Error: 'authorization required to access package @PACKAGE/hamelin-front' +0ms
  verdaccio:auth allow access for '@PACKAGE/hamelin-form-back' +0ms
  verdaccio:auth:utils allow_action "access": groups [ '$all', '$anonymous', '@all', '@anonymous' ] +0ms
  verdaccio:auth:utils allow_action "access": groupAccess [ '$authenticated' ] +1ms
  verdaccio:auth:utils package "undefined" has permission "false" +0ms
  verdaccio:auth forbidden access for '@PACKAGE/hamelin-form-back'. Error: 'authorization required to access package @PACKAGE/hamelin-form-back' +1ms
  verdaccio:auth allow access for '@PACKAGE/hamelin-form-front' +0ms
  verdaccio:auth:utils allow_action "access": groups [ '$all', '$anonymous', '@all', '@anonymous' ] +0ms
  verdaccio:auth:utils allow_action "access": groupAccess [ '$authenticated' ] +0ms
  verdaccio:auth:utils package "undefined" has permission "false" +0ms
  verdaccio:auth forbidden access for '@PACKAGE/hamelin-form-front'. Error: 'authorization required to access package @PACKAGE/hamelin-form-front' +1ms
  verdaccio:middleware:error error handler init +18ms
  verdaccio:middleware:error no error to report, jump next layer +0ms
  verdaccio:middleware:final set json type header support +46ms
  verdaccio:middleware:final set etag header 58e0494c51d30eb3494f7c9198986bb9 +0ms
{"level":25,"time":1744881662566,"pid":2875,"hostname":"debian-22","sub":"in","request":{"method":"GET","url":"/-/verdaccio/data/packages"},"user":null,"remoteIP":"88.174.71.150 via 192.168.0.6","status":304,"bytes":{"in":0,"out":0},"msg":"304, user: null(88.174.71.150 via 192.168.0.6), req: 'GET /-/verdaccio/data/packages', bytes: 0/0"}
```

**Comment by TxX8N8LN** [comment]
And i try without reverse proxy, i have same problem

**Comment by Michsior14** [comment]
Same on my side, but with ldap auth plugin.

**Comment by mbtools** [comment]
I think I found the root cause and have messaged @juanpicado on Discord.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/releases/tag/v6.1.3

**Comment by abdelfattahradwan** [comment]
I just tested 6.1.3, and I am still having the same issue. ☹

**Comment by juanpicado** [comment]
> I just tested 6.1.3, and I am still having the same issue. ☹

Could you share a detailed use case so I can test it? The original author case might be different. @abdelfattahradwan

**Comment by TxX8N8LN** [comment]
@juanpicado 

I just tested version 6.1.3 as well, and I'm still having the same issue.

In the log, I see "user: null" again when I try to access the package.

**Comment by juanpicado** [comment]
Thanks I'll look again, thanks for the feedback

**Comment by abdelfattahradwan** [comment]
@juanpicado I am using Verdaccio normally as a private NPM repository. I am getting the same logs as the original author, too.

My configuration file looks like this:
```yml
storage: /verdaccio/storage/data

plugins: /verdaccio/plugins

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

packages:
  "@*/*":
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated

  "**":
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
```

**Comment by mpcaddy** [comment]
I think it might be related to the main page. If I do a search I can still find packages and access the packages just not on the list from the page.
I just saw in your commit that your unit test has 
```
web:
  login: true
```
I've just added that and its working as expected now

**Comment by juanpicado** [comment]
👍🏼 that's true, then I should enforce `true` by default because many people does not have this on their local config most probably.  also not here https://github.com/verdaccio/verdaccio/blob/master/packages/config/src/conf/default.yaml#L21

**Comment by abdelfattahradwan** [comment]
I added:
```yaml
web:
  login: true
```
And still, no packages show up by default or when searching as an authenticated user. Here's the new configuration file:
```yaml
storage: /verdaccio/storage/data

plugins: /verdaccio/plugins

web:
  login: true

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

packages:
  "@*/*":
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated

  "**":
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
```
