### ISSUE TITLE
Unpublish is broken in 6.1.2

### ISSUE THREAD

**Issue by dafanasiev** [verdaccio/verdaccio#5214]
**Describe the bug**
Verdaccio fails to unpublish v1.0.0 after v1.0.1 is published (returns HTTP404):

**To Reproduce**
NOTE: bug is reproduced here: https://github.com/dafanasiev/verdaccio-6.1.2_unpublish_bug
1. publish 1.0.0 of a package
2. publish 1.0.1 of a package
3. try to unpublish 1.0.0 of a package

**Actual behavior**
verdaccio returns HTTP404,  unpublish fails

**Expected behavior**
Package is unpublished

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```yaml
storage: /tmp

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: trace }

packages:
  "**":
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

max_body_size: 256mb


security:
  api:
    jwt:
      sign:
        expiresIn: 3650d
  web:
    sign:
      expiresIn: 3650d

```

**Environment information**

official docker container image v6.1.2
