### ISSUE TITLE
Problem with access public registry via proxy

### ISSUE THREAD

**Issue by Chazing** [verdaccio/verdaccio#525]
My reason:

hi, my organization use internet behined a proxy,
We use npm public registry after set npm config proxy, http-proxy, https-proxy variables and it work fine.
I install verdaccio for official packages,
When i set the npm registry to be my verdaccio server, i can install local packages that i published,
but verdaccio cannot access http://registry.npmjs.org/.

####  Config file:	

```
# path to a directory with all packages
storage: ./storage

http-proxy:  http://myorgproxy/
https-proxy:  http://myorgproxy/

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000
web:
  enable: true
  title: My Npm Gellery

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: http://registry.npmjs.org/

listen: 1.0.0.25:5555

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: debug}
````

#### Additional information:

 - `$ npm --verbose` prints:
```
C:\Users\aaa>npm --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli
.js',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm verb config Skipping project config: C:\Users\aaa/.npmrc. (matches userco
nfig)
```
 - `$ npm config get registry` prints:
```
http://my ip:5555/
```
 - Verdaccio terminal output
````
 http --> ERR, req: 'GET http://registry.npmjs.org/npm', error: connect ETIMEDOU
T 
 http <-- 404, user: undefined(), req: 'GET /npm', error: no such pa
ckage available
 http --> ERR, req: 'GET http://registry.npmjs.org/bootstrap', error: connect ET
IMEDOUT 
 http <-- 404, user: undefined(), req: 'GET /bootstrap', error: no s
uch package available
 warn --> host registry.npmjs.org is now offline
````
 - Window
