### ISSUE TITLE
Error Writing Private Proxied npmjs Package with S3 Storage plugin

### ISSUE THREAD

**Issue by noahjohnhay** [verdaccio/verdaccio#5259]
**Your environment**
* **verdaccio version**: 6.0.5
* **s3 plugin**: latest

 
* **os**: linux
* **platform**: docker
* **reverse proxy**: behind an ALB

**Describe the bug**

Error proxying private npmjs packages, I can run npm view, and it shows the package but when installing it errors with a 404 and the following error log in Verdaccio about writing to S3. The folder is created and package.json, but the tar.gz files are not created

The weirdest thing is it works for packages proxied from Nexus which is private and it works for packages from the same uplink on npmjs that are public. I know the permissions are working as it can list the packages etc but seems to be breaking when trying to write to s3 which is so strange.

```
at Redirect.onResponse (/usr/local/lib/node_modules/verdaccio/node_modules/@cypress/request/lib/redirect.js:88:27)
at /usr/local/lib/node_modules/verdaccio/node_modules/@cypress/request/request.js:1053:10
at Request.emit (node:domain:489:12)
at Request.emit (node:events:530:35)
at Request.<anonymous> (/usr/local/lib/node_modules/verdaccio/build/lib/up-storage.js:424:23)
at ReadTarball.emit (node:domain:489:12)
at ReadTarball.emit (node:events:518:28)
at ReadTarball.<anonymous> (/usr/local/lib/node_modules/verdaccio/build/lib/storage.js:248:24)
at uploadStream.abort (/usr/local/lib/node_modules/verdaccio/build/lib/local-storage.js:434:19)
at uploadStream.abort (/verdaccio/plugins/verdaccio-aws-s3-storage/lib/s3PackageManager.js:332:29)
at ManagedUpload.abort (/verdaccio/plugins/verdaccio-aws-s3-storage/node_modules/aws-sdk/lib/s3/managed_upload.js:256:12)
at ManagedUpload.cleanup (/verdaccio/plugins/verdaccio-aws-s3-storage/node_modules/aws-sdk/lib/s3/managed_upload.js:635:10)
at ManagedUpload.callback (/verdaccio/plugins/verdaccio-aws-s3-storage/lib/s3PackageManager.js:285:60)
at convertS3Error (/verdaccio/plugins/verdaccio-aws-s3-storage/lib/s3Errors.js:40:47)
at getInternalError (/verdaccio/plugins/verdaccio-aws-s3-storage/node_modules/@verdaccio/commons-api/lib/index.js:131:26)
at getError (/verdaccio/plugins/verdaccio-aws-s3-storage/node_modules/@verdaccio/commons-api/lib/index.js:113:45)
InternalServerError: request aborted
}: request aborted
registry: 'npmjs'
sha: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
url: 'https://registry.npmjs.org/@XXXXXXXXXXXX/logger/-/logger-4.0.7.tgz',
warn --- error saving file {
error--- s3: [S3PackageManager writeTarball managedUpload send] emit error request aborted
info --- making request: 'GET https://registry.npmjs.org/@XXXXXXXXXXXX/logger/-/logger-4.0.7.tgz'
```

Example pnpm install output

```
pnpm i                                                                       
Scope: all 4 workspace projects
 WARN  27 deprecated subdependencies found: @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, @oclif/command@1.8.22, @oclif/config@1.18.2, @oclif/config@1.18.6, @oclif/config@1.18.8, @oclif/errors@1.3.5, @oclif/errors@1.3.6, @oclif/help@1.0.5, @oclif/parser@3.8.10, @tsconfig/esm@1.0.5, @tsconfig/node16-strictest-esm@1.0.3, @tsconfig/node16-strictest@1.0.4, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, har-validator@5.1.5, inflight@1.0.6, npmlog@5.0.1, querystring@0.2.0, read-package-json@7.0.0, request@2.88.2, right-pad@1.0.1, rimraf@2.6.3, rimraf@3.0.2, uuid@3.4.0
Packages: +27
+++++++++++++++++++++++++++
 ERR_PNPM_FETCH_404  GET https://VERDACCIO_ADRESS/@XXXXXX/logger/-/logger-4.0.7.tgz: Not Found - 404

This error happened while installing a direct dependency of /home/XXXX/code/verdaccio

An authorization header was used: Bearer XXXXXXXX
Progress: resolved 1866, reused 1811, downloaded 0, added 0
```

**Steps to reproduce**

Using Verdaccio 6.0.5 with s3-storage plugin
One uplink is npmjs with credentials to a private repository the other is to Nexus
installs/downloads from Nexus or public npmjs packages work as expected, but private npmjs ones fail to write to s3

**Expected behavior**

running "npm -i @XXXXX/package"
install succeeds (this throws a 404)
The file tar.gz is written to S3

**Configuration file**

```
storage: /verdaccio/storage/data

plugins: /verdaccio/plugins

web:
  enable: true
  title: Verdaccio
  darkMode: true
  login: true
  showInfo: false
  showSettings: false
  showFooter: false

auth:
  htpasswd:
    file: /verdaccio/htpasswd
    max_users: -1
    algorithm: bcrypt
    rounds: 12
  ldap:
    type: ldap
    groupNameAttribute: "cn"
    cache:
      size: 1000
      expire: 300
    client_options:
      url: "ldap://XXXX:3268"
      adminDn: "cn=XXXX,ou=XXXX,ou=XXXX,dc=XXXX,dc=net"
      searchBase: "dc=XXXX,dc=XXXX"
      searchFilter: "(&(objectClass=person)(cn={{username}}))"
      reconnect: true

store:
  aws-s3-storage:
    bucket: S3_BUCKET

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
    maxage: 5m
    auth:
      type: bearer
      token_env: true
  nexus:
    url: https://XXXXXXXX/
    cache: true
    maxage: 5m

packages:
  "@*/*":
    access: $authenticated
    proxy: nexus npmjs
  "**":
    access: $authenticated
    proxy: nexus npmjs

filters:
  plugin-secfilter:
    block:
      - package: next
        versions: ">11.1.4 <12 || >12.0 <12.3.5 || >13.0 <13.5.9 || >14.0 <14.2.25 || >15.0 <15.2.3" # https://github.com/vercel/next.js/security/advisories/GHSA-f82v-jwr5-mffw

server:
  keepAliveTimeout: 60

security:
  api:
    legacy: true
    jwt:
      sign:
        expiresIn: 365d

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: info }
```

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇
