### ISSUE TITLE
cannot download package from external repository

### ISSUE THREAD

**Issue by fadelguy** [verdaccio/verdaccio#616]
Verdaccio ver : 2.7.0

I have server 2012 R2 with verdaccio install on iisnode in internal network.
In our company we have a Nexus that open to npmjs.
In config.yalm i have config the uplinks to the nexus url:

uplinks: 
 nexus:
   url: http://nexus.com/npm

packages:
 access: $all
 publish: $authenticated
 proxy: nexus

My npm registy config to verdaccio.

I want that verdaccio auto download packages to store from nexus if the package don't exist

when i do npm install i saw in the verdaccio store the packages it try do download with .tmp but after seconds it deleted.

In iis logs i the see error:

>http --> 200, req: 'GET http://nexus.com/npm/@angular%2Fflex-layout' (streaming)
>http --> 200, req: 'GET http://nexus.com/npm/@angular%2Fflex-layout', bytes: 0/22906
>http <-- 200, user: undefined(undefind), req 'GET /@angular/flex-layout, bytes: 0/4351
>error--- unexpected error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
>Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
       at Object.exports._errnoException (util.js:1018:11)
       at errnoException (dns.js:33:15)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
http <-- 500, user: undefined(undefined), req: 'GET /@angular/flex-layout/-/flex-layout-2.0.0-rx.1.tgz', error: internal error

Please help me to fix that.
Thanks!

**Comment by fadelguy** [comment]
The Full config file:

`#
`# This is the default config file. It allows all users to do anything,
`# so don't use it on production systems.
`#
`# Look here for more config file examples:
` # https://github.com/verdaccio/verdaccio/tree/master/conf
`#
`# path to a directory with all packages
`storage: ./storage
`auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000
`# a list of other known repositories we can talk to`
uplinks:
  nexus:
    url: http://nexus.com/npm
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: nexus
  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all
    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: nexus
`# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
listen:

http://verdaccio.com:4873/         # default value`

**Comment by juanpicado** [comment]
Ok, I see more clearly your issue. `@*/*'` only will route any scoped packages through your nexus uplink. So, any other dependency, eg: `react` or `babel-core` will try to access the default one which is `npmjs` **even if is not defined in your config file**. So, if you want to solve your issue, either all resolve your traffic goes through `'**':` through nexus uplink or allow verdaccio to connect to `registry.npmjs.org`.

more info http://www.verdaccio.org/docs/en/packages.html

**Comment by fadelguy** [comment]
You can see that i have config the file right:
'**':
proxy: nexus

and it not working

**Comment by juanpicado** [comment]
Sorry, I did not see on my mobile the rest of the config file.
```
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: nexus
  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all
    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: nexus
```
