### ISSUE TITLE
The webinterface doesn't load when hosted with https as it tries to download scripts over http

### ISSUE THREAD

**Issue by arnederuwe** [verdaccio/verdaccio#622]
#### My reason:
I want to host the webinterface over https because of user credential security
#### Steps to reproduce:
I followed the exact same setup steps as described here: http://www.verdaccio.org/docs/en/iss-server.html
With the exception that I created a https binding using a wildcard certificate
I'm using IIS10 on Windows server 2016

Navigating to the web interface doesn't work. The index page is loaded but it tries to download additional resources over http:
![image](https://user-images.githubusercontent.com/3369747/37088882-0a3ffe20-21ff-11e8-8430-d17893b4d6ba.png)

adding a http binding and navigating over http works fine
#### App Version:
2.7.4
#### Config file:
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  activedirectory:
    url: "ldap://***"
    baseDN: '***'
    domainSuffix: '***'
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
 
listen: 
  - https://***/
```

**Comment by ayusharma** [comment]
I am looking into it.

**Comment by juanpicado** [comment]
@ayusharma he is using `2.1.0` ...

**Comment by arnederuwe** [comment]
my mistake, i'm using the latest version, 2.7.4

**Comment by ayusharma** [comment]
<img width="1280" alt="screen shot 2018-03-07 at 5 28 46 pm" src="https://user-images.githubusercontent.com/6918450/37091259-7f68ba42-222d-11e8-8af1-4dcbb0e9389a.png">

I setup verdaccio locally on https. It's working fine.

### Config 
```
# path to a directory with all packages
storage: ./storage

# a list of users
#
# This is deprecated, use auth plugins instead (see htpasswd below).
# users:
  # admin:
    # crypto.createHash('sha1').update(pass).digest('hex')
    # password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false

  title: Verdaccio

  # logo: logo.png

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

    # amount of time to wait for repository to respond
    # before giving up and use the local cached copy
    #timeout: 30s

    # maximum time in which data is considered up to date
    #
    # default is 2 minutes, so server won't request the same data from
    # uplink if a similar request was made less than 2 minutes ago
    #maxage: 2m

    # if two subsequent requests fail, no further requests will be sent to
    # this uplink for five minutes
    #max_fails: 2
    #fail_timeout: 5m

    # timeouts are defined in the same way as nginx, see:
    # http://wiki.nginx.org/ConfigNotation

    # add/override HTTP headers sent to the uplink server
    # this allows for HTTP Basic auth for example:
    #headers:
    #  authorization: "Basic YourBase64EncodedCredentials=="

    # set this to false to prevent tarballs from this upstream
    # to be stored in the local storage (defaults to true)
    #cache: false

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs
  # uncomment this for packages with "local-" prefix to be available
  # for admin only, it's a recommended way of handling private packages
  #'local-*':
  #  access: admin
  #  publish: admin
  #  # you can override storage directory for a group of packages this way:
  #  storage: 'local_storage'

  '**':
    # allow all users to read packages (including non-authenticated users)
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow 'admin' to publish packages
    publish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

#####################################################################
# Advanced settings
#####################################################################

## Special packages publish configurations
#publish:
## This will allow the publisher to publish packages even if any uplink is down.
#  allow_offline: true

# if you use nginx with custom path, use this to override links
#url_prefix: https://dev.company.local/verdaccio/

# You can specify listen address (or simply a port).
# If you add multiple values, verdaccio will listen on all of them.
#
# Examples:
#
listen:
# - localhost:4873            # default value
 - https://localhost:4873     # same thing
# - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
# - https://example.org:4873  # if you want to use https
# - [::1]:4873                # ipv6
# - unix:/tmp/verdaccio.sock    # unix socket

# Configure HTTPS, it is required if you use "https" protocol above.
https:
   key: /Users/ayush/.config/verdaccio/verdaccio-key.pem
   cert: /Users/ayush/.config/verdaccio/verdaccio-cert.pem
   ca:  /Users/ayush/.config/verdaccio/verdaccio-csr.pem
# type: file | stdout | stderr
# level: trace | debug | info | http (default) | warn | error | fatal
#
# parameters for file: name is filename
#  {type: 'file', path: 'verdaccio.log', level: 'debug'},
#
# parameters for stdout and stderr: format: json | pretty | pretty-timestamped
#  {type: 'stdout', format: 'pretty', level: 'debug'},
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

# you can specify proxy used with all requests in wget-like manner here
# (or set up ENV variables with the same name)
#http_proxy: http://something.local/
#https_proxy: https://something.local/
#no_proxy: localhost,127.0.0.1

# maximum size of uploaded json document
# increase it if you have "request entity too large" errors
#max_body_size: 1mb

# Notify Settings
# Notify was built primarily to use with Slack's Incoming
# webhooks, but will also deliver a simple payload to
# any endpoint. Currently only active for publish / create
# commands.
notify:
  # # Choose a method. Technically this will accept any HTTP
  # # request method, but probably stick to GET or POST
  # method: POST
  # # Only run this notification if the package name matches the regular
  # # expression
  # packagePattern: ^example-package$
  # # Any flags to be used with the regular expression
  # packagePatternFlags: i
  # # If this endpoint requires specific headers, set them here
  # # as an array of key: value objects.
  # headers: [{'Content-type': 'application/x-www-form-urlencoded'}]
  # # set the URL endpoint for this call
  # endpoint: https://hooks.slack.com/...
  # # Finally, the content you will be sending in the body.
  # # This data will first be run through Handlebars to parse
  # # any Handlebar expressions. All data housed in the metadata object
  # # is available for use within the expressions.
  # content: ' {{ handlebar-expression }}'
  # # For Slack, follow the following format:
  # # content: '{ "text": "Package *{{ name }}* published to version *{{ dist-tags.latest }}*", "username": "Verdaccio", "icon_emoji": ":package:" }'

  # Multiple notification endpoints can be created by specifying a collection
  'example-package-2':
    method: POST
    # Only run this notification if the package name matches the regular
    # expression
    packagePattern: ^(.*)$
    # Any flags to be used with the regular expression
    # since verdaccio 2.2.2 this property has been disabled read #108
    # it will be re-enabled after 2.5.0
    # packagePatternFlags: i
    # If this endpoint requires specific headers, set them here
    # as an array of key: value objects.
    # headers supports as well a literal object
    headers: {'Content-type': 'application/x-www-form-urlencoded'}
    # set the URL endpoint for this call
    endpoint: https://hooks.slack.com/services/x/xxxxxxxx/xxxxxxxxxxxxx
    # Finally, the content you will be sending in the body.
    # This data will first be run through Handlebars to parse
    # any Handlebar expressions. All data housed in the metadata object
    # is available for use within the expressions.
    # content: ' {{ handlebar-expression }}'
    # For Slack, follow the following format:
    content: '{ "text": "Package *{{ name }}* published to version *{{ dist-tags.latest }}*", "username": "Verdaccio", "icon_emoji": ":package:" }'

  'example-package-1':
    method: POST
    # Only run this notification if the package name matches the regular
    # expression
    packagePattern: ^(.*)$
    # Any flags to be used with the regular expression
    # since verdaccio 2.2.2 this property has been disabled read #108
    # it will be re-enabled after 2.5.0
    # packagePatternFlags: i
    # If this endpoint requires specific headers, set them here
    # as an array of key: value objects.
    # headers supports as well a literal object
    headers: {'Content-type': 'application/x-www-form-urlencoded'}
    # set the URL endpoint for this call
    endpoint: https://hooks.slack.com/services/xxxxxx/xxxxxxx
    # Finally, the content you will be sending in the body.
    # This data will first be run through Handlebars to parse
    # any Handlebar expressions. All data housed in the metadata object
    # is available for use within the expressions.
    # content: ' {{ handlebar-expression }}'
    # For Slack, follow the following format:
    content: '{ "text": "Package *{{ name }}* published to version *{{ dist-tags.latest }}*", "username": "Verdaccio", "icon_emoji": ":package:" }'
``` 

### Version
```
 warn --- config file  - /Users/ayush/.config/verdaccio/config.yaml
 warn --- http address - https://localhost:4873/ - verdaccio/2.7.4
```
