### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by askz** [verdaccio/verdaccio#625]
#### Config file: 
```yaml
storage: /var/lib/verdaccio
packages:
  '@*/*':
    allow_access: admin 
    allow_publish: admin 
    proxy: npmjs
  '**':
    allow_access: admin 
    allow_publish: admin 
    proxy: npmjs
  '*':
    allow_access: admin 
    allow_publish: admin 
    proxy: npmjs

listen: 0.0.0.0:4873

logs:
  - {type: 'file', path: '/var/log/verdaccio/verdaccio.log', level: 'warn'}

max_body_size: 50mb
```

#### Additional information:

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
Nothing interesting, since I can't even make requests
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
same here

Its running on debian on debian jessie 
Has been running for months without problems...

EDIT: I rebooted the server but the issue still remains.. why?
