### ISSUE TITLE
Some packages do not download

### ISSUE THREAD

**Issue by kneczaj** [verdaccio/verdaccio#645]
This might be a question, or issue specific to my setup but is very strange, so any help appreciated :)

#### My reason:
I use verdaccio with docker. I tried both https and http to query registry.npmjs.org. For now I would like just to have verdaccio to cache public packages.

**Currently I use http** as I had some other problems with https.

I have set up registry with `npm set registry` to verdaccio on a client machine. Afterwards I try to install all my dependencies of a project with `npm install`. Results:

Success for following and many more (part of `docker logs verdaccio`):
```
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-discard-duplicates', bytes: 0/3903
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-filter-plugins', bytes: 0/3637
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-merge-longhand', bytes: 0/2791
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-minify-font-values', bytes: 0/2950
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-minify-gradients', bytes: 0/2863
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-merge-rules', bytes: 0/5759
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-minify-params', bytes: 0/3373
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-normalize-charset', bytes: 0/2021
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-ordered-values', bytes: 0/3871
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-reduce-transforms', bytes: 0/2408
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-reduce-initial', bytes: 0/2492
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-normalize-url', bytes: 0/4980
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-minify-selectors', bytes: 0/5168
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-zindex', bytes: 0/3805
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-reduce-idents', bytes: 0/4286
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-unique-selectors', bytes: 0/2433
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /function-bind', bytes: 0/2471
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /postcss-message-helpers', bytes: 0/2074
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /reduce-css-calc', bytes: 0/5758
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /balanced-match', bytes: 0/3570
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /math-expression-evaluator', bytes: 0/4911
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /reduce-function-call', bytes: 0/1901
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /colormin', bytes: 0/3309
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /color', bytes: 0/6101
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /css-color-names', bytes: 0/1700
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /clone', bytes: 0/7382
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /color-string', bytes: 0/4133
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /color-convert', bytes: 0/6164
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /color-name', bytes: 0/1775
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /uniqs', bytes: 0/1307
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /uniqid', bytes: 0/3120
 http <-- 200, user: undefined(106.120.107.44), req: 'GET /macaddress', bytes: 0/1936
```

Problems just with these:
```
 http <-- 404, user: undefined(106.120.107.44), req: 'GET /postcss-svgo', error: no such package available
 http <-- 404, user: undefined(106.120.107.44), req: 'GET /caniuse-api', error: no such package available
 http <-- 404, user: undefined(106.120.107.44), req: 'GET /vendors', error: no such package available
 http <-- 404, user: undefined(106.120.107.44), req: 'GET /lodash.memoize', error: no such package available
 http <-- 404, user: undefined(106.120.107.44), req: 'GET /lodash.uniq', error: no such package available
```
The same when I run `npm install <package_name>` for a particular package. It is 100% reproducable for the same packages on my setup.

#### App Version:
I use docker image downloaded an hour ago. 
```
$ docker images
verdaccio/verdaccio     latest              cab129e3f6f6        2 months ago        345MB
```

#### Config file:
```
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: http://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

#### Additional information:
 - Which (Windows, OS X/macOS, or Linux) environment are you running verdaccio?
Red Hat Enterprise Linux Server 7.4
