### ISSUE TITLE
Unable to install the bitbucket plugin using Docker

### ISSUE THREAD

**Issue by maximelebastard** [verdaccio/verdaccio#662]
#### My reason

Use Verdaccio with a Bitbucket Auth, and through the Dockerfile of my tooling server

#### Steps to reproduce

* Edit the Dockerfile to add the plugin installation step
./verdaccio/Dockerfile
```docker
FROM verdaccio/verdaccio:latest

RUN npm install verdaccio-bitbucket
```
* Run the and launch the container

docker-compose.yml
```yaml
  verdaccio:
    build: ./verdaccio
    restart: always
    volumes:
      - ${VERDACCIO_DATA_DIR}:/verdaccio
      - ./verdaccio/config.yaml:/verdaccio/conf/config.yaml
```

```bash
docker-compose up --build verdaccio
```

* Get this error

```bash
verdaccio_1        |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio_1        |  error--- plugin not found. try npm install verdaccio-bitbucket
verdaccio_1        | /usr/local/app/src/lib/plugin-loader.js:60
verdaccio_1        |       throw Error('"' + p + '" plugin not found\ntry "npm install verdaccio-' + p + '"');
verdaccio_1        |       ^
verdaccio_1        |
verdaccio_1        | Error: "bitbucket" plugin not found
verdaccio_1        | try "npm install verdaccio-bitbucket"
verdaccio_1        |     at /usr/local/app/src/lib/plugin-loader.js:60:13
verdaccio_1        |     at Array.map (<anonymous>)
verdaccio_1        |     at load_plugins (/usr/local/app/src/lib/plugin-loader.js:34:51)
verdaccio_1        |     at new Auth (/usr/local/app/src/lib/auth.js:38:20)
verdaccio_1        |     at module.exports (/usr/local/app/src/api/index.js:21:16)
verdaccio_1        |     at afterConfigLoad (/usr/local/app/src/lib/cli.js:118:15)
verdaccio_1        |     at Object.<anonymous> (/usr/local/app/src/lib/cli.js:69:1)
verdaccio_1        |     at Module._compile (module.js:635:30)
verdaccio_1        |     at Object.Module._extensions..js (module.js:646:10)
verdaccio_1        |     at Module.load (module.js:554:32)
verdaccio_1        |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio_1        |  error--- plugin not found. try npm install verdaccio-bitbucket
verdaccio_1        | /usr/local/app/src/lib/plugin-loader.js:60
verdaccio_1        |       throw Error('"' + p + '" plugin not found\ntry "npm install verdaccio-' + p + '"');
verdaccio_1        |       ^
```

#### App Version

latest (2.7 I guess from Docker hub)

#### Config file

```yaml
#
# Verdaccio (NPM server) configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./verdaccio/storage

# Web ui
web:
  enable: true
  title: Verdaccio

auth:
  bitbucket:
    allow: myorg(admin|collaborator)

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@myorg/*':
    # scoped packages
    access: myorg
    publish: myorg
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: myorg

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: myorg

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}

publish:
  ## This will allow the publisher to publish packages even if any uplink is down.
  allow_offline: true
```

#### Additional information:

Running with Docker on MacOS

It's the same for a global install with this Dockerfile

```docker
FROM verdaccio/verdaccio:latest

USER root
RUN npm install -g verdaccio-bitbucket
USER verdaccio
```
