### ISSUE TITLE
Only  package.json being saved in storage/<npm-package-name> for public package

### ISSUE THREAD

**Issue by mdfirozansari** [verdaccio/verdaccio#664]
after running the following command
npm i composer-common

only packge.json file is created under following directory.
```
cd ~/.local/share/verdaccio/storage/composer-common/
```
If I run the 'ls' command , I am only getting the package.json file. No other *.tgz file is created for composer-common package. Because of this reason 'npm i composer-common' is failing when there is not Internet connection.

Here is my configuration:
npm@5.8.0
node@v8.11.1

Output of  - `$ npm config get registry` prints:
http://localhost:4873/

 - Which (Windows, OS X/macOS, or Linux) environment are you running verdaccio?:
I am using on Ubuntu

 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
Output : 
```
storage: /home/firoz/.local/share/verdaccio/storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
     access: $all

   
    publish: $authenticated

    
    proxy: npmjs


logs:
  - {type: stdout, format: pretty, level: http}

```
