### ISSUE TITLE
Uplink documentation is confusing setting Auth headers

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#670]
#### My reason:

The following question in StackOverflow

https://stackoverflow.com/questions/49946420/npm-verdaccio-set-uplink-to-own-remote-server?noredirect=1#comment87120890_49946420

We need to upgrade the uplink documentation to be more clear when the user sets Authorization headers. We do not explain we use JWT instead Basic Auth.

This commit is not documented properly, Verdaccio uses JWT instead Basic authorization, was deprecated in `v2.3.0`

https://github.com/verdaccio/verdaccio/commit/d6e04be39ff9b177e33423bce87d0185392e29de#diff-574051ef1fbe43a2746c5cd241d631c7L370

https://github.com/verdaccio/verdaccio/blob/master/docs/uplinks.md#configuration

#### Steps to reproduce:
* Setup 2 verdaccio servers in the way is explained in the question
* Install any package

#### App Version:
- All 
#### Config file:

```
uplinks:
  aws:
    url: https://our-NPM-AWS-server.com/
    #strictUrlMatch: false
    headers:
      authorization: "Basic <token_which_I_harvested_from_/.npmrc_file>"

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: aws

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: aws
```

#### Additional verbose log:

```
http --> 200, req: 'GET https://our-NPM-AWS-server.com/verdaccio-bitbucket' (streaming)
 http --> 200, req: 'GET https://our-NPM-AWS-server.com/verdaccio-bitbucket', bytes: 0/34578
 http <-- 200, user: <npm_account>(127.0.0.1), req: 'GET /verdaccio-bitbucket', bytes: 0/5038
 http <-- 500, user: <npm_account>(127.0.0.1), req: 'GET /verdaccio-bitbucket/-/verdaccio-bitbucket-1.0.0.tgz', error: bad uplink status code: 403
 http <-- 500, user: <npm_account>(127.0.0.1), req: 'GET /verdaccio-bitbucket/-/verdaccio-bitbucket-1.0.0.tgz', error: bad uplink status code: 403
 http <-- 500, user: <npm_account>(127.0.0.1), req: 'GET /verdaccio-bitbucket/-/verdaccio-bitbucket-1.0.0.tgz', error: bad uplink status code: 403
````
