### ISSUE TITLE
package list is not properly reloaded after login

### ISSUE THREAD

**Issue by jharris4** [verdaccio/verdaccio#679]
**Describe the bug**
We have a verdaccio server setup with private packages that are authenticated using the `verdaccio-ldap` plugin. This means that in the web ui, anonymous (logged out) users will get an empty package list, but logged in users will see the packages they are allowed to.

When I visit the verdaccio web interface I initially see an empty package list. When I log in, the web interface updates to show `Hi, <username>` and a logout button but the package list stays empty.

Refreshing the page fixes the issue.

**To Reproduce**
1. visit the web interface while logged out
2. login
3. the package list is not properly updated for the logged in user

**Expected behavior**

The package list should properly refresh to show the packages for the logged in user.

**Docker || Kubernetes (please complete the following information):**

Not using Docker

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
listen: http://0.0.0.0:4873

storage: ./storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://ldap.domain.com"
      adminDn: "uid=verdaccio,cn=sysaccounts,cn=etc,dc=domain,dc=com"
      adminPassword: "thepassword"
      searchBase: "cn=users,cn=accounts,dc=domain,dc=com"
      searchFilter: "(uid={{username}})"
      cache: False
      searchAttributes:
        - "*"
        - memberOf
      tlsOptions:
        rejectUnauthorized: False

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: verdaccio
    publish: verdaccio
    proxy: npmjs

  '**':
    access: verdaccio
    publish: verdaccio
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}
```

**Debugging output**
 
I traced the network requests to load the package list both when the user is logged out, and then after they have logged in:

```
** First load first request while logged out

Request Headers

:authority: verdaccio.xxxxxx.com
:method: GET
:path: /-/verdaccio/packages
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr;q=0.8
cache-control: no-cache
pragma: no-cache
referer: https://verdaccio.artsman.com/
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Response Headers

access-control-allow-origin: *
content-length: 3
content-type: application/json; charset=utf-8
date: Mon, 07 May 2018 21:16:49 GMT
etag: "58e0494c51d30eb3494f7c9198986bb9"
server: nginx/1.10.3 (Ubuntu)
status: 200
strict-transport-security: max-age=31536000; preload
strict-transport-security: max-age=31536000
vary: Accept-Encoding
x-frame-options: deny
x-powered-by: verdaccio/2.7.4
x-status-cat: http://flic.kr/p/aVuVsF

Response

[]
```

```
** User logged in first request

Request Headers

:authority: verdaccio.xxxx.com
:method: GET
:path: /-/verdaccio/packages
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr;q=0.8
authorization: xxxxxxxxxxxx
if-none-match: "58e0494c51d30eb3494f7c9198986bb9"
referer: https://verdaccio.xxxxxx.com/
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Response Headers

access-control-allow-origin: *
date: Mon, 07 May 2018 21:17:45 GMT
etag: "58e0494c51d30eb3494f7c9198986bb9"
server: nginx/1.10.3 (Ubuntu)
status: 304
strict-transport-security: max-age=31536000; preload
strict-transport-security: max-age=31536000
x-frame-options: deny
x-powered-by: verdaccio/2.7.4
x-status-cat: http://flic.kr/p/aXY3dH

Response

[]
```

Notice that after login, the server is giving a `304` status code but the `authorization` header was present on the request.

**Comment by juanpicado** [comment]
I updated the code, removing authorization headers and domain.

**Comment by juanpicado** [comment]
Dummy question, Have you tried with default auth plugin?

**Comment by jharris4** [comment]
`I've updated the code, removing authorization headers and domain.`

Is there a PR related to that? I would have thought the authorization headers were necessary!

`Dummy question, Have you tried with default auth plugin?`

We haven't been using the default auth plugin since we finally got ldap auth working the way we wanted. I could probably hack things up to test with basic auth, do you suspect that this problem is specific to that plugin?

**Comment by ayusharma** [comment]
@matiascarranza Please share following:

**Verdaccio version**

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:beta]
 - Docker commands [e.g. docker pull ...]
 - Docker Version [e.g. v18.05.0-ce-rc1]

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**
Add any other context about the problem here.

**Comment by matiascarranza** [comment]
OK sure @ayusharma, here you have the info:

Maybe I'm expecting that web UI shows the "Search box" to navigate all the available packages after login, and it's not a feature supported.

I'll provide the info you asked me though:
```
$ verdaccio -V
3.4.1
```

### Screenshots
**Not logged in**
![image](https://user-images.githubusercontent.com/557979/43584575-2030d750-9639-11e8-803e-4834cc7662e7.png)


**Logged in**
![image](https://user-images.githubusercontent.com/557979/43584599-30b8344c-9639-11e8-9492-17e7f9094a71.png)

### Configuration File
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /Users/[user]/.local/share/verdaccio/storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 100

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true
  #github-oauth:
  #  client-id: 0951accf56280c208b7f # required
  #  client-secret: 29d1ce421b9fa1f34c7b54050b349965d4fdda4a # required

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
listen:
  - 0.0.0.0:4000

```
### Debugging output

```
$ NODE_DEBUG=request verdaccio
 warn --- config file  - /Users/[user]/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://0.0.0.0:4000/ - verdaccio/3.4.1
 http <-- 200, user: test(127.0.0.1), req: 'POST /-/verdaccio/login', bytes: 40/464
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/0.style.fc04f35bd94cadfc0b88.css', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/7.style.aa656b2ed0a72983e193.css', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/manifest.565068b6767c42a66a2b.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/vendors.565068b6767c42a66a2b.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/main.565068b6767c42a66a2b.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/1.565068b6767c42a66a2b.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/2.565068b6767c42a66a2b.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/4.style.7810a9ba1e42f2cb3a9c.css', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/4.565068b6767c42a66a2b.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/logo', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/logo.png', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0
```


```
$ npm -ddd
npm info it worked if it ends with ok
npm verb cli [ '/Users/[user]/.nvm/versions/node/v6.11.5/bin/node',
npm verb cli   '/Users/[user]/.nvm/versions/node/v6.11.5/bin/npm',
npm verb cli   '-ddd' ]
npm info using npm@3.10.10
npm info using node@v6.11.5
```
```
$ npm config get registry
http://localhost:4000/
```
