### ISSUE TITLE
Rewrite requested package for upstream repository

### ISSUE THREAD

**Issue by MartinLoeper** [verdaccio/verdaccio#684]
**Is your feature request related to a problem? Please describe.**
I would like to change the request for upstream packages. Example: We configured our ci server to use verdaccio as repository. There is a package at npmjs which crashes our build: mkdirp@0.5.0 is a dependency which is required by another package (extract-zip).   
We would like to redirect all requests for mkdirp@0.5.0 to mkdirp@0.5.1.

Is this currently possible?

**Describe the solution you'd like**
A simple config option in the config file where you can map requests for specific packages to other upstream packages, such as:
```
uplinks:
  npmjs:
   url: https://registry.npmjs.org/
   rewrite:
   - mkdirp@0.5.0: mkdirp@0.5.1
```

**Describe alternatives you've considered**
I am not a npm expert. I appreciate any hint for solving the kind of npm issues descibed above.
