### ISSUE TITLE
Publish testing package "lodash" to private registry and find that new installed package overrided the real package 'lodash' from upstream registry

### ISSUE THREAD

**Issue by gemmi** [verdaccio/verdaccio#686]
**Describe the bug**
i publish a testing pacakge `lodash` with the same name of real package lodash from upstream and verdaccio accepted, then i run `npm install lodash` and found installed pacakge is the testing package but not the real one, which means that package with the same name of upstream registry is overriden by the testing package, and i cann't get the real one via "npm install" comman.

**To Reproduce**
read as upside

**Expected behavior**
people cannot publish package with the same name of package from upstream reigstry, verdaccio checks name-confliction with upstream registry before publish.
as no one knows whether his package name is conficted with public packages from upstream registry, if verdaccio checks name-confliction before publish, that will help people to avoid package overriding.

**Screenshots**
not needed

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
uplinks:
  mirror:
    url: xxxxxxxxxxxxxxxxxxxxxxx
packages:

  '**':
    access: $all
    publish: $authenticated
    proxy:  mirror

publish:
    allow_offline: true

```

**Debugging output**
not needed

**Additional context**
Verdeccio version:  2.7.4

**Comment by juanpicado** [comment]
You can do the following.

```
uplinks:
  mirror:
    url: xxxxxxxxxxxxxxxxxxxxxxx
packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: mirror
  'lodash':
     access: $all
    publish: $all
    ## <---- here the key, set up such module do not proxy at all. 
  '**':
    access: $all
    publish: $authenticated
    proxy:  mirror
publish:
    allow_offline: true
```
Please try, but, before clear the `lodash` folder in your storage.
