### ISSUE TITLE
Should SSL be activated when using behind a NGINX ssl proxy.

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#690]
This is my nginx SSL vhost : 

```ruby
server {
  listen 443 ssl http2;

  server_name npm.example.com;
  server_tokens off;
  root /dev/null;

  ## Increase this if you want to upload large attachments
  ## Or if you want to accept large git objects over http
  client_max_body_size 20m;

  add_header Strict-Transport-Security max-age=63072000;
  # add_header X-Frame-Options DENY;
  # add_header X-Content-Type-Options nosniff;

  ## include domain ssl config
  include /etc/nginx/ssl-conf/wildcard.example.com.ssl.conf;

  ## Redirect all request
  location / {
    proxy_pass http://172.16.0.2:31138;
    proxy_set_header Host            $host:$server_port;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  access_log  /var/log/nginx/example/verdaccio_access.log;
  error_log   /var/log/nginx/example/verdaccio_error.log;

}
```

The background verdaccio service is configured with:

```yaml
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
#   # Maximum amount of users allowed to register, defaults to "+inf".
#   # You can set this to -1 to disable registration.
#   # currently used only for deployment accounts
    max_users: 2

# a list of other known repositories we can talk to

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@my-org/*':
    # scoped packages
    access: $authenticated
    publish: RedactedADGroup

  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
web:
  enable: true
  title: Redacted
```

I am using

```env
VERDACCION_VERSION=2.7.4
VERDACCION_LDAP_VERSION=1.3.0
```

The DOC say right after the reverse nginx proxy configuration to configure SSL:

https://www.verdaccio.org/docs/en/ssl.html

I believe this should only be done to have it without nginx in SSL instead of http, am I correct ?
Or should I configure my certificate in order to work with the npm registry.
