### ISSUE TITLE
Publish without publishing to proxy

### ISSUE THREAD

**Issue by reggi** [verdaccio/verdaccio#705]
* I am using the default configuration
* I am unable to publish.
* I am getting the `Cannot publish over existing version.` error.
* I would like to maintain `npmjs` proxy for downloads.
* I would like to ignore `npmjs` proxy for publishing

If I remove the `npmjs` proxy right now, and publish it works as expected, but then installs of all npm packages will fail. 

I kind of what the best of both worlds.

The only way I believe this is possible right now would be to have two verdaccio servers running one for publishing with no proxy and one with `npmjs` and the `publishing` server as proxyies.

I am trying to have a registry that has duplicate packages / versions that may overwrite existing packages in the npm registry.

**Comment by juanpicado** [comment]
`Cannot publish over existing version` it is by design. 

Using `yarn` as example. I'm trying to publish `1.6.0`. But with proxy enabled always we ask for metadata, which contains all versions existing in the selected uplink (npmjs as default). In the following execution would be true and returns `409` error.

```
  'yarn':
    access: all
    publish: all
    proxy: npmjs
```

![screen shot 2018-05-24 at 7 48 12 am](https://user-images.githubusercontent.com/558752/40466667-e9f0ef8e-5f26-11e8-8018-adb42a865b46.png)

I think we cannot change this, otherwise would be a mess, packages published should be immutable if you want to proxy from somewhere else.

If you are interested only on override completely a package and do not proxy at all is follow this section https://www.verdaccio.org/docs/en/packages.html#usage and just ignore proxy such package (eg: yarn) and let verdaccio downloads the remaining ones.

```
packages:
 '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
  'yarn':
    access: all
    publish: all
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

```
I'm asuming you want override one single package, since you did not explained whether what's your specific strategy.
