### ISSUE TITLE
Whether the login authentication can consider the custom interface

### ISSUE THREAD

**Issue by yansenlei** [verdaccio/verdaccio#713]

**Comment by juanpicado** [comment]
You will need to elaborate a bit more what you are requesting.

**Comment by yansenlei** [comment]
Thank you for your reply, I've written a authentication plugin [verdaccio-delegated-auth](https://github.com/yansenlei/verdaccio-delegated-auth)

**Comment by juanpicado** [comment]
@yansenlei Awesome! Happy to see a new plugin.  But I do not understand the objective of this ticket.

**Comment by yansenlei** [comment]
@juanpicado 
I refer to [sinopia-delegated-auth](https://github.com/milinnovations/sinopia-delegated-auth), Make the authentication more flexible

**Comment by juanpicado** [comment]
> Whether the login authentication can consider the custom interface

@yansenlei  I meant the title of the ticket.

**Comment by yansenlei** [comment]
@juanpicado 
My mean to do custom authentication 😉

**Comment by juanpicado** [comment]
There is custom authentication already since sinopia. Sorry I still do not get it.

**Comment by yansenlei** [comment]
Maybe i do not understand, I hope to support 'name' and 'password' fields can be customized, And api style support restful and json-rps

**Comment by juanpicado** [comment]
Could you provide an example?

**Comment by yansenlei** [comment]
Sure, for example, such a `config.yaml`:
```yaml
auth:
  # htpasswd:
  #   file: ./htpasswd
  delegated-auth:
    url: https://your-auth-api/
    user_key: name # username field, default: username
    pwd_key: password # password field, default: password
```
