### ISSUE TITLE
Uplink timeouts/connectivity issues reported as "no such package available"

### ISSUE THREAD

**Issue by edmorley** [verdaccio/verdaccio#720]
**Describe the bug**
If the uplink request to a registry fails with a connectivity error such as `socket hang up` or `ETIMEDOUT`, the response to the client is an HTTP 404 which makes it give a misleading error message about the package not existing.

The yarn client reports:
```
error Couldn't find package "align-text@^0.1.3" required by "center-align@^0.1.1" on the "npm" registry.
...
Error: Couldn't find package "har-schema@^2.0.0" required by "har-validator@~5.0.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/travis/.yarn/lib/cli.js:243:66)
    at new MessageError (/home/travis/.yarn/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/home/travis/.yarn/lib/cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (/home/travis/.yarn/lib/cli.js:98:30)
    at /home/travis/.yarn/lib/cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
...
```

However the Verdaccio logs show the real cause:
```
 info <-- 127.0.0.1 requested 'GET /har-schema'
 info --> making request: 'GET https://registry.yarnpkg.com/har-schema'
...
 info <-- 127.0.0.1 requested 'GET /align-text'
 info --> making request: 'GET https://registry.yarnpkg.com/align-text'
...
 http --> ERR, req: 'GET https://registry.yarnpkg.com/har-schema', error: socket hang up
 http <-- 404, user: undefined(127.0.0.1), req: 'GET /har-schema', error: no such package available
...
 http --> ERR, req: 'GET https://registry.yarnpkg.com/align-text', error: ETIMEDOUT
 http <-- 404, user: undefined(127.0.0.1), req: 'GET /align-text', error: no such package available
```

**To Reproduce**
1. Open a PR against `master` of https://travis-ci.org/mozilla-neutrino/neutrino-dev thereby triggering the TravisCI run
2. Retrigger the TravisCI job until it fails due to their current connectivity flakiness
3. Look at the Verdaccio logs

**Expected behavior**
* (ideally, but not the primary issue here) the initial request to the registry should be retried
* if the retry fails, Verdaccio should reply with an HTTP 504 ("Gateway timeout") or some other HTTP status code that would let the yarn client show the correct error message

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```yml
store:
  memory:
    limit: 10000
uplinks:
  yarnpkg:
    url: https://registry.yarnpkg.com/
    timeout: 20s
    max_fails: 5
packages:
  'neutrino':
    access: $anonymous
    publish: $anonymous
  '@neutrinojs/*':
    access: $anonymous
    publish: $anonymous
  '**':
    access: $anonymous
    proxy: yarnpkg
logs:
  - {type: stdout, format: pretty, level: debug}
```

**Debugging output**
https://travis-ci.org/mozilla-neutrino/neutrino-dev/jobs/385364189#L989

**Additional context**
This issue also occurred when using the npmjs.org registry instead of Yarn's.
