### ISSUE TITLE
verdaccio is requesting packages that are only hosted locally from the upstream registry.

### ISSUE THREAD

**Issue by jharris4** [verdaccio/verdaccio#741]
verdaccio is requesting packages that are only hosted locally from the upstream registry.

Here's a relevant snippet/example from my verdaccio.log file:

```
{"name":"verdaccio","hostname":"verdaccio1","pid":3474,"sub":"in","level":30,"req":{"method":"GET","url":"/@artsman%2freact-router-nav","headers":{"origin":"https://verdaccio.artsman.com","connection":"keep-alive","host":"verdaccio.artsman.com","x-real-ip":"100.12.42.32","x-forwarded-for":"100.12.42.32","x-forwarded-proto":"https","user-agent":"yarn/1.7.0 npm/? node/v10.3.0 darwin x64","accept":"application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*","authorization":"<Classified>","accept-encoding":"gzip, deflate"},"remoteAddress":"192.168.11.31","remotePort":48902},"ip":"192.168.11.31","msg":"@{ip} requested '@{req.method} @{req.url}'","time":"2018-06-06T16:49:51.928Z","v":0}
{"name":"verdaccio","hostname":"verdaccio1","pid":3474,"sub":"out","level":30,"method":"GET","headers":{"Accept":"application/json;","Accept-Encoding":"gzip","User-Agent":"npm (verdaccio/3.0.0)","Via":"1.1 00bcb945d706 (Verdaccio)"},"uri":"https://registry.npmjs.org/@artsman%2Freact-router-nav","msg":"making request: '@{method} @{uri}'","time":"2018-06-06T16:49:51.938Z","v":0}
{"name":"verdaccio","hostname":"verdaccio1","pid":3474,"sub":"out","level":35,"request":{"method":"GET","url":"https://registry.npmjs.org/@artsman%2Freact-router-nav"},"status":404,"msg":"@{!status}, req: '@{request.method} @{request.url}' (streaming)","time":"2018-06-06T16:49:52.071Z","v":0}
{"name":"verdaccio","hostname":"verdaccio1","pid":3474,"sub":"out","level":35,"err":null,"request":{"method":"GET","url":"https://registry.npmjs.org/@artsman%2Freact-router-nav"},"status":404,"bytes":{"in":0,"out":21},"msg":"@{!status}, req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}","time":"2018-06-06T16:49:52.071Z","v":0}
{"name":"verdaccio","hostname":"verdaccio1","pid":3474,"sub":"in","level":35,"request":{"method":"GET","url":"/@artsman%2freact-router-nav"},"user":"jharris","remoteIP":"100.12.42.32 via 192.168.11.31","status":200,"bytes":{"in":0,"out":2053},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}","time":"2018-06-06T16:49:52.073Z","v":0}
{"name":"verdaccio","hostname":"verdaccio1","pid":3474,"sub":"in","level":35,"request":{"method":"GET","url":"/@artsman%2freact-router-nav"},"user":"jharris","remoteIP":"100.12.42.32 via 192.168.11.31","status":200,"bytes":{"in":0,"out":2053},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}","time":"2018-06-06T16:49:52.073Z","v":0}
```

And here's my config.yaml:

```
listen: http://0.0.0.0:4873

storage: ./storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://the-domain.com"
      adminDn: "uid=verdaccio,cn=sysaccounts,cn=etc,dc=the-domain,dc=com"
      adminPassword: "the-password"
      searchBase: "cn=users,cn=accounts,dc=the-domain,dc=com"
      searchFilter: "(uid={{username}})"
      cache: False
      searchAttributes:
        - "*"
        - memberOf
      tlsOptions:
        rejectUnauthorized: False

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: verdaccio
    publish: verdaccio
    proxy: npmjs

  '**':
    access: verdaccio
    publish: verdaccio
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}
```

I suspect that I should be changing the above config to NOT proxy packages that are in the `@my-private-scope/*` scope somehow?

If that's the case, I could use some help with the correct config file syntax for that! thanks.
