### ISSUE TITLE
verdaccio endpoint in generated lockfiles

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#801]
It seems the localhost address of verdaccio gets written to the lockfile. Is there a solution to prevent this (without using /etc/hosts).

**Comment by juanpicado** [comment]
I've been tracking this issue for a while, unfortunately, we cannot do anything, not even other private registries. I ignore whether `pnpm` has the same issue cc @zkochan 

npm
https://github.com/npm/npm/issues/19578

Yarn
https://github.com/yarnpkg/rfcs/pull/64
https://github.com/yarnpkg/yarn/issues/3330

**Comment by zkochan** [comment]
In `shrinkwrap.yaml` (which is the lockfile created by `pnpm`) there is a field called [registry](https://github.com/pnpm/spec/blob/master/shrinkwrap/3.8.md#registry). We don't include the full URLs of packages, only if they are from a different registry.

`shrinkwrap.yaml` file example:

```yaml
dependencies:
  is-positive: 3.1.0
packages:
  /is-positive/3.1.0:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-hX21hKG6XRyymAUn/DtsQ103sP0=
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 8
shrinkwrapVersion: 3
specifiers:
  is-positive: ^3.1.0
```
