### ISSUE TITLE
install package with optional dependencies would show verbose warning on windows

### ISSUE THREAD

**Issue by calledT** [verdaccio/verdaccio#831]
**Describe the bug**
install package with optional dependencies by verdaccio registry would show verbose warning on windows.
```log
WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\webpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules\webpack\node_modules\fsevents\node_modules\abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\abbrev' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules\webpack\node_modules\fsevents\node_modules\ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\ansi-regex' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules\webpack\node_modules\fsevents\node_modules\aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\aproba' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules\webpack\node_modules\fsevents\node_modules\balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\balanced-match' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.0.1 (node_modules\webpack\node_modules\fsevents\node_modules\chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\chownr' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules\webpack\node_modules\fsevents\node_modules\code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\code-point-at' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules\webpack\node_modules\fsevents\node_modules\concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\concat-map' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules\webpack\node_modules\fsevents\node_modules\console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\console-control-strings' -> 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\.console-control-strings.DELETE'
```

after install,  run `npm ls -g --depth=0`  would show the below error

```log
npm ERR! error in C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents: ENOENT: no such file or directory, open 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\package.json'
npm ERR! error in C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\rc: ENOENT: no such file or directory, open 'C:\Users\home\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\node_modules\rc\package.json'
```

**To Reproduce**
1.  npm install -g webpack --registry=myverdaccioregistry

**Expected behavior**
like use npm registry, show the below warning and no error when list global package
```log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\webpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```yaml
listen:
  - 0.0.0.0:3163

# path to a directory with all packages
storage: ./storage

auth:
  ldap:
    type: ldap
    client_options:
      ...
      
# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```
