### ISSUE TITLE
Request authentication is not being called when user attemps to do: npm update

### ISSUE THREAD

**Issue by Yvtq8K3n** [verdaccio/verdaccio#889]
**Describe the bug**
Request authentication is not being called when user attemps to do: npm update

**To Reproduce**
- npm install body{dependencies: head:1.0.0, hands:latest, legs:1.0.0}
- On hands: - npm version 2.0.0
- On hands - npm publish
- On body - npm update FAILS 

```
Config.yaml:
auth:
   auth-request:
   ...

packages:
  'body':
    access: $authenticated
    publish: $authenticated
    #proxy: npmjs
  'body':
    access: $authenticated
    publish: $authenticated
    #proxy: npmjs
  'body':
    access: $authenticated
    publish: $authenticated
    #proxy: npmjs
```

**Screenshots**
- install --save hands[ok] 
![image](https://user-images.githubusercontent.com/19397871/43552582-f51d66ec-95e2-11e8-9d09-fe00576b8ef7.png)
 As u can see in order to run the npm install verdaccio calls 1st the authenticate_route and only then applys the allow_access route.

- npm update
![image](https://cdn.discordapp.com/attachments/388675051710447616/474144179040026624/unknown.png)
However this does not happen when u do npm update since only allow_acess route is called, the current user is set as undefined and so it fails

I apologize for the name of the packages in the images being in portuguese(but it would require alot of time to change them to english, i still converted the name in this issuie for the sake of comprehension)

**Additional context**
More info about what im talking can be found in here: https://www.verdaccio.org/docs/en/dev-plugins#api
In case u need to use the plugin in order to test(Not that i recomend:3):
https://www.npmjs.com/package/verdaccio-auth-request
