### ISSUE TITLE
health-check on docker container

### ISSUE THREAD

**Issue by rong0312** [verdaccio/verdaccio#923]
Greetings,

I find this project very attractive, the only missing component is the health-check mechanism
via docker. 
I am getting an error when i am trying to curl -f, probably the image does not support curl.
this is my docker-compose.yml;
```
version: '3'
services:

  verdaccio:
    image: "verdaccio/verdaccio:3.5"
    ports: 
      - "4873:4873"
    container_name: "NPM_verdaccio"
    volumes:
      - /Users/ron/dev/npm/verdaccioVol:/verdaccio/storage
    restart: always
    labels:
      - "verdaccio.description=NPM private repository"
      - "verdaccio.department=DevOps"
    **healthcheck:
      test: curl -f http://localhost:4873 || exit 1
      interval: 30s
      timeout: 5s
      retries: "3"**
```
I would love to hear if there is any docker image made for health checking.

thank you very much.
