### ISSUE TITLE
Downloading a package fails with "404 Not Found" after a previous attempt to publish the package with an existing version fails

### ISSUE THREAD

**Issue by ryanewtaylor** [verdaccio/verdaccio#940]
**Describe the bug**
Downloading a package fails with "404 Not Found" after a previous attempt to publish the package with an existing version fails. 

**To Reproduce**
1. Create a new package, @my-co/my-package
2. Modify package @my-co/my-package
    ```
    echo bump>>readme.md
    yarn version
    ```
3. Publish package @my-co/my-package
    ```
    npm pack
    npm publish
    ```
3. In another project, my-consumer, consume package @my-co/my-package
    ```
    yarn add @my-co/my-package
    yarn build
    ```
4. Modify original package, @my-co/my-package, but do not bump its version
    ```
    echo bump>>readme.md
    ```
5. Publish same versioned package, @my-co/my-package
    ```
    npm pack
    npm publish
    ```
    This will correctly fail with an EPUBLISHCONFLICT error
6. Clear yarn cache and attempt to reconsume the package in my-consumer
    ```
     yarn cache clean
     yarn
    ````
    Here the download fails with the following error
    ```
    $ yarn
    yarn install v1.7.0
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    error An unexpected error occurred: "https://npmjs.myco.com/@my-co%2fmy-package/-/my-package-1.14.0.tgz: Request failed \"404 Not Found\"".
   ```

When inspecting differences changes in verdaccio\storage\@my-co\my-package\package.json it appears the _rev property is changed even when the package should fail to be uploaded.

Rebooting the web server does not resolve the issue. The package at the version where the overwrite failed remains permanently unavailable.
    
**Expected behavior**
The package should remain available for download even when a previous attempt to overwrite it with the same version fails.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: ./storage
auth:
  activedirectory:
    url: "ldap://ad.myco.local"
    baseDN: 'dc=myco,dc=local'
    domainSuffix: 'myco.local'
packages:
  '@*/*':
    access: $all
    publish: $authenticated
  '**':
    access: $all
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
url_prefix: https://npmjs.myco.com
```
