### ISSUE TITLE
Registered user can't login

### ISSUE THREAD

**Issue by bodz1lla** [verdaccio/verdaccio#943]
**Log-in Bug**
Hi Guys,

Maybe you can assist me regarding the following issue.
I tried to find the solution but found nothing. 
Please review. 

**Verdaccio - 3.5.1.**

1. When the existing user is trying to log in via npm, it gets an error "username is already registered".

2. If I disable registration with option "max_users: -1" in config.yaml, then I get an error "maximum amount of users reached".

**Terminal output**
```
$ npm login --registry=https://registry-npm.example.com
Username: test.user
Password:
Email: (this IS public) test@example.com
npm ERR! code E409
npm ERR! Registry returned 409 for PUT on https://registry-npm.example.com/-/user/org.couchdb.user:test.user: username is already registered

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test.user/.npm/_logs/2018-08-23T12_45_12_403Z-debug.log
```
```
$ npm login --registry=https://registry-npm.example.com
Username: test.user
Password:
Email: (this IS public)
Email: (this IS public) test@example.com
npm ERR! code E403
npm ERR! Registry returned 403 for PUT on https://registry-npm.example.com/-/user/org.couchdb.user:test.user: maximum amount of users reached

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test.user/.npm/_logs/2018-08-23T12_43_19_284Z-debug.log
```

**Expected behavior**

Log-in to Verdaccio server with a registered user. 

**Configuration File** 
```
web:
  # WebUI is enabled as default, if you want to disable it, just uncomment this line
  enable: true
  title: Verdaccio NPM
  logo: logo.png

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
```

**Debugging output**

```
$ npm login --registry=https://registry-npm.example.com -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/10.9.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'login',
npm verb cli   '--registry=https://registry-npm.example.com',
npm verb cli   '-ddd' ]
npm info using npm@6.2.0
npm info using node@v10.9.0
npm verb config Skipping project config: /Users/test.user/.npmrc. (matches userconfig)
npm verb npm-session 821b0c437be02ea2
npm verb web login before first POST
npm http request → POST https://registry-npm.example.com/-/v1/login
npm http 404 ← Not Found (https://registry-npm.example.com/-/v1/login)
npm verb web login not supported, trying couch
Username: test.user
Password:
Email: (this IS public) test@example.com
npm verb login before first PUT { _id: 'org.couchdb.user:test.user',
npm verb login   name: 'test.user',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2018-08-23T13:02:26.562Z' }
npm http request → PUT https://registry-npm.example.com/-/user/org.couchdb.user:test.user
npm http 409 ← Conflict (https://registry-npm.example.com/-/user/org.couchdb.user:test.user)
npm http request → GET https://registry-npm.example.com/-/user/org.couchdb.user:test.user?write=true
npm http 200 ← OK (https://registry-npm.example.com/-/user/org.couchdb.user:test.user?write=true)
npm http request → PUT https://registry-npm.example.com/-/user/org.couchdb.user:test.user/-rev/undefined
npm http 409 ← Conflict (https://registry-npm.example.com/-/user/org.couchdb.user:test.user/-rev/undefined)
npm verb adduser before first PUT { _id: 'org.couchdb.user:test.user',
npm verb adduser   name: 'test.user',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: '',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2018-08-23T13:02:26.622Z' }
npm http request → PUT https://registry-npm.example.com/-/user/org.couchdb.user:test.user
npm http 409 ← Conflict (https://registry-npm.example.com/-/user/org.couchdb.user:test.user)
npm verb stack Error: Registry returned 409 for PUT on https://registry-npm.example.com/-/user/org.couchdb.user:test.user: username is already registered
npm verb stack     at fetch.defaults.catch.then.then.result (/usr/local/lib/node_modules/npm/node_modules/npm-profile/index.js:376:13)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:68:7)
npm verb statusCode 409
npm verb cwd /Users/test.user
npm verb Darwin 17.6.0
npm verb argv "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/bin/npm" "login" "--registry=https://registry-npm.example.com" "-ddd"
npm verb node v10.9.0
npm verb npm  v6.2.0
npm ERR! code E409
npm ERR! Registry returned 409 for PUT on https://registry-npm.example.com/-/user/org.couchdb.user:test.user: username is already registered
npm verb exit [ 1, true ]
npm timing npm Completed in 17112ms
```

**Temporary solution**

Only possible to log-in with the registered user is allowed in config.yaml access and publish to all, anonymous.

```
access: $all, $anonymous
publish: $all
```
But it's not secure.

**Comment by bodz1lla** [comment]
@juanpicado yes, please.

```
$ verdaccio -V
3.5.1
```

Also, added to an issue.

**Comment by ayusharma** [comment]
I am not able to replicate it.

**Comment by bodz1lla** [comment]
@ayusharma 
That's strange. Did you try with the same version? 
I also use Apache proxy on the front and pm2 as service runner.  
Please review the configuration file. 
Thanks.

```
<VirtualHost *:80>
  ServerName registry-npm.example.com

  ## Vhost docroot
  DocumentRoot "/var/www"

  ## Directories, there should at least be a declaration for /var/www

  <Directory "/var/www">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Require all granted
  </Directory>

  ## Load additional static includes
  Include "includes/general_settings"

  ## Load additional static includes
  Include "includes/ssl"

  ## Logging
  ErrorLog "/var/log/httpd/registry-npm.example.com-443_error_ssl.log"
  ServerSignature Off
  CustomLog "/var/log/httpd/registry-npm.example.com-443_access_ssl.log" combined

  ## Custom fragment

        <Location />
        Require all granted
        ProxyPassReverse http://127.0.0.1:4873/
        ProxyPassReverse http://registry-npm.example.com/
        </Location>
        RequestHeader unset Authorization
        ProxyRequests     Off
        ProxyPreserveHost On
        RewriteEngine On
        AllowEncodedSlashes NoDecode
        <Proxy>
        Order deny,allow
        Allow from all
        </Proxy>

        ProxyPass         /  http://127.0.0.1:4873/ nocanon
        ProxyPassReverse  /  http://127.0.0.1:4873/
</VirtualHost>
```

**Comment by cara** [comment]
I'm getting the same error with verdaccio version 3.7.1 in docker with a nginx proxy
config.yaml:
`storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users:  10 // later: -1 
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated    
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
`
I start with 10 max_users:
`npm adduser --registry  reg.url
Username: severin
Password:
Email: (this IS public) mail@mail.de`
Now I change config to -1 max_users
`npm logout --registry  reg.url
pm adduser --registry  https://npm.severinfink.de/
Username: severin
Password:
Email: (this IS public) mail@mail.de`
Response:
`
npm ERR! code E403
npm ERR! Registry returned 403 for PUT on  reg.url/-/user/org.couchdb.user:severin: maximum amount of users reached
`

Server Log:
`
 http <-- 201, user: severin(85.183.148.83 via 172.17.0.4), req: 'PUT /-/user/org.couchdb.user:severin/-rev/undefined', bytes: 182/108
 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/3.7.1
(node:5) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 http <-- 200, user: severin(85.183.148.83 via 172.17.0.4), req: 'DELETE /-/user/token/4h0bpV6K0tTBinz3KiJqqjtwu3LI/8lSy6JnCzY7nwc=', bytes: 0/25
 http <-- 200, user: severin(85.183.148.83 via 172.17.0.4), req: 'DELETE /-/user/token/4h0bpV6K0tTBinz3KiJqqjtwu3LI/8lSy6JnCzY7nwc=', bytes: 0/25
 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/3.7.1
 http <-- 404, user: null(85.183.148.83 via 172.17.0.4), req: 'POST /-/v1/login', bytes: 22/150
 http <-- 404, user: null(85.183.148.83 via 172.17.0.4), req: 'POST /-/v1/login', bytes: 22/150
 http <-- 403, user: null(85.183.148.83 via 172.17.0.4), req: 'PUT /-/user/org.couchdb.user:severin', error: maximum amount of users reached
(node:5) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 http <-- 403, user: null(85.183.148.83 via 172.17.0.4), req: 'PUT /-/user/org.couchdb.user:severin', error: maximum amount of users reached
`

**Comment by michaelfig** [comment]
I can reproduce by setting max_users to 10, running "npm login" successfully, then setting max_users back to -1 and running "npm login" again, which fails due to the "error:maximum amount of users reached" even though I used identical credentials and e-mail.

**Comment by juanpicado** [comment]
@michaelfig please provide your env info, version, etc.

**Comment by michaelfig** [comment]
I'll try to get you exact steps to reproduce, but for now:

Kubernetes Helm chart 0.5.0, verdaccio docker image 3.8.1

I first set up verdaccio with a custom config map and mounted a read-only /etc/verdaccio/htpasswd, and set max_users to -1.

Then when that didn't work (npm adduser failed even though I verified that the password was correct... Maybe an issue with @verdaccio/file-locker not working on a read-only filesystem), I updated the config to use /verdaccio/storage/htpasswd. Then I got the above behavior.

Everything works fine when running npm adduser and max_users is 10.  Then I can set max_users to -1 and everything works except for npm adduser (even with identical credentials).

Lmk if you need anything further.

**Comment by juanpicado** [comment]
Thanks @michaelfig I'll dig into it.

**Comment by cojack** [comment]
Okey, so we have some misleading information, because config.yaml saying:

```
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
```

But documentation saying:

`In case to decide do not allow user to login, you can set max_users: -1.`

And by this behaviour I guess, documentation is right. Because when I change it to max_users: 1, Im able to login by user I've created.

So yeah...

**Comment by juanpicado** [comment]
Thanks for point it out, we are moving all documentation to a single place so in the future we avoid this kind of inconsistency.

**Comment by michaelfig** [comment]
Now I can do exactly what I need... create htpasswd manually and deploy verdaccio via Helm.  My steps are:

Create a secret to contain the verdaccio.htpasswd identifying valid users.  

```
$ htpasswd -c verdaccio.htpasswd <USER>
$ htpasswd verdaccio.htpasswd <OTHER-USER>
[Repeat as necessary]
$ kubectl create secret generic etc-verdaccio --from-file verdaccio.htpasswd
```

Then install verdaccio.

```
$ helm install -f verdaccio.yaml stable/verdaccio
```

I use the following stanzas in my Helm config file, verdaccio.yaml:

```
persistence:
  volumes:
    - name: etc-verdaccio
      secret:
        secretName: etc-verdaccio
  mounts:
    - mountPath: /etc/verdaccio/secrets
      name: etc-verdaccio
      readOnly: true

configMap: |
  # ... many lines skipped.
  auth:
    htpasswd:
      # Mount from our etc-verdaccio secret.
      file: /etc/verdaccio/secrets/verdaccio.htpasswd
      # Allow all existing logins, but don't allow registration (since we already have at least one user in htpasswd).
      max_users: 1
```

Please document this case in the sample configs.

Thanks,
Michael.
