### ISSUE TITLE
Separate cache directory

### ISSUE THREAD

**Issue by psyhomb** [verdaccio/verdaccio#965]
**Is your feature request related to a problem? Please describe.**
I'm using `verdaccio-s3-storage` plugin to store all the packages and metadata in S3 datastore, when I'm listing content of the bucket where packages are stored I would like to have a clear view of what is published locally and what's cached, downloaded from uplinks.

How it looks now:
```
verdaccio-s3-bucket-name
|_ verdaccio-s3-db.json
|_ pkg1
|_ pkg2
|_ pkg11
|_ pkg12
|_ pkg13
```

How it should look like IMHO:
```
verdaccio-s3-bucket-name
|_ verdaccio-s3-db.json
|_ published or local
   |_ pkg1
   |_ pkg2
|_ cache or uplinks
   |_ pkg11
   |_ pkg12
   |_ pkg13
```

I'm asking this because it crossed my mind how painful it would be if I want to flush cache directly by using S3 API, I would basically have no clue what have been download from uplinks and what published locally.

Is something like this even possible (I'm not nodejs developer so maybe I'm missing something) and do you guys maybe have some better solution?

BTW nice work!

**Comment by juanpicado** [comment]
cc @apexskier

**Comment by juanpicado** [comment]
I think we had a similar question long time ago, I have some thoughts, but I will extend them later on. AFK :)

**Comment by apexskier** [comment]
I think that's possible, but we'll have to think carefully about a migration/upgrade/versioning plan, since it has the potential to break existing setups.

I think it'll require changes to Verdaccio's plugin api. When [fetching the storage location for a single package](https://github.com/Remitly/verdaccio-s3-storage/blob/44648b5/src/index.js#L107) we'll have to pass an indicator to tell if it's locale or cached. (`IPluginStorage { getPackageStorage(packageInfo: string): verdaccio$IPackageStorage; }` needs to be `IPluginStorage { getPackageStorage(packageName: string, packageInfo: { options of some sort }): verdaccio$IPackageStorage; }`)

**Comment by psyhomb** [comment]
One potential way of achieving this could be additional `cache_path` parameter under `uplinks` section which will be relative to `storage` path.

That way you wouldn't have to worry about breaking existing setups, because default configuration would generate the same directory structure we have now (`cache_path` => `/verdaccio/storage`) ...
```
storage: /verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 10m
    cache: false
    cache_path: ./
```

... but if you specify some other directory, cached packages will be stored there (`cache_path` => `/verdaccio/storage/cache`)
```
storage: /verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 10m
    cache: false
    cache_path: ./cache
```

**Comment by juanpicado** [comment]
After dig into this, I found the following info.

Let's assume we have this configuration.
```
uplinks:
  npmjs:
    fail_timeout: 5s
    max_fails: 1
    maxage: 5s
    url: https://registry.npmjs.org/
  yarn:
    fail_timeout: 5s
    max_fails: 1
    maxage: 5s
    url: https://registry.yarnpkg.com/
packages:
  '@juan/*':
    # scoped packages
    access: jpicado
    publish: jpicado
    proxy: npmjs
    storage: private_juan
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
    storage: npmjs_scoped_cached
  '*webpack*':
    # scoped packages
    access: $all
    publish: $all
    proxy: yarn
    storage: custom_folder
  'jquery':
    # scoped packages
    access: $all
    publish: $all
    proxy: yarn
    storage: custom_folder
  'parcel':
    # scoped packages
    access: $all
    publish: $all
    proxy: yarn
    storage: custom_folder
```
In short, I defined 3 custom folders, **custom_folder**, **npmjs_scoped_cached**, and **private_juan**, where I plan to organize my packages.

This functionality was already somehow implemented, but at package access level instead uplink level. 
In the configuration below I tried to somehow organize my packages by folder.  The result is the following.

![screen shot 2018-09-22 at 9 18 11 am](https://user-images.githubusercontent.com/558752/45914672-7a163a80-be48-11e8-86af-d7071be1817e.png)

> I had to fix a bug (https://github.com/verdaccio/local-storage/pull/96) before make it run, so with the latest release won't work properly.

Something else I found digging is this is done at **storage plugin level**, so, each plugin might decide whether or not use this functionality (https://github.com/verdaccio/local-storage/blob/master/src/local-database.js#L216). So, there is no need to change anything (perhaps minor stuff) in the main project. Honestly I think the code is not readable enough in the *local-storage* plugin, so, I'll refactor it. 

My next steps are:

* Provide better documentation (https://verdaccio.org/docs/en/packages#configuration) since the storage section was never documented and not clear at all, perhaps we forgot it during the Verdaccio 3 release. 
* Fix the bug in `local-storage`(only available since Verdaccio 4) and this will drive us to a breaking change, it will be a string instead boolean.

In conclusion, **I think do it at package access level is much flexible than do it as uplink level**, futhermore, plugins does not have access to uplinks, only package access. Verdaccio always has recommened to keep private packages under some sort of prefix (https://github.com/verdaccio/verdaccio/blob/test-api/docs/use-cases.md#using-private-packages) and using the `storage` properly will help to organize better your packages.

**Comment by juanpicado** [comment]
ok, please allow me to update your example with a variant I saw along my research.

```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 10m
    cache: true
    cache_path: ./cache_folder

packages:
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    storage: custom_folder
```

Since we cannot remove `storage` prop from packages, Which one will have higher priority here?
