### ISSUE TITLE
docs bug - unclear how to use for simple use case - dynamically creating dummy packages for packages that do not exist on official NPM registry.

### ISSUE THREAD

**Issue by ORESoftware** [verdaccio/verdaccio#971]
I am looking at the docs in the docs/ folder, I see:
https://github.com/verdaccio/verdaccio/blob/master/docs/use-cases.md

my use case - in some cases I am using `npm install foo`, but foo is not published to the official NPM registry. So I want to use a proxy that can create a dummy package for foo, and it needs to be dynamic. So whenever a package cannot be found in the NPM registry, a dummy package will be created and sent in its place. 

Is this use case possible with verdaccio? Maybe I didn't read the docs carefully enough, but it would be nice to have a "case study" approach to how to use verdaccio in the wild.

Here are related questions on StackOverflow:
https://stackoverflow.com/questions/51888198/skip-install-for-particular-dep

Essentially, if I cannot skip installing a dep, what I need to do is retrieve a dummy package so that `npm install` will not fail.

I believe these are the steps, we wrap `npm install` with this script:

1. For all packages in package.json, check to see which packages aren't published to official registry.
2. For each unpublished package, publish a dummy package to verdaccio, which runs as a proxy 
3. Run npm install, any package that can be found by verdaccio will be returned, o/w the request will be forwarded to the official npm registry.

Is that about right? How do I do that exactly? There should be a case study for this IMO, since this seems like a common use case.

**Comment by ORESoftware** [comment]
One thing I see, I start the verdaccio server, and run

`npm publish --registry http://0.0.0.0:4873`

I get this error:

http <-- 409, user: oresoftware(172.17.0.1), req: 'PUT /npm-link-up', error: this package is already present

but that package is not in my local registry - why is it checking to see what is on the official registry?

**Comment by juanpicado** [comment]
The default uplink is the main registry if you see the `config.yaml` file

```
# a list of other known repositories we can talk to
uplinks:
  npmjs:
    fail_timeout: 5s
    max_fails: 1
    maxage: 5s
    url: https://registry.npmjs.org/
```
thus if your package access has as a proxy the uplink `npmjs` as
```
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
```
it will check wether package@version already exist on remote, if you want to override such behavior just create a custom package access section for such dependency and remove the `proxy` field.
