### ISSUE TITLE
Problem with @angular/core and npm search

### ISSUE THREAD

**Issue by gbasisty** [verdaccio/verdaccio#976]
Just installed the last version of verdaccio (3.7.1, debian linux 9 stretch):

`# npm install -g verdaccio`

And as a regular user started it:

```
$ verdaccio
 warn --- config file  - /var/lib/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/3.7.1

```
my config.yaml:

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

listen:
        0.0.0.0:4873

```
Then I setted up the local registry:

`$ npm set registry http://xxxxxxxx
`

With non scoped packages, no problem. For example: npm search jquery works fine. But if I try:

```
$ npm search @angular/core
npm WARN search fast search endpoint errored. Using old search.
No matches found for "@angular/core"
$
```

Any Ideas? Best regards
