### ISSUE TITLE
htpasswd + ldap plugins not work

### ISSUE THREAD

**Issue by vegawong** [verdaccio/verdaccio#978]
**Describe the bug**
login with command `npm login` or `npm add user` would auto adduser in htpasswd file,but not verify.
then if i execute any command need authorized such as `npm info xxx`, it would return E403 if the username & password not verified by ldap plugin. and i can't relogin with the collect username & password again because the account were already in the htpasswd file.

**To Reproduce**
1. excute `npm adduser --registy=http:localhost:4873`
2. type the right username and wrong password
3. excute `npm info react`
4. See Error `return E403`
5. redo step 1 - 4 but type right username & right password in step2
6. See the same error as step4

**Expected behavior**
npm login with wrong username or wrong password should be crash

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:beta]
 - Docker commands [e.g. docker pull ...]
 - Docker Version [e.g. v18.05.0-ce-rc1]

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**
verdaccio@3.7.1
verdaccio-ldap@3.0.0

**Comment by juanpicado** [comment]
@vegawong 
About ldap plugin:
I'd rather first ask here https://github.com/Alexandre-io/verdaccio-ldap I cannot do too much.
About the htpasswd I think you need to share the config file first.

**Comment by vegawong** [comment]
@juanpicado thank reply!
about the auth config like this:
```yaml
auth:
  htpasswd:
    file: /app/data/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    max_users: 1001
  ldap:
  ...
```

BTW: my npm version is 5.6.0, it's login action didn't add token to the npmrc file
