### ISSUE TITLE
please report this: AssertionError

### ISSUE THREAD

**Issue by apopescu-im** [verdaccio/verdaccio#980]
**Describe the bug**
Verdaccio server crashed

**To Reproduce**
Unknown
We've had the server running for days/weeks in a Docker container until we noticed it had been dead a few hours.  We found this output in the log and reporting it here as requested by the output:

```
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/3.0755676185b6ed73e9d2.js', bytes: 0/5273
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/5.style.fdd4df75f6193950e8bd.css', bytes: 0/1016
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/5.0755676185b6ed73e9d2.js', bytes: 0/3918
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/1.0755676185b6ed73e9d2.js', bytes: 0/5358
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/3.style.e3f12f205fb1bfaa0cfe.css', bytes: 0/2150
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/3.0755676185b6ed73e9d2.js', bytes: 0/5273
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/5.style.fdd4df75f6193950e8bd.css', bytes: 0/1016
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/5.0755676185b6ed73e9d2.js', bytes: 0/3918
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/1.0755676185b6ed73e9d2.js', bytes: 0/5358
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/verdaccio/logo', bytes: 0/53
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/verdaccio/logo', bytes: 0/53
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/logo.png', bytes: 0/12940
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/static/logo.png', bytes: 0/12940
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/verdaccio/package/readme/@inbox/credentials-client', bytes: 0/687
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/verdaccio/package/readme/@inbox/credentials-client', bytes: 0/687
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/verdaccio/sidebar/@inbox/credentials-client', bytes: 0/1469
http <-- 200, user: undefined(10.1.20.121), req: 'GET /-/verdaccio/sidebar/@inbox/credentials-client', bytes: 0/1469
http --> 304, req: 'GET https://registry.npmjs.org/nodemon' (streaming)
http --> 304, req: 'GET https://registry.npmjs.org/nodemon', bytes: 0/0
http --> 304, req: 'GET https://registry.yarnpkg.com/nodemon' (streaming)
http --> 304, req: 'GET https://registry.yarnpkg.com/nodemon', bytes: 0/0
http <-- 200, user: undefined(10.1.20.89), req: 'GET /nodemon', bytes: 0/39713
http <-- 200, user: undefined(10.1.20.89), req: 'GET /nodemon', bytes: 0/39713
fatal--- uncaught exception, please report this
AssertionError [ERR_ASSERTION]: false == true
    at TLSWrap.onhandshakestart (_tls_wrap.js:66:3)
```

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio/verdaccio:3.4
 - Docker commands: via docker-compose (docker-compose up) and our custom compose / Dockerfile to provide configuration and certificates
 - Docker Version: 18.05.0-ce

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

From `/etc/verdaccio/config.yaml` (we specify --config /etc/verdaccio/config.yaml in the CMD)

```
storage: /var/lib/verdaccio/storage
url_prefix: https://HOSTNAME_REMOVED:4873/
auth:
  htpasswd:
    file: /etc/verdaccio/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  yarn:
    url: https://registry.yarnpkg.com/
packages:
  '@NAME_REMOVED/*':
    access: $all
    publish: $authenticated
  '@*/*':
    access: $all
    proxy: npmjs yarn
  '**':
    access: $all
    proxy: npmjs yarn
logs:
  - {type: stdout, format: pretty, level: http}
web:
  enable: true
  title: Verdaccio
https:
  key: /certificates/DOMAIN_REMOVED.key
  cert: /certificates/cert.pem
  ca: /certificates/ca.pem
middlewares:
  audit:
    enabled: true
notify:
  slack:
    method: POST
    headers: [{'Content-Type': 'application/json'}]
    endpoint: SLACK_WEBHOOK_URL_REMOVED
    content: '{"text": "{{ name }}", "attachments": [{"author_name": "{{ publisher.name }} published", "title": "{{#each versions}} v{{version}}{{/each}}"}]}'
```

The various *_REMOVED values have correct, actual values in the file.
