### ISSUE TITLE
can not install public packages removing '**' pattern in package section

### ISSUE THREAD

**Issue by huangshuwei** [verdaccio/verdaccio#981]
**Describe the bug**
First of all, thank you very much Verdaccio, really great.
The problem is that I can install private package but I can't install the public package.

**To Reproduce**

**server**
config.yaml is

```

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  enable: true

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '@local-choice/*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    
    # defalut $authenticated
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: shuwei

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  - {type: file, path: verdaccio.log, level: info}

# listen
listen: 172.16.57.120:4005
```

**client**
1. Registry setting globally for all my projects
```
npm set registry http://172.16.57.120:4005/
```
2. Install public packages in my project
```
npm install vue
```
3.Client error
![image](https://user-images.githubusercontent.com/6047141/45068979-d1a07080-b0fc-11e8-9ea3-03e60e7e993e.png)

4. Verdaccio server error
![image](https://user-images.githubusercontent.com/6047141/45069030-13311b80-b0fd-11e8-8300-67869f62555b.png)

**Additional context**
I found the source code based on the wrong prompts. 
![image](https://user-images.githubusercontent.com/6047141/45069172-b8e48a80-b0fd-11e8-9c9d-fced167de3c8.png)

But I don't know why.I hope to receive your reply.
